### ISSUE TITLE
AuthCrypt on Python 3.8 broken (clock removed from module time)

### ISSUE THREAD

**Issue by 1000stSheep** [Kozea/Radicale#1001]
No auth encryption on Python 3.8 (tested 64-bit version on Win10).
Runtime Exception at loading passlib module, as soon as md5 or bcrypt is selected for htpasswd encryption. Others not tested.
Plain is working. Python 3.7 is working (as expected).

**Comment by Unrud** [comment]
I've included Python 3.8 in Travis-CI. The **passlib** module works now.
