### ISSUE TITLE
CalDAV 'REPORT' with VTODO also sends back VEVENT blocks (and viceversa)

### ISSUE THREAD

**Issue by neandr** [Kozea/Radicale#101]
This REPORT should only give VTODO of the 
calendar, but also sends VEVENT blocks.

    CalDAV:
      method: REPORT  headers:Depth:1;User-Agent:Reminderfox/2.1.4
      urlstr:http://localhost:5232//gTest/  login : admin
      contentType:application/xml
      content:
    <c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
      <d:prop>
        <d:getetag />
      </d:prop>
      <c:filter>
        <c:comp-filter name="VCALENDAR">
          <c:comp-filter name="VTODO" />
          </c:comp-filter>
      </c:filter>
    </c:calendar-query>

AFAIK this shouldn't be the case .. if so --> BUG!

Günter

**Comment by liZe** [comment]
It should be fixed by a28df4.
