### ISSUE TITLE
OSError: Apache/mod_wsgi log object is not associated with a file descriptor.

### ISSUE THREAD

**Issue by return42** [Kozea/Radicale#1013]
Logging cause exception when using apache mod_wsgi (libapache2-mod-wsgi-py3). 

    File "/var/www/pyApps/Radicale/radicale/log.py", line 158, in get_default_handler
        st = os.fstat(sys.stderr.fileno())
    OSError: Apache/mod_wsgi log object is not associated with a file descriptor. 

 I see this bug with:

    Package: libapache2-mod-wsgi-py3
    Version: 4.5.17-1
    Python version:    '3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]'

It is caused by this line ..

https://github.com/Kozea/Radicale/blob/db7587c59335fa00580ce88d583419ce45594143/radicale/log.py#L158

A hotfix for me was to use `sys.__stderr__` instead of `sys.stderr` ... here is my solution:

````python
st = os.fstat(sys.__stderr__.fileno())
````

**Comment by pbiering** [comment]
obsolete, current version is logging via journald only
