### ISSUE TITLE
Can't import online ics-file (public holiday calendar)

### ISSUE THREAD

**Issue by wolfischwarz** [Kozea/Radicale#1014]
Hi,

how can I import an online ics-file from the internet (it has all the public holidays from the country)? 

`example file: h**p://i.cal.to/ical/65/bayern/feiertage/f5ceab2f.0369fa21-e935fc04.ics`

I have imported this file to Google Calendar and it worked well. But now I want to switch to radicale and not using Google Calendar any more.

Tried downloading the ics file, create a new calendar (via radicale webpage) and moved it to the created folder + set correct permissions. When trying to connect to the calendar via Thunderbird/Lightning -> in the log I find the error: 

`Failed to load item 'f5ceab2f.0369fa21-e935fc04.ics' in 'user/b840f0f3-acbe-9925-ce30-bed21c320274': Multiple VEVENT components with different UIDs in object`

It would be awesome if I could add the ics-file via the online link so that I don't need to download the ics file each year manually (or via a cron-job).

The other created calendar with radicale works fine 😃 
`My radicale version: 2.1.11`

Thanks a lot!

**Comment by Unrud** [comment]
https://github.com/Kozea/Radicale/issues/955#issuecomment-574998984

The next version will have an upload dialog on the web interface.
