### ISSUE TITLE
Can't set "host" to server's IP address

### ISSUE THREAD

**Issue by kpatch-admin** [Kozea/Radicale#1015]
I recently installed Radicale on my server, which is running Ubuntu Server 18.04.3. I have been able to get it to work with http://localhost:5232, as well as set it up as a service. 

Additionally, I have set up the config file in /etc/radicale. I have also opened port 5232 in my firewall. However, when I set "hosts = 192.168.0.109:5232" in /etc/radicale/config and attempt to connect, I get 
[radicale_screenshot](https://user-images.githubusercontent.com/32489583/73692630-b1366600-46a2-11ea-9efa-c5b66f4e69ee.gif)
The same thing happens with hosts = 0.0.0.0:5232.

Any suggestions to fix this would be greatly appreciated. My config file is attached. (It has a .txt entension so I could upload it to this post.)
[config.txt](https://github.com/Kozea/Radicale/files/4150084/config.txt)

Thank you.

**Comment by kpatch-admin** [comment]
I have abandoned the suggested Radicale setup as described on [https://radicale.org/setup/] and have embarked on setting it up to be delivered by Apache v(2.4.29) as described on [https://wiki.debian.org/Radicale].

**Comment by swdee** [comment]
I setup Radicale today and had no problem with having it run on any interface I wanted with the `hosts =  <interface>:<port>` option.

When you tried did you check the output of `netstat -an | grep :5232` to see if the server was in fact listening on that configured interface?  If it was then it would be a firewall configuration issue.
