### ISSUE TITLE
Standalone FastCGI (also OpenBSD compatibility)

### ISSUE THREAD

**Issue by kousu** [Kozea/Radicale#1017]
I'm trying to run radicale on the [OpenBSD stack](https://bsd.plumbing/). I've decided FastCGI is the way to go, but I'm having trouble getting it to work well.

I've used radicale before in its default setup, running HTTP at https://myserver.com:5232/, but now I want to run it at https://myserver.com/radicale/ in parallel with other pieces of my site. I tried to follow [the nginx reverse proxy guide](https://radicale.org/proxy/), but eventually I realized that wasn't going to work because radicale needs the "/radicale" stripped, but HTTP proxies in relayd(8) don't (yet) support URL rewriting, and while httpd(8) does (`request strip 1`) it purposefully [*only* supports](http://man.openbsd.org/httpd.conf#socket) HTTP-to-FastCGI proxies. So I need to get Radicale running as a FastCGI.

Once I realized this I quickly found https://github.com/Kozea/Radicale/blob/master/radicale.fcgi. As is, it doesn't work with httpd(8) because

a. httpd(8) doesn't *spawn* FastCGI processes:
  * flup defaults to "a normal FastCGI" assuming that the HTTP server spawns the FastCGI and is in charge of replacing stdin with a socket. But OpenBSD encourages _standalone_ FastCGI processes which open their own sockets.

b. It does not daemonize itself
c. If it does daemonize itself, OpenBSD's `rcctl` infrastructure gets confused so that `rcctl stop radicale` and `rcctl check radicale` fail.
  * OpenBSD's daemon infrastructure works by `pgrep`ing for full command lines. It is expecting `/usr/local/bin/python3.7 /usr/local/bin/radicale` but with the shebang `#!/usr/bin/env python3`, radicale shows up like

    ```
    _radical 29507  0.0  0.2 20648 13672 ??  S       9:25PM    0:00.04 python3 /usr/local/bin/radicale (python3.7)
    ```
    
    whereas with `#!/usr/local/bin/python3.7` it shows up like
    
    ```
    _radical 87684  0.0  0.2 20520 13184 ??  S       9:26PM    0:00.03 /usr/local/bin/python3.7 /usr/local/bin/radicale
    ```

I ended up adapting it like this:

```
$ cat /usr/local/bin/radicale
#!/usr/local/bin/python3.7

from flup.server.fcgi import WSGIServer

import radicale
from radicale.__main__ import daemonize

if __name__ == "__main__":
    radicale._init_application("/etc/radicale/config")
    
    daemonize(radicale._application.configuration, radicale._application.logger)

    WSGIServer(radicale._application, bindAddress=("localhost", 5232)).run()
```

It's trickier to get the permissions right -- since httpd(8) runs as www and radicale runs as _radicale -- but theoretically more secure to use a Unix Domain socket instead of TCP with

```
    WSGIServer(radicale._application, bindAddress="/var/www/run/radicale.sock", umask=0o002).run()
```

This somewhat works but I'm worried I've missed initializing something properly, since `radicale.__main__` does a lot more work than that before it starts serving files, and the call to _init_application() seems ugly. It'll also be confusing when I forget the details and come back to see that I'm using /etc/radicale/config yet ignoring the `hosts` setting.

My questions are:

i. Any tips on refining this script? And would it be worth making a PR out of?
ii. Would you consider adding a standalone FastCGI mode into `__main__` as a config option?

**Comment by kousu** [comment]
I am running radicale like this:

/usr/local/bin/radicale.fcgi:

```
#!/usr/local/bin/python3.7

"""
Radicale FastCGI Example.

Launch a Radicale FastCGI server according to configuration.
"""

from flup.server.fcgi import WSGIServer
from radicale import application

import radicale
import os

if __name__ == "__main__":
    radicale._init_application("/etc/radicale/config") # this needs to happen for .configuration and .logger to exist
    WSGIServer(radicale._application, bindAddress=("localhost", 5232)).run()
```

httpd.conf:

```
chroot "."

server "default" {
        listen on localhost port 80
        root "."
        directory auto index

        location "/radicale" {
            request rewrite "$DOCUMENT_URI/"
        }

        location "/radicale/*" {
            request strip 1
            fastcgi socket :5232
        }

        log syslog
}
```

http://localhost/radicale works, successfully bouncing to http://localhost/radicale/.web/ which also works, but http://localhost/radicale/ doesn't: it misinterprets that URL *as if* it was http://localhost/radicale and ends up *doubling up* the "radicale" part:

```
$ curl -s -v -L http://localhost/radicale/; echo 
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /radicale/ HTTP/1.1
> Host: localhost
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Connection: keep-alive
< Content-Type: text/plain; charset=utf-8
< Date: Mon, 17 Feb 2020 10:32:53 GMT
< Location: radicale/.web
< Server: OpenBSD httpd
< Transfer-Encoding: chunked
< 
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost/radicale/radicale/.web'
* Found bundle for host localhost: 0xa181462e580 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /radicale/radicale/.web HTTP/1.1
> Host: localhost
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Connection: keep-alive
< Content-Type: text/plain; charset=utf-8
< Date: Mon, 17 Feb 2020 10:32:53 GMT
< Server: OpenBSD httpd
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
The requested resource could not be found.
```

If I put radicale at /path/to/some/thing instead then http://localhost/path/to/some/thing/ goes to http://localhost/path/to/some/thing/thing/.web and if /whats/up/doc it goes to /whats/up/doc/doc/.web.

Here's the logs from radicale:

```
[2b86ed61040] INFO: GET request for '' received from 127.0.0.1 using 'curl/7.66.0'
[2b86ed61040] DEBUG: Request headers:
{'DOCUMENT_ROOT': '.',
 'DOCUMENT_URI': '/radicale/',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_HOST': 'localhost',
 'HTTP_USER_AGENT': 'curl/7.66.0',
 'PATH_INFO': '',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '21535',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/radicale/',
 'SCRIPT_FILENAME': './',
 'SCRIPT_NAME': '/radicale/',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_NAME': 'default',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'OpenBSD httpd',
 'wsgi.errors': <flup.server.fcgi_base.TeeOutputStream object at 0x2b7c75913d0>,
 'wsgi.input': <flup.server.fcgi_base.InputStream object at 0x2b7c7590410>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2b86ed61040] DEBUG: Sanitized script name: '/radicale'
[2b86ed61040] DEBUG: Sanitized path: '/'
[2b86ed61040] DEBUG: Response content:
Redirected to radicale/.web
[2b86ed61040] INFO: GET response status for '' in 0.009 seconds: 302 Found
[2b86ed5f040] INFO: GET request for '/radicale/.web' received from 127.0.0.1 using 'curl/7.66.0'
[2b86ed5f040] DEBUG: Request headers:
{'DOCUMENT_ROOT': '.',
 'DOCUMENT_URI': '/radicale/radicale/.web',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_HOST': 'localhost',
 'HTTP_USER_AGENT': 'curl/7.66.0',
 'PATH_INFO': '/radicale/.web',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '21535',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/radicale/radicale/.web',
 'SCRIPT_FILENAME': '.',
 'SCRIPT_NAME': '/radicale',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_NAME': 'default',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'OpenBSD httpd',
 'wsgi.errors': <flup.server.fcgi_base.TeeOutputStream object at 0x2b7c7591dd0>,
 'wsgi.input': <flup.server.fcgi_base.InputStream object at 0x2b7c7591210>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2b86ed5f040] DEBUG: Sanitized script name: '/radicale'
[2b86ed5f040] DEBUG: Sanitized path: '/radicale/.web'
[2b86ed5f040] DEBUG: Unsafe path 'radicale/.web' requested from storage: Can't translate name safely to filesystem: '.web'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/radicale/storage.py", line 883, in discover
    filesystem_path = path_to_filesystem(folder, sane_path)
  File "/usr/local/lib/python3.7/site-packages/radicale/storage.py", line 306, in path_to_filesystem
    raise UnsafePathError(part)
radicale.storage.UnsafePathError: Can't translate name safely to filesystem: '.web'
[2b86ed5f040] DEBUG: Response content:
The requested resource could not be found.
[2b86ed5f040] INFO: GET response status for '/radicale/.web' in 0.005 seconds: 404 Not Found
```

I've tracked this down: OpenBSD's httpd sends `'SCRIPT_NAME': '/radicale/', 'PATH_INFO': ''}` in the /radicale/ case, but `'SCRIPT_NAME': '/radicale', 'PATH_INFO': '/.web'}` in the /radicale/.web case. It seems to be something to do with the `request strip` option, some off-by-one thing. That then hits this corner-case code:

https://github.com/Kozea/Radicale/blob/db7587c59335fa00580ce88d583419ce45594143/radicale/app/get.py#L64-L69

which sees the empty PATH_INFO and assumes that implies the REQUEST_URI had no trailing slash, and therefore it needs to compensate to make the relative link work.

**Comment by kousu** [comment]
I don't know a reliable way to make this work. I am leaning to say that this is a problem with OpenBSD's httpd. But I don't know if I can get it fixed over there.

**Comment by ZipFile** [comment]
FCGI support is quite meh nowadays. With HTTP/3 around the corner it could be considered legacy, even. In a Python world we have [WSGI](https://www.python.org/dev/peps/pep-0333/) for running web apps.

Consider one of the following configurations:

* [nginx + uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/Nginx.html) combo.
* [uwsgi in http mode](https://uwsgi-docs.readthedocs.io/en/latest/HTTP.html) or gunicorn and configure nginx/httpd to reverse proxy/load balance.

**Comment by Unrud** [comment]
> FCGI support is quite meh nowadays.

The `radicale.fcgi` script is an old relict. Only the internal server and WSGI are supported and automatically tested in CI.
