### ISSUE TITLE
Changelog covering changes between master and latest release

### ISSUE THREAD

**Issue by TribuneX** [Kozea/Radicale#1029]
I wonder how many benefits one would get from installing radicale from the master branch instead of using the latest release version?

Is there a kind of changelog / list of improvements for the master branch? Any chance that we will see a new release in the future?

Thanks!

**Comment by Unrud** [comment]
Changelog: https://github.com/Kozea/Radicale/blob/master/NEWS.md#master
Documentation: https://radicale.org/master.html

> Any chance that we will see a new release in the future?

Hopefully soon.

**Comment by TribuneX** [comment]
Thanks! I am looking forward to the release.
