### ISSUE TITLE
[Windows 10] After about 2 hours python.exe process goes up to 30% CPU usage

### ISSUE THREAD

**Issue by bege10** [Kozea/Radicale#1030]
Hello,
I have recently installed the Radicale server with the latest Python and basic configuration on Windows 10 Professional 64 bit and run it with NSSM as a service.
After about 2 hours the python.exe process goes up to 30% CPU usage and remains there.
If I restart the service the CPU usage goes down.
What may cause the high CPU usage and how can this be fixed?

**Comment by pbiering** [comment]
can this be replicated with latest version 3.1.x?

**Comment by bege10** [comment]
Sorry, forgot to close this pretty old issue. It ist obsolete for a long time already.
