### ISSUE TITLE
Unable to use CardDAV on macOS High Sierra. 

### ISSUE THREAD

**Issue by viertelb** [Kozea/Radicale#1032]
I installed the package on my RaspberryPi and successfully used the Calendar on my Mac. I was not able to use the addressbook I created. I confirmed that the addressbook works by importing it in Thunderbird on a Windows 10 machine. 

The error I get is "Unable to confirm authentication" or something similar (I am German). 

I tried in expert mode my pasting in the server URL without the path to the addressbook. I also used the whole URL for the entry in server. I tried without putting the port in and with putting it in, with/without SSL and so forth. I used the port 5232. 

Do you need more information?

**Comment by tgy** [comment]
I have the same issue I think. Radicale returns a 404:
```
80.215.226.179 - valentin [25/Apr/2020:17:09:02 +0200] "PROPFIND /.well-known/carddav HTTP/1.1" 404 60 "-" "Mac OS X/10.15.4 (19E266) AddressBookCore/1"
```

**Comment by tgy** [comment]
I figured out how to connect to my CardDav account:
<img width="414" alt="Screenshot 2020-04-25 at 19 37 32" src="https://user-images.githubusercontent.com/694873/80286534-3f633b00-872c-11ea-8e69-edc4f0cc2a46.png">

you have to give the Server path like in this picture

**Comment by alberttwong** [comment]
I don't have any issues on Mac 10.15.5

**Comment by bvrulez** [comment]
> you have to give the Server path like in this picture

Sorry for the late answer. It does not work on macOS 10.13.6. I am logged in via webGUI on parallel. 


![Bildschirmfoto 2021-01-02 um 16 25 45](https://user-images.githubusercontent.com/7363661/103460584-a0113180-4d17-11eb-9688-37762949489b.png)
![Bildschirmfoto 2021-01-02 um 16 26 36](https://user-images.githubusercontent.com/7363661/103460586-a1425e80-4d17-11eb-9a7c-6fcb95bc194c.png)

**Comment by pbiering** [comment]
was this solved now?

**Comment by tgy** [comment]
yes this was solved
