### ISSUE TITLE
Directly import addressbooks from .vcf file to radicale server

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [Kozea/Radicale#1033]
Are there any direct ways to import addressbooks which are existing in .vcf file to radicale server without using any client.

**Comment by Unrud** [comment]
You can upload files with ˋˋcurlˋˋ. (Search the closed issues this question was answered before.)

The next release of Radicale will contain a upload formular on the web interface.

**Comment by Unrud** [comment]
The feature is included in the new release.
