### ISSUE TITLE
Setting the ID manually

### ISSUE THREAD

**Issue by iot-resister** [Kozea/Radicale#1038]
Once I created a calendar and I set the id myself. Its my ownn self hosted thing so i don't need uuids. 

it was `/resister/coding-calendar ` instead of `/resister/a32e02e3-0868-42ae-8e54-8872f0a063ff`

How did I do that 😅 ?

**Comment by Unrud** [comment]
To change the name rename the folder in the filesystem storage folder.

**Comment by iot-resister** [comment]
on the client?

**Comment by Unrud** [comment]
> on the client?

On the server.

If you want to create a collection with a specific name directly the client must support it. The documentation contains an [example with curl](https://radicale.org/2.1.html#documentation/clients/manual-creation-of-calendars-and-address-books/http-requests-with-curl).

**Comment by iot-resister** [comment]
@Unrud  Thank you so much :D !
