### ISSUE TITLE
radicale v3 integration with external 2FA/SSO using X-Remote-User headers? examples?

### ISSUE THREAD

**Issue by pgnd** [Kozea/Radicale#1045]
I run Radicale, now v3x, behind an Nginx reverse proxy.

My current security protections include 

	-- ssl crt verification from clients
	-- Auth-Basic protection for WebUI Login

Reading at

	https://radicale.org/3.0.html#tutorials/reverse-proxy/manage-user-accounts-with-the-reverse-proxy

> Manage user accounts with the reverse proxy
> 
> Set the configuration option type in the auth section to http_x_remote_user. Radicale uses the user name 
> provided in the X-Remote-User HTTP header and disables HTTP authentication.

Header-based X-Remote-User protection can be provided by external auth systems as well.

e.g., a simple 2FA/SSO provider, Authelia, populates
```
	$_SERVER['HTTP_REMOTE_GROUPS']
	$_SERVER['HTTP_REMOTE_USER']
```

after successful 1FA+2FA credentials submit.

it's trivially set to protect access to any backend @ a reverse-proxy subdomain, e.g.

	https://example.com/radicale

but as for *integrating* with Radicale to *replace* the Auth-Basic protection, AND, more-importantly, NOT screwing up access to DAV clients ...
I'd prefer to get it right and avoid any subtle surprises.

is there a known/working example of using X-Remote-User from an *external* auth system with Radicale in this way?

**Comment by sphakka** [comment]
I guess this is now possible with auth type `http_x_remote_user`. 

I managed to have it _somewhat_ working with [Authelia Trusted Header SSO](https://www.authelia.com/integration/trusted-header-sso/introduction/) via the [standard Nginx example](https://www.authelia.com/integration/proxies/nginx/#standard-example) plus an additional header: 
```nginx
server {
  server_name radicale.*;
  ...

  location / {
    include /config/nginx/snippets/proxy.conf;
    include /config/nginx/snippets/authelia-authrequest.conf;
    proxy_pass http://radicale;
    # This gets rewritten to 'HTTP_X_REMOTE_USER'
    proxy_set_header X-Remote-User $user;     
  }
}
```
That allows logging in to the Web GUI, but, alas, it breaks DAV. So, it would be good to know if there's an explicit DAV endpoint for which a location by-pass can be set.
