### ISSUE TITLE
'Bad value substitution' in rights file (only with the latest version)

### ISSUE THREAD

**Issue by pi-no** [Kozea/Radicale#1046]
I'm using a rights file with some `collection = %(login)s(/.*)?` like in your example. That worked with former versions, but since 2.1.12, I can't access it anymore, but I see this in the logs:

`Error in section 'owner-write' of rights file '...': Bad value substitution: option 'collection' in section 'owner-write' contains an interpolation key 'login' which is not a valid option name.`

**Comment by Unrud** [comment]
Check the version with ``radicale --version``. I think you accidentally updated to 3.0.0 instead of 2.1.12.

**Comment by pi-no** [comment]
Thank you very much!! Yesss, sorry, that's what pip installed me.
