### ISSUE TITLE
No refresh on iOS / iPhone (OS 13)

### ISSUE THREAD

**Issue by safason** [Kozea/Radicale#1048]
After upgrading to 3.0.x, iPhone does not refresh changes made on server by other CalDAV clients ... (write mode iPhone to Radicale works ok)

Reverting back to version 2.1.12 resolved the issue.

**Comment by Unrud** [comment]
Try version 3.0.1, maybe it is caused by #825.

**Comment by safason** [comment]
With version 3.0.1 it works. Thank you @Unrud .
