### ISSUE TITLE
How-to instructions on convert from 1->3  and 2->3??

### ISSUE THREAD

**Issue by canDry** [Kozea/Radicale#1051]
When 2 came out there were instructions on converting from the previous version.  Perhaps I missed it, but where are the instructions?

**Comment by Unrud** [comment]
The instructions for 2 > 3 are in the changelog: https://github.com/Kozea/Radicale/blob/3.0.x/NEWS.md#upgrade-checklist

**Comment by canDry** [comment]
Thanks, sorry I missed the instructions in the changelog.  I'm still running on the latest V1... what would be the easiest route to upgrade to V3?  Must I first convert to V2, or is there a direct way?

**Comment by Unrud** [comment]
You have to upgrade the storage as described for [V1 -> V2](https://radicale.org/2.1.html#documentation/migration-from-1xx-to-2xx/storage). The storage format didn't change in V3.

**Comment by canDry** [comment]
Ok, so I'll use V1 to convert the db to V2 format, then install V3 and see how it goes.   
 
p.s. thanks to you and the team for continuing to maintain and improve this awesome product!
