### ISSUE TITLE
unhandled socket error

### ISSUE THREAD

**Issue by caywin25** [Kozea/Radicale#1062]
hello, 

I have updated my radicale server on 3.0.2 version.
But now I have this issue when I want to check my calendars : 

`Traceback (most recent call last):
  File "/home/user/radicale/lib/python3.8/site-packages/radicale/__main__.py", line 150, in run
    server.serve(configuration, shutdown_socket_out)
  File "/home/user/radicale/lib/python3.8/site-packages/radicale/server.py", line 274, in serve
    raise RuntimeError("unhandled socket error")
RuntimeError: unhandled socket error
`

My python version is 3.8
Thanks for your help

**Comment by caywin25** [comment]
I just went back to version 2.1 and I don't have any more problems.
I don't know if the problem is me or radical.

**Comment by Unrud** [comment]
What operating system and architecture are you using?

**Comment by caywin25** [comment]
Hello, I'm on openbsd amd64.
