### ISSUE TITLE
Import fails with error 400 if .vcf file have at least one record without FM

### ISSUE THREAD

**Issue by uniconstructor** [Kozea/Radicale#1066]
Steps to reproduce:
1) Export contacts from gmail (in vcf fromat)
2) Log in into radicale
3) Select "Upload addressbook or calendar"
4) Upload exported vcf with your contacts
5) Error 400

Error message from logs:

```
Bad PUT request on '/user/container-data/': Failed to serialize item None from 'user/container-data': 'VCARD components must contain at least 1 FN'
```

I've found a workaround for this problem by editing file manually. Deletion of those two records from contacts.vcf makes import run successfully:

```
BEGIN:VCARD
VERSION:3.0
FN:3GB
N:;3GB;;;
TEL;TYPE=CELL:*155*181#
CATEGORIES:myContacts
END:VCARD
BEGIN:VCARD
VERSION:3.0
TEL;TYPE=CELL:4*
CATEGORIES:myContacts
END:VCARD
```

I think that even if Google provides us one or two broken contacts in the export file - this is still should not be a reason to prevent an entire import process.

**Comment by PolGZ** [comment]
You save me. In case anyone goes crazy like me, because they can't find all the contact missing the FN, here's how you look for that on VIM:

/VERSION:3.0\n*\FN\@!

Looks for `VERSION:3.0`, followed by `\n` (a new line) that contains `*` (anything) but FN `\FN\@!`

Cheers!

**Comment by hobofan** [comment]
@PolGZ 

Thanks! I just need to do a small adjustment for the Vim regex:
```
/VERSION:3.0\n\(FN\)\@!
```

**Comment by bgstack15** [comment]
Ah, the related issue #830 states that VCARD format requires a first name field. Of course Google Contacts doesn't conform. Here was my hacky solution for finding the line numbers for the faulty vcard entries:
```
awk 'BEGIN{c=0} /FN:/{a=a+1} /END:VCARD/{b=b+1;if(b>(a+c)){c=c+1;print NR}} END{print a,b}' < contacts.vcf
```

**Comment by rernko** [comment]
I needed /VERSION:2.1\n.*\n[^FN] to search for them in vim. It occurs with records where a name is omitted but ORG is used to store the name.

**Comment by pbiering** [comment]
@rernko has this specific VCF passed validation? 
https://github.com/Kozea/Radicale/wiki/01-%E2%80%90-Reporting-Issues

If no, report issue to client which has generated an invalid VCF.

If yes, report issue to "vobject" because "radicale" is not validating VCF itself.

**Comment by da4089** [comment]
vCard 2.1 requires only the VERSION field: all others are optional, although N _should_ be present (see s2.2.2).  FN is _optional_ (see s2.2.1).

vCard 3.0 requires VERSION, N (name), and FN (formatted name).

I'm curious about the first card above: at first glance, it looks ok.  The second card should fail vCard 3.0 validation.

**Comment by rernko** [comment]
The two validators I found need at least version 4.0 or higher. I have version 2.1 entries. I would expect some backward compatibility, but I don’t know what problems that would create… I also had to change all the ‘BASE64’ entries into ‘B’ and join al the broken lines to make it accept my file.

I am guessing ‘google’ doesn’t like us wondering off and putting our private stuff on our own servers… ;-)

**Comment by pbiering** [comment]
1. "vobject" would need to be extended to accept version 2.1 entries
2. clients have to accept version 2.1 entries and display them and potentially on write update version

"radicale" cannot do anything here

-> please file an issue to "vobject"

**Comment by da4089** [comment]
I have been working towards good vCard 2.1 support in vObject. It's a little complicated in its handling of character encoding.

Once that's done, I'm planning a simple CLI app to enable translation between vCard versions which might be useful in this kind of situation.

**Comment by fdavies93** [comment]
I wrote a quick Python script for anyone else that may have this issue, using `vobject` library - it just reads from a 'bad' vcf file and spits out a 'good' vcf file. You'll need to install `vobject` using pip, probably in a venv.

```py
import vobject

input_path = "contacts.vcf"
output_path = "contacts-clean.vcf"

with open(input_path) as input_file, open(output_path, "w") as output_file:
    cards = vobject.readComponents(input_file)
    while True:
        try:
            card = next(cards)
            card.prettyPrint()
            output_file.write(card.serialize())
        except Exception as err:
            break
```

Note that this will not work if vobject itself finds your cards unacceptable but for me it worked well.

**Comment by clavisound** [comment]
> I wrote a quick Python script for anyone else that may have this issue, using `vobject` library.

Thank you. In my case I didn't have FN, or F fields so I wrote the script to

1. continue if no fields found or
2. with `-o` option use ORG field for FN.

It's here: https://gitlab.com/-/snippets/4896747
