### ISSUE TITLE
radicale won't start due to logging config change in v3 ?

### ISSUE THREAD

**Issue by fredmedia** [Kozea/Radicale#1068]
radicale service complains about having `file` in logging section of config. Is there a new way of doing this in v3? 

/etc/radicale/config
```
[logging]
file = /etc/radicale/logging
```

/etc/raciale/logging
```
[loggers]
keys = root

[handlers]
keys = file

[formatters]
keys = full

[logger_root]
#level = WARNING
level = DEBUG
handlers = file

[handler_file]
class = FileHandler
args = ('/var/log/radicale/radicale.log',)
formatter = full

[formatter_full]
format = %(asctime)s - [%(thread)x] %(levelname)s: %(message)s
```

**Comment by Unrud** [comment]
> Is there a new way of doing this in v3?

It was removed in favor of using the logging facilities of the service manager (e.g. systemd) or the WSGI server (e.g. Apache). (https://radicale.org/3.0.html#documentation/configuration/logging)

**Comment by ell1e** [comment]
Would it be possible to document this? What does that actually mean? Where are the logs now, and how can they be redirected?
