### ISSUE TITLE
Question: Licence of Logo / Allowance of usage

### ISSUE THREAD

**Issue by valoricDe** [Kozea/Radicale#1072]
Hi there, am I allowed to use the logo to integrate radicale as one-click-app into caprover (a docker based app deployment container)?
I could not find the logo in this repository, only on the website and I'm unsure if the website is also under GPLv3

https://github.com/caprover/one-click-apps/pull/133

**Comment by Unrud** [comment]
> Hi there, am I allowed to use the logo to integrate radicale as one-click-app into caprover (a docker based app deployment container)?

Yes, this shouldn't be an issue.

**Comment by valoricDe** [comment]
Nice
