### ISSUE TITLE
Update client documentation for Gnome Evolution

### ISSUE THREAD

**Issue by dilyanpalauzov** [Kozea/Radicale#1074]
Please update the information at https://radicale.org/master.html#documentation/supported-clients about Gnome/Evolution. Users shall create one 'Collection account' and it will contain all addreeabooks and calendars.

**Comment by ialokim** [comment]
I tried to add my Radicale account in Evolution using the 'Collection account', but I was not able to do so. Is there any special trick needed to get it working?

Btw, this is a duplicate of #1057.

**Comment by dilyanpalauzov** [comment]
It should work without special tricks.

**Comment by ialokim** [comment]
Just for the record, Evolution seems to have a bug when using e-mail addresses as usernames: Instead of sending the whole e-mail address, it removes the domain and therefore authorization is not possible. I'll probably open an issue over there.

**Comment by dilyanpalauzov** [comment]
This was addressed in https://gitlab.gnome.org/GNOME/evolution/-/issues/610#note_598801 .

**Comment by ialokim** [comment]
Wow, true, I'm still using an older version. Thank you very much!
