### ISSUE TITLE
3.0: Error: 401 Unauthorized for additional users

### ISSUE THREAD

**Issue by bstabens** [Kozea/Radicale#1075]
I'm using htpasswd-authentication with md5 encryption. I created five users (one, two, three and so on) with differing passwords.
I can login as the first created user, One. If I try to authenticate as Two, I get an Error: 401 Unauthorized. 
If I now connect to the radicale server and repeat 
htpasswd -c /path/to/userfile Two
to re-set the password, I'm able to login with user Two/PasswordTwo, but now user One will get the unauthorized message.
So to me it seems Radicale 3.0 will only store one password/user at a time? 
I can not login using user One and PasswordTwo or any other connection.
[config.txt](https://github.com/Kozea/Radicale/files/4858171/config.txt)

**Comment by jonassmedegaard** [comment]
Might be a problem with the client you use.

I suggest you try test with curl or wget, and share here the exact commands you used and how they fail.

**Comment by bstabens** [comment]
Found out htpasswd will only store one entry. Using a secondary file and copying over works now.

**Comment by jonassmedegaard** [comment]
Quoting bstabens (2020-07-01 15:42:59)
> Found out htpasswd will only store one entry. Using a secondary file and copying over works now. 

Maybe you used the option "-c" which _creates_ the file?

Generally it is a good idea to share exact commands you use, not (only) your interpretation of what is happening.

**Comment by bstabens** [comment]
Ouch! Yes, I literally did, even mentioned it in my original post. Maybe I need a second pair of glasses...

**Comment by jonassmedegaard** [comment]
Quoting bstabens (2020-07-01 17:49:45)
> Ouch! Yes, I literally did, even mentioned it in my original post. Maybe I need a second pair of glasses...

Heh, then it seems I need a second pair as well :-D

**Comment by pbiering** [comment]
assuming solved since longer time
