### ISSUE TITLE
List of all accessible calendars

### ISSUE THREAD

**Issue by peetervois** [Kozea/Radicale#1076]
Hello, I have been playing around with radicale 2.1. I was browsing a little about reports, if there is something similar already reported and did not find. So, please excuse me if this is duplicate.

I am verifying if the server supports my needs and I see that it is almost there. It took a while to get the ssl working and to get to know how to order the records in the right file. It seems that the first match to rights record is used and rest is ignored. Thus I have the rights file that gives readwrite access to users own collections and readwrite acces to collections of user 'common' for the users 'theonename' and 'theanothername'. The rights file contains:

```
[owner-write]
user: .+
collection: %(login)s(/.*)?
permission: rw

[common-write]
user: theonename|theanothername
collection: common(/.*)?
permission: rw

[read-root-collection]
user = .+
collection =
permission = r
```

It is ok to log in as user 'common' and create and manage the calendars in the server. What I am missing is to see list of ALL available calendars when logging as the user 'theonename'. Currently radicale does list only the calendars of 'theonename' but the calendars of 'common' are not listed. I mean that they are not listed on the web frontend and it also seems that they are not listed over CalDAV connection. With Thunderbird@Lightning, I can register into specific calendar by providing full path for the calendar of user 'common' while adding the calendar into list of calendars. With OneCalendar I can see only the calendars that are listed when connected with my user (similar to the web frontend) and I have no possibility to give direct link to the calendar. 

Although from one side it seems to be like a client issue, from another side it is more like generic usability issue.

I would very much get the full list of accessible calendars. It seems like I can not bypass this issue.

Is there any plans to list all accessible calendars for the user? Or is it a big task to implement? Or is it violating some standards? Or... ? 

Thanks for reading this far.

**Comment by jonassmedegaard** [comment]
> Is there any plans to list all accessible calendars for the user? Or is it a big task to implement? Or is it violating some standards? Or... ? 

In my understanding, this is a (quite common) client issue - i.e. server _does_ permit access to URLs outside of users' own base URL, but Lightning is unusual in using explicit URLs where the common approach is to resolve URLs derived from base URL.

My workaround so far is to add symlinks server-side for each calendar that should be shared.

**Comment by peetervois** [comment]
I tried the symlinks too and was able to see and use the calendars. At the same time I was puzzled that it would give read-write permission to that calendar. I forgot to mention the read-only case in my initial message. For example: when 'theanotheruser' would have read-only access to 'theoneuser' calendars. 

I think that in short-term I will also use the symlink approach and instruct users to handle carefully the other user's calendars.

Just for an idea: maybe the file **.Radicale.props** shall contain list of users and access permissions for that user, like:

``` json
{
   "C:calendar-description": "My specific description", 
   "C:supported-calendar-component-set": "VEVENT,VJOURNAL,VTODO", 
   "D:displayname": "Peeter", 
   "ICAL:calendar-color": "#65d96eff", 
   "tag": "VCALENDAR",
   "permissions": [
       { "user":"theusername", "rights":"r" }, 
       { "user":"anotheruser", "rights":"rw" }, 
       { "user":".+", "rights":"r", "placeholderonly":true }
    ]
}

```

The specific user 'theusername' has read only rights. The specific user 'anotheruser' does have read and write rights. The other authorized users will see only placeholders and no contents of the entries.

**Comment by jonassmedegaard** [comment]
Please beware that this is an issue tracker, not a support forum: It is much easier to process if filing each individual issue separately.

**Comment by peetervois** [comment]
Thanks, I was not trying to confuse and I was thinking that it is much of the same issue I am puzzled with. The idea part is too much extra ofcourse.
