### ISSUE TITLE
add manual ics / replace generated ics?

### ISSUE THREAD

**Issue by prankousky** [Kozea/Radicale#1077]
Hi,

I have set up `radicale` on a VPS to synchronize calendars between our household and the neighbors'. We all share the same login for a particular calendar (later there will be individual calendars with separate logins as well).

Radicale crated this in the `data` folder linked to the docker container: `collections/collection-root/<everybody>/<snsnnns-ssnn-snns-snnssssnsnnn>` s being letters, d being numbers. Inside this folder, there are

```
<same-as-directory>.ics
<ddssdsds-dddd-ssdd-sdsd-dsddsssddddd>.ics
.Radicale.cache/
.Radicale.props
```

This calendar currently has two events; I assume each event is it's own .ics file? At least when I `cat` each .ics file, each one contained one event...? The calendar is set to `[calendar, journal and tasks]`.

I then created another calender via webUI as the <everbody> user. I synced this (then empty) calendar with my phone, and it created a template .ics file in the folder that had been created for that calendar.

When I exchange this template .ics file for another ics, I will get `Error 500` when I try syncing via `Davx5`. When I add another .ics (and keep the .ics template), there will also be an error 500.

I'd like to do the following, which I have scripted successfully so far except for the part where the .ics file can be synced via davx5.

* curl an .ics file from our garbage collector's schedule website
* run `awk` on this file adding reminders to each event (this is why I am doing this!)
* copy the modified .ics file with added reminders to the appropriate directory 
* sync via davx5

Why? Our garbe collector does provide an .ics calendar people can subscribe to, **but** it is read-only, so if you use, for example, `ICSx5` to subscribe to this calendar, you will neither have any alerts / reminders for these events by default, **nor** will you be able to create those - and even if you were, you'd have to do it for every single event, as those events are individually set (not one event that repeats by a set pattern where the reminder would automatically be set for every single repetition).

Currently, I have my script set so that this file will be downloaded, modified, then pushed to my **local** server, then `ICSx5` syncs from my local server. However, now that other people will be using it as well, I thought I'd put it on the VPS, and since we're using radicale already, we might be able to integrate it this way.

Is this possible? Can I somehow manually the .ics file that had been created by radicale without getting this 500 error when trying to sync? If so, what do I have to watch out for? 

Thank you for your help :)

**Comment by pbiering** [comment]
closing after many years, if still an issue, please re-open but also provide server logs.
