### ISSUE TITLE
Disable deprecated TLS protocols

### ISSUE THREAD

**Issue by krathalan** [Kozea/Radicale#1083]
Is there a way to disable deprecated TLS protocols? Using https://testssl.sh/ I can see that the radicale web interface on my server supports TLS v1-1.3. I would like to disable all TLS versions except for 1.2 and 1.3, as prior versions are deprecated and do not support modern encryption algorithms, perfect forward secrecy, etc. (https://www.ghacks.net/2018/10/16/all-major-browsers-drop-tls-1-0-and-1-1-in-2020/)

Edit: this question applies to both the web interface and actual DAV sync.

**Comment by Unrud** [comment]
There is no settings for this, we use the defaults provided by Python: https://github.com/Kozea/Radicale/blob/f3b6b4869d53ee368235732b3496a848baa0126e/radicale/server.py#L129

You would need to add something like:

```python3
context.options |= ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1
```

**Comment by krathalan** [comment]
It would be great to have a setting for this, as most other server software that uses HTTPS does (apache, nginx, postfix, dovecot). There's more examples at https://ssl-config.mozilla.org/

**Comment by krathalan** [comment]
Hi, it seems after doing some more research the best way to do this is a reverse proxy with nginx or another web server. I use nginx and was having trouble getting the right config to work, but I figured it out after some fiddling and this was my result: 

```
  # Reverse proxy for Radicale DAV server
  location /radicale/ {
    proxy_pass           http://localhost:5232/;
    proxy_set_header     X-Script-Name /radicale;
    proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header     X-Remote-User $remote_user;
    proxy_set_header     Host $http_host;
    auth_basic           "Radicale DAV: please sign in";
    auth_basic_user_file /etc/krathalan/users;

    # Stop BREACH
    brotli off;
    gzip off;
  }
```

You can see my full config at [https://git.sr.ht/~krathalan/etc-config/tree/master/item/nginx/sites-available/default](https://git.sr.ht/~krathalan/etc-config/tree/master/item/nginx/sites-available/default), but that is the relevant snippet. The 5232 port is where radicale is being hosted locally; check `/etc/radicale/config` for your port if you've changed it from the default. `/etc/krathalan/users` is where my `htpasswd` file is.

Then in `/etc/nginx.conf` you can put something like:

```
http {
  # SSL: follow Mozilla nginx intermediate https://ssl-config.mozilla.org/
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers on;
  ...
```

And/or whatever other SSL settings you desire.

**Comment by pbiering** [comment]
since 3.3.1 TLS protocols and cipher suites can be specified
