### ISSUE TITLE
Debian (Wheezy) with SysV and Radicale

### ISSUE THREAD

**Issue by kittonian** [Kozea/Radicale#1085]
Radicale has been an amazing solution for our small business, and we are using it to interface our Mac OS X desktop clients, with our iOS devices (iPhone and iPad), however, our server is running an older version of Debian (Wheezy) and cannot make use of the latest SystemD integration.

**Please note:** We are unable to upgrade the server due to other critical server software running on the same server, but have Python3 and Radicale running. In fact, we've been using Radicale since v2.x, and no, we do not wish to downgrade to an older version, potentially losing new security updates and features. As Radicale 3.x runs on this server just fine, and it is only the systemd and logging configurations that are the issues at hand, we are only interested in sticking with the latest builds.

Unfortunately, the idea of removing the ability to daemonize Radicale, and specify a logfile location, has made the following next to impossible:

1. As we cannot use systemd, an init.d script does nothing more than running python3 -m radicale & from the command line. You cannot use the start-stop-daemon with a python statement such as this (at least as far as I know), and the start_daemon doesn't write the pidfile, even with the -p operator.

2. If we can no longer specify a logfile, and cannot use systemd, we have no way to monitor the logs and check for any errors. In fact, when I was working through these issues yesterday, after rebooting our server for the first time in over 250 days, the only way I was able to get Radicale running was to first run it in debug mode (python3 -m radicale --debug). Only then would it properly start up with just the python3 -m radicale command, and of course to ensure that it returns us to a command prompt, we run it via python3 -m radicale & and then have to logout of the ssh session so we don't constantly receive the logging to stderr.

Both of these seem to be big misses on the part of the dev team. I'm all for implementing new technologies, but most all server software has the ability to be daemonized and allows you to specify where you wish to write your log files. I would ask that you reconsider this move and add back in these abilities.

That being said, I would really like to get Radicale back and running in the best way possible right now, so I am certainly open to suggestions in the meantime. I have tried asking in the ##kozea freenode channel for the past two days, but no one of any consequence is present. Also, your forums are offline. This is why I am now posting here.

**Comment by felixfontein** [comment]
As I mentioned on ##kozea, installing supervisord and running radicale with it might solve this without needing to upgrade the OS. 

Also, please note that the extended LTS support for Debian Wheezy ended in June 2020, so not receiving security updates for Radicale might be the least of your problems.

**Comment by kittonian** [comment]
> As I mentioned on ##kozea, installing supervisord and running radicale with it might solve this without needing to upgrade the OS.
> 
> Also, please note that the extended LTS support for Debian Wheezy ended in June 2020, so not receiving security updates for Radicale might be the least of your problems.

While it "might" solve this, it would be much better to just add the ability to daemonize and specify a logfile back into Radicale. Also, we manually compile most everything we use on this server so the OS has little to do with anything, other than ensuring that we can run some legacy server software we require.

**Comment by ehem** [comment]
> 1. As we cannot use systemd, an init.d script does nothing more than running python3 -m radicale & from the command line. You cannot use the start-stop-daemon with a python statement such as this (at least as far as I know), and the start_daemon doesn't write the pidfile, even with the -p operator.

Having run into this myself (I found #1183 first), `start-stop-daemon` has a "-b" option which makes it run the program in the background (adequate for a workaround).  `start-stop-daemon` will also pass anything after "--" to the invoked program, so combined with "--exec" you can run almost any command.

> 2. If we can no longer specify a logfile, and cannot use systemd, we have no way to monitor the logs and check for any errors. In fact, when I was working through these issues yesterday, after rebooting our server for the first time in over 250 days, the only way I was able to get Radicale running was to first run it in debug mode (python3 -m radicale --debug). Only then would it properly start up with just the python3 -m radicale command, and of course to ensure that it returns us to a command prompt, we run it via python3 -m radicale & and then have to logout of the ssh session so we don't constantly receive the logging to stderr.

This though is a Problem.  The documentation needs to state only SystemD is allowed if the Radicale developers have made that decision.  Perhaps rename it "SystemD-Radicale" to emphasize the point?

Logging to standard output/error is **not** standard.  Daemons are supposed to either use syslog, or manage logs themselves.

> Both of these seem to be big misses on the part of the dev team. I'm all for implementing new technologies, but most all server software has the ability to be daemonized and allows you to specify where you wish to write your log files. I would ask that you reconsider this move and add back in these abilities.

Seconded.

**Comment by kousu** [comment]
Logging to stderr **is** becoming standard. I discovered in #1194 that even OpenBSD got on board [last year](https://www.openbsd.org/plus69.html), where you basically just need to set this:

```
echo radicale_logger=daemon.info | doas tee -a /etc/rc.conf.local
```

Otherwise, it's 2022 now and all the major Linux distributions are on systemd (love it or hate it -- I certainly have lots of gripes with it), and cloud-y deployments are mostly using some variant of docker which also records stderr to its logs.

If you're supporting a SysV system, you can still log to stderr via [logger(1)](https://manpages.debian.org/bullseye/bsdutils/logger.1.en.html); just write a wrapper for `radicale` that reads:

```
#!/bin/sh

radicale "$@" 2>&1 | logger -ip daemon.info -t radicale
```

and point your sysvinit script at that instead.
