### ISSUE TITLE
Tutorial for 2.1 installs 3.0

### ISSUE THREAD

**Issue by hcgrove** [Kozea/Radicale#1088]
The title pretty much says it all, but with a few more details:

In [the tutorial on the 2.1 page](https://radicale.org/2.1.html#documentation/tutorial) the python command used to install radicale is the same as in the tutorial for 3.0, and executing it results in the installation of 3.0.3 (from last line in the output).

As I need the same version as in the debian package that's quite annoying.

**Comment by Unrud** [comment]
```bash
python3 -m pip install --upgrade radicale==2.1.*
```

**Comment by Unrud** [comment]
Fixed in 81911eaa49702d9540075ad9754ac4bb07024c0e and 7f587c5438efa16a8a04ddf562aacc8d08ad6a39.
