### ISSUE TITLE
iCal v7.0 - color of calendar resets on sync

### ISSUE THREAD

**Issue by gregorvolkmann** [Kozea/Radicale#109]
I can change the colors of my calendars in iCal, but when it starts to auto-sync with Radicale (0.8), Radicale sets back the color of my calendars.

**Comment by mcantsin** [comment]
I am using [radicale 0.9-1 on GNU/Linux Debian 8.0 (jessie)](https://packages.debian.org/jessie/radicale) and still have the same issue.
