### ISSUE TITLE
Support for systemd socket activation

### ISSUE THREAD

**Issue by Boris-de** [Kozea/Radicale#1090]
Hello,

when checking if systemd socket activation was supported by radicale and I found 2275ba4f9323e87eeac61f8811a4cc2773061e70 which added support for socket activation, but then I realized that 66fabbead9027495fb526b482606c295d84818eb (_"Use socket pairs to communicate with client threads"_) seemed to remove it again.

Is that something that was done on purpose or was it just lost when doing the latter change? I'd love to have that and would have a look at it unless there's a good reason not to.

Cheers,
Boris

**Comment by Unrud** [comment]
It was removed to keep things simple. You can use a "real" WSGI server like **Gunicorn**, **uWSGI** or **Apache**. They all support socket activation.

**Comment by Boris-de** [comment]
Oh, of course. I didn't even think about that because I was always running it standalone (behind an httpd). I think that will be good enough for me, thanks for the hint :)
