### ISSUE TITLE
Migrating from 1.x with --export-storage IsADirectoryError

### ISSUE THREAD

**Issue by tilkov** [Kozea/Radicale#1098]
Hi, following the upgrade guide from 1.x to the new storage format and i am stuck:

Error while reading item '/var/lib/radicale/collections/collection-root': IsADirectoryError(21, 'Is a directory')

Inside this folder i have all my user's folders with addresses and calendars. What i am doing wrong?

Ubuntu 18.04, Python 3.6.9, Radicale 1.1.7 installed with pip3 in a venv

[storage]
type = multifilesystem
filesystem_folder = /var/lib/radicale/collections

**Comment by Unrud** [comment]
> Error while reading item '/var/lib/radicale/collections/collection-root': IsADirectoryError(21, 'Is a directory')

This folder should not exist in Radiale 1 storage. It was introduced in Radicale 2.

**Comment by tilkov** [comment]
Thank you, Unrud,

That system was a mess of APT and PIP installed versions of Radicale. Indeed the storage was from 2.x and i was trying to run 1.x on it.
