### ISSUE TITLE
Error with parameter '--server-hosts' on Windows 7

### ISSUE THREAD

**Issue by Computadoralibre** [Kozea/Radicale#1099]
Try to run Radicale v3.0.5 on Windows 7 and --server-hosts 0.0.0.0:5232, returns error "[Errno 11004] getaddrinfo failed'. Well complete error:

"[2020-09-07 19:25:59 -0300] [5136] [CRITICAL] An exception occurred during serve
r startup: Failed to start server '[0.0.0.0]:5232': [Errno 11004] getaddrinfo fa
iled"

It's seems like a bug in the current version. Going to try an older version to see.

**Comment by Unrud** [comment]
I can't reproduce the problem on Windows 10. Unfortunately I don't have Windows 7.

**Comment by Computadoralibre** [comment]
Versión 2.1.0 works in Windows 7
