### ISSUE TITLE
iCal v5.0.3 can't fetch Accountinformations from Server

### ISSUE THREAD

**Issue by gregorvolkmann** [Kozea/Radicale#110]
On setting up my new account for calendar, the Servers debug info gives:

> 2014-02-05 22:29:20,387 - DEBUG: Sanitized path: /user/calendar.ics/
> 2014-02-05 22:29:20,388 - DEBUG: Anonymous has read access to collection gregor/calendar.ics/
> 2014-02-05 22:29:20,389 - DEBUG: Anonymous has write access to collection gregor/calendar.ics/
> 2014-02-05 22:29:20,389 - DEBUG: Answer status: 200 OK

But iCal won't finish the account Setup with the error: "The Accountinformation could not be found."

The same accountSetup *works* with iCal v7.0. Still, the account is unusable in both versions.

This Issue is new since the previous "stable" commit: https://github.com/Kozea/Radicale/commit/e2dbdd4d9669b86e604bf7534735162cabf4b84e

**Comment by liZe** [comment]
Is this issue fixed?

**Comment by gregorvolkmann** [comment]
I moved to another software.
