### ISSUE TITLE
Possible SSL Certificate Issue when using Thunderbird 72+

### ISSUE THREAD

**Issue by nyclabels** [Kozea/Radicale#1103]
Issue raised on the TB bug forum (https://bugzilla.mozilla.org/show_bug.cgi?id=1660859), but in short with the new versions of Thunderbird it kicks up an error when using SSL on Radicale. 

Thunderbird appears to load the correct certificate (either signed by a local CA or by a "Big Name" CA), but I'm unsure if Radicale is sendiding the correct information to TB and TB is broken, or if Radicale isn't sending the correct information.

I will be spinning up an Internet accessible server for testing on the TB side of things, will provide credentials here once completed.

**Comment by logological** [comment]
Any update on this, @nyclabels? Presuming it was you who filed the bug on the Thunderbird Bugzilla, I tried contacting you there five months ago for further details but so far haven't received any response.  I'm experiencing a similar issue ([Thunderbird Bug 1666871](https://bugzilla.mozilla.org/show_bug.cgi?id=1666871)) and it would be nice to know if our problems are the same and, if so, whether we might work together to identifying the cause or a workaround.

**Comment by tyll** [comment]
For me it worked on Fedora 33 with thunderbird-78.8.1-1.fc33 with a hostname for the Radicale server and a self-managed CA (using XCA) that I imported into Thunderbird.

**Comment by nyclabels** [comment]
Sorry, no updates. I wound up moving to just normal HTTP instead of HTTPS
as a workaround (since all traffic is internal to the LAN), and never got a
chance to test it further with COVID basically stopping all changes in the
environment.

**Comment by ehem** [comment]
Might this be related to bug #1183?  #1183 has an actual error message from distinct clients.  If these are the same bug, might SSL/TLS simply be completely broken in Radicale v3.0?

**Comment by logological** [comment]
I believe I may have discovered the cause and a workaround for this issue—see [Bug 1666871 Comment 27](https://bugzilla.mozilla.org/show_bug.cgi?id=1666871#c27) on the Mozilla Bugzilla.  Could those affected by this issue please try the workaround and report whether it solves the issue?  If so, then the cause seems to be a problem not with Radicale but with Thunderbird/Lightning writing the wrong port number to its certificate exception file.
