### ISSUE TITLE
3.0.6: need clarfication about strange log entry

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#1106]
Hi,

during creation of a new event I got following in log:

```
[INFO] Rights: 'user':'user/Peter.ics/******-a8b9-45d2-bb86-e59a7449058d.ics' doesn't match any section
[INFO] PUT response status for '/user/Peter.ics/******-a8b9-45d2-bb86-e59a7449058d.ics' in 0.075 seconds: 201 Created
```

another entry with debug enabled:
```
[DEBUG] Sanitized script name: ''
[DEBUG] Sanitized path: '/user/Peter.ics/***-3674-49f8-bd06-7508174ef011.ics'
[INFO] Successful login: 'user'
[DEBUG] Rule 'user':'user/Peter.ics/***-3674-49f8-bd06-7508174ef011.ics' doesn't match '.+':'' from section 'root'
[DEBUG] Rule 'user':'user/Peter.ics/***-3674-49f8-bd06-7508174ef011.ics' doesn't match '.+':'{user}' from section 'principal'
[DEBUG] Rule 'user':'user/Peter.ics/***-3674-49f8-bd06-7508174ef011.ics' doesn't match '.+':'{user}/[^/]+' from section 'content'
[INFO] Rights: 'user':'user/Peter.ics/***-3674-49f8-bd06-7508174ef011.ics' doesn't match any section
[DEBUG] Rule 'user':'user/Peter.ics' doesn't match '.+':'' from section 'root'
[DEBUG] Rule 'user':'user/Peter.ics' doesn't match '.+':'{user}' from section 'principal'
[DEBUG] Rule 'user':'user/Peter.ics' matches '.+':'{user}/[^/]+' from section 'content'
...
[INFO] PUT response status for '/user/Peter.ics/***-3674-49f8-bd06-7508174ef011.ics' in 0.061 seconds: 201 Created
```

Makes the "doesn't mach any section" sense in combination with allowed PUT?

It it working as expected (event is created), but then the "Rights" log message then makes not much sense imho.

rights is configured according to example:

```
[root]
user: .+
collection:
permissions: R
  
# Allow reading and writing principal collection (same as user name)
[principal]
user: .+
collection: {user}
permissions: RW

# Allow reading and writing calendars and address books that are direct
# children of the principal collection
[content]
user: .+
collection: {user}/[^/]+
permissions: rw
```
Any mistake by me?

**Comment by Unrud** [comment]
> Makes the "doesn't mach any section" sense in combination with allowed PUT?

For PUT requests the permissions of  `/user/Peter.ics/***-3674-49f8-bd06-7508174ef011.ics` and `/user/Peter.ics` are checked. This is required because we initially don't know if the uploaded file is supposed to a new/changed entry in an existing calendar or a whole calendar itself.

> Any mistake by me?

No.

**Comment by pbiering** [comment]
What is then  the recommendation? Extending the "rights" file or changing log level from "info" to "debug" for that particular message type as it is not containing any helpful information imho.

**Comment by Unrud** [comment]
> What is then the recommendation?

Ignore the log message.

> changing log level from "info" to "debug" for that particular message type as it is not containing any helpful information imho.

We don't know if the log message will be useful when we are writing it. We can only decide that after we acquired the storage lock and all further checks are completed. In theory we could defer the message and output it at a later stage but I don't think that's worth the hassle.

**Comment by pbiering** [comment]
it disappeared after rights file got some extension and looks like the following now - perhaps you have additional hints regarding applying RWrwi for the related parts...


```
[root]
user: .+
collection:
permissions: R

[principal]
user: .+
collection: {user}
permissions: RW

[calendarfolders]
user: .+
collection: {user}/[^/]+.ics
permissions: rw

[addressbookfolders]
user: .+
collection: {user}/[^/]+.vcf
permissions: rw

[calendarcontent]
user: .+
collection: {user}/[^/]+/[^/]+.ics
permissions: rw

[addressbookcontent]
user: .+
collection: {user}/[^/]+/[^/]+.vcf
permissions: rw
```

**Comment by Unrud** [comment]
Remove the following rules:

```
[calendarcontent]
user: .+
collection: {user}/[^/]+.ics/[^/]+.ics
permissions: rw

[addressbookcontent]
user: .+
collection: {user}/[^/]+.vcf/[^/]+.vcf
permissions: rw
```

Radicale 3 rights only work with collections (folders). When a collection has "rw" permissions (and a calendar/address book was created at the path) access to the content (files) is granted (without additional rules in the rights file).

**Comment by pbiering** [comment]
Hmm, if I remove them, then the strange info message reappears
```
[INFO] Rights: 'user':'user/Peter.ics/***-54b1-41f1-80d4-437743aea108.ics' doesn't match any section
```
so they are at least helpful to get this particular info message disappeared...
