### ISSUE TITLE
iCal v7.0 can't fetch correct calendar location / base

### ISSUE THREAD

**Issue by gregorvolkmann** [Kozea/Radicale#111]
Account setup works with iCal v7.0, but on sync the server doesn't accept the calendar's location:

> The server specified an invalid calendar location (base?).
> For the account "**Accountname*" was no calendar location specified.

When you try to create a new calendar, the logs get a massive error:

> Calendar: Core Data: warning: validation recovery attempt FAILED with Error Domain=NSCocoaErrorDomain Code=1570 "calendarPath is a required value." UserInfo={ […]NSValidationErrorKey = calendarPath;[…]}

The account is unusable in iCal.

This Issue is new since the previous "stable" commit: https://github.com/Kozea/Radicale/commit/e2dbdd4d9669b86e604bf7534735162cabf4b84e

**Comment by liZe** [comment]
Is this fixed with 0.10?
