### ISSUE TITLE
Radicale web interface requires 2 logins

### ISSUE THREAD

**Issue by TonyMorehen** [Kozea/Radicale#1114]
Radicale 3.0.6 on Manjaro kernel 5.8.11, Apache 2.4.46
I have Radicale running as a wsgi app under Apache, which handles ssl and authentication.  Direct access to calendars works fine ie https://davserver.ajmconsulting.ca/tony/00fccb3a-416f-a99b-c699-5ba2944a4f65/ with an appropriate authentication header works properly.
However, if a user uses a browser to go to https://davserver.ajmconsulting.ca, he will be shown the standard popup login prompt and then, after a successful login, shown radicale's login page, as if the first, successful login never happened.

**Comment by pbiering** [comment]
is this now fixed or still an issue?
