### ISSUE TITLE
radicale rights file and case-sensitive issue

### ISSUE THREAD

**Issue by vijaysar** [Kozea/Radicale#1118]
Looks like the rights file regex is compared case-sensitive by default.  We have users whose URL is http://calurl/user/user.ics but the user is allows to login with credentials of User or usEr without any case checking.  Is it possible to support this in rights file?  Or in the code you could check regex match with 
```
re.IGNORECASE
```
flag.  The later seems like a good long term option.

**Comment by GuruSR** [comment]
Suggestion:  Add a flatten (all lowercase) or raise (all uppercase) to the username at login, ignoring case is fine for just all lowercase, but in some instances having the ability to do 2 of the same ID can be useful:  USER would be easier to read in a list than user, especially with logins with i and l's in them, their uppercase counterparts are typically easier to read when looking for something manually.

**Comment by pbiering** [comment]
There is already a option converting usernames to lower case, can be enabled if required

https://github.com/Kozea/Radicale/blob/master/DOCUMENTATION.md#lc_username

Does this not already help?

**Comment by GuruSR** [comment]
No, there was no issue, was just a suggestion to offer lowercase and uppercase as 2 options, not just lowercase.

**Comment by pbiering** [comment]
fixed now
