### ISSUE TITLE
Discover shared calenders

### ISSUE THREAD

**Issue by har0ke** [Kozea/Radicale#1123]
Is it a design choice not to detect readable calendars outside of `/USERNAME/`? 

And concerning data races: It is probably not safe to symbolically link a calendar to a user's folder to bypass said limitation?

**Comment by fschrempf** [comment]
> Is it a design choice not to detect readable calendars outside of `/USERNAME/`?

I was wondering the same thing.

**Comment by tyler71** [comment]
> Is it a design choice not to detect readable calendars outside of /USERNAME/?

https://radicale.org/3.0.html#documentation/configuration/rights/type
```
The backend that is used to check the access rights of collections.

The recommended backend is owner_only. If access to calendars and address books outside the home directory of users (that's /USERNAME/) is granted, clients won't detect these collections and will not show them to the user. Choosing any other method is only useful if you access calendars and address books directly via URL.

Available backends:

authenticated : Authenticated users can read and write everything.

owner_only : Authenticated users can read and write their own collections under the path /USERNAME/.

owner_write : Authenticated users can read everything and write their own collections under the path /USERNAME/.

from_file : Load the rules from a file.

Default: owner_only
```

> And concerning data races: It is probably not safe to symbolically link a calendar to a user's folder to bypass said limitation?

This is what I do and I've never run into a problem, I don't have anything to point to, but I believe it's an accepted way to share calendars and such.
I believe storage is locked during any change. This link refers to manual / plugin modification
https://radicale.org/3.0.html#documentation/storage/locking

**Comment by pavinjosdev** [comment]
> Is it a design choice not to detect readable calendars outside of /USERNAME/?

Yes, it seems from the Radicale [docs](https://radicale.org/3.0.html#documentation/storage/manually-creating-collections).

`Calendar and address book collections must not have any child collections. Clients with automatic discovery of collections will only show calendars and address books that are direct children of the path /USERNAME/.`

> And concerning data races: It is probably not safe to symbolically link a calendar to a user's folder to bypass said limitation?

I have tested and found no issues with simultaneous access to a symlinked shared calendar, using this in production where calendars are shared with up to 50 people.

**Comment by dstrelnikov** [comment]
That would be really amazing to make other user's calendars discoverable provided the corresponding rights are set.

**Comment by pbiering** [comment]
Collection sharing is documented now here https://github.com/Kozea/Radicale/wiki/Sharing-Collections - that's the only method which is currently possible.
