### ISSUE TITLE
Bug after plain install 

### ISSUE THREAD

**Issue by xerostomus** [Kozea/Radicale#1127]
I run: 

    sudo apt install radicale

after I run:

$ radicale

```
Traceback (most recent call last):
  File "/usr/bin/radicale", line 32, in <module>
    radicale.__main__.run()
  File "/usr/lib/python2.7/dist-packages/radicale/__main__.py", line 210, in run
    log.start()
  File "/usr/lib/python2.7/dist-packages/radicale/log.py", line 54, in start
    configure_from_file(filename, debug)
  File "/usr/lib/python2.7/dist-packages/radicale/log.py", line 40, in configure_from_file
    logging.config.fileConfig(filename)
  File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/log/radicale/radicale.log'

```
It is not a correct output, is it?

**Comment by jonassmedegaard** [comment]
This bugtracker is for Radicale released independently.

When you use apt to install radicale, it implies that you install if via some Debian-based distribution.
Please report bugs in such package at the distribution that you use.

E.g. if you use Debian itself, then see https://bugs.debian.org/radicale

**Comment by xerostomus** [comment]
Thank you for your answer. I am a bit lost in these rules...

Anyway, I installed Radicale via python. It works ok. I only had problems with 
[2020-12-31 21:09:28 +0100] [11749] [CRITICAL] Invalid configuration: Invalid section 'well-known' in config file '/etc/radicale/config'

I had to comment with # sections [well-known] and [git].  Please if you can remove this mistake. It is puzzling for a newbe like me. 

Thank you anyway for the great program. :-)

x.

**Comment by pavinjosdev** [comment]
> Thank you for your answer. I am a bit lost in these rules...
> 
> Anyway, I installed Radicale via python. It works ok. I only had problems with
> [2020-12-31 21:09:28 +0100] [11749] [CRITICAL] Invalid configuration: Invalid section 'well-known' in config file '/etc/radicale/config'
> 
> I had to comment with # sections [well-known] and [git]. Please if you can remove this mistake. It is puzzling for a newbe like me.
> 
> Thank you anyway for the great program. :-)
> 
> x.

I believe the config file was added when the radicale package was installed from apt. When installing using pip, for example, it doesn't generate a config file automatically. Radicale's major versions are not backward compatible, so the error with the old config file format is expected.

**Comment by xerostomus** [comment]
Yes, I understand. But anyway I still use Radicale for my PC Calender. Only synchronization with android is somehow crapy... :-)
