### ISSUE TITLE
Password file permission denied - Which user is reading it?

### ISSUE THREAD

**Issue by bvrulez** [Kozea/Radicale#1130]
I wanted to point out a problem in the description. I did not manage to get the `htpasswd` thing set up the first time I tried this months ago. 

The problem seems to be that the password file has to be readable to the the user running the server. While the server gets run by a normal user in the test sequence from command line it later will be run by user `radicale`. User `radicale` will probably not have access to the password file if it is in the home folder of the user it was created from. So I created this file in my user's folder, applied `sudo chown radicale:radicale FILE` and then moved it to `/home/radicale`.

**Comment by bvrulez** [comment]
Actually, this does not work as expected. I though it had worked previously. Now I get this error which I don't understand because the systemd `radicale.service` is running as `User=radicale`:  

`Jan 02 15:38:42 raspberrypi env[1751]: [2021-01-02 15:38:42 +0100] [1751/Thread-2] [ERROR] An exception occurred during GET request on '/favicon.ico': Failed to load htpasswd file '/home/radicale/passwords': [Errno 13] Permission denied: '/home/radicale/passwords'`

**Comment by bvrulez** [comment]
I just found in the text: 

"First a users file with all user names and passwords must be created. It can be stored in the same directory as the configuration file."

So I tried putting the password file into `/etc/radicale` and this worked. But I think it is a bit weird that it only works there, since a configuration file could also be put anywhere else...

**Comment by felixfontein** [comment]
@bvrulez if you disallow Radicale to access `/home` (you have `ProtectHome=true` in your service unit), it can in particular not load nothing from `/home/radicale/passwords`.

**Comment by bvrulez** [comment]
@felixfontein Thank you very much for clarifying. This is the standard config from the website.
