### ISSUE TITLE
Problems with "rights"-file after migrating RP1 to RP3 --> 500 internal server error

### ISSUE THREAD

**Issue by Aqmos** [Kozea/Radicale#1135]
Hi all,

I recognized a strange behavior of radicale when trying to transfer a well running radicale-application from a raspberry 1b to a raspberry 3. Starting from a fresh installation on the RP3, I reused the “config”, “rights” and “user”-files from the RP1-application.

Issue: when logging into an account (e.g. using http://localhost:5232) and entering the password for one of the users, I instantaneously get the message “500 internal server error”.

- after commenting out all lines of the “rights-file” (ie. the file still exists but has no content anymore), the error is gone but I get the message “forbidden”,  probably because no rights are granted -> that's o.k.

- after commenting out the “rights-section” in the config-file (i.e. no explicit access-rights are defined), authentication works well for all users and I see all calendars of the respective users

→ Everything works well if the "rights-file" is not used or if the file has not content. As soon as I define access-rights, the error "500 internal server error" appears instantaneously (usually radicale needs some moments for authentication. After definition of rights, the error message appears immediately when logging in). The "rights-file" however works well with the RP1-installation.

Any idea what causes the problem?

Thanks!

`**Config-File**:

[auth]
type = htpasswd
htpasswd_filename = /home/pi/.config/radicale/users
htpasswd_encryption = bcrypt
delay = 1

[rights]
type = from_file
file = /home/pi/.config/radicale/rights

[storage]
filesystem_folder = ~/.var/lib/radicale/collections
`
`**rights-file**:
# Block access for the user "user" to everything.
#[block]
#user = user
#collection = .*
#permission =

# Authenticated users can read and write their own collections.
[owner-write]
user = .+
collection = %(login)s(/.*)?
permission = rw

# dedicated access rights
[shared]
user = user001
collection = user002(/.*)?
permission = r

# Everyone can read the root collection
[read]
user = .+
collection =
permission = r`

**Comment by pavinjosdev** [comment]
Radicale 3.x has changed a lot of config params with backward incompatible ones. See the [changelog](https://github.com/Kozea/Radicale/blob/3.0.1/NEWS.md#upgrade-checklist).

**Comment by Aqmos** [comment]
Thanks for the answer!
According to the changelog "Permission r replaced by Rr"; this could be the root cause. However, I'm not sure how to read it: does the changelog mean "<r> replaced by either <r> or <R>" or really "<r> replaced by <Rr>"? The former would comply to the official documentation.
Anyways, I wonder why it worked on my RPi 1b, since I also installed Radicale 3 here and the rights-file given above worked... Therefore I suspected the newer OS of the Pi 3 or a newer Python-version causing the trouble. Nevertheless, I will try it out!

**Comment by pavinjosdev** [comment]
Previously `r` encompassed both of the options below I think:

```
R: read collections (excluding address books and calendars)
r: read address book and calendar collections
```

> Anyways, I wonder why it worked on my RPi 1b

Could it be it's still using the older Radicale version from `apt`? I'd try searching for it and removing it. Make sure Radicale is invoked with Python 3.6+

Add this to config:

```
[logging]
level = info
```

Then run, `radicale --verify-storage`

**Comment by Aqmos** [comment]
I used the method recommended on radicale.org: "python3 -m pip install --upgrade radicale". But I will check to be sure. Thanks a lot!

**Comment by pbiering** [comment]
old issue, closing
