### ISSUE TITLE
Orgzly/non-calendar item sync

### ISSUE THREAD

**Issue by bobrippling** [Kozea/Radicale#1145]
I'm interested in using Radicale to sync [Orgzly](http://www.orgzly.com/).

Currently Orgzly's `PUT` is rejected [here](https://github.com/Kozea/Radicale/blob/d48bacc8e3414ffba7c3c8c21987f2ada8f0ab48/radicale/app/put.py#L131), as the content isn't a vobject (just plain "todo text"). Looking at the code, I imagine I would have to have some way of permitting parse errors / non-vobject content (perhaps via a new collection type) and skip the parsing.

I have two questions from this:
1. Does this seem like a reasonable approach? I believe I'd only need to modify `put.py`, the other HTTP methods don't seem to parse any vobjects.
2. Would this be accepted as a PR back into this repo? Happy to make it if so.

**Comment by bobrippling** [comment]
Did this the other way round - radicale behind a more generic webdav (see #1161)

**Comment by jonassmedegaard** [comment]
@bobrippling you mean a more generec webserver (not webdav), right?

**Comment by bobrippling** [comment]
Ah yeah that's what I meant, a webserver that can delegate for radicale and otherwise handle non-radicale webdav requests

**Comment by jonassmedegaard** [comment]
thanks for clarifying - I was just curious if lighttpd had a generic (whatever that means) plugin to do WebDAV... :-)

**Comment by Ineluki** [comment]
I would be very interested in this feature as well. Would is be feasible to disable parsing by selecting a special non-vObject type when creating the collection?

**Comment by pbiering** [comment]
Radicale is a pure C*DAV server and there are no plans to enrich it to standard WebDAV server for file management. Use build-in features in common webservers to cover this.
