### ISSUE TITLE
python-pam drop-in replacement available for python3

### ISSUE THREAD

**Issue by leonnnn** [Kozea/Radicale#115]
I’ve noticed radicale doesn’t support PAM with python3 because it relies on the python-pam module.

Hence, I’d like to let you know that I’m maintaining a python3 port of this module at <https://github.com/leonnnn/python3-simplepam>, so it should be easy for you guys to add PAM support for python3.

That module will also be available in Fedora in about a week. 

(Please note that although I’ve renamed the python3 version of that module to python3-simplepam, it provides the same functionality as the python-pam module. I decided to rename to avoid confusion with an Ubuntu package called python-pam, which is a completely different module.)

I’m not a radicale user myself, just wanted to let you know. If you don’t care, feel free to just close the issue :-)

**Comment by liZe** [comment]
Auth modules have been removed from Radicale and will be available as external modules. As soon as #391 is closed, anybody interested in this feature will be able to implement its own module and share it with the whole world :smile:.
