### ISSUE TITLE
Any way to populate adressbook externally?

### ISSUE THREAD

**Issue by FirstLobster** [Kozea/Radicale#1150]
Hi!

I'm trying to make a shared adressbook that I want to populate with vcf files that I have generated from an csv file through a script.

I have tried to just move my vcf files to my adressbook folder that I created though the web interface but with no luck.

Is this something radicale supports, and if so how would implement it?

Edit: Uploading the cvf file works great but the only problem is that every time I upload I get a new adressbook instead of updating the current one.

**Comment by Bangaio65** [comment]
This worked for me:
1. Create `.Radicale.props` in the folder (check an existing one for the format)
2. Copied some .vcf files from another address book, and edited the UID field and the filename (not sure if necessary but for consistency's sake), using `uuidgen` plus `sed`/`mv`.

After that I could add the address book to Cardbook in Thunderbird and all the contacts showed up.

**Comment by pbiering** [comment]
closing as old and looks like proposal worked.
