### ISSUE TITLE
Can't sync contact with string 'pref' in email address

### ISSUE THREAD

**Issue by Bangaio65** [Kozea/Radicale#1154]
Example: `starwood.preferred.guest@starwoodhotels.com`

Whenever I try to sync a contact with an email address containing `pref` I get: 
```
[WARNING] Bad PUT request on '/user01/ab01/330e433e-83b5-4814-9021-57d84d8daa17.vcf': At line 7: Failed to parse line: EMAIL;pref@test.com
[INFO] PUT response status for '/user01/ab01/330e433e-83b5-4814-9021-57d84d8daa17.vcf' in 0.002 seconds: 400 Bad Request
```
Client: Thunderbird with CardBook

I reported it to Cardbook here, but the auther says it's a radicale bug
https://gitlab.com/CardBook/CardBook/-/issues/1202

**Comment by pbiering** [comment]
is this still happen? If yes I would assume it's related to `vobject`

**Comment by da4089** [comment]
Sounds easy enough to unit test in vObject.

**Comment by pbiering** [comment]
> Given the PRODID, that might be a problem with cards generated by Thunderbird CardBook V56.9?

I've checked my collections and found following formats:

```
EMAIL;TYPE=work,pref:user@domain.example
EMAIL;TYPE=home,pref:user2@domain2.example2
```

So the format shown in the report looks really broken. I'm using up-to-date Thunderbird with CardBook and haven't seen any issues here.
