### ISSUE TITLE
how to configure radicale when using wsgi

### ISSUE THREAD

**Issue by oupala** [Kozea/Radicale#1155]
I'm trying to use and configure radicale 2.1.11 with wsgi and I don't really understand how to do so.

The [CHANGELOG](https://github.com/Kozea/Radicale/blob/2.1.11/NEWS.md#2110---wild-radish) stands that:

> Get `RADICALE_CONFIG` from WSGI environ

But the [default WSGI config file](https://github.com/Kozea/Radicale/blob/2.1.11/radicale.wsgi) does not set anything about config file.

> from radicale import

Moreover, there is a commit 8b1547cbe53c14208ea4001997b3c45453f60c95 that "move WSGI initialization into module".

If I understand it well, there is **no** default location for a configuration file, the configuration path is now [retreived from the environment](https://github.com/Kozea/Radicale/commit/8b1547cbe53c14208ea4001997b3c45453f60c95#diff-093742d2ee8abcde334a0541a190381e5f7404d60c6585e547dca107225a5b72R964).

Am I right?

If yes, how can I set such environment variable when using the radicale package from debian and wsgi?

I was expecting the [default file radicale.wsgi](https://github.com/Kozea/Radicale/blob/2.1.11/radicale.wsgi) to be directly usable. It seems not to be directly usable.

Do you have any opinion on this question?

**Comment by oupala** [comment]
I now have an opinion on this question, as I have made a lots of tests.

I have found 3 different solutions, each one will be described in a dedicated comment.

1. add configuration to wsgi launching file
2. add configuration to apache virtual host
3. use default radicale configuration files

**Comment by oupala** [comment]
The first solution is to add configuration to wsgi launching file.

I found this solution thanks to [msdigital.de](https://www.msdigital.de/entries/2018.12.02,Radicale%20CalDAV%20CardDAV%20Server,linux,server,sync.md) website which proposes the following configuration:

- `/var/radicale/radicale.wsgi`

```
import os
from radicale import Application, config, log
configuration = config.load(["/var/radicale/config"])
filename = os.path.expanduser(configuration.get("logging", "config"))
debug = configuration.getboolean("logging", "debug")
logger = log.start("radicale", filename, debug)
application = Application(configuration, logger)
```

This allow to set the path to configuration file so that it is taken in account by radicale at startup of apache.

**Comment by oupala** [comment]
The second solution is to add configuration to the virtual host of apache.

This solution has been taken from a [gentoo user forum](https://archives.gentoo.org/gentoo-user/message/c9d756d7066196ad43d25370311b1a92) and consist in using the apache [SetEnv directive](https://httpd.apache.org/docs/2.4/en/mod/mod_env.html#setenv):

```apache
<VirtualHost hostname:80>
...
SetEnv RADICALE_CONFIG /etc/radicale/config
...
</VirtualHost>
```

With this configuration the path of radical configuration file is set in apache environment, and transmitted to radicale by the environment, as the wsgi application is taking in account the whole environment from apache.

With this solution, adding configuration to wsgi launching file is no longer required.

**Comment by oupala** [comment]
The third and last solution is in the end the simplest solution: use default radicale configuration files.

```bash
>ls -l /etc/radicale/
total 3
-rw-r--r-- 1 root root      81 avril 12 23:24 config
-rw-r--r-- 1 root root     979 nov.   5  2018 logging
-rw-r--r-- 1 root root     775 avril 11 00:59 rights
-rw-r----- 1 root www-data 132 avril 11 00:59 users
```

There is no need to configuration wsi launching file, there is no need to set an environment variable in apache. Just use the default configuration path of radicale, and radicale will work like a charm.

**Comment by oupala** [comment]
I hope that this issue might help you set radicale in a way that is as simple as possible, and effectively working.

It might complete some lacks of documentation.

**Comment by oupala** [comment]
See [this previous comment](/Kozea/Radicale/issues/1155#issuecomment-818287231):

> When the apache virtual host does not set an environment variable, radicale is starting using a default configuration, but this default configuration is not the configuration from /etc/radicale/config but a (probably similar) configuration from elsewhere (but I don't know where).
> 
> I'm then re-opening this issue to try to find out where is the default configuration taken from.

**Comment by pbiering** [comment]
please reopen if still a problem with current version and configuration based on examples from here https://github.com/Kozea/Radicale/tree/master/contrib/apache
