### ISSUE TITLE
[5533/Thread-16] [ERROR] failed to find DUE at all.

### ISSUE THREAD

**Issue by AL-Ghub** [Kozea/Radicale#1157]
First post so if there is a better place to ask please advise, and I am a user only.

I get the error:
[5533/Thread-16] [ERROR] failed to find DUE at all.
when starting Radicale on Kubuntu 20.04 LTS and would like to try and diagnose/isolate the entry/entries that cause it.

I am running Python 2.7.18 (default, Mar  8 2021, 13:02:45),
 radicale --version 3.0.6

The same data (ie folder system) is accessed via Radicale on Windows 10 - the data being on an NTFS partition.
The data is sync'd to my Android using Davx5.

**Comment by pbiering** [comment]
Storage verification is now documented here: https://github.com/Kozea/Radicale/wiki/Server-Diagnostics---Troubleshooting#storage-verification
