### ISSUE TITLE
Cyrilic symbols in calendar name

### ISSUE THREAD

**Issue by Forket** [Kozea/Radicale#116]
I have situation that when I try to publish calendar with russian (cyrilic) symbols server returns me error. If I use english characters then everything is OK. So where is problem? Please, help me to fix шею What additional information I have to provide?

![image 1](https://f.cloud.github.com/assets/6735288/2216541/ad37f6de-9a0c-11e3-9189-54ab977104c0.png)
![image 2](https://f.cloud.github.com/assets/6735288/2216540/ad377eac-9a0c-11e3-9796-666bd2e316ec.png)

**Comment by liZe** [comment]
Actually duplicates #238.
