### ISSUE TITLE
Add ReadWritePaths=/var/log/radicale entry to radicale.service file example on web pages

### ISSUE THREAD

**Issue by gedakc** [Kozea/Radicale#1170]
First let me say thanks to the folks who develop and maintain Radicale.  I've been successfully using Radicale since Kubuntu 12.04, and value that Radicale enables me to directly control my personal data.

# REQUEST

Please update the systemd radicale.service documentation on the Radicale web site.  More specifically please add:

     ReadWritePaths=/var/log/radicale

to the `/etc/systemd/system/radicale.service` file on the following web pages.

https://radicale.org/2.1.html#documentation/basic-setup/running-as-a-service

https://radicale.org/3.0.html#tutorials/running-as-a-service

I recognize that this entry is related to logging, but if there is no harm in including it by default then it would help save time for others who do have logging enabled.

# BACKGROUND

Recently I updated to Kubuntu 20.04 which has the version 2.1.11-8 in its package repository.  With version 2 comes a new file format.  Fortunately the Radicale web site describes how to [migrate the data](https://radicale.org/2.1.html#documentation/migration-from-1xx-to-2xx) (thank you for this).

My difficulties arose when I was unable to start radicale as a systemd service.  I finally traced the issue down to the following error message(s) in `/var/log/syslog`:

```
<snip>
Jul  4 16:38:34 kaby env[4944]: ERROR: Failed to start logger: Failed to load logging configuration file '/etc/radicale/logging': [Errno 30] Read-only file system: '/var/log/radicale/radicale.log'
<snip>
```

The above error message made me think that it was a permissions problem with directories or files.  However even by making permissions wide open it still did not work.

Eventually I was able to find reference to how to [resolve the issue](https://github.com/Kozea/Radicale/issues/902#issuecomment-442084205) by adding the `ReadWritePaths=/var/log/radicale` entry to the `/etc/systemd/system/radicale.service` file.

It would have saved me (and likely will save others) much time if this entry was included by default in the Radicale website documentation.

Thank you for considering this request.

Sincerely,
Curtis Gedak

**Comment by ArchangeGabriel** [comment]
`LogsDirectory=radicale` would be a cleaner solution.

**Comment by pbiering** [comment]
Radicale version 3 only logs to systemd journal, no extension required
