### ISSUE TITLE
Help upgrading Radicale

### ISSUE THREAD

**Issue by scottsavarese** [Kozea/Radicale#1171]
I'm upgrading from an old Radicale server running 0.10 to one running version 3. It looks like between the two versions alot changed with the storage backend.

I copied over my collection tree from the old version to the new but clients are not able to see the collection I have. I have an address book in a file /var/lib/radicale/collections/collection-root/<username>/contacts.vcs. However, when I try and point a client to it, it doesn't work. I see the file being opened via strace on the radicale daemon but the client fails to see the data.

From the logs, I see the following:

> Jul 19 22:50:32 services env[2836]: [2021-07-19 22:50:32 -0400] [2836/Thread-19] [WARNING] Failed to load item cache entry 'contacts.vcf' in 'username': pickle data was truncated
> Jul 19 22:50:32 services env[2836]: Traceback (most recent call last):
> Jul 19 22:50:32 services env[2836]:   File "/usr/local/lib/python3.7/dist-packages/radicale/storage/multifilesystem/cache.py", line 91, in _load_item_cache
> Jul 19 22:50:32 services env[2836]:     cache_hash, *content = pickle.load(f)
> Jul 19 22:50:32 services env[2836]: _pickle.UnpicklingError: pickle data was truncated
> Jul 19 22:50:32 services env[2836]: [2021-07-19 22:50:32 -0400] [2836/Thread-19] [WARNING] Failed to load item cache entry 'contacts.vcf' in 'username': pickle data was truncated
> Jul 19 22:50:32 services env[2836]: Traceback (most recent call last):
> Jul 19 22:50:32 services env[2836]:   File "/usr/local/lib/python3.7/dist-packages/radicale/storage/multifilesystem/cache.py", line 91, in _load_item_cache
> Jul 19 22:50:32 services env[2836]:     cache_hash, *content = pickle.load(f)
> Jul 19 22:50:32 services env[2836]: _pickle.UnpicklingError: pickle data was truncated

In order to get to that point, I've had to manually create a Radicale cache item and do some weird behind the scenes stuff. What Is there a better or more correct way to bring existing contacts and calendar files to the new version of Radicale? What am I doing wrong?

**Comment by felixfontein** [comment]
Quite a lot changed, especially with storage between 1.x and 2.x. You might want to migrate one major version at a time, and first read the relevant changelog entries which describe how to migrate. 0.10 is from January 2015, which is over six years ago.

**Comment by scottsavarese** [comment]
Yes, it has been a long time since I upgraded it. Even the `--export-storage` function from the 1.x branch didn't do a good job of fixing it. But I did learn that in the new storage layout, monolithic files are broken up into smaller batches. I did mine one card at a time via a quick perl script and I've got my contacts back. 

However, calendars are an issue. It looks like I need to break up the calendar into 1 file per event as well. But the structure of a vcalendar is different than a contact list. There is a calendar container which contains entries, todos, timezones etc. Can you point me to the bit of code in github that might help me to slice up my calendars properly?

The other issue I'm seeing is 
> Jul 21 14:27:26 services env[4756]:   <response>
> Jul 21 14:27:26 services env[4756]:     <href>/radicale/<username>/contacts/<guid>.vcf</href>
> Jul 21 14:27:26 services env[4756]:     <propstat>
> Jul 21 14:27:26 services env[4756]:       <prop>
> Jul 21 14:27:26 services env[4756]:         <CR:supported-address-data />
> Jul 21 14:27:26 services env[4756]:       </prop>
> Jul 21 14:27:26 services env[4756]:       <status>HTTP/1.1 404 Not Found</status>
> Jul 21 14:27:26 services env[4756]:     </propstat>

I'm assuming its because there is a property in the card that it can't see. Any idea on that one?

**Comment by scottsavarese** [comment]
Im closing this issue. I was able to copy over the calendars. I spun up a virtual python environment and ran the export storage function on 1 calendar file at a time.
