### ISSUE TITLE
Error uploading ics file 

### ISSUE THREAD

**Issue by davidschnermann** [Kozea/Radicale#1172]
Hi there,
I get the same Error as people had years ago by trying to upload a ics-file to my radicale server.
So is there a known solution?
In Issue #806 is an Answer from @Unrud but I don't know how to specify which versions for VOject and python-dateutil.

I use ubuntu 20.04 and radicale 3.0.6, vobject 0.9.6.1, python-dateutil 2.7.3
Please help.

`
> It's a bug in VObject, in combination with a new version of python-dateutil. It got fixed in version 2.1.9 by specifying the exact versions for VObject and python-dateutil.
`

_Originally posted by @Unrud in https://github.com/Kozea/Radicale/issues/806#issuecomment-384027370_

**Comment by pbiering** [comment]
issue solved with latest versions?

**Comment by pbiering** [comment]
no response, please reopen if reproducable with latest version
