### ISSUE TITLE
webdav, files, zotero support?

### ISSUE THREAD

**Issue by fieryflamon** [Kozea/Radicale#1177]
Hi I am currently using nextcloud for caldav, carddav, and webdav (for zotero). I understand the caldav/carddav functionality can be replaced by radicale. But what about the webdav storage for zotero pdfs?

thank you

**Comment by jonassmedegaard** [comment]
Even though CalDAV and CardDAV protocols are extensions to WebDAV, Radicale is (deliberately, to keep code complexity relatively low) a crude implementation of only practically required parts of the CalDAV and CardDAV protocols, and you cannot expect generic WebDAV to work.

**Comment by hjudt** [comment]
If it helps, you could simply use radicale and wsgidav to get similar functionality, which probably works good enough for personal use-cases. If you need more functionality for public file sharing with passwords, you'd need to script that, though.

**Comment by pbiering** [comment]
closing, no plans to extend _radicale_
