### ISSUE TITLE
git broken after update 2 -> 3

### ISSUE THREAD

**Issue by 532910** [Kozea/Radicale#1181]
After update from debian buster (2.1.11-6) to bullseye (3.0.6-5) git is broken:
```
[ERROR] An exception occurred during PUT request on '/user@domain/addressbook/ID.vcf': Command 'git add -A && (git diff --cached --quiet || git commit -m "Changes by "user@domain)' returned non-zero exit status 128.
```

Storage section remains the same:
```
[storage]
hook = git add -A && (git diff --cached --quiet || git commit -m "Changes by "%(user)s)
```

Running git manually as radicale user in its home `/var/lib/radicale` returns `0`:
```
$ git diff --cached --quiet || git commit -m "Changes by "user@domain)' && echo OK
OK
```

**Comment by 532910** [comment]
even `test.sh` returns non-zero:
```
[storage]
hook = /tmp/test.sh
```
```
% cat /tmp/test.sh
#!/bin/bash -e

pwd
exit 0
```
```
% ls -l /tmp/test.sh
-rwxr-xr-x 1 sergio sergio 27 2021-09-03 00:57 /tmp/test.sh*
```

**Comment by mvetoshkin** [comment]
for me, git was complaining that empty ident name not allowed.
just set identity for your repo something like this:
  git config user.email "radicale@example.com"
  git config user.name "Radicale"

**Comment by bordenc** [comment]
I don't suppose there would be any chance of including a sample .git/config file with all the necessary options in the documentation? The snippets would not be clear to people unfamiliar with git.

**Comment by pbiering** [comment]
will be covered by https://github.com/Kozea/Radicale/pull/1631
