### ISSUE TITLE
Login returns 500 and gives internally  [Errno 30] ng PROPFIND request on '/': [Errno 30] Read-only file system: '/var/lib/radicale/collections/.Radicale.lock'

### ISSUE THREAD

**Issue by gruberb** [Kozea/Radicale#1182]
I setup Radicale on a Ubuntu server behind a reverse proxy. I set everything up, the service is running and I see the login screen. But after trying to login, I am getting internally this error:

`[ERROR] An exception occurred during PROPFIND request on '/': [Errno 30] Read-only file system: '/var/lib/radicale/collections/.Radicale.lock'`

What should the permissions be? I do 

```
sudo chown -R radicale:radicale /var/lib/radicale/collections/.Radicale.locks
```

To be sure the radicale user has access to the file. Am I missing something?

**Comment by hephaisto** [comment]
I have the same issue after updating. What did you do to fix?

**Comment by hephaisto** [comment]
Turned out that debian shipped a new service file which blocked write access, since I did not use the default data location.
