### ISSUE TITLE
[ERROR] An exception occurred during request: SSL handshake failed: EOF occurred in violation of protocol (_ssl.c:749)

### ISSUE THREAD

**Issue by uenz** [Kozea/Radicale#1183]
Hi,
i set up radicale with ssl according to the documentation with self signed certificate. To get it work with an iPhone i hat to comment out the  certificate_authority part.  It works fine with iPhones over ssl.
`[server]`
`ssl = True `
`certificate = /path/to/server_cert.pem`
`key = /path/to/server_key.pem`
`#certificate_authority = /path/to/client_cert.pem`
   
But with MacOS connecting the same url as the iphone i get the
[ERROR] An exception occurred during request: SSL handshake failed: EOF occurred in violation of protocol (_ssl.c:749)
The certificate is also set to trusted. Now i ran out of ideas. Can someone give me an hint?

**Comment by ehem** [comment]
I've seen something suspiciously similar with DAVx5 and Radicale 3.0.  I'm wondering how Radicale 3.0 broke DAVx5.  There are a number of potential causes, but right now I don't have any clues.

**Comment by ehem** [comment]
Any news on bug 1183?  This seems a serious issue since I hope no one sends their contacts and calendar around without SSL/TLS.

**Comment by ehem** [comment]
Due to factors it was handy to test 3.1.5.  For me Radicale 3.1.5 appears to solve this issue.

This issues DB is looking like a black hole.  There is no reference to this in any commit message, so I'm completely unaware what the problem was.

**Comment by Woastscho** [comment]
I also have Radicale 3.1.5.
iOS  works, with latest MacOS Monterey (12.3.1) adding a CalDAV account with SSL brings
"[ERROR] An exception occurred during request: SSL handshake failed: EOF occurred in violation of protocol (_ssl.c:1129)"
What's your setup ?

**Comment by uenz** [comment]
If get no more SSL Exception with MacOS Monterey (12.3.1) since Radicale 3.1.5.

**Comment by Woastscho** [comment]
@unez @ehem 
I have Ubuntu 21.10 with Radicale 3.1.5, MacOS 12.3.1.
I add CalDAV account in  MacOS Calendar App and get:
"[ERROR] An exception occurred during request: SSL handshake failed: EOF occurred in violation of protocol (_ssl.c:1129)"
on server side
[config.txt](https://github.com/Kozea/Radicale/files/8513911/config.txt)
Do you have any hints for me about your setup ?

**Comment by Woastscho** [comment]
@uenz sorry

**Comment by uenz** [comment]
@Woastscho The SSL related parts in my config are the same. But MacOS sync is not working for me, only iPhone.

**Comment by habibi-hapti** [comment]
Except for the last bit – (_ssl.c:997) – , I get the same error on iOS when I try to synchronize my tasks. Calendar on iOS works fine, on macOS everything works fine.

**Comment by pbiering** [comment]
@uenz : is this issue still reproducable with latest versions?

**Comment by uenz** [comment]
@pbiering: Calendar sync now works with fine latest radicale version and MacOS Sequoia. 
But contacts (CardDAV) sync does not work with MacOS, but that might have another reason. 
Need to dig deeper in the logs for the reason. Shall i close this issue?

**Comment by pbiering** [comment]
related to MacOS check for other issue or discussion, looks like there is a more generic problem.
