### ISSUE TITLE
bcrypt authentication failing with version 1.1.6

### ISSUE THREAD

**Issue by PeterNSteinmetz** [Kozea/Radicale#1189]
I am running Radicale on Ubuntu Linux bionic 18.04.6. The package on that distribution installs Radicale 1.1.6. I have python3-passlib and python3-bcrypt packages installed.

My installation works fine with the following in config.

   [auth]
   htpasswd_encryption = plain

But if I change to 

   [auth]
   htpasswd_encryption = bcrypt

and regenerate the users file using a command like 

   sudo htpasswd -B -c users username

when I start the server the radicale.log simply shows

2021-10-23 00:25:20,820 - INFO: Starting Radicale
2021-10-23 00:25:20,821 - DEBUG: Authentication type is htpasswd
2021-10-23 00:25:20,853 - DEBUG: Cleaning up

And is not answering on the socket.

Any suggestions to fix or further debugging?

**Comment by pbiering** [comment]
current version works with bcrypt
