### ISSUE TITLE
Radicale Push Notifications

### ISSUE THREAD

**Issue by yeehi** [Kozea/Radicale#1191]
If a calendar is being served on Radicale, and somebody subscribes to that calendar, will Radicale push changes to events to people? For example, an event is created and scheduled to start at 2PM, but later changed to start at 3PM, will people subscribing to the calendar have the event updated on their client? 

How could that be arranged?

**Comment by bedwardly-down** [comment]
How are they accessing the calendar? From what I can tell, if you run it through the native caldav protocol on iOS or calDAVx on Android, it should automatically push / fetch as long as they have that set up correctly in their settings

**Comment by pbiering** [comment]
this is a client side issue
