### ISSUE TITLE
should waitress be removed from setup.py?

### ISSUE THREAD

**Issue by yuluc123** [Kozea/Radicale#1192]
Hi
I notice that waitress are listed as dependencies in the configuration file-setup.py but it is not used in source code.
So is it necessary to remove waitress from dependencies?

**Comment by Unrud** [comment]
It's used for tests:

https://github.com/Kozea/Radicale/blob/f72b3449818600962268bc96a2a12e8e022a0c42/radicale/tests/test_server.py#L230-L232
