### ISSUE TITLE
PROPFIND / without body and auth gives 207 rather than 401

### ISSUE THREAD

**Issue by tobixen** [Kozea/Radicale#1195]
Doing a PROPFIND towards radicale without username/password and without a body given in the request will cause radicale to return data - while I'm expecting a 401.

Doing a PROPFIND towards radicale without username/password and with a body given in the request will cause radicale to return 401 as expected.

(It's so much fun doing debugging into such issues.  I just had lots of frustrations with a NextCloud instance that would break the TCP communication rather than return a 401 and a `WWW-Authenticate`-header when sending a PROPFIND with a body but without valid auth - hence I rewrote the auth logic in the python caldav library.  Dtails at https://github.com/python-caldav/caldav/issues/158 for those who may be specially interested.  The python caldav client library version 0.8.2 works both for that nextcloud instance and for radicale, but it has some code duplication.  After a proper clean up, radicale support broke.  Version 0.9 is likely to contain some extra code lines referring to this issue).

**Comment by Unrud** [comment]
It will return 401 if you are unauthorized. Do you have the setting `auth-type` set to `None` (the default)?

**Comment by tobixen** [comment]
It's set up quite default - but the `auth-type` setting is a bit beside the point here.  Either the server should deliver 401 for all requests, or for none of the requests.

**Comment by Unrud** [comment]
> Either the server should deliver 401 for all requests, or for none of the requests.

Do you query the `DAV:current-user-principal` property? In this case 401 is returned even when you are authorized but no username/password is given.
RFC 5397 says that a `DAV:unauthenticated` XML element should be returned but it caused issues with clients not handling this case.

**Comment by tobixen** [comment]
That's likely to be the reason - I'll verify it a bit later.

**Comment by tobixen** [comment]
Indeed, you are right.  Closing the issue.
