### ISSUE TITLE
Documentation: Radicale & DAVx5

### ISSUE THREAD

**Issue by Semmelrocks** [Kozea/Radicale#1196]
I was trying to bring Radicale and DAVx5 on my home server together these days,
but it was nerve-racking because of a simple thing, which is mentioned nowhere.

[https://radicale.org/3.0.html#documentation/supported-clients](url)
Here you can read:

> DAVx⁵
Enter the URL of the Radicale server (e.g. http://localhost:5232) and your user name. DAVx⁵ will show all existing calendars and address books and you can create new.

Nevertheless the example contains a necessity, namely the protocol (http) including '://'.
I was trying the IP+Port of my home server only (192.168.0.28:5232), but then DAVx5 shows me

> Illegal character in scheme name at index 0:

Without the port (IP only) DAVx5 will add 'https://' at the beginning, but that's port 443.
Switching the Radicale port to 443 wasn't successful:

> radicale[23290]: [2021-11-30 17:28:02 +0100] [23288] [CRITICAL] An exception occurred during server startup: Failed to start server '[192.168.0.28]:443': [Errno 13] Permission denied

I dunno why. According to the config file scheme it looks like a IPv6 syntax, but my config uses the IPv4 syntax.

Nevermind. Indicate the network protocol is a must!

**Comment by Unrud** [comment]
>> radicale[23290]: [2021-11-30 17:28:02 +0100] [23288] [CRITICAL] An exception occurred during server startup: Failed to start server '[192.168.0.28]:443': [Errno 13] Permission denied
>
> I dunno why. According to the config file scheme it looks like a IPv6 syntax, but my config uses the IPv4 syntax.

You need admin privileges to bind ports <1024. It's not IPv6 syntax.

**Comment by dilyanpalauzov** [comment]
My reading is, that in DAVx⁵ it is not possible to enter `http://ip-address:port-number` as base-URL.  You might want to contact the developers of DAVx⁵ on this.

**Comment by Semmelrocks** [comment]
> My reading is, that in DAVx⁵ it is not possible to enter `http://ip-address:port-number` as base-URL. You might want to contact the developers of DAVx⁵ on this.

I already contacted them and explain the problem. They wanna forwarding it to the developer team.

**Comment by Unrud** [comment]
> My reading is, that in DAVx⁵ it is not possible to enter `http://ip-address:port-number` as base-URL.

It works.

**Comment by pbiering** [comment]
looks like solved.
