### ISSUE TITLE
Documentation: Hint when using the example rights file when there is a .Radicale.props-File in collection-root/<user>/

### ISSUE THREAD

**Issue by svenuniku** [Kozea/Radicale#1197]
I had a few hours of searching and debugging why the section [principal] in the example example rights[1] file did not work.
Even with log level debug there was no hint, that there was a .Radicale.props-File in collection-root/<user>/ folder, which contained '{"tag": "VCALENDAR"}'.
After deleting this file, everything worked as expected.
As far as I see, the behavior is as expected, but hard to investigate for the average user.
Would it be possible to give a hint in the Documentation?
Or within the log level 'debug' a more precise logging, because of which file the regex failed?
I also think that a .Radicale.props-File doesn't make any sense/is wrong in this location.
Don't ask me, why there was this file in this location.

I am using the packaged Debian version:
Package: radicale
Version: 3.0.6-3

[1]: https://radicale.org/3.0.html#documentation/authentication-and-rights

**Comment by pbiering** [comment]
Logging related to rights file parsing is at least in newer versions existing and an unexpected .Radicale.props which turns the folder into a collection should be indirectly now visible by a new log message introduced with 3.3.1
