### ISSUE TITLE
Bad request on task with expiration date, hour and time zone

### ISSUE THREAD

**Issue by symphorien** [Kozea/Radicale#1201]
When importing this ics with evolution:
```
BEGIN:VCALENDAR
PRODID:-//Ximian//NONSGML Evolution Calendar//EN
VERSION:2.0
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:/freeassociation.sourceforge.net/Europe/Paris
X-LIC-LOCATION:Europe/Paris
END:VTIMEZONE
BEGIN:VTODO
UID:f0021b0b5ca1397caa92e5b56360941906949c25
DTSTAMP:20211228T212831Z
SUMMARY:test
DUE;TZID=/freeassociation.sourceforge.net/Europe/Paris:20220101T100000
PERCENT-COMPLETE:0
CLASS:PUBLIC
SEQUENCE:1
CREATED:20211231T130337Z
LAST-MODIFIED:20211231T130337Z
END:VTODO
END:VCALENDAR

```
I get bad request:
`2021-12-31T14:05:35.101 784256418240 radicale.service radicale[956988] INFO [2021-12-31 14:05:35 +0100] [956988/Thread-39] [WARNING] Bad PUT request on '/symphorien/0aff2591-0cbd-4b20-a8d0-b67c6fbf1edc/f0021b0b5ca1397caa92e5b56360941906949c25.ics': "In transformToNative, unhandled exception on line None: <class 'ValueError'>: at least one component is needed (<VTIMEZONE| [<TZID{}Europe/Paris>, <X-LIC-LOCATION{}Europe/Paris>]>)"`

The ics was produced with evolution by creating a task with an expiration date, hour and timezone. Unsetting the timezone solves the issue.

radicale 3.1.0, python3.9, Linux x86_64 NixOS 21.11

**Comment by Unrud** [comment]
The time zone component is incomplete.
https://datatracker.ietf.org/doc/html/rfc2445#section-4.6.5:
> one of 'standardc' or 'daylightc' MUST occur

I wasn't able to recreate the issue with Evolution 3.42.2 (flatpak git). The time zone was complete and contained STANDARD and DAYLIGHT components.

On a side note I noticed that tasks have the same problem as https://github.com/Kozea/Radicale/issues/1146.

**Comment by symphorien** [comment]
Thanks for the diagnostic. Since it seems the issue is with evolution, I opened an issue against it: https://gitlab.gnome.org/GNOME/evolution/-/issues/1754
Feel free to close this issue if you think it's better.
