### ISSUE TITLE
Color of calendar disappearing due to RGB clash (+ current set up)

### ISSUE THREAD

**Issue by harryHoward** [Kozea/Radicale#1203]
I may have resolved a problem of the color of a calendar disappearing when syncing with Thunderbird, plus my setup is perhaps a little more up to date than the documentation.

Hardware: MacBook Pro 2017 with OSX 10.13.6 High Sierra <> Moto g fast with Android 11
Software workflow: Thunderbird 91.4.1 <> Radicale 3.1 <> DAVx5 4.1 <> Tasks 11.12.3 + Google Calendar

Radicale path: 

> Mac/Users/my_user/var/lib/radicale/collections/…

(Note that I wanted to use the standard _var_ directory so it is not prefixed with a dot.)

Set up:

1. Install Thunderbird and Radicale on Mac; F-Droid and then DAVx5 and Tasks on Moto.
2. In Terminal window used to install Radicale, start server with 

> $ python3 -m radicale --storage-filesystem-folder=~/var/lib/radicale/collections --server-hosts=0.0.0.0:5232

3. Open Radicale Web Interface in browser with `http://localhost:5232/` and create credentials (I forgot exactly how I did that).
4. Click on "Create new addressbook or calendar".
5. Give it a title and description and keep default "calendar, journal tasks".
6. Pick a color and write down its RGB coordinates.
7. Click on "Create" and copy the URL to the clipboard.
8. Open Thunderbird and click on Calendar "+" to create a new calendar.
9. Select "On the Network"; click "Next".
10. Type your Radicale user into Username and paste the URL into Location. Click on "Find Calendars".
11. In the new window (Create New Calendar), click on "Properties".
12. In the new window (Edit Calendar), fill in the Calendar Name with the calendar's title.
13. Click on the color, go to the RGB sliders and fill in the RGB coordinates from Radicale. (I originally used the pencils, which would never correspond to the RGB coordinates of Radicale. I think that was the cause of the disappearing calendar color.) Click on "OK".
14. You should see the new calendar in the calendar list. Click "Synchronize" at the top left.
15. Pick up your phone, open DAVx5 and create a user from your Radicale credentials. I forgot exactly how I did that, but the crucial step is to set the server address to an IP address on your Mac. I used the IP address of my wifi client, found in the Network Control Panel. Be sure to suffix the port "5232" with a colon. (Several hours of my life were lost figuring that out.)
16. Open your user account in DAVx5 (if not already open), press "CALDAV" and you should see your calendar. If not, press the three dots and "Refresh your calendar list". (Every time you change a calendar in Radicale, you have to refresh the calendar list in DAVx5. Again, I lost several hours of my life figuring that out.) Check the box for the calendar.
17. Hit the refresh button at the bottom right. 
18. You may have already run across the screen in DAVx5 that asks for permissions for Tasks. You can add it now if you haven't done so already.
19. Open Tasks and sync by dragging down from the top. If you haven't made any tasks in Thunderbird, none will appear. Otherwise, I have found Tasks to work on its own.
20. If you are a newbie like me, it may not be immediately clear that the Radicale server must be running for all this stuff to work together. So start the server first thing. I am working on a way to start it when I log on to my user account on my Mac.

So far, everything works together rather well, though I am not sure that the disappearing calendar color is actually fixed. I have not tried to work with contacts yet, but I have done lots of tasks and calendar entries.

**Comment by Unrud** [comment]
In Thunderbird the calendar type must not be **iCalendar (ICS)**. It must be **CalDAV**, otherwise you will experience problems like the calendar color disappearing.

When you add the calendar to Thunderbird, you can just enter the server address and port into the address field (like DAVx5) and it will find all your calendars automatically. (Also, this way I doesn't let you select the wrong calendar type.)
I need to update the documentation on this, it's a new feature of Thunderbird that I didn't know about.

**Comment by pbiering** [comment]
closing as no update since 2+ years
