### ISSUE TITLE
user addition problem in FreeBSD 13.0 p4

### ISSUE THREAD

**Issue by hakova** [Kozea/Radicale#1211]
Hi,

Thank you for this great server. I have been using it for >5 years now and I am very grateful for it. With FreeBSD, it has been set it up and forget it kind of experience since it just works with no maintenance. My son recently got old enough to have a cell phone and I wanted to create an account for him on my existing set up (radicale 3.0.6, bcrypt 3.2.0 python 3.7.12_1). Unfortunately this didn't go smoothly.My attempts to add his name and password to my users file included using the following command:
`htpasswd.py -b users hisname hispasswd` resulted in addition of a line in the users file as expected, but by close inspection, his hashed password looked quite different than other family members'. While all other hashed passwords start with a "$2" prefix, it is not the case for his hashed password. When tried to login with his user name and password from radicale's web interface, I get a "500: Internal server error" and cannot log in. Anybody else on the other hand can login. My guess is that htpasswd is not behaving as it should while hashing the password and writing it to this file, but I am not sure what I am missing. Any pointers will be greatly appreciated.

Thanks!

**Comment by Unrud** [comment]
The encryption method for the password must match the setting `auth`->`htpasswd_encryption` (md5 by default).
I don't know what **htpasswd.py** is or what it does. Apache's **htpasswd** uses md5 by default, too.

**Comment by hakova** [comment]
Thank you for your response. It was installing apache in FreeBSD that
provided the htpasswd executable that solved the problem indeed, as you
suggested. Thank you so much again for building and maintaining this
awesome server!
