### ISSUE TITLE
radicale.org down

### ISSUE THREAD

**Issue by nmoseman** [Kozea/Radicale#1214]
Radicale.org is down.   It no longer has a DNS record.

I am curious if this means the end of the project or what.  The domain does not expire until 2023.  So I am not sure what is going on here.

**Comment by liZe** [comment]
> The domain expired. @liZe?

Sorry, I forgot to renew the domain. It will be should back soon.

**Comment by nmoseman** [comment]
Very nice.  I see the website is up.  

Thank you!
