### ISSUE TITLE
Add first login hook

### ISSUE THREAD

**Issue by itglob** [Kozea/Radicale#1219]
Add ability to hook first user login to propagate default address book and calendar, in simple scenario coping two folders from template.

Variant 1:
```
Add hook= to Auth section
[auth] 
# args send to init-usr.sh $1 – collection-root $2 - username
hook = /full-path/init-usr.sh
```

Variant 2:
```
Reorganize hooks, add hooks section and rename old hook to storage_change
[hooks]
storage_change= “as old hook”
# args send to init-usr.sh $1 – collection-root $2 - username
first_login = /full-path/init-usr.sh
```
I think second variant better because of clearer names. If it’s ok as concept, I can implement it.

**Comment by pbiering** [comment]
Please provide a PR for that, potentially on top of https://github.com/Kozea/Radicale/pull/1092

**Comment by pbiering** [comment]
This was meanwhile implemented, see option `predefined_collections`

-  https://github.com/Kozea/Radicale/releases/tag/v3.2.2
