### ISSUE TITLE
Global state in radicale

### ISSUE THREAD

**Issue by untitaker** [Kozea/Radicale#122]
Radicale has global state. While this is not a problem when running a single server per process, which is the usecase everybody thinks of, it makes the opposite case where one wants to run multiple servers with different configuration much harder.

I am using radicale as a server to test against in vdirsyncer: https://github.com/untitaker/vdirsyncer/blob/master/tests/storage/dav/__init__.py

and have to use weird and possibly malfunctioning hacks to reset radicale for each test function. It would be nice if i didn't have to.

**Comment by liZe** [comment]
I'm currently working on it!

**Comment by liZe** [comment]
2f97d7d probably fixes most of this problem. The tests pass and I've played with cadaver, but many bug may have been introduced (and should be easy to fix).

@untitaker if there's anything else I've missed, just ask! If everything fits your needs, you can close the issue.

**Comment by untitaker** [comment]
Works very well, thank you.
