### ISSUE TITLE
"NOTES" field not working on iOS with Radicale 3.1.5

### ISSUE THREAD

**Issue by Tamerz** [Kozea/Radicale#1220]
We have been running 1.x for years to sync contacts to iPhones. I'm trying to get updated to a newer version of Radicale.

I am using the same vobject library this project uses to create my cards. For whatever reason, the "NOTES" field does not show up in the iOS contacts even though it is in the vcard file.

I even copied and pasted from the old server to the new server, and the field shows up on a phone connected to the old server, but not the new one.

Anyone see this issue before or have any suggestions?

**Comment by pbiering** [comment]
please try with latest _vobject_, if still an issue, report bug there
