### ISSUE TITLE
after upgrade from 2.1.x to 3.1.5: thunderbird does not display calender entries

### ISSUE THREAD

**Issue by m1027** [Kozea/Radicale#1222]
We have upgraded radicale from 2.1.x to 3.1.5 as described here:
https://github.com/Kozea/Radicale/issues/1142#issuecomment-1049078918

The setup is: Apache + mod_wsgi + radicale.

We have this issue issue:

- vdirsyncer works
- davx5 works
- thunderbird: HAS ISSUES

Issue details:

Thunderbird shows none of the existing calendar entries. It can create
calendar entries and other clients can see them but TB does not
display any previous calender entries nor those newly created by other
clients.

The radicale logs show that TB currently tries PROPFIND with depth = 0 while
the other clients try or retry with depth = 1. So it seems that TB does not
read the actual files, just the properties.

Other tests so far:

(1) With debug level logging there is no significant hint:

> [INFO] PROPFIND response status for '/user1/' with depth '0' in 0.698
> seconds: 207 Multi-Status

This should probably be depth '1' to read all files and take about 10 seconds
here.

(2) Thunderbird caches cleared

Thunderbird was tested newly, without any local cache files etc.

(3) Thunderbird against radicale 2.1.x works

When creating two calendar accounts, one against a radicale-2.1.x server the
other against another that was newly upgraded from 2.1.x to 3.1.5 as mentioned
above, then thunderbird shows calendar entries from 2.1.x quite immediately
but nothing for 3.1.5.

What next:

It should be helpful to know if anyone has a working setup with thunderbird
against radicale 3.x, optimally using apache + mod_wsgi.

**Comment by henning-schild** [comment]
As i said before, TB and stand-alone radicale work (for me). So it might well be somewhere in your apache+mod_wsgi setup.

Please double check if stand-alone works better than via apache. Later move into apache (maybe reverse proxy) ... check, then move into wsgi. The wsgi might mean that radicale is in fact running as your apache user and you just have permission problems.

**Comment by m1027** [comment]
> TB and stand-alone radicale work (for me). So it might well be somewhere in
> your apache+mod_wsgi setup.

Thanks for your hints.

> The wsgi might mean that radicale is in fact running as your apache user and
> you just have permission problems.

Keep in mind that:

- The other caldav clients, vdirsyncer and davx5, do work
- Only TB has issues, and only against radicale 3.x.
- and TB can create and publish events

I will try to track that issue further down.

**Comment by m1027** [comment]
Fixed.

Summary: While davx5 and vdirsyncer worked against radicale, thunderbird did
not display anyting (or worse display calendar entries but could not change
them).

Solution:

For davx5 and vdirsyncer you can specify your URL and local storage PATHs in
radicale like this:

```
https://host/ANYTHING/ [ics files here]
```
resp.
```
/var/lib/radicale/collections/collection-root/ANYTHING/ [ics file here]
```

For thunderbird, however, you should use:

```
https://host/USERNAME/CALENDARNAME
```
resp.
```
/var/lib/radicale/collections/collection-root/USERNAME/CALENDARNAME
```

So, if you omit USERNAME then for thunderbird we have the issue mentioned
above, with really a lot of misleading log messages according permissions and
what not.

Side note: I did not solve this issue continuing the original setup via
mod_wsgi but meanwhile switched to apache remote proxy setup. Just because the
documentation was better on radicale.org. But I believe this should even fix
it for setups with mod_wsgi.
