### ISSUE TITLE
Documentation of SystemD service definition probably incorrect

### ISSUE THREAD

**Issue by Lvceo** [Kozea/Radicale#1223]
Hi there,

I've been trying to start my already working configuration of Radicale 3.5.1 on Debian 10 with Systemd service definition as shown into the [documenttion](https://radicale.org/v3.html#running-as-a-service).

In debug mode, Radicale throw
`[CRITICAL] An exception occurred during server startup: [Errno 13] Permission denied: '/blabla/radicale'.`
After investigating I fixed the problem setting 
`ProtectHome=false`

After reading [this](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectHome=)

I suggest to change this in docs if I'm not wrong.
Cheers

**Comment by felixfontein** [comment]
Does your `/blabla/` path somehow lies inside the `/home` directory? If yes, you are using Radicale not exactly as in the documentation you are linking to (which stores the data in `/var/lib/radicale`). For the example in the docs, `ProtectHome=true` is absolutely correct and best practices.

**Comment by Lvceo** [comment]
Yeap `blabla` is inside my `/home`, it's an architecture choice.
My bad
Thanks for your answer.
