### ISSUE TITLE
Help!! While trying to install on Windows 2019 server Command line to complete install never processes. Urgent need to install.

### ISSUE THREAD

**Issue by McFarkey** [Kozea/Radicale#1224]
In the instructions to install on Windows the first of 2 Python lines are given abd the first works but the second, can sit for hours and nothing happens.

Thoughts??

Launch a command prompt and type:

python -m pip install --upgrade https://github.com/Kozea/Radicale/archive/master.tar.gz
python -m radicale --storage-filesystem-folder=~/radicale/collections - This one just sits.

**Comment by McFarkey** [comment]
I reinstalled with a newer version and did the install very cleanly - same issue - when running this line from an elevated command prompt nothing ever happens.
python -m radicale --storage-filesystem-folder=~/radicale/collections

**Comment by Chiller2019** [comment]
Same on UbuntuLTS

**Comment by ChefAndy** [comment]
Is something supposed to happen? On my system that ran the application and I was able to connect to it on localhost through port 5232

**Comment by pbiering** [comment]
@McFarkey : is this still reproducable, if not, please close

**Comment by pbiering** [comment]
no response, please reopen if reproducable with latest version
