### ISSUE TITLE
Unable to access read-only calendar

### ISSUE THREAD

**Issue by orange-toothbrush** [Kozea/Radicale#1235]
I have two users, let's call them Bob and Alice. I'd like Alice to be able to read Bob's calendar, but not write to it.

For rights, I'm keeping it simple and using `owner_write`. From the docs, I know that Alice won't be able to discover Bob's calendar:

> The recommended backend is owner_only. If access to calendars and address books outside the home directory of users (that's /USERNAME/) is granted, clients won't detect these collections and will not show them to the user. Choosing any other method is only useful if you access calendars and address books directly via URL.

The issue is that I tried adding Bob's calendar (full URL) into Alice's calendar client, but the calendar can't be found. I checked and the credentials are correct. Alice is able to find her calendar (using the root collection) but not Bob's. 

For more details, I'm using nginx to access radicale using a subdomain, i.e. pointing _cal.domain.com_ to _domain.com:5232_. I've tried both the subdomain and full URL with ports and neither work. I don't think this is the root of the issue.

Any help would be appreciated!

**Comment by pbiering** [comment]
See now https://github.com/Kozea/Radicale/wiki/Sharing-Collections how to share calendars
