### ISSUE TITLE
Unable to access calendar via DAVx5

### ISSUE THREAD

**Issue by anishmittal2020** [Kozea/Radicale#1239]
I successfully installed Radicale on my LinuxMint 20.3 using pip --user. I created calendars using radicale's web interface at http://localhost:5232/.web. I am able to access the Radicale created calendars at Thunderbird.

My Laptop IP address are as follows
| | |
---|---
Ethernet IP|                   192.168.178.22
WLAN IP    |                  192.168.178.21

I have Davx5 installed on My Android 11 in the same LAN. When I enter `http://192.168.178.22:5232` I get the following error:

![image](https://user-images.githubusercontent.com/42092626/165145308-6d8f52c3-1231-4663-89f1-5b9ab2e97829.png)

Also, when I type  `http://localhost:5232`, it gives same error: 

![image](https://user-images.githubusercontent.com/42092626/165145691-24f78a26-4f1a-435e-b47f-af0377649a72.png)

Also, I am unable to access radical web interface from firefox browser installed on android.

![image](https://user-images.githubusercontent.com/42092626/165146491-cf8e25f6-aab5-4042-8701-16a5327a0fb8.png)

I am able to access, other web server running on my laptop on my mobile. For example, I use Calibre to read books, that creates a web server on LAN to read books from other devices, it works flawlessly from my android.

![image](https://user-images.githubusercontent.com/42092626/165147071-291dc541-0b65-4531-8174-5af931d08304.png)

# Please help

**Comment by WithThisHerring** [comment]
I tried these same steps.  Calibre's port 8080 works, and Radicale's port 5232 does not.  How did you solve this?  I'm sure I'm missing something very basic.

**Comment by anishmittal2020** [comment]
Just change the configuration of Radicale. Check for configuration on internet
