### ISSUE TITLE
vdirsyncer error: Remote end closed connection without response

### ISSUE THREAD

**Issue by lokesh-krishna** [Kozea/Radicale#1240]
Attempting to use Radicale (3.1.7-1) with vdirsyncer. My collections were created on my Android device using DecSyncCC and then synced over to my laptop using Syncthing. Then I have Radicale running locally and vdirsyncer then attempts to interface with it to expose my collections to a bunch of utilities. 

Whenever I run `vdirsyncer sync`, I get the following error: 

```
Syncing calendars/calendars-655c997b-5938-499b-9348-e26bbaf26a85
Syncing contacts/contacts-3e3ca063-d88c-4cd7-9141-69eb2ca57602
Syncing tasks/tasks-a2e77698-f5c0-4e17-98f1-b16ba78909bd
error: Unknown error occurred for tasks/tasks-a2e77698-f5c0-4e17-98f1-b16ba78909bd: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
error: Use `-vdebug` to see the full traceback.
error: Unknown error occurred for contacts/contacts-3e3ca063-d88c-4cd7-9141-69eb2ca57602: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
error: Use `-vdebug` to see the full traceback.
error: 2 out of 6 tasks failed.
```

Link to debug output: [debug](https://paste.sr.ht/~low-key/f99a1fdd5e896128b24c63f0f27e75fcf4677b1c)

Is there anything that I might be missing on the Radicale end of things?

**Comment by pbiering** [comment]
Is this solved? If not, server side logs are required, potentially in debug mode for the particular request.

**Comment by pbiering** [comment]
no response, please reopen if reproducable with latest version
