### ISSUE TITLE
Not possible to edit collection types

### ISSUE THREAD

**Issue by JohnVeness** [Kozea/Radicale#1242]
I have a collection of type "calendar, journal and tasks" that I would like to change to calendar only. If I edit the collection, the type drop-down only has "calendar, journal and tasks" in it.

If I try to edit a collection of type "tasks", the drop-down contains entries for "calendar, journal and tasks", "calendar and tasks", "journal and tasks" (and "tasks"), but choosing one of those doesn't seem to change the collection.

Is this by design or is it fixable?

Many thanks for this app!

**Comment by pbiering** [comment]
A collection currently can only be of type

- VADDRESSBOOK
- VCALENDAR

see also content of `.Radicale.props` in each collection directory.

**Comment by JohnVeness** [comment]
Thanks for the reply. Having played with this a bit more, I see that if I create a "calendar, journal and tasks" collection, it actually creates three collections with different URLs, one of type calendar, one of type journal, one of type tasks. All with tag: VCALENDAR, but with different C:supported-calendar-component-set, of VEVENT, VJOURNAL or VTODO.

So I can see how it might not be possible to change one type to another. But I still think there's a user-interface issue here, as there is a drop-down in the Edit screen which certainly suggests the type can be changed later. Maybe change the drop-down to just a label?
