### ISSUE TITLE
ios cannot access server

### ISSUE THREAD

**Issue by Machineandrew** [Kozea/Radicale#1261]
I setup radicale server in debian9 and login as user in chrome. But i cannot use my iphone connect to server.

**Comment by GaiusVampus** [comment]
Did you set up a valid SSL certificate in order to enable https instead of http? This seems to be required by iOS.

**Comment by B4stl3r** [comment]
As GaiusVampus mentioned, iOS requires HTTPS to work with caldav.

**Comment by bitsandscraps** [comment]
I think I have a similar issue. I can log in to view my calendar on my PC, but cannot on my Android phone. It gives me "Error: 200 OK" I've tried both Firefox and Chrome, but neither of them works. It's an nginx reverse proxy server that redirects HTTP to HTTPS.

**Comment by bitsandscraps** [comment]
> I think I have a similar issue. I can log in to view my calendar on my PC, but cannot on my Android phone. It gives me "Error: 200 OK" I've tried both Firefox and Chrome, but neither of them works. It's an nginx reverse proxy server that redirects HTTP to HTTPS.

This wasn't a mobile problem but a firewall problem. Sorry for the confusion.
