### ISSUE TITLE
ios SSL Errors with Reminders, Calendar working

### ISSUE THREAD

**Issue by B4stl3r** [Kozea/Radicale#1263]
Hi,

just updated radicale to latest version, as I've seen the required redirect issues started with iOS 13 have been implemented in release 3.1.3..
https://hostname:5232/.well-known/caldav 
redirects me now to 
https://hostname:5232/.web/ in the browser.

I got a self created CA, which is trusted by all my devices and a signed and valid certificate <825 days provided for radicale.
rest of certificate properties from here: https://bob.gatsmas.de/caldav-sync-erinnerungen-app-ios-13-und-macos-1015 (unfortunately german, sorry).
just have DNS.1 entry with the hostname of my pizero (dns is working).
Certificate is imported (sudo update-ca-certificates), link is available.

Calendar synchronisation is working fine and flawless, but when I open reminders, I immediately receive an ssl exception:

Sep 28 22:50:04 pizerow env[432]: [2022-09-28 22:50:04 +0200] [432/Thread-16] [ERROR] An exception occurred during request: SSL handshake fa
Sep 28 22:50:04 pizerow env[432]: Traceback (most recent call last):
Sep 28 22:50:04 pizerow env[432]:   File "/usr/local/lib/python3.7/dist-packages/radicale/server.py", line 190, in finish_request_locked
Sep 28 22:50:04 pizerow env[432]:     request.do_handshake()
Sep 28 22:50:04 pizerow env[432]:   File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
Sep 28 22:50:04 pizerow env[432]:     self._sslobj.do_handshake()
Sep 28 22:50:04 pizerow env[432]: OSError: [Errno 0] Error
Sep 28 22:50:04 pizerow env[432]: The above exception was the direct cause of the following exception:
Sep 28 22:50:04 pizerow env[432]: Traceback (most recent call last):
Sep 28 22:50:04 pizerow env[432]:   File "/usr/local/lib/python3.7/dist-packages/radicale/server.py", line 194, in finish_request_locked
Sep 28 22:50:04 pizerow env[432]:     raise RuntimeError("SSL handshake failed: %s" % e) from e
Sep 28 22:50:04 pizerow env[432]: RuntimeError: SSL handshake failed: [Errno 0] Error
Sep 28 22:50:04 pizerow env[432]: [2022-09-28 22:50:04 +0200] [432/Thread-17] [ERROR] An exception occurred during request: SSL handshake fa
Sep 28 22:50:04 pizerow env[432]: Traceback (most recent call last):
Sep 28 22:50:04 pizerow env[432]:   File "/usr/local/lib/python3.7/dist-packages/radicale/server.py", line 190, in finish_request_locked
Sep 28 22:50:04 pizerow env[432]:     request.do_handshake()
Sep 28 22:50:04 pizerow env[432]:   File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
Sep 28 22:50:04 pizerow env[432]:     self._sslobj.do_handshake()
Sep 28 22:50:04 pizerow env[432]: OSError: [Errno 0] Error
Sep 28 22:50:04 pizerow env[432]: The above exception was the direct cause of the following exception:
Sep 28 22:50:04 pizerow env[432]: Traceback (most recent call last):
Sep 28 22:50:04 pizerow env[432]:   File "/usr/local/lib/python3.7/dist-packages/radicale/server.py", line 194, in finish_request_locked
Sep 28 22:50:04 pizerow env[432]:     raise RuntimeError("SSL handshake failed: %s" % e) from e
Sep 28 22:50:04 pizerow env[432]: RuntimeError: SSL handshake failed: [Errno 0] Error

Any ideas what could be missing?

**Comment by B4stl3r** [comment]
... if you find this.. installing, trusting the root ca is for iOS NOT ENOUGH!!!

you need to enable "full trust for root certificates in
settings => general => about => certificate trust settings

**Comment by harrystuart** [comment]
I am encoutnerring the same issue but I have toggled on "ENABLE FULL TRUST FOR ROOT CERTIFICATES" and reminders still isn't working (calendar is...)

**Comment by B4stl3r** [comment]
reminders takes (for whatever reason) in my setup always really long to sync.. so maybe just need to give it some time and be more patient. when calendar is working, reminders should work also fine (but maybe slower, as  mentioned).

Create a reminder on 1 device. wait 10 mins, pick up the next device, open reminder, wait for some mins..
That's how it's working in my env, even when i'm not happy with it.
