### ISSUE TITLE
Radicale hangs on launch / no output given

### ISSUE THREAD

**Issue by poisonborz** [Kozea/Radicale#1268]
After successful installation on Debian 10 (both through python or the debian package), when I launch radicale, the process starts but no output is displayed and server is not started.

![image](https://user-images.githubusercontent.com/1070611/200143351-2216f671-283a-4deb-9c7c-ee8afc6c4493.png)

What could be the issue?

**Comment by pbiering** [comment]
In such cases I would use `-v` for verbose or `strace` or `ltrace`  in front of for further diagnostics.

**Comment by poisonborz** [comment]
Turns out Radicale was running alright - although the server feedback/documentation could be better - I created two follow-up tickets to address these.
