### ISSUE TITLE
Events do not add

### ISSUE THREAD

**Issue by voncloft** [Kozea/Radicale#1283]
I have a calendar that is strictly holidays (I only have a few I genuinely care about)

When I try to add the event to the calendar on my phone the event never appears. It acts like it did but it will fail

I use a samsung ultra 23 and use the default calendar.

Any bugs I can gladly send I have debug as the level and nothing occurs when I try to add the event

**Comment by pbiering** [comment]
check log of "radicale" on server side, potentially exception lines were found.

**Comment by voncloft** [comment]
How? The only way to see logs are via stdout meaning there is no log file I use v3 which did away with log files (which is a stupid idea)

If I start the program via command line with error, warning, or critical nothing ever occurs debug however returns information nothing stating errors. I can edit events just fine in Korganizer and Google Calendar - but Samsung Calendar for what ever reason will not add events.

**Comment by pbiering** [comment]
Note: if started by `systemd`, logging is piped into `journald`, means one can check the log via `journalctl -f -u radicale`

Do you have a reverse proxy in front of `radicale`? If so, do you see any related request (hopefully, the logged user agent can be used to distinguish between the different calendar applications) - potentially the one from Samsung Calendar is blocked already here.

If not even the request can be found in log, one has to start debugging on phone side using `adb logcat`

**Comment by pbiering** [comment]
Any update? Otherwise this issue will be closed.

**Comment by pbiering** [comment]
no response, please reopen if reproducable with latest version
