### ISSUE TITLE
radicale unmaintained by Kozea Community and turning stale?

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#1284]
there are 31 outstanding pull requests, which need review/discussion and potential merge.

@Unrud : last merge was on Jul 14, 2022

how to continue further on, any ideas like
- extend maintainer list?
- create a new master fork and mark Kozea's radicale as stale and overtake also the https://radicale.org/ for further maintenance?
- (other ideas)?

Note also that the link to the community group is broken currently: https://community.kozea.fr/ -> `Internal Server Error`

**Comment by Unrud** [comment]
I will take a look at the pull requests. (I work on the project in my spare time.)

Advancing the project in a significant way will be difficult:

* We rely on [vobject](https://github.com/eventable/vobject/) for parsing iCalendar and vCard
  * unmaintained for a long time
  * very slow (caching is used by Radicale to mitigate the problem)
  * doesn't support vCard 4.0
* WebDAV/CalDAV/CardDAV protocols
  * complex
  * only partial (and buggy) support by software

**Comment by pbiering** [comment]
> I will take a look at the pull requests. (I work on the project in my spare time.)

Feel free to contact me for any further review work or support or testing (if possible by me).

Regarding "advancing" the project: potential other contributors can help here.

**Comment by MatthewHana** [comment]
Completely understandable @Unrud. I too am also happy to help with contributions where I can.

**Comment by da4089** [comment]
> I will take a look at the pull requests. (I work on the project in my spare time.)
> 
> Advancing the project in a significant way will be difficult:
> 
>     * We rely on [vobject](https://github.com/eventable/vobject/) for parsing iCalendar and vCard
>       
>       * unmaintained for a long time
>       * very slow (caching is used by Radicale to mitigate the problem)
>       * doesn't support vCard 4.0
> 
>     * WebDAV/CalDAV/CardDAV protocols
>       
>       * complex (for no reason)
>       * only partial (and buggy) support by software

I am looking at reviving vObject.  It'd be great if you could create an issue on the vObject repo, listing all your concerns (esp. v4 support, and performance).

**Comment by da4089** [comment]
I'm working on a vObject fork (https://github.com/py-vobject/vobject), with the intention of bringing it back into a well-maintained state.  Given Radicale is an important downstream user, I'd like to keep track of any issues reported here that are caused by vObject.

Would you consider adding a tag so that issues could highlight vObject problems?  That'd make it much easier for me to keep track of them, and triage appropriately.

@unrud @pbiering

**Comment by pbiering** [comment]
> Would you consider adding a label so that issues could highlight vObject problems? That'd make it much easier for me to keep track of them, and triage appropriately.
> @pbiering

Have requested permissions to be able to support.

**Comment by gentooboontoo** [comment]
@pbiering has been granted write permissions for the repository and will be able to triage and merge outstanding pull requests. Thanks @pbiering for your proposal.
Thank you @Unrud for your valuable work. On my side, I will try to allocate some of my own time to the project.

New contributors are of course welcomed and encouraged to join and contribute to the ongoing progress of Radicale. Perhaps a more visible call to contributions would be useful in the README or the main site...

**Comment by pbiering** [comment]
@gentooboontoo : thank you very much for enriching my permissions
@gentooboontoo : can you please enable "Discussions" for "radicale", potentially also some issues can be converted to this tab then.

**Comment by gentooboontoo** [comment]
> @gentooboontoo : can you please enable "Discussions" for "radicale", potentially also some issues can be converted to this tab then.

:+1: Great suggestion @pbiering, it would be a better place for help support or ideas… Discussions are now enabled for Radicale project.

**Comment by pbiering** [comment]
@gentooboontoo : can you also enable "Wiki", potentially some can contribute here related to use of features / howtos which is too much content for the documentation files.

**Comment by gentooboontoo** [comment]
@pbiering I have reactivated the wiki feature. There are existing pages that may require updating, removal, or revamping, as they are likely outdated now.
