### ISSUE TITLE
Proxy timeout during big uploads

### ISSUE THREAD

**Issue by mc3** [Kozea/Radicale#1286]
radicale-3.1.8 with apache 2.4.55 as reverse proxy displays Error: 

`502 Proxy Error`

 on big uploads of calendars or addressbooks.
Apache error log:

`[Wed Mar 08 17:13:45.466506 2023] [proxy_http:error] [pid 90110] (70007)The timeout specified has expired: [client 2a05:bec0:26:10::124:63951] AH01102: error reading status line from remote server 212.71.193.50:8443, referer: https://cal.nepustil.net/radicale/.web/
[Wed Mar 08 17:13:45.466563 2023] [proxy:error] [pid 90110] [client 2a05:bec0:26:10::124:63951] AH00898: Error reading from remote server returned by /radicale/familie.rau@chaos1.de/d4555056-75b8-6a8b-cc57-51f05c5f6291/, referer: https://cal.nepustil.net/radicale/.web/`

Setting bigger timeout (300) in [server] section does not help.
As we have already a connection, I did not increase apache connection timeout.
apache keepalive timeout is not set.

I'm new to radicale and apache.

**Comment by mc3** [comment]
Setting

'ProxyTimeout     1200'

in apache proy config solves the issue.

**Comment by GaiusVampus** [comment]
We faced similar problems while uploading a 2MB calendar file with about 5000 VEVENTs. 
The setting which helped us was "ProxyTimeout     240".
