### ISSUE TITLE
Unable to migrate Adressbooks from Apple calendarserver to radicale

### ISSUE THREAD

**Issue by mc3** [Kozea/Radicale#1287]
macos 10.15 up to 13 seems unable to open addressbooks in radicale.
Same with thunderbird 102.

Addressbook has been exported as vcf with macos 10.15 contacts app.

server account configuration in contacts App is:

`serveraddress: fqdn_of_server/ath_to_radicale_proxy`
`server path: user_name`

Is this correct?

On IOS/IipadOS configuration works flawless, but contact groups are missing

Any advice welcome.

**Comment by pbiering** [comment]
is the issue still existing with latest version?

**Comment by pbiering** [comment]
no response, please reopen if reproducable with latest version
