### ISSUE TITLE
infcloud: Hangs on loading calendars

### ISSUE THREAD

**Issue by OlegHahm** [Kozea/Radicale#1296]
I'm using my radicale setup with infcloud for a quite a while (one year+) already but recently infcloud stopped working correctly. After logging in, it gets past "Loading resources" but hangs infinitely on "Loading calendars (5 of 7)". The only warning I see in the radicale logs are:
```
"radicale[XXX]: [2023-04-06 15:49:10 +0200] [XXX/Thread-99 (process_request_thread)] [WARNING] Unsupported REPORT method 'D:expand-property' on '/foo/' requested
```

**Comment by pbiering** [comment]
Support is now implemented by https://github.com/Kozea/Radicale/pull/1292, please try master branch and file comment on PR if still a problem
