### ISSUE TITLE
Discussion: Proposed changes to storage api for 1.0

### ISSUE THREAD

**Issue by jdccdevel** [Kozea/Radicale#130]
I'm writing a custom storage backend, and the more I dig into the storage API, the more I see opportunities for improved efficiency.

This seems like a reasonable forum to discuss those improvements.

For example, several places in the code, I've seen this:
"if name in (item.name for item in collection.items)"

I'd like to start by suggesting a "has_item(name)" method be added to the "Collection" object to replace this. Alternatively, an "item_names" property could be created, but I believe that would be less efficient. 

The code right now is REALLY inefficient, as it requires the storage backend to load the ENTIRE collection, just to test if the collection contains a particular item name. This doesn't allow for any indexing or caching of item names, and hinders any efficiency improvements possible with databases.

This code pattern is repeated with the headers and properties, but it's less of an issue there due to their relatively small size.

**Comment by liZe** [comment]
@untitaker your API is wonderful, thanks a lot!
