### ISSUE TITLE
MOVE: code still does not cover all proxy configurations

### ISSUE THREAD

**Issue by mc3** [Kozea/Radicale#1301]
We run radicale via http on a special port on the same host behind an apache servicing requests on http and https.
radicale requests use https on the apache only.
Recent code does not cover this situation:

{'CONTENT_LENGTH': '0',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'de-de',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DESTINATION': 'https://<radicale-fqdn>/radicale/<user-name-escaped>/8de935ff-4f15-a0f4-6c2a-9e59f48b491a/678E9874-C933-4D9D-95FA-9DDF25559676.ics',
 'HTTP_HOST': '<radicale-IP>:8443',
 'HTTP_IF_MATCH': '"7908c9d13e345d25a0db5c766f6fce09782b6d66d1236815e66e9ac8dc1ad373"',
 'HTTP_OVERWRITE': 'F',
 'HTTP_USER_AGENT': 'Mac+OS+X/10.15.7 (19H2026) CalendarAgent/930.5.1',
 'HTTP_X_FORWARDED_FOR': '<client-IP6>',
 'HTTP_X_FORWARDED_HOST': '<radicale-fqdn>',
 'HTTP_X_FORWARDED_SERVER': '<radicale-fqdn>',
 'HTTP_X_REMOTE_USER': '<user-name>',
 'HTTP_X_SCRIPT_NAME': '/radicale',
 'PATH_INFO': '/<user-name>/e25f7a69-2102-393a-37db-d45221d885ad/678E9874-C933-4D9D-95FA-9DDF25559676.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '<radicale-IP>',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'MOVE',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '<radicale-fqdn>',
 'SERVER_PORT': '8443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2023-04-28 10:48:39 +0200] [97494/Thread-121729] [DEBUG] Base prefix (from HTTP_X_SCRIPT_NAME): '/radicale'
[2023-04-28 10:48:39 +0200] [97494/Thread-121729] [DEBUG] Sanitized path: '/<user-name>/e25f7a69-2102-393a-37db-d45221d885ad/678E9874-C933-4D9D-95FA-9DDF25559676.ics'
[2023-04-28 10:48:39 +0200] [97494/Thread-121729] [INFO] Successful login: '<user-name>'
[2023-04-28 10:48:39 +0200] [97494/Thread-121729] [INFO] Unsupported destination address: 'https://<radicale-fqdn>/radicale/<user-name-escaped>/8de935ff-4f15-a0f4-6c2a-9e59f48b491a/678E9874-C933-4D9D-95FA-9DDF25559676.ics'
[2023-04-28 10:48:39 +0200] [97494/Thread-121729] [DEBUG] Response content:
Remote destination not supported.
[2023-04-28 10:48:39 +0200] [97494/Thread-121729] [INFO] MOVE response status for '/<user-name>/e25f7a69-2102-393a-37db-d45221d885ad/678E9874-C933-4D9D-95FA-9DDF25559676.ics' in 0.001 seconds: 502 Bad Gateway

If I change the apache ProxyPassReverse and ProxyPass from IP to FQDN, it does not help:
Any fix or workaround appreciated.

**Comment by pbiering** [comment]
are you using radicale "latest" or only latest release?

See also here: https://github.com/Kozea/Radicale/pull/1271

**Comment by mc3** [comment]
Yes, I'm running HEAD.
The situation is so:
https://<server-IP>:443 (apache proxy) => http://<server-IP>:8443 (radicale )
Currently w eare running with this hack:
`[root@cal /usr/local/lib/python3.9/site-packages/radicale/app]# diff move.py.radicale.org move.py
54,55c54,57
<             to_netloc_with_port += (":443" if to_url.scheme == "https"
<                                     else ":80")
---
>             ##to_netloc_with_port += (":443" if to_url.scheme == "https"
>             ##                        else ":80")
> 	    # hack: proxy talks via http to radicale on port 8443 but proxy listens on 443
>             to_netloc_with_port += ":80"
`
I think radicale code can't find out such a situation. Perhaps we need a config for that?

**Comment by mc3** [comment]
radicale is not listening at localhost or a socket:
https://<server-fqdn>:443 (apache proxy) => http://<server-fqdn>:8443 (radicale)

**Comment by pbiering** [comment]
@Unrud : can it be that your implementation (instead of mine from https://github.com/Kozea/Radicale/pull/1271 is not working proper? MOVE is very seldom on my server, but it looks I had the last sucessful one on 2023-03-04, since then I had only 401+502

@mc3 : can you try my original patch from https://github.com/Kozea/Radicale/pull/1271

**Comment by mc3** [comment]
> Am 29.04.2023 um 15:54 schrieb Peter Bieringer ***@***.***>:
> 
> 
> @Unrud <https://github.com/Unrud> : can it be that your implementation (instead of mine from #1271 <https://github.com/Kozea/Radicale/pull/1271> is not working proper? MOVE is very seldom on my server, but it looks I had the last sucessful one on 2023-03-04, since then I had only 401+502
> 
> @mc3 <https://github.com/mc3> : can you try my original patch from #1271 <https://github.com/Kozea/Radicale/pull/1271>
> Yes. Running code attached.

Axel

---
PGP-Key: CDE74120  ☀ mobile: +49 160 7568212
computing @ chaos claudius


def get_server_netloc(environ: types.WSGIEnviron, force_port: bool = False):
    if environ.get("HTTP_X_FORWARDED_HOST"):
        host = environ["HTTP_X_FORWARDED_HOST"]
        proto = environ.get("HTTP_X_FORWARDED_PROTO") or "http"
        port = "443" if proto == "https" else "80"
    else:
        host = environ.get("HTTP_HOST") or environ["SERVER_NAME"]
        proto = environ["wsgi.url_scheme"]
        port = environ["SERVER_PORT"]
    if (not force_port and port == ("443" if proto == "https" else "80") or
            re.search(r":\\d+$", host)):
        return host
    return host + ":" + port


class ApplicationPartMove(ApplicationBase):

    def do_MOVE(self, environ: types.WSGIEnviron, base_prefix: str,
                path: str, user: str) -> types.WSGIResponse:
        """Manage MOVE request."""
        raw_dest = environ.get("HTTP_DESTINATION", "")
        to_url = urlparse(raw_dest)
        to_netloc_with_port = to_url.netloc
        if to_url.port is None:
            ##to_netloc_with_port += (":443" if to_url.scheme == "https"
            ##                        else ":80")
            # hack: proxy talks via http to radicale on port 8443 but proxy listens on 443
            to_netloc_with_port += ":80"
        if to_netloc_with_port != get_server_netloc(environ, force_port=True):
            logger.info("Unsupported destination address: %r", raw_dest)
            # Remote destination server, not supported
            return httputils.REMOTE_DESTINATION
        access = Access(self._rights, user, path)

**Comment by pbiering** [comment]
have now catched a MOVE from an iOS client and able to replicate issue with additional debug lines:

```
Unsupported destination address: 'https://dav.server.example/user/caendar.ics/file.ics'
to_netloc_with_port: 'dav.server.example:443'
get_server_netloc: 'dav.server.example:80'
```

will now investigate what @Unrud did with code proposal

**Comment by pbiering** [comment]
Found reason, at least Apache reverse proxy is not setting `X-Forwarded-Proto` by default, therefore the magic code in function `get_server_netloc` in file `move.py` is appending ":80" instead of appending ":443".

Following extension for the Apache reverse proxy will fix this:

```
        <If "%{HTTPS} =~ /on/">
                RequestHeader set X-Forwarded-Proto "https"
        </If>
```

**Comment by mc3** [comment]
Fixed it !
Thanks !

**Comment by luckydonald** [comment]
@mc3 how?

https://xkcd.com/979/

**Comment by pbiering** [comment]
@luckydonald : I assume @mc3  fixed it by adding the in https://github.com/Kozea/Radicale/issues/1301#issuecomment-1528809515 mentioned Apache config lines into local config.
