### ISSUE TITLE
Can't connect to running server on raspi after reboot

### ISSUE THREAD

**Issue by fuzzbian** [Kozea/Radicale#1307]
Hi,
I can't connect to the radicale-server on my raspi after rebooting it. The server seems to be ruinning:

```
% sudo systemctl status radicale.service
● radicale.service - A simple CalDAV (calendar) and CardDAV (contact) server
     Loaded: loaded (/lib/systemd/system/radicale.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-06-08 17:15:37 CEST; 8s ago
       Docs: man:radicale(1)
   Main PID: 56661 (python3)
      Tasks: 1 (limit: 3933)
        CPU: 1.169s
     CGroup: /system.slice/radicale.service
             └─56661 python3 -m radicale

Jun 05 17:42:28 raspberrypi systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.

```
```
% curl https://0.0.0.0:5232
curl: (7) Failed to connect to 0.0.0.0 port 5232: connection refused
```

Any ideas? Thanks!

**Comment by fiwswe** [comment]
Yes, use a valid IP address. 0.0.0.0 is not a valid IP. Maybe you meant to use 127.0.0.1 aka localhost?

**Comment by fuzzbian** [comment]
Sorry, yes, but same result.

**Comment by fiwswe** [comment]
Also you will likely have trouble with the TLS certificate. You may need to use the `--insecure` option with curl or maybe just `http://…`? Depends on your configuration.

**Comment by fuzzbian** [comment]
I have it configured to work with TLS and it used to work.

**Comment by pbiering** [comment]
1. check for listen port running as root `netstat -nlpt | grep :5232` and `netstat -nlpt |grep python`
2. check radicale log

**Comment by fiwswe** [comment]
You could also try to see if radicale is listening and on what IP(s). Try `netstat -ln|grep LISTEN` (or similar — I have not used Linux for a while…)

**Comment by fuzzbian** [comment]
```
% sudo netstat -nlpt | grep :5232
tcp        0      0 127.0.1.1:5232          0.0.0.0:*               LISTEN      56661/python3       
tcp6       0      0 2003:cf:571e:2e00::5232 :::*                    LISTEN      56661/python3       
```

Where do I find the log?

**Comment by fuzzbian** [comment]
```
% curl http://127.0.1.1:5232     
curl: (52) Empty reply from server
```

```
% curl https://127.0.1.1:5232                                                                    :(
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by fiwswe** [comment]
`127.0.1.1:5232`should give you a clue ;-)

Logs are often found in `/var/log/`.

**Comment by pbiering** [comment]
Log: `journalctl -u radicale -b 0 | tail -10`
why your radicale is listen on strange loopback IP `127.0.1.1` instead of `127.0.0.1` you have to investigate configuration. But the config is insecure because it's in parallel listen on the public IPv6 address....

**Comment by fiwswe** [comment]
> ```
> % curl https://127.0.1.1:5232                                                                    :(
> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: https://curl.se/docs/sslcerts.html

Try the `--insecure` option I mentioned.

**Comment by fiwswe** [comment]
> But the config is insecure because it's in parallel listen on the public IPv6 address....

Not so sure about that. `2003:cf:571e:2e00::5232`expands to `2003:00cf:571e:2e00:0000:0000:0000:5232` without any port. Or maybe netstat has a problem printing IPv6 addresses and `2003:00cf:571e:2e00:0000:0000:0000:0000` port 5232 is actually meant? Still a strange IPv6 address. Looks like it is just the public /56 IPv6 prefix without an Interface Identifier.

Anyway there is no way to get a certificate from a publicly accepted CA for a private IP address such as 127.0.1.1. So the certificate is probably self-signed. Hence the `--insecure`.

**Comment by pbiering** [comment]
> Not so sure about that. `2003:cf:571e:2e00::5232`expands to `2003:00cf:571e:2e00:0000:0000:0000:5232` without any port. Or maybe netstat has a problem printing IPv6 addresses and `2003:00cf:571e:2e00:0000:0000:0000:0000` port 5232 is actually meant?

Yes, netstat has a problem and not displaying the whole IPv6 address with port, one can use `lsof -iTCP`

**Comment by pbiering** [comment]
> Yes, netstat has a problem and not displaying the whole IPv6 address with port, one can use `lsof -iTCP`

one can also use `ss -lnt | grep :5232`

**Comment by fuzzbian** [comment]
> Log: `journalctl -u radicale -b 0 | tail -10` why your radicale is listen on strange loopback IP `127.0.1.1` instead of `127.0.0.1` you have to investigate configuration. But the config is insecure because it's in parallel listen on the public IPv6 address....

In the config I have:
`
hosts = raspberrypi:5232 `
Because that's the name of my raspi in my network (maybe that's why it's listening on 127.0.1.1). I also have activated port forwarding in my router (IPV4 and 6) which I guess is why there is this weird IPv6 address. 

Log says:
```
Jun 08 17:07:33 raspberrypi systemd[1]: radicale.service: Consumed 1.428s CPU time.
Jun 08 17:15:37 raspberrypi systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
Jun 08 18:22:23 raspberrypi env[56661]: [2023-06-08 18:22:23 +0200] [56661/Thread-1] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
Jun 08 18:22:54 raspberrypi env[56661]: [2023-06-08 18:22:54 +0200] [56661/Thread-2] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
Jun 09 11:12:08 raspberrypi systemd[1]: Stopping A simple CalDAV (calendar) and CardDAV (contact) server...
Jun 09 11:12:08 raspberrypi systemd[1]: radicale.service: Succeeded.
Jun 09 11:12:08 raspberrypi systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
Jun 09 11:12:08 raspberrypi systemd[1]: radicale.service: Consumed 1.306s CPU time.
Jun 09 11:13:47 raspberrypi systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
Jun 09 11:14:09 raspberrypi env[70106]: [2023-06-09 11:14:09 +0200] [70106/Thread-1] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
```

(I restarted the server a few times.)

**Comment by fuzzbian** [comment]
Ok, I fixed it by setting the host-entry in the config to the local IP-address (v4) of my raspi.

Thanks everyone!
