### ISSUE TITLE
Appache proxy server return 502 error

### ISSUE THREAD

**Issue by PowaBanga** [Kozea/Radicale#1311]
Hi everybody,
I am on archlinux, and i am trying do do a proxy reverse to my radicale server.

so, i have this httpd config : 
```
<VirtualHost *:80>      
    ServerName  radicale.domain.com
    Redirect / https://radicale.domain.com/
</VirtualHost>
     
<VirtualHost *:443>
    ServerName radicale.domain.com
    SSLEngine On
    SSLCertificateFile /etc/httpd/conf/server.crt
    SSLCertificateKeyFile /etc/httpd/conf/server.key
    SSLProxyEngine On
    ProxyPreserveHost On                                                                                              
    ProxyPass / http://192.168.0.10:5232/ retry=0
    ProxyPassReverse / http://192.168.0.10:5232/
    RewriteEngine On
    RewriteRule ^/radicale$ /radicale/ [R,L]
     
    RequestHeader    set X-Script-Name /radciale
    ErrorLog /var/log/httpd/radicale.domain.com.error.log
    CustomLog /var/log/httpd/radicale.domain.com.access.log combined
</VirtualHost>
```
But the server return a 502 error in my client. There is probably that i misunderstood with requestHeader, but i really do not understand what is it exactly...
Does anybody can help me ?

**Comment by pbiering** [comment]
have you investigated all logs (Apache, Radicale) and tried without ` RequestHeader` config?

**Comment by pbiering** [comment]
also check for listen daemon and SElinux settings, can be that Apache is by default blocked to connect further on.

**Comment by rockstorm101** [comment]
> RequestHeader    set X-Script-Name /radciale

s/radciale/radicale
