### ISSUE TITLE
calendar on server deleted - optional protection required

### ISSUE THREAD

**Issue by mc3** [Kozea/Radicale#1314]
It just happened 2nd time that a calendar has been deleted for no reason.
I'm using Apple clients only. On macos I can delete a calendar via context menu.
If I do so, the calendar is not deleted at the server. (Still shows up on the web site).

What can cause the server to delete a calendar?

**Comment by pbiering** [comment]
Radicale supports "delete" of a "collection" (which is a "calendar") inside the code. Looks like the Apple client requested this.

Related part in the code is in file: `radicale/storage/multifilesystem/delete.py` called by `radicale/app/delete.py`

```
class CollectionPartDelete(CollectionPartHistory, CollectionBase):

    def delete(self, href: Optional[str] = None) -> None:
        if href is None:
            # Delete the collection
     ...
        else:
            # Delete an item
```

Code is currently not protecting deletion of a collection, neither at all nor by permissions, second would need implementation of extra definition, first by introducing a global option which can be used to forbid such deletion.

**Comment by mc3** [comment]
OK, so I guess this is bug at Apples side.
If time allows, I will try to provide a patch.

Thanks for explanation.

**Comment by pbiering** [comment]
A user is reporting by private e-mail that there should be an ability to protect this, therefore reopen now

**Comment by pbiering** [comment]
Global option introduced: https://github.com/Kozea/Radicale/pull/1409
