### ISSUE TITLE
Carddav with Thunderbird

### ISSUE THREAD

**Issue by MaDill** [Kozea/Radicale#1318]
I have problems with the buildin carddav integration of the Thunderbird adressbook.

In Radicale I setup a user with a calendar (calendar, journal and tasks) and an adressbook. Then I setup the account on my android cellphone withDAVx5. It detect the calendar and the adressbook without any issue. In Thunderbird I setup the calendar and it detect the calendar without issue. Then I tried to setup the adressbook with the buildin carddav integration (without any addon). I type the username and the url, but Thunderbird complain that it not find any adressbooks. Why?

When I copy the whole URL from the adressbook, then it is working.

Why is DAVx5 working with adressbook and calendar and Thunderbird only with the calendar?

How can I debug this? What information is needed to find the problem?

**Comment by pbiering** [comment]
I'm using Thunderbird with "Cardbook" plugin, and yes, you have to configure each addressbook manually by URL (same as for calendar, but here without plugin), I'm not aware of any autodiscovery implementation on Thunderbird side.

**Comment by jonassmedegaard** [comment]
this is an issue with Thinderbird, not with Radicale: Try search the web for "thunderbird carddav discovery" for various discussions and workarounds - and if you don't find a reported issue report then you might consider reporting as an issue against Thunderbird.

**Comment by jonassmedegaard** [comment]
[This](https://discourse.mozilla.org/t/caldav-and-carddav-autoconfig/113695/2) looks lie a good place to start - i.e. not exactly same issue but very close, so an inspiration for how you might file an issue yourself

**Comment by MaDill** [comment]
Thank you for the information.

The strange thing is, that the CalDAV did automatic discover all the calendars from the account. No need to setup the full address.

But with CardDAV it could not discover the address book.

I created a ticket at Thunderbird: https://bugzilla.mozilla.org/show_bug.cgi?id=1844954
