### ISSUE TITLE
How to rename a collection in its URL?

### ISSUE THREAD

**Issue by randolf** [Kozea/Radicale#1327]
When I create a new calendar in Radicale, there doesn't seem to be any option for changing the URL portion of the collection -- it's just a long string of alphanumeric characters with some hyphens.

The reason I need to change this is so that users can simply type a recognizable and easy-to-remember word like "meetings" instead of a long string of potentially-error-prone letters, digits, and dashes.

Thanks in advance.

**Comment by pbiering** [comment]
The "exposed" calendar name is the same as the related directory is named on the file system -> rename it on the file system, restart radicale.

**Comment by randolf** [comment]
That's an easy solution that answers my question.  Thank you!

**Comment by randolf** [comment]
That's an easy solution that answers my question.  Thank you!
