### ISSUE TITLE
Webcal-subscriptions in a Docker Image (Homeassistant)

### ISSUE THREAD

**Issue by Slin-nilS** [Kozea/Radicale#1333]
Hi, I want to add a ICAL url to my Baikal Server. I use Baikal on my Homeassistant Pi [Plugin](https://github.com/alexbelgium/hassio-addons/tree/1de33f5e3307d7ef65c63664aca40b87603cfb8f/baikal)

I saw the  Conversation from @leso-kn  #1229 . But where I have to create the ` .Radicale.props` file?
Inmy Docker installation I have only these directorys:
```ssh
➜  ~ docker exec -it 9eb4ff58ed8c bash
root@db21ed7f-baikal:/data# ls -lahtr
total 72K
drwxr-xr-x 4 nginx nginx 4.0K Sep 24 20:15 Core
-rw-r--r-- 1 nginx nginx 1.4K Sep 24 20:15 README.md
-rw-r--r-- 1 nginx nginx  35K Sep 24 20:15 LICENSE
drwxr-xr-x 4 nginx nginx 4.0K Sep 24 20:15 html
drwxr-xr-x 8 nginx nginx 4.0K Sep 24 20:15 vendor
drwxr-xr-x 2 nginx nginx 4.0K Sep 24 20:20 config
drwxr-xr-x 3 nginx nginx 4.0K Sep 24 20:22 Specific
-rw------- 1 nginx nginx    2 Sep 26 18:34 options.json
drwxr-xr-x 1 root  root  4.0K Sep 26 18:34 ..
drwxr-xr-x 7 nginx nginx 4.0K Sep 26 20:01 .
root@db21ed7f-baikal:/data#
```
Thanks

**Comment by leso-kn** [comment]
Hey :) Those instructions were applicable for another calendar server project unrelated to Baïkal (the [radicale calendar server](https://radicale.org). As mentioned in the followup discussion, Baikal does not currently implement the announcement of webcal subscriptions.

If you're looking for a calendar server with this feature you may want to check out Radicale and clone the branch I submitted for merging: [here](https://github.com/Kozea/Radicale/pull/1229#issuecomment-1704319284).

Personally overall I would recommend Baïkal though, as besides webcal subscriptions it as a wider set of features.

**Comment by Slin-nilS** [comment]
Hey @leso-kn, Thank´s for your answer. I will have a look "radicale" and I will test it.

**Comment by Slin-nilS** [comment]
@leso-kn In the moment I test the [Nextcloud Calender function ](https://docs.nextcloud.com/server/latest/user_manual/de/groupware/calendar.html)
The installing as a [plugin](https://github.com/alexbelgium/hassio-addons/tree/master/nextcloudl) was very easy
