### ISSUE TITLE
Fail with Python 3.11.4 (ValueError: An IPv4 address cannot be in brackets)

### ISSUE THREAD

**Issue by petterreinholdtsen** [Kozea/Radicale#1336]
This is Debian bug https://bugs.debian.org/1038687 .

Several automated tests of the installed radicale package (Debian autopkgtest) fail with:

[...]
hostname = '127.0.0.1'

    def _check_bracketed_host(hostname):
        if hostname.startswith('v'):
            if not re.match(r"\Av[a-fA-F0-9]+\..+\Z", hostname):
                raise ValueError(f"IPvFuture address is invalid")
        else:
            ip = ipaddress.ip_address(hostname) # Throws Value Error if not
IPv6 or IPv4
            if isinstance(ip, ipaddress.IPv4Address):
>               raise ValueError(f"An IPv4 address cannot be in brackets")
E               ValueError: An IPv4 address cannot be in brackets

/usr/lib/python3.11/urllib/parse.py:448: ValueError[...]

This changed after Python 3.11.4 and Python 3.12 was introduced. The test cases or code probably need some adjustments.

The tests are in debian/tests/ in the git source available via https://tracker.debian.org/radicale .  The failing CI test logs are available via the same page.

**Comment by jonassmedegaard** [comment]
This issue is solved by https://github.com/Kozea/Radicale/pull/1328

**Comment by pbiering** [comment]
https://github.com/Kozea/Radicale/pull/1328 merged today
