### ISSUE TITLE
Apache proxy 502 when uploading files

### ISSUE THREAD

**Issue by bobbyl140** [Kozea/Radicale#1348]
I set up Radicale yesterday, and it works perfectly with my IP over LAN. But when I set up Apache to proxy to Radicale, I can't seem to upload anything to the server. I went on the web UI and uploaded a single contact card, and got `502 Bad Gateway`. I gave Radicale its own subdomain. Here is the Apache config:
```
<VirtualHost *:80>
        ServerName dav.example.com
        <Location "/">
                ProxyPass http://127.0.0.1:5232/
                ProxyPassReverse http://127.0.0.1:5232/
        </Location>
</VirtualHost>
```
What exactly am I doing wrong? 
Thank you!

**Comment by pbiering** [comment]
Can you provide detailed logs from Apache and Radicale?

**Comment by pbiering** [comment]
please check/compare with supplied reference config, reopen with logs in case still an issue
https://github.com/Kozea/Radicale/tree/master/contrib/apache
