### ISSUE TITLE
syslog shows wrong timestamp

### ISSUE THREAD

**Issue by Semmelrocks** [Kozea/Radicale#1349]
Hi together,

I've a weird problem with logging radicale. I'm using 'syslog-ng' as
syslog which is working fine - except one thing.
This is a snippet of my logs some minutes ago:

> Jan 12 23:04:45 server radicale: [2024-01-14 18:46:19 +0100]
> [3038/Thread-122 (process_request_thread)] [INFO] PROPFIND response
> status for '/user/' with depth '0' in 0.005 seconds: 207 Multi-Status
> Jan 14 18:59:08 server su[5651]: (to user) root on pts/1

As you can see syslog is starting with a two day back timestamp while
the radical log itself delivers the correct time. To compare I'd made a
'su' some minutes later which shows the correct time. 'date' and
'hwclock' showing equal values. The timezone in /etc is set correct.

Where does the fully wrong time come wrong? Can the time for WSGI be
different to radicale? Is it actually a syslog-ng problem? Any ideas?

Thanks in advance!

**Comment by pbiering** [comment]
@Semmelrocks : have you checked any other log event which is stored by `syslog-ng` into another file...potentially `syslog-ng` started before timesync was successful and did not update it's internal time for logging since then.

**Comment by pbiering** [comment]
closed because of no feedback
