### ISSUE TITLE
Support events without UIDs

### ISSUE THREAD

**Issue by MacGyverNL** [Kozea/Radicale#135]
I set up remote calendar sync using the wget-in-cron method from issue #98. I've setup a script which is run through cron.hourly, downloading five calendars from different sources. I'm having the following problems:

1. Thunderbird (24.4.0) with Lightning (2.6.4) is unable to sync these remote calendars when selecting the Caldav-method. I can only access them if I set the calendar type to iCalendar when I add them.

2. One specific calendar, https://mozorg.cdn.mozilla.net/media/caldata/DutchHolidays.ics, is causing strange behaviour in Thunderbird and CalDAV-sync (0.4.5) for android. Note that the four other calendars do not have this problem.

2.1. First, CalDAV-sync is attempting to sync all external calendars every 1 or 2 minutes, even though it is set to sync every 6 hours at most. I'm not sure where the cause of this is yet, but it might actually be triggered by Radicale, because:

2.2. Every time CalDAV-sync attempts to sync the DutchHolidays-calendar, it performs GET-requests for each of the events it wants to synchronize. I see these requests in the Radicale-log. That's all events from 2 weeks in the past to 6 weeks in the future. However, these do not show up in the Calendar app on android, the other external calendars show up fine.

2.3. Then, every time Thunderbird attempts to synchronize this calendar, it duplicates all events which have had GET-requests from CalDAV-sync, so that's all events from 2 weeks in the past to 6 weeks in the future. It only does one duplication per event per Thunderbird-sync, even though by then there will have been 20 GET-requests for each event.

I log in with user1, who has (working) read-only access to the external calendars through the read-only folder structure with symlink shown below. The calendars are marked as read-only in Thunderbird, and CalDAV-sync is set to only sync from server to client.

~~My Radicale folder-setup for these calendars is as follows:~~
Can't get this to look as it should, so if it is relevant drop a comment.

**Comment by liZe** [comment]
It should be fixed now!
