### ISSUE TITLE
Where is the config folder located on Windows

### ISSUE THREAD

**Issue by richard3840** [Kozea/Radicale#1351]
Hello. I am trying to configure Radicale on Windows.

I have installed it according to the documentation here: https://radicale.org/v3.html

I have reached the Basic Configuration section where it says that config files by default are loaded from the folowing folders:
/etc/radicale/config
~/.config/radicale/config

My question is, where are those folders located on Windows.

Using the search program Everything, i have confirmed that the only folders on my system named radicale are located here:
C:\Users\(Username)\radicale
C:\Users\(Username)\AppData\Local\Programs\Python\Python312\Lib\site-packages\radicale
C:\Users\(Username)\AppData\Local\Programs\Python\Python312\Lib\site-packages\Radicale-3.1.8.dist-info

Thanks.

**Comment by MatthewHana** [comment]
Hi @richard3840 ,

From DOCUMENTATION.md:
```
Radicale tries to load configuration files from `/etc/radicale/config` and
`~/.config/radicale/config`.
Custom paths can be specified with the `--config /path/to/config` command
line argument or the `RADICALE_CONFIG` environment variable.
Multiple configuration files can be separated by `:` (resp. `;` on Windows).
Paths that start with `?` are optional.
```

Pass the config using the --config argument or set the environment variable.

**Comment by richard3840** [comment]
Thank you
