### ISSUE TITLE
LDAP/AD plugin for v3 available at my repo

### ISSUE THREAD

**Issue by 11notes** [Kozea/Radicale#1352]
Hi, 
Just to let you know I've added a v3 LDAP/AD plugin for LDAP auth to radicale in case you are interested: https://github.com/11notes/docker-radicale/tree/253adaae73305c2737a79d80ebfc8ae9270e4098/rootfs/plugins/radicale_auth_ldap

**Comment by shroomify-it** [comment]
I've done the same, a v0.3 auth plugin with LLDAP
https://github.com/shroomify-it/radicale-auth-ldap-plugin

**Comment by 11notes** [comment]
> I've done the same, a v0.3 auth plugin with LLDAP https://github.com/shroomify-it/radicale-auth-ldap-plugin

That is great! I use mine for UPN to Windows AD and it works flawlessly so far.
