### ISSUE TITLE
radicale.org is lost

### ISSUE THREAD

**Issue by gdweber** [Kozea/Radicale#1353]
The README.me file says
"For the complete documentation, please visit [Radicale master Documentation](https://radicale.org/master.html)."
but for at least a few days now the DNS address of radicale.org cannot be found.  

Brave Browser says 
"This site can’t be reachedradicale.org’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE"

Firefox:

"Hmm. We’re having trouble finding that site.

We can’t connect to the server at radicale.org.

If you entered the right address, you can:

    Try again later
    Check your network connection
    Check that Firefox has permission to access the web (you might be connected but behind a firewall)

"

**Comment by gdweber** [comment]
Until this is restored, perhaps [Radicale](https://github.com/Kozea/Radicale/tree/master)
/DOCUMENTATION.md provides the equivalent documentation?

**Comment by krukai** [comment]
Correct, see https://web.archive.org/web/20240205215302/https://radicale.org/v3.html

**Comment by pbiering** [comment]
the web pages of radicale.org are stored in a special branch here:

https://github.com/Kozea/Radicale/tree/gh-pages

**Comment by pbiering** [comment]
radicale.org lost it's NS entries in DNS, I would assume someone did not prolong the domain.
Maintainer is still active ( https://github.com/Unrud ) - no clue why not reacting here in this particular repo anymore :-( 

@Unrud : do you have explanations/reason for being so quiet here? Can you at least support in
- transfer of domain "radicale.org" to a party which will eventually further host the website
- mark this repository as stale/orphan once overtaken into a new one if it cannot be proper maintained under "Kozea" anymore?

**Comment by Unrud** [comment]
@pbiering I don't have control of the domain. Try to contact @liZe. He can also give you write access to the repo if you are interested.

**Comment by gdweber** [comment]
radicale.org has reappeared.

**Comment by liZe** [comment]
> radicale.org has reappeared.

Sorry for the inconvenience. 🙏🏽

**Comment by pbiering** [comment]
> @pbiering I don't have control of the domain. Try to contact @liZe. He can also give you write access to the repo if you are interested.

I've contacted @liZe by private e-mail now, hopefully willing to agree to grant required permissions.

**Comment by liZe** [comment]
> I've contacted @liZe by private e-mail now, hopefully willing to agree to grant required permissions.

I’m not administrator of the repository anymore, maybe @gentooboontoo can help.

**Comment by pbiering** [comment]
> I’m not administrator of the repository anymore, maybe @gentooboontoo can help.

Thank you for that hint, contacted now @gentooboontoo  by private e-mail.
