### ISSUE TITLE
Documentation error: "any username and password"

### ISSUE THREAD

**Issue by gdweber** [Kozea/Radicale#1354]
DOCUMENTATION.md states, under Getting Started / Installation : "You can login with any username and password."
and repeats this statement under Tutorials / Simple 5-minute setup / Linux / *BSD, and again under Windows.

The statement is incorrect.  Entering any user name and password without further configuration results in 403: Forbidden.

To enable login with any user name and password, it seems necessary to create a config file with the lines
~~~
[auth]
type = none
~~~
or use equivalent command-line flags.

This documentation error is likely to deter potential users, as it is the first thing they are likely to try and it does not work.  (It almost drove me away.)

**Comment by pbiering** [comment]
Cannot reproduce, even without having `[auth]` section in config, on startup it reports:

```
auth type is 'radicale.auth.none'
```

and access without credentials is working. Do you have a modifed version of "radicale" in use?

**Comment by gdweber** [comment]
On 2024 Feb 6 I installed radicale with this command (as
ordinary user, not root or sudo):

~~~
$ python3 -m pip install --upgrade https://github.com/Kozea/Radicale/archive/master.tar.gz
~~~

It identifies itself as
~~~
$ python3 -m radicale  --version
3.dev0
~~~

I did not modify the code.

But, my apologies, I also am unable to reproduce the error today,
so let's consider the issue closed.
