### ISSUE TITLE
Radicale is vulnerable to enumeration for at least python 3.6

### ISSUE THREAD

**Issue by LuminatiHD** [Kozea/Radicale#1443]
We have a carddav server with radicale 3.1.8, with the underlying version of python being 3.6.18. I noticed that when trying to log in as a nonexistent user, radicale errors out.
```
env[313396]: Traceback (most recent call last):
env[313396]:   File "/usr/local/lib64/python3.6/site-packages/radicale/app/__init__.py", line 105, in __call__
env[313396]:     status_text, headers, answers = self._handle_request(environ)
env[313396]:   File "/usr/local/lib64/python3.6/site-packages/radicale/app/__init__.py", line 239, in _handle_request
env[313396]:     user = self._auth.login(login, password) or "" if login else ""
env[313396]:   File "/usr/local/lib/python3.6/site-packages/radicale_auth_ldap/__init__.py", line 208, in login
env[313396]:     logger.error("LDAP user %s not found" % user)
env[313396]: NameError: name 'user' is not defined
```
Which will make radicale return an http code 500. In contrast, logging in as an existent user with wrong credentials returns a 401. This makes radicale vulnerable to enumeration, for at least the python version 3.6.18.

**Comment by felixfontein** [comment]
The error seems to come from the Python package `radicale_auth_ldap`, which is not part of Radicale.

**Comment by pbiering** [comment]
There are legacy PRs adding LDAP authentication support to "radicale", none of them were merged so far, please file ticket to this particular package.
