### ISSUE TITLE
constant Client provided invalid sync token on new install

### ISSUE THREAD

**Issue by Josh65-2201** [Kozea/Radicale#1479]
## Description
I setup a install on Windows using python a few days ago and imported my calendar/contacts from google. They are syncing to thunderbird client on Windows and DavX5 on android. But when ever I make a change or open thunderbird it will show
```
Client provided invalid sync token 'http://radicale.org/ns/sync/4b056d69795590f1cccd1156e96cd2da9368b872e4600b8303a825bdd211691b': Token not found: 'http://radicale.org/ns/sync/4b056d69795590f1cccd1156e96cd2da9368b872e4600b8303a825bdd211691b'
```
Thunderbird also seem to break syncing because of this, locking the calendar to read only. Contacts are working fine.

## Versions
Radical: 3
Python: 3.11.0
OS: Windows 11 build 22621.3447

**Comment by pbiering** [comment]
Can you cleanup the whole cache per calendar folder on server side by 

1. stop radicale
2. remove all files in .Radicale.cache
3. start radicale

**Comment by Josh65-2201** [comment]
Done that, still shows

**Comment by Josh65-2201** [comment]
Since doing that, the error still shows but syncing is working correctly. I'm going to close this since there no issue with functionality.
