### ISSUE TITLE
Publish to PyPi workflow broken

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#1483]
This happened after the release of 3.2.0:

https://github.com/Kozea/Radicale/actions/runs/8943158465/job/24567264820

I have no experiences here, can one support me please? Looks like several things must be fixed...

**Comment by ZingyAwesome** [comment]
Apologies if I am just stating the obvious, but there is this error in the log:
```
User 'unrud' does not have a verified primary email address. Please add
         a verified primary email before attempting to upload to PyPI. See      
         https://pypi.org/help/#verified-email for more information.
```
So it looks like there's something wrong with the PyPi user account? I believe the other warnings can be ignored for now.

**Comment by liZe** [comment]
We could add a repository admin in the list of PyPI maintainers. Anyone interested?

**Comment by pbiering** [comment]
> We could add a repository admin in the list of PyPI maintainers. Anyone interested?

Add at least me, thank you very much, I have created now an account here: pbiering

**Comment by liZe** [comment]
> Add at least me, thank you very much, I have created now an account here: pbiering

Done!

**Comment by pbiering** [comment]
@liZe : thank you for the invitation, but my current permissions on "Radicale" prevent me entering the "Settings" page and configure the required secret.

According to https://github.com/marketplace/actions/pypi-publish an API token 

`${{ secrets.PYPI_API_TOKEN }}`

must be configured, as it is a personal one it should be not disclosed here...so either you enrich my permissions or I send it to you by e-mail.

**Comment by liZe** [comment]
@pbiering I’m not admin on GitHub. Maybe you can write a mail to @gentooboontoo 😄.

**Comment by pbiering** [comment]
@gentooboontoo : can you support here, a value must be set in Settings -> Security -> Secrets and variables -> Actions

**Comment by pbiering** [comment]
@gentooboontoo / @Unrud : any change to fix this?

**Comment by pbiering** [comment]
@gentooboontoo : thank you, received

>  PyPI user gentooboontoo has added a new trusted publisher to a project (Radicale) that you manage. Trusted publishers act as trusted users and can create project releases automatically.
> 
> Publisher information:
> 
>     Publisher name: GitHub
>     Workflow: pypi-publish.yml
>     Owner: Kozea
>     Repository: Radicale

and re-triggered the workflow, now 3.2.0 is visible here: https://pypi.org/project/Radicale/#history

**Comment by gentooboontoo** [comment]
> @gentooboontoo : thank you, received

Sorry @pbiering, I missed the notification for the previous messages, hence the delay…
