### ISSUE TITLE
Pytest 8 support

### ISSUE THREAD

**Issue by dvzrv** [Kozea/Radicale#1486]
Hi! :wave: 

I'm packaging this project for Arch Linux.
We are currently trying to get rid of pytest 7 in our repositories, which we had to introduce for some packages.
Radicale appears to be not compatible with pytest > 7 (which is now at 8.1.2) and also locks typeguard to < 3 (which is now at 4.2.1).

It would be awesome if compatibility could be fixed! :)
Thanks

**Comment by pbiering** [comment]
Even Fedora 40 as only pytest 7 available (7.4.3) - so potentially you have to tweak that locally on Arch Linux meanwhile by tweaking `setup.py` and hopefully it passes then the test suite, can't help here much.

**Comment by dvzrv** [comment]
> Even Fedora 40 as only pytest 7 available (7.4.3)

I'm not sure what this has to do with Fedora 40. They will update pytest to version > 8 soon as well and this will have to be done either way.
Do you not test this application in a venv and update dependencies regularly?

> so potentially you have to tweak that locally on Arch Linux meanwhile by tweaking setup.py and hopefully it passes then the test suite

It doesn't, that's why I'm writing this ticket.

Radicale is one of nine packages that is not compatible with pytest > 8 (https://archlinux.org/todo/pytest7-removal/).
In contrast hundreds of packages are already compatible: https://archlinux.org/packages/extra/any/python-pytest/

**Comment by pbiering** [comment]
> Do you not test this application in a venv and update dependencies regularly?

I try to keep this project running with the limited time I have and for the use case I have (which is a working installation on EL9) - the former maintainer turned too busy.

So feel free to contribute.

**Comment by pbiering** [comment]
Looks like this broke all the tests beside `*-pypy-*`

**Comment by pbiering** [comment]
adjusting to ` "typeguard>=4"` was not a good idea as newest is 4.3 which broke many test jobs. Fixed now by limiting to "typeguard<4.3".
