### ISSUE TITLE
vdirsyncer config with webcal

### ISSUE THREAD

**Issue by DhruvaSambrani** [Kozea/Radicale#1496]
I have set up a webcal calendar and DAVx/ICSx on android works perfectly good with it.

However, i am not entirely sure how to set up the vdirsyncer so that it picks up the metadata and events. This is my current setup:

```
[pair feiertage]
a = "feiertage_local"
b = "feiertage_remote"
collections = null

# Calendars also have a color property
metadata = ["displayname", "color"]

[storage feiertage_local]
type = "filesystem"
path = "~/.calendars/feiertage"
post_hook = "notify-send"
fileext = ".ics"

[storage feiertage_remote]
type = "http"
url = "https://archacer.rove-koi.ts.net/radicale/dhruva/nrw-holidays/"
username = "dhruva"
password = "mypassforradicalehere" 
```

No events are picked, and metasync gives

```
error: Unknown error occurred for feiertage: This storage does not support metadata.
```

**Comment by DhruvaSambrani** [comment]
Probably similar to #1484

**Comment by pbiering** [comment]
"vdirsyncer" has either to honor the response and sync with provided source or skip.

**Comment by applesoff** [comment]
I do not see any documentation regarding how to set up webcals. for the source am I pointing this to another calendar? or is this webcal its own standalone calendar?

**Comment by pbiering** [comment]
added a page in Wiki now: https://github.com/Kozea/Radicale/wiki/Collection-type-VSUBSCRIBED-(Webcal)

**Comment by applesoff** [comment]
Thanks for that. I am not that technically inclined. Firstly, is there a better spot to ask questions about these? I would be happy to move it off this issue. 

I see the wiki, but when I saw the source listed it was "http://i.cal.to/ical/65/bayern/feiertage/499a5ad5.07785850-d8e6092a.ics"
I was curious if "https://radicale.mydomain.com/user/8bdc9bfa-b6c5-7227-c41c-ab1cec7d6ad1/" was also good. Essentially referencing a calendar I made as the source of a webcal to send to others. I may be convoluting this. 
Is there an easy way to share a calendar with others that updates automatically when I add/remove events? Most don't want to install DAVx5 or add my server when I want to share my calendar

**Comment by pbiering** [comment]
> Most don't want to install DAVx5 or add my server when I want to share my calendar

What do you want now? Serving a calendar URL like the "feiertage" above?
- unauthenticated (public): simply "cat together" all related *.ics files into a single file and publish on a web server and distribute the URL
- with authentication
  - same as above, but let webserver authenticate the user
  - using "radicale" and softlinking into user's directory and try to use the permission "i" for such users+collection (never done this so far)

**Comment by pbiering** [comment]
@applesoff : I've checked and found a way how to use "radicale" to share a collection as read-only to public while being able to administrate the collection content as admin.

Example documented in the Wiki now: https://github.com/Kozea/Radicale/wiki/Sharing-Collections#sharing-a-collections-read-only-to-public-as-webcal.

**Comment by pbiering** [comment]
closed now, please reopen if needed
