### ISSUE TITLE
Calendar can no longer be opened after upgrade to version 3.2

### ISSUE THREAD

**Issue by RalfJung** [Kozea/Radicale#1498]
I upgraded radicale from 3.1.8 to 3.2.0, and now I can no longer access my calendar:
```
Mai 27 08:48:39 r-ethtop radicale[313128]: [313128/Thread-15 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ralfj/kalender.cal/': Failed to load item '87a651b3-153b-46e5-bd26-d9fa5beb21b8.ics' in 'ralfj/kalender.cal': At line 32: Failed to parse line:                      \n                                                   
Mai 27 08:49:29 r-ethtop radicale[313128]: [313128/Thread-18 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ralfj/kalender.cal/': Failed to load item '87a651b3-153b-46e5-bd26-d9fa5beb21b8.ics' in 'ralfj/kalender.cal': At line 32: Failed to parse line:                      \n                                                   
Mai 27 08:49:41 r-ethtop radicale[313128]: [313128/Thread-19 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ralfj/kalender.cal/': Failed to load item '87a651b3-153b-46e5-bd26-d9fa5beb21b8.ics' in 'ralfj/kalender.cal': At line 32: Failed to parse line:                      \n                                                   
```

Seems like past versions of radicale created an invalid item? But then radicale should ideally fix such issues itself on an upgrade rather than making the admin manually fiddle with the internal storage of the calendar server.

**Comment by pbiering** [comment]
At least the pasted ICS was rejected by the validator, see also https://github.com/Kozea/Radicale/wiki/Reporting-Issues

Unfortunatly, there are clients existing which create buggy content.

Also I'm not aware of any code changes between 3.1.8 and 3.2.0 in that area.

**Comment by RalfJung** [comment]
Thanks for taking a look!

Yeah I don't doubt that the ICS is invalid. radicale should surely reject that when a client adds a new invalid event. But that's not what happened here, this event was created in 2020 and caused no visible issue until now. What happened recently is: everything worked fine, and then I did a system update, and then I can't access my calendar any more. No new event added, just the same calendar data as before. Clearly that's a bug, right? My guess is that some ancient version of radicale accepted the buggy ICS, and then until recently radicale tolerated the existence of buggy ICS, and now that tolerance is over, but there's not a good way for users to deal with buggy ICS that radicale accidentally accepted years ago.

**Comment by pbiering** [comment]
I can understand, but I'm unable at the moment to trace down what happened between 3.1.8 and 3.2.0 preventing this inside the server. Did you update `vobject` also, on which `radicale` relies on parsing the files?

The only thing I can imagine is that the cached entry turned stale and a re-parsing happened.

**Comment by RalfJung** [comment]
I did a very big `apt upgrade` so tons of stuff changed its version. However, python3-vobject has not been updated in Debian since 2022, so that stayed unchanged.

Sorry, I should probably have mentioned that this is using the Debian package.

**Comment by strauss115** [comment]
I got exactly the same error as @RalfJung with the following invalid ics

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PYVOBJECT//NONSGML Version 1//EN
BEGIN:VEVENT
UID:removed@google.com
DTSTART:20211022T140000Z
DTEND:20211024T214500Z
ATTENDEE;CN=removed;EMAIL=removed@removed.com;RSVP=FALSE:mailto:
 removed@removed.com
ATTENDEE;CN=removed;CUTYPE=INDIVIDUAL;EMAIL=removed@removed.com;PARTSTA
 T=ACCEPTED;X-CALENDARSERVER-DTSTAMP=20221227T172148Z:mailto:removed@removed.co
 m
CLASS:PUBLIC
CREATED:20221227T172148Z
DESCRIPTION;ALTREP="data:text/html,%3Ctable%3E%3Ctbody%3E%3Ctr%3E%3Ctd%3EDi
 e%20Buchungremovednotrelevant
 A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A%3A~%3A~%3A%3A-%3Cbr%3E":
                             \nDie Buchung für den folgenden Zeitraum wurd
 e geändert\n22.10.2021 16:00 - 24.10.2021 23:45\n \nDas Fahrzeug befindet
  sich am folgenden Standort\n                                removed
                      \n \nWeitere Buchungsdetails\n




                                                      \nBenutzer:       removed
 \nFahrzeug: Renault Zoe\nNummernschild:     removed\nFahrziel:     removed
 \nFahrzweck:   Privat\nBenutzungsart:  Privat\n\n\n-::~:~::~:~:~:~:~:~:~:~:~:
 removed
 ~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-\n
DTSTAMP:20231231T121233Z
LAST-MODIFIED:20221227T172148Z
ORGANIZER;CN=removed@removed.com;EMAIL=removed@removed.com:mailto
 :removed@removed.com
SEQUENCE:0
SUMMARY:s Leasing Fahrzeug "Renault Zoe"
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

Radicale 3.1.9 based on Alpine 3.18.2 worked fine. Since Radicale 3.2.0 and Alpine 3.19.1 it stopped working.
Anyway, I removed the file and everything is fine. But it seems that this issue occured several times, here is another example [https://github.com/tomsquest/docker-radicale/issues/149](https://github.com/tomsquest/docker-radicale/issues/149)

**Comment by pbiering** [comment]
There is a command to verify the storage, documented now here explicitly

https://github.com/Kozea/Radicale/wiki/Server-Diagnostics---Troubleshooting

BTW: was the PROPFIND request still successful but leaving out the problematic one or did it not respond at all.

Question would be how to handle that...potentially by adding a "lazy" option, leaving out problematic entries, but log this.

**Comment by RalfJung** [comment]
> BTW: was the PROPFIND request still successful but leaving out the problematic one or did it not respond at all.

The client indicated an error, so I assume it did not respond at all or responded with an error code.

> There is a command to verify the storage, documented now here explicitly

Thanks! Looks like I no longer have any invalid entries. I get another error, and opened a separate [discussion](https://github.com/Kozea/Radicale/discussions/1506) for that.

**Comment by pbiering** [comment]
Looks like a code extension to skip but report in log broken entries is required, contributions are welcome.

**Comment by pbiering** [comment]
@RalfJung : https://github.com/Kozea/Radicale/pull/1520 implemented now an option to skip broken entries, can you give a try to latest master?

**Comment by RalfJung** [comment]
I have already deleted the problematic events... I don't think I will easily be able to test this, sorry.

**Comment by pbiering** [comment]
I've ran a local test with a broken item, looks good, will close this now.
