### ISSUE TITLE
Don't re-tag!

### ISSUE THREAD

**Issue by dotlambda** [Kozea/Radicale#1508]
I ask you to immediately restore tag v3.2.1 to where it previously pointed to. Otherwise this breaks the build in Linux distributions that use hashes to check tarball integrity: https://github.com/NixOS/nixpkgs/issues/317147
You can always tag a new version 3.2.2.
Please never ever do this again!

**Comment by pbiering** [comment]
tag adjusted by @gentooboontoo , sorry, lession learnt
