### ISSUE TITLE
Floccus  bookmark sync 

### ISSUE THREAD

**Issue by Lik-the-Fluffin** [Kozea/Radicale#1513]
I tried to set up Floccus WebDAV bookmark synhttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntaxc with my Radicale instance and got "Syncing failed with E018: Couldn't authenticate with the server."
Wasn't able to find any information on how Radicale works with bookmarks, but instruction on Floccus page says "You can use it with any WebDAV-compatible server."
My [docker log](https://github.com/user-attachments/files/15746099/radicale.log) and [config file](https://github.com/user-attachments/files/15746122/config.txt)

**Comment by pbiering** [comment]
"Radicale" is a pure Cal/CardDAV server, not being able to act as a WebDAV server. Use e.g. Apache's WebDAV extension for use with Floccus (I have personally running such setup).

Example for Apache config sniplet:

```
	# WebDAV
	DavLockDB /path/to/DavLock

	Alias "/dav" "/path/to/pub-dav"

	UserDir /path/to/pub-dav
	UserDir enabled USER1 USER2
	UserDir disabled root

	<Directory "/path/to/USER1">
		Dav			On
		AuthType		Basic
		AuthName		"dav"
		AuthUserFile 		/path/to//htpasswd-users
		Order			deny,allow
		Satisfy			all
		Require			user USER1
	</Directory>
```
