### ISSUE TITLE
Meeting invitations with 'X-MICROSOFT-DISALLOW-COUNTER' result in error 400

### ISSUE THREAD

**Issue by nl06857** [Kozea/Radicale#1524]
Meeting invitations (.ics event files) from an online meeting scheduling application (datumprikker.nl) are not accepted by Radicale; it responds with code 400. (In fact, I tried to import in Thunderbird, but it was Radicale that rejected it).
Looking for the differences between a rejected .ics file and .ics files from other origins that Radicale did accept, I noticed one line that was only present in the rejected files:
**SET X-MICROSOFT-DISALLOW-COUNTER:TRUE**
After removing this line from the .ics file, it was accepted.
Maybe, it is possible to ignore X-Microsoft-… crap?

**Comment by nl06857** [comment]
The meeting invitation did pass the Validator successfully.
Another consideration: according to RFC 5545 'Applications MUST ignore x-param and iana-param values they don't    recognize.' (section 3.2), but the 'SET' is a strange thing that is not mentioned in the RFC.
I would conclude that it were nice if an .ics file like this would be accepted, especially since the Validator accepts it as valid, but that the file under consideration is not in line with the RFC.

**Comment by pbiering** [comment]
@nl06857 : created an issue here https://github.com/py-vobject/vobject/issues/49, please attach there anonymized ICS.
