### ISSUE TITLE
Wrong packaging numbers for the .egg-infos (3.dev0 vs. 3.2.2)

### ISSUE THREAD

**Issue by szotsaki** [Kozea/Radicale#1528]
Expected directory structure after compiling and installing Radicale:

```
/usr/lib/python3.11/site-packages/Radicale-3.2.2-py3.11.egg-info/PKG-INFO
```

Actual:

```
/usr/lib/python3.11/site-packages/Radicale-3.dev0-py3.11.egg-info/PKG-INFO
```

**Comment by pbiering** [comment]
oops, sorry, fixed, new tag applied, new release generated to push to PyPI.

Are there any ideas how such human mistakes can be avoided by e.g. extension of release+publishing workflow?

**Comment by szotsaki** [comment]
Thanks for the quick fix.

To be honest, I'm not very well-versed in Github, but I saw that others use various bots to do the chores.
Also, another approach, that you bump the version to the next one (3.2.3 in this case) very early in the dev cycle and use that during development, up until (and including) the release.

**Comment by pbiering** [comment]
Any idea how to remove the "3.dev" from PyPI (and some old *rc* can be wiped also)?
