### ISSUE TITLE
Follow XDG for default filesystem_folder

### ISSUE THREAD

**Issue by jonassmedegaard** [Kozea/Radicale#153]
Currently filesystem_folder has no internal default and the sample config has it set to ~/.config/radicale/collections

I recommend to change that to internally consult PyXDG for the value of XDG_DATA_HOME, which should by default resolve to ~/.local/share/Radicale/collections

...and then in sample config have filesystem_folder empty and commented out, with comment referencing support for overiding also by setting XDG_DATA_HOME, and how it by default resolves to ~/.local/share/Radicale/collections

**Comment by liZe** [comment]
The default path has been set to `/var/lib/radicale/collections`.
