### ISSUE TITLE
log.set_level() includes breaking change

### ISSUE THREAD

**Issue by tschai-yim** [Kozea/Radicale#1530]
Hello, [EteSync DAV](https://github.com/etesync/etesync-dav) no longer starts up correctly (errors at [this line](https://github.com/etesync/etesync-dav/blob/master/etesync_dav/radicale_main/__init__.py#L136)) because `log.set_level()` got a new mandatory parameter [`backtrace_on_debug`](https://github.com/Kozea/Radicale/commit/ad596002f3dbae6079f2663218596cd670449328#diff-81d5443673540013f5a432a6c7b4a053976b26ca51a43542c6e5fc450ea639ccR223) parameter in version `3.2.2`. 

If this intentional and EteSync is using Radical incorrectly, please close this issue again and excuse the disturbance. I've not taken the time to look into how EteSync nor Radical works and integrates exactly, but instead opted to just freeze my local Radicale version to `3.2.1`. Thanks for your package and cheers :+1:

**Comment by pbiering** [comment]
I was not aware about that other projects using "radicale" internal functions to work-on-top...

The only supportable ways are well-known exposed APIs, which in case of "radicale" the HTTP(S) interface only so far.

Every other method is on high risk to stop working by accident in the future.
