### ISSUE TITLE
[ERROR] Failed to connect to systemd journal: [Errno 97] Address family not supported by protocol

### ISSUE THREAD

**Issue by BlueMax** [Kozea/Radicale#1532]
I get the error below when starting radicale. It starts up nevertheless and works properly.
I'm using IPv4 only but there is an IPv6 local address assigned.

Arch Linux 6.9.7
radicale 3.2.2
python 3.12.4

```
[server]
hosts = 127.0.0.1:5678, 192.168.2.2:5678
```
```
Jul 02 20:43:50 host radicale[4675]: [2024-07-02 20:43:50 +0200] [4675] [ERROR] Failed to connect to systemd journal: [Errno 97] Address family not supported by protocol
Jul 02 20:43:50 host radicale[4675]: Traceback (most recent call last):
Jul 02 20:43:50 host radicale[4675]:   File "/usr/lib/python3.12/site-packages/radicale/log.py", line 148, in _try_emit_journal
Jul 02 20:43:50 host radicale[4675]:     journal_socket = socket.socket(
Jul 02 20:43:50 host radicale[4675]:                      ^^^^^^^^^^^^^^
Jul 02 20:43:50 host radicale[4675]:   File "/usr/lib/python3.12/socket.py", line 233, in __init__
Jul 02 20:43:50 host radicale[4675]:     _socket.socket.__init__(self, family, type, proto, fileno)
Jul 02 20:43:50 host radicale[4675]: OSError: [Errno 97] Address family not supported by protocol
Jul 02 20:43:50 host radicale[4675]: [2024-07-02 20:43:50 +0200] [4675] [INFO] Logging of backtrace is disabled in this loglevel
``` 
```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.2/24 brd 192.168.2.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::xxxx:xxxx:xxxx:xxxx/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

**Comment by pbiering** [comment]
This is a strange error and the message is misleading.

"radicale" want to open a UNIX socket

```
           try:
                journal_socket = socket.socket(
                    socket.AF_UNIX, socket.SOCK_DGRAM)
                journal_socket.connect("/run/systemd/journal/socket")
            except OSError as e:
```

this is totally unrelated to inet/inet6 sockets.

@BlueMax : can you check whether this socket file exist at all? Should look like

```
$ ll /run/systemd/journal/socket
srw-rw-rw-. 1 root root 0 27. Jun 10:45 /run/systemd/journal/socket
```

**Comment by BlueMax** [comment]
Yes, its there:
```
$ ls -al /run/systemd/journal/socket
srw-rw-rw- 1 root root 0 Jul  2 20:03 /run/systemd/journal/socket
```

**Comment by pbiering** [comment]
Do you have SELinux active? What is the result of `getenforce`?

**Comment by BlueMax** [comment]
No, selinux is not active. I'm not at the system right now so I can give you getenforce result later.
I have 'audit=0' kernel command set. Not sure if that's related though. Will test that as well.

**Comment by des-b** [comment]
I observed the same here...

Seems like the line `OSError: [Errno 97] Address family not supported by protocol` was already present for a few versions now. (maybe since 3.0.0?) The  new logging configuration in 3.2.2 just adds the traceback to it.

I guess the origin seems to be this line of the service file (delivered by Arch sources):
[radicale.service](https://gitlab.archlinux.org/archlinux/packaging/packages/radicale/-/blob/main/radicale.service#L28)

When removing `AF_UNIX` from `RestrictAddressFamilies` the error message goes away.

**Comment by pbiering** [comment]
> When removing `AF_UNIX` from `RestrictAddressFamilies` the error message goes away.

This makes sense as 3.x has introduced logging to systemd journal socket, which is a AF_UNIX socket to connect to.

=> it's not a bug, it's a too restrict configured systemd unit file of the used distro.
