### ISSUE TITLE
Allow overriding filesystem_folder as commandline option

### ISSUE THREAD

**Issue by jonassmedegaard** [Kozea/Radicale#154]
In some environments (like the Debian packaging, where I am involved) it is desirable for identical setup to be usable both per-user and as a system-wide daemon.

When used as a single (desktop) user, it makes best sense for the data to be stored according to XDG standards (see issue #153 ), whereas a system-wide daemon preferrably would not store in a "hidden" dot-dir location.

Arguably, if XDG support was implemented, daemon init script could then override XDG_DATA_HOME but that feels counterintuitive. The ideal is, I believe, to allowoverriding settings (filesystem_folder in particular, but I imagine there are config parsers making it just as simple to allow overriding any config option) as commandline arguments when starting the daemon.

**Comment by liZe** [comment]
We've added CLI options for all the config values (and keep backward compatibility), I hope that you'll love that :wink:!
