### ISSUE TITLE
I keep getting - The server responded with “504” or "500" on my Mac

### ISSUE THREAD

**Issue by eleaner** [Kozea/Radicale#1560]
Hi
I keep getting weird errors on my radicale
the entries either do not get recorded to radicale or duplicated
kind of feels like the updates are not propagated properly
What I might be doing wrong?
Where I should look to resolve it?

**Comment by pbiering** [comment]
- Error 504 is "gateway timeout"
- Error 500 is a generic server or reverse proxy error

=> please check content of logs of the reverse proxy and the _radicale_ server itself, there should be something logged related to the errors reported to  the client.

_radicale_ has also some debug options, the upload is a PUT request, so search for this.

**Comment by eleaner** [comment]
Thank you!!!
After looking into logs I understood that the problem is caused by versioning with git. 
I understand that the git commands are effectively part of update and they were failing causing update failures.
all fixed now!
