### ISSUE TITLE
`[ERROR] An exception occurred during GET request on '/.web/': string indices must be integers, not 'str'` when using LDAP

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#1567]
### Discussed in https://github.com/Kozea/Radicale/discussions/1566

<div type='discussions-op-text'>

<sup>Originally posted by **poperigby** September 14, 2024</sup>
I'm running Radicale from this commit da844f48e6809d7d93e6ffef30d9051be00b74b5, and I have the following configuration file:

```ini
[auth]
type = ldap
ldap_uri = ldap://localhost:3890
ldap_base = dc=haddock,dc=cc
ldap_reader_dn = uid=radicale,ou=people,dc=haddock,dc=cc
ldap_secret = REDACTED
ldap_filter = (objectClass=person)
```

When I attempt to access Radicale at https://dav.haddock.cc/radicale/, I get the following error message in the Radicale log:

```console
[INFO] GET request for '/' received from 127.0.0.1 (forwarded for '192.168.1.1') using 'Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0'
[ERROR] An exception occurred during GET request on '/': string indices must be integers, not 'str'
```

I'm greeted with this message on the webpage:

```console
A server error occurred.  Please contact the administrator.
```</div>

**Comment by pbiering** [comment]
@petervarkoly : can you investigate? The built-in webserver serving javascript should not have any authentication applied.

**Comment by petervarkoly** [comment]
I'll take care.

Dipl. Ing. Péter Varkoly
EDV/IT Beratung
+49-15257491205
i.A. Cranix-Solutions GmbH
Steuernummer: 238/283/00067
Ust-ID: DE257896578
________________________________
Von: Peter Bieringer ***@***.***>
Gesendet: Sonntag, 15. September 2024 10:14
An: Kozea/Radicale ***@***.***>
Cc: Peter Varkoly ***@***.***>; Mention ***@***.***>
Betreff: Re: [Kozea/Radicale] `[ERROR] An exception occurred during GET request on '/.web/': string indices must be integers, not 'str'` when using LDAP (Issue #1567)


@petervarkoly<https://github.com/petervarkoly> : can you investigate? The built-in webserver serving javascript should not have any authentication applied.

**Comment by petervarkoly** [comment]
Fixed in https://github.com/Kozea/Radicale/pull/1570
