### ISSUE TITLE
Add TLS support for LDAP plugin

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#1578]
LDAP implementation introduced with https://github.com/Kozea/Radicale/pull/1218 misses TLS support which results in that user or bind-DN secret will be transferred in cleartext over network

**Comment by pbiering** [comment]
@petervarkoly please implement before release of 3.3.0

**Comment by petervarkoly** [comment]
Done https://github.com/Kozea/Radicale/pull/1579

**Comment by pbiering** [comment]
Thank you!
