### ISSUE TITLE
Using urls for webcal subscriptions containing an "&" (ampersand) seems to require using HTML entities instead

### ISSUE THREAD

**Issue by lindenstruth** [Kozea/Radicale#1582]
It seems that adding a webcal url containing an ampersand ("&") character such as `https://example.net/path?parm1=value1&parm2=value2` doesn't seem to be working right away. Nothing happens when pressing the "Create" button. 

When being replaced with the respective HTML entity `&amp;` however it does work perfectly, and the Apple Calendar app shows the correct url for the subscription.

When editing such a collection it shows the proper url, but again shows the same behavior and thus requires replacing the `&` with `&amp;` for saving the changes.

Vrsion 2.3.2 on Ubuntu 22.04 (arm64)

**Comment by pbiering** [comment]
I assume you mean version 3.2.2?

@MatthewHana can this be an encoding issue?

**Comment by lindenstruth** [comment]
Yes you're right, of course it's Version 3.2.2

**Comment by pbiering** [comment]
@MatthewHana - issue replicated, log shows:

```
[2024-10-08 07:55:30 +0200] [1218/Thread-21] [DEBUG] Request content (Invalid XML):
<?xml version="1.0" encoding="UTF-8" ?><mkcol xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CR="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/" xmlns:I="http://apple.com/ns/ical/" xmlns:INF="http://inf-it.com/ns/ab/"><set><prop><resourcetype><collection /><CS:subscribed /></resourcetype><displayname>webcal2</displayname><I:calendar-color>#5d3100ff</I:calendar-color><C:calendar-description>webcal2</C:calendar-description><CS:source>https://example.net/path?parm1=value1&parm2=value2</CS:source></prop></set></mkcol>
[2024-10-08 07:55:30 +0200] [1218/Thread-21] [WARNING] Bad MKCOL request on '/testmd5/webcal2/': Failed to parse XML: not well-formed (invalid token): line 1, column 516
[2024-10-08 07:55:30 +0200] [1218/Thread-21] [DEBUG] Response content: suppressed by config/option [logging] response_content_on_debug
[2024-10-08 07:55:30 +0200] [1218/Thread-21] [INFO] MKCOL response status for '/testmd5//webcal2/' in 0.030 seconds: 400 Bad Request
```

Beside `&` needs to be encoded, the WebUI should also catch the `400 Bad Request`
