### ISSUE TITLE
Spurious backslash in GEO property lines

### ISSUE THREAD

**Issue by l0b0** [Kozea/Radicale#1587]
[The vCard 3.0 `GEO` type](https://datatracker.ietf.org/doc/html/rfc2426#section-3.4.2) example shows a line like `GEO:37.386013;-122.082932`, but it seems the `;`s are all prefixed by backslash when exporting from Radicale, becoming `GEO:37.386013\;-122.082932`. This causes [validation](https://gitlab.com/engmark/vcard/) to fail.

Workaround: `sed --in-place --expression='s/\(GEO:.*\)\\;/\1;/' addresses.vcf`

**Comment by pbiering** [comment]
Strange, also Thunderbird here in use? Don't believe "vobject" is applying here tweaks.

**Comment by l0b0** [comment]
Unlike the other issue, this one *does* seem to be related to Radicale. I've tried to reproduce with the following trivial vCard:

```vcard
BEGIN:VCARD
VERSION:3.0
FN:Full Name
N:Family Name;Given Name;Additional,Names;First Honorific Prefix,Second Hon
 orific Prefix;First Honorific Suffix,Secord Honorific Suffix
GEO:37.386013;-122.082932
END:VCARD
```

If I import this into a *local* Thunderbird address book, and export that to vCard, the only difference is the `UID` field added by Thunderbird:

```vcard
BEGIN:VCARD
VERSION:3.0
FN:Full Name
N:Family Name;Given Name;Additional,Names;First Honorific Prefix,Second Hon
 orific Prefix;First Honorific Suffix,Secord Honorific Suffix
GEO:37.386013;-122.082932
UID:b7f6f405-955d-4ed1-8934-911878ea314e
END:VCARD
```

If I instead import into the address book _backed by Radicale_ and export that, the file has a broken field, but _different_ from the original bug I reported - the `GEO` field is missing the second half:

```vcard
BEGIN:VCARD
VERSION:3.0
UID:f9013fbf-a0a2-42ee-bb31-a513ec083257
FN:Full Name
GEO:37.386013
N:Family Name;Given Name;Additional,Names;First Honorific Prefix,Second Hon
 orific Prefix;First Honorific Suffix,Secord Honorific Suffix
END:VCARD
```

Software:

- Thunderbird 128.2.3esr (64-bit)
- Radicale 3.2.3

**Comment by pbiering** [comment]
which version of _vobject_ is in use?

**Comment by pbiering** [comment]
Reproduced with _vobject_ 0.9.6.1 by running raw PUT request and check content of created file

vcf used on PUT

```
BEGIN:VCARD
VERSION:3.0
UID:b7f6f405-955d-4ed1-8934-911878ea314e
FN:Full Name
N:Family Name;Given Name;Additional,Names;First Honorific Prefix,Second Hon
 orific Prefix;First Honorific Suffix,Secord Honorific Suffix
GEO:37.386013;-122.082932
END:VCARD
```

File in storage 

```
BEGIN:VCARD
VERSION:3.0
UID:b7f6f405-955d-4ed1-8934-911878ea314e
FN:Full Name
GEO:37.386013\;-122.082932
N:Family Name;Given Name;Additional,Names;First Honorific Prefix,Second Hon
 orific Prefix;First Honorific Suffix,Secord Honorific Suffix
END:VCARD
```

-> `\`  added before the `;` but only on GEO property

**Comment by pbiering** [comment]
Reproduced with _vobject_ 0.9.8, please file a bug to https://github.com/py-vobject/vobject
