### ISSUE TITLE
Problem with PUT method

### ISSUE THREAD

**Issue by Desiderius77** [Kozea/Radicale#162]
Hi all,

I try to put ICS files to my Radicale server  using the HTTP PUT method.
( I have tried with the stable 0;8 version and with the beta version cloned from this site)

As a client I use curl to send the HTTP request to Radicale : 

curl -T calendar.ics http://didier@localhost:5232/

where "didier" is the user who has read/write permissions to the Radicale collections.

The Radicale server receives the PUT request but crashes :

phoenix-didier(29)% python radicale.py -D
Logging configuration file '/etc/radicale/logging' not found, using stdout.
Starting Radicale
Authentication type is None
Base URL prefix: /
Listening to localhost port 5232
Radicale server ready
PUT request at /didier/calendar.ics received
Request headers:
{'CONTENT_LENGTH': '482',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '_/_',
 'HTTP_AUTHORIZATION': 'Basic ZGlkaWVyOg==',
 'HTTP_EXPECT': '100-continue',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_USER_AGENT': 'curl/7.31.0',
 'PATH_INFO': '/didier/calendar.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': 'localhost',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.5',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f0f5a2ea1e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0xae5c80>,
 'wsgi.input': <socket._fileobject object at 0xbb75d0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
Sanitized path: /didier/calendar.ics
Request content:
BEGIN:VCALENDAR
VERSION:1.0
BEGIN:VEVENT
URL:https://www.eventbrite.fr/e/billets-journees-informatique-et-moocs-de-la-sif-11429837953
DTSTART:20140623T073000Z
DTEND:20140624T143000Z
SUMMARY:Journées Informatique et MOOCs de la SIF
DESCRIPTION:For details, click here: https://www.eventbrite.fr/e/billets-journees-informatique-et-moocs-de-la-sif-11429837953
LOCATION:Conservatoire national des arts et métiers - 292 Rue Saint-Martin - 75003 Paris - France
END:VEVENT
END:VCALENDAR

didier has read access to collection didier/
didier has write access to collection didier/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/didier/Radicale/radicale/**init**.py", line 303, in **call**
    user)
  File "/home/didier/Radicale/radicale/**init**.py", line 556, in put
    xmlutils.put(environ["PATH_INFO"], content, collection)
  File "/home/didier/Radicale/radicale/xmlutils.py", line 479, in put
    collection.append(name, ical_request)
  File "/home/didier/Radicale/radicale/ical.py", line 370, in append
    self.write(items=items)
  File "/home/didier/Radicale/radicale/ical.py", line 394, in write
    self.save(text)
  File "/home/didier/Radicale/radicale/storage/filesystem.py", line 81, in save
    with open(self._path, "w") as fd:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/didier/Radicale/radicale/storage/filesystem.py", line 51, in open
    with codecs.open(abs_path, mode, config.get("encoding", "stock")) as fd:
  File "/usr/lib64/python2.7/codecs.py", line 881, in open
    file = **builtin**.open(filename, mode, buffering)
IOError: [Errno 21] Is a directory: '/home/didier/.config/radicale/collections/didier'

**Comment by Lekensteyn** [comment]
I tried to put an exported Google Calendar into Radicale:
```sh
curl -T basic.ics https://example.com/calendar.ics/basic.ics
```

This is accepted by Radicale, but subsequently clients will only find one event even though all other events are listed in the filesystem storage. It turns out that the `X-RADICALE-NAME` field is set to `basic.ics` for all events in that collection instead of being based on `UID` (or some other unique value). When I copy the file to the storage folder directly, it seems to work. Intentional or bug?

**Comment by untitaker** [comment]
It is a bug that Radicale accepts this kind of request. You should only be able to upload a ics file with exactly one event.
