### ISSUE TITLE
Linux (Debian 12) Address family for hostname not supported on Reboot

### ISSUE THREAD

**Issue by ganakee** [Kozea/Radicale#1620]
**Report Date: 2024-11-07**

### Problem Summary
On reboot, `systemctl `radicale 3  service fails to start with critical error:
```
journalctl --unit radicale.service
...
Nov 06 09:36:01 openmediavault env[1683]: [2024-11-06 09:36:01 -0500] [1683] [CRITICAL] An exception occurred during server startup: Failed to start server '[192.168.2.10]:8888': [Errno -9] Address family for hostname not supported
```

### Other Information
Debian 12 with all updates

Radicale installed (reinstalled) using 
```
sudo apt install python3-radicale
 sudo systemctl daemon-reload
 sudo systemctl restart radicale.service
 journalctl --unit radicale.service
```

Radicale worked fine after the Debian 11 to Debian 12 upgrade. Several reboots worked fine. Suddenly, after a reboot on 2024-11-06 after an `apt update`, the reboot problem started. There are several attempts at restarting according to journalctl.

```
journalctl --unit radicale.service
-- Boot 634...a93ba7371...97 --
Nov 06 09:36:00 openmediavault env[1610]: [2024-11-06 09:36:00 -0500] [1610] [CRITICAL] An exception occurred during server startup: Failed to start server '[192.168.2.10]:8888': [Errno -9] Address family for hostname not supported
Nov 06 09:36:00 openmediavault env[1674]: [2024-11-06 09:36:00 -0500] [1674] [CRITICAL] An exception occurred during server startup: Failed to start server '[192.168.2.10]:8888': [Errno -9] Address family for hostname not supported
Nov 06 09:36:00 openmediavault env[1681]: [2024-11-06 09:36:00 -0500] [1681] [CRITICAL] An exception occurred during server startup: Failed to start server '[192.168.2.10]:8888': [Errno -9] Address family for hostname not supported
Nov 06 09:36:01 openmediavault env[1682]: [2024-11-06 09:36:01 -0500] [1682] [CRITICAL] An exception occurred during server startup: Failed to start server '[192.168.2.10]:8888': [Errno -9] Address family for hostname not supported
Nov 06 09:36:01 openmediavault env[1683]: [2024-11-06 09:36:01 -0500] [1683] [CRITICAL] An exception occurred during server startup: Failed to start server '[192.168.2.10]:8888': [Errno -9] Address family for hostname not supported
```

I then tried a manual restart of `radicale.service`.
```
sudo systemctl restart radicale.service
 journalctl --unit radicale.service
```
The manual restart seems to be OK.

**Comment by pbiering** [comment]
Looks like a systemd dependency issue in this particular case, try add dependency to "network - online"

**Comment by pbiering** [comment]
I can't currently lookup correct syntax, but the require statement should be adjusted to wait until network is online in your case and the specific BIND address available in an interface

**Comment by pbiering** [comment]
Here is the config, which waits with start of _radicale_ until network interfaces are up:

```
[Unit]
Wants=network-online.target
After=network-online.target
```

Example in Wiki extended https://github.com/Kozea/Radicale/wiki/Simple-installation#set-up-service-on-server-to-allow-radicale-to-run-in-background-all-the-time

**Comment by ganakee** [comment]
Thank you @pbiering. I tested and confirm this resolves my issue.

I had done some research into the systemd modules but did not find this specific command.

If this helps others, follow the steps in general in [ https://github.com/Kozea/Radicale/wiki/Simple-installation#set-up-service-on-server-to-allow-radicale-to-run-in-background-all-the-time]( https://github.com/Kozea/Radicale/wiki/Simple-installation#set-up-service-on-server-to-allow-radicale-to-run-in-background-all-the-time) as @pbiering notes.

### More Detailed Steps (Assuming Radicale Already Setup for systemd)

1.  Open `sudo nano /etc/systemd/system/radicale.service`
2. Under `[Unit]` add: 
```
#After=network.target
#Requires=network.target
Wants=network-online.target
After=network-online.target
```
3. CTRL+X in nano and approve save.
4. Execute `sudo systemctl daemon-reload` . This is important to update systemd.
5. In my case, I rebooted the system.
6. Then I checked `sudo systemctl status radicale.service` If successful, I get:
```
sudo systemctl status radicale.service
● radicale.service - A simple CalDAV (calendar) and CardDAV (contact) server
     Loaded: loaded (/etc/systemd/system/radicale.service; enabled; preset: ena>
     Active: active (running) since Tue 2024-11-12 10:43:51 EST; 6min ago
   Main PID: 1681 (python3)
      Tasks: 1 (limit: 19030)
     Memory: 25.2M
        CPU: 356ms
     CGroup: /system.slice/radicale.service
             └─1681 python3 -m radicale

Nov 12 10:43:51 myhost systemd[1]: Started radicale.service - A simpl
```

7. You might also check `journalctl --unit radicale.service` for errors.
