### ISSUE TITLE
Web interface doesn't work on 3.3.0

### ISSUE THREAD

**Issue by Josh65-2201** [Kozea/Radicale#1623]
## Description
Entering the ip:port from the config.txt it will redirect with a `ip:port/.web` and show `The requested resource could not be found.` I have tried in Microsoft Edge and Firefox. It work when I was using 3.1.9.

## Logs
None shown in console

## Versions
Python: 3.11
Windows: build 26100.2033
Radicale: 3.3.0

**Comment by Josh65-2201** [comment]
I ran it with `"C:\Program Files\Python311\python.exe" -m radicale --logging-level info --config=[file path]` terminal show it logging but doesn't show anything when I go to the IP into either Edge or Firefox. I have make sure that https only mode and DNS over https are off in Firefox.

**Comment by pbiering** [comment]
Can you confirm that after start the last logging lines you see are similar to the following ones:

```
[2024-11-13 20:44:09 +0100] [1355] [INFO] Listening on '0.0.0.0:5232'
[2024-11-13 20:44:09 +0100] [1355] [INFO] Listening on '[::]:5232'
[2024-11-13 20:44:09 +0100] [1355] [INFO] Radicale server ready
```

And then you start request to ` <ip>:<port>` and nothing is shown further in log? If so, shutdown the server and retry....potentially you connect to a different server?

**Comment by Josh65-2201** [comment]
Opening task manager there where multiple instances open. I ended them and started a new one and it working, thank you.
