### ISSUE TITLE
python-dateutil seems to be unused

### ISSUE THREAD

**Issue by lahwaacz** [Kozea/Radicale#1626]
Searching for `dateutil` in this repository yields only three matches:

https://github.com/search?q=repo%3AKozea%2FRadicale%20dateutil&type=code

One in `pyproject.toml`, another one in `setup.py.legacy`, and the last in `radicale/storage/__init__.py` where it is only used as part of the `CACHE_VERSION` bytestring.

**Comment by pbiering** [comment]
Thank you for reporting, looks like a legacy reference, nowadays all is handled by _vobject_
