### ISSUE TITLE
Fail after editing a recurring event (`Overwritten recurrence with RRULESET`)

### ISSUE THREAD

**Issue by Massedil** [Kozea/Radicale#1635]
Hello, 

I have a sync problem with one event.

I have used Etar to update a recurring event and change one specific day title from "Escalade" to "Escalade avec Romain".

On the server, the event before change is : 

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:DAVx5/4.4.0.1-ose ical4j/3.2.18
BEGIN:VTIMEZONE
TZID:Europe/Paris
BEGIN:STANDARD
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:9fb6578a-07a6-4c61-8406-69229713d40e
DTSTART;TZID=Europe/Paris:20240606T193000
DTEND;TZID=Europe/Paris:20240606T203000
CLASS:PUBLIC
DTSTAMP:20240622T134646Z
EXDATE;TZID=Europe/Paris:20240704T193000
RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=TH
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:Escalade
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Escalade
TRIGGER:-P1D
END:VALARM
END:VEVENT
END:VCALENDAR
```

The changes sent by DAVx5 (tabs are added by me for readability) :

```
BEGIN:VCALENDAR
	VERSION:2.0
	PRODID:DAVx5/4.4.3.2-ose ical4j/3.2.19
	BEGIN:VEVENT
		DTSTAMP:20241125T195941Z
		UID:9fb6578a-07a6-4c61-8406-69229713d40e
		SEQUENCE:3
		SUMMARY:Escalade
		DTSTART;TZID=Europe/Paris:20240606T193000
		DTEND;TZID=Europe/Paris:20240606T203000
		RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=TH
		EXDATE;TZID=Europe/Paris:20240704T193000
		CLASS:PUBLIC
		STATUS:CONFIRMED
		BEGIN:VALARM
			TRIGGER:-P1D
			ACTION:DISPLAY
			DESCRIPTION:Escalade
		END:VALARM
	END:VEVENT
	BEGIN:VEVENT
		DTSTAMP:20241125T195941Z
		UID:9fb6578a-07a6-4c61-8406-69229713d40e
		RECURRENCE-ID;TZID=Europe/Paris:20241128T193000
		SEQUENCE:1
		SUMMARY:Escalade avec Romain
		DTSTART;TZID=Europe/Paris:20241128T193000
		DTEND;TZID=Europe/Paris:20241128T203000
		EXDATE;TZID=Europe/Paris:20240704T193000
		CLASS:PUBLIC
		STATUS:CONFIRMED
		BEGIN:VALARM
			TRIGGER:-P1D
			ACTION:DISPLAY
			DESCRIPTION:Escalade avec Romain
		END:VALARM
	END:VEVENT
	BEGIN:VTIMEZONE
		TZID:Europe/Paris
		BEGIN:STANDARD
			TZNAME:CET
			TZOFFSETFROM:+0200
			TZOFFSETTO:+0100
			DTSTART:19961027T030000
			RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
		END:STANDARD
		BEGIN:DAYLIGHT
			TZNAME:CEST
			TZOFFSETFROM:+0100
			TZOFFSETTO:+0200
			DTSTART:19810329T020000
			RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
		END:DAYLIGHT
	END:VTIMEZONE
END:VCALENDAR
```

Radicale answer with a `400 Bad Request` HTTP reply. 

In Radicale's logs, I found : 

```
[WARNING] Bad PUT request on 'XXXXXXXXXX.ics': Overwritten recurrence with RRULESET
```

- What is the problem ? 
- Who is responsible of the problem ? Etar, Radicale or DAVx5 ? 
- Can Radicale handle this problem ? (Even if not responsible)

Versions : 
- Radicale : 3.0.6
- DAVx5 : 4.4.3.2-ose
- Etar : 1.0.48

**Comment by pbiering** [comment]
Radicale 3.0.6 was released 2020 and is no longer supported. Also there were a bunch of changes in this area since this time. Please check with 3.3.1 and vobject 0.9.8, in case reproducable, reopen the ticket.

**Comment by pbiering** [comment]
relates to https://github.com/Kozea/Radicale/issues/1264

**Comment by Massedil** [comment]
Thank you for your quick reply. 


- Can you confirm me the request is wrong ? (I saw you put the "not our bug" tag.

- Can you tell me who is responsible of the wrong request ? DAVx5 or Etar ?

Thanks in avance.

**Comment by rfc2822** [comment]
I suggest to ignore recurrences with unneeded recurrence set for better compatibility:

- It's not 100% clear that it's not allowed (and I have seem events event from Apple with RRULE in the exception).
- Rejecting a request with an error is more likely to cause problems for a user than silently ignore it, if it's not of use (an application of "be conservative in what you send, be liberal in what you accept").

**Comment by Massedil** [comment]
> Can you check that @Massedil?

Not easily. It is on a production Debian server. So I need to test and update everything before.

Can @pbiering or someone else with curl and my event details check it quickly ? Or write a test in Radicale code ?

**Comment by Massedil** [comment]
The error seems to be still here in code : 
https://github.com/Kozea/Radicale/blob/64acfe27f40ab6b99ba50a18615e94325714d2f3/radicale/item/filter.py#L277

**Comment by pbiering** [comment]
I will check in the next days

**Comment by pbiering** [comment]
I traced it down, the issue is caused by

```
EXDATE;TZID=Europe/Paris:20240704T193000
```

in block of  `SEQUENCE:1` which is related to the renamed single schedule and should not exist because no `RRULE` is defined.

Generally I cannot replicate the behavior with current DAVx (PRODID:DAVx5/4.4.3.2-ose ical4j/3.2.19) or Thunderbird by following steps:

- create daily schedule with repeat span of 5 days
- delete single occurence on the 3rd day
- rename single occurence on the 2nd day

Is this the only event you have with this issue?

**Comment by Massedil** [comment]
May be this can be interesting for you : 
https://github.com/bitfireAT/ical4android/discussions/189#discussioncomment-11451925

Can I help you more ?

**Comment by pbiering** [comment]
both ICS from above are valid according to validator, potentially simply ignoring the `EXDATE` in case no `RRULE` exists would be an option.

**Comment by pbiering** [comment]
Further analysis show that it looks like it's "dateutil" is creating an rrule object in case even only `EXDATE` appears:

{'_cache': None,
 '_cache_complete': False,
 '_exdate': [datetime.datetime(2024, 7, 4, 19, 30, tzinfo=<tzicalvtz 'Europe/Paris'>)],
 '_exrule': [],
 '_len': None,
 '_rdate': [],
 '_rrule': []}

will try to ignore such.
