### ISSUE TITLE
Sync Issue with Tasks (Docker on Synology DS920+)

### ISSUE THREAD

**Issue by ghost** [Kozea/Radicale#1638]
Good Morning,

## Setup Details:
- **Platform**: Synology DS920+
- **Radicale Deployment**: Running in Docker, accessed through Synology's reverse proxy.
- **Databases**:
  - Calendar: Includes calendar, journal, and tasks.
  - Contacts: Includes the address book.
- **Clients**:
  - iPhone (using CalDAV/CardDAV for Calendar, Contacts, and Reminders).
  - Thunderbird (for Calendar, Contacts, and Tasks).

## Current Behavior:
- Calendar events sync perfectly between Thunderbird and iPhone.
- Contacts sync seamlessly as well.
- Tasks (or iOS Reminders):
  - I can add tasks on either device, and they sync bidirectionally without issue.
  - **Problem**: When I mark a task as completed on either Thunderbird or iPhone, the status does not sync to the other device.

## Question:
Are there any specific configurations required in **Radicale**, **Thunderbird**, or **iOS** to ensure that task/reminder completion statuses sync properly? 

Here is my compose file in case it helps:

```yml
services:
 radicale:
  image: tomsquest/docker-radicale
  container_name: radicale
  ports:
   - 5232:5232
  init: true
  security_opt:
   - no-new-privileges:true
  cap_drop:
   - ALL
  cap_add:
   - SETUID
   - SETGID
   - CHOWN
   - KILL
  deploy:
   resources:
    limits:
     memory: 256M
     pids: 50
  healthcheck:
   test: curl -f http://127.0.0.1:5232 || exit 1
   interval: 30s
   retries: 3
  restart: unless-stopped
  volumes:
   - /volume2/docker/radicale:/data
  environment:
   - PUID=1026
   - PGID=100

**Comment by pbiering** [comment]
> Problem: When I mark a task as completed on either Thunderbird or iPhone, the status does not sync to the other device.

Can you please replay using

- create task in client -> a PUT request should be visible on server side (showing the filename)
- copy task ICS on server side for source to diff later (e.g. ICS.old)
- update task on client side -> another PUT request should be visible no server side
- copy updated task ICS on server side for destination to diff now (e.g. ICS.new)

Provide `diff -u ICS.old ICS.new`  (wipe privacy related data before) -> there should be a difference visible

**Comment by pbiering** [comment]
cal/carddav is pull-only with Radicale server, so update time on other clients strongly rely on their configured update frequency, ususally configurable, please check., do not decrease that much, minimum I would recommend is 10 min.
