### ISSUE TITLE
Either Documentation (Wiki) is outdated or this is an error with the RIGHTS file pertaining to permissions.

### ISSUE THREAD

**Issue by GuruSR** [Kozea/Radicale#1647]
Updated to the latest version, found I couldn't log in to the web interface (internal), used the Wiki's example [Authentication and Rights](https://radicale.org/v3.html#authentication-and-rights) of the RIGHTS file (said in caps for better visibility) and found I still couldn't log in.

The **permissions** for **[root]** state is **r**, but **r** does not let you sign in at all, 403 error happens.  Upon changing it to **R**, the login works as expected and the collections are available again and also can be used.

Can someone fill us all in on what is supposed to be correct?

**Comment by pbiering** [comment]
thank you for notification, this was indeed a bug, example files were fixed, doc forgotten.
