### ISSUE TITLE
Radicale cannot accept htpasswd that starts with semicolon

### ISSUE THREAD

**Issue by ryan-c-dev** [Kozea/Radicale#1661]
It took me some tweaking but as desperately trying to figure out why i kept getting 301 errors from NGINX for my site after proper ssl cert.

for some reason nginx seems to throw an error (could be related to parsing)

**You cannot have your password start with a semicolon or atleast two semicolons!!**

I ran *curl -u username:password http://127.0.0.1:5232* and got a strange error i now lost.

Sorry I couldn't be more helpful, but this is worth looking into!

**Comment by pbiering** [comment]
cannot replicate, how does /etc/radicale/users look like? Tested with

```
testsemicolon:;testsemicolon
testsemicolon2:;;testsemicolon
```

related curl requests passed directly or via nginx

```
# direct
curl -s --header 'Depth: 1' --request PROPFIND -u "testsemicolon:;testsemicolon" http://localhost:5232/testsemicolon
curl -s --header 'Depth: 1' --request PROPFIND -u "testsemicolon2:;;testsemicolon" http://localhost:5232/testsemicolon2
# via nginx
curl -s --header 'Depth: 1' --request PROPFIND -u "testsemicolon:;testsemicolon" http://localhost:80/radicale/testsemicolon
curl -s --header 'Depth: 1' --request PROPFIND -u "testsemicolon2:;;testsemicolon" http://localhost:80/radicale/testsemicolon2
```

can you confirm that username+password in curl request is quoted and that you do not a strange version of `;` in UTF format in the file?

If issue is still unsolvable, check for any UTF "accident" with

```
hexdump -C /etc/radicale/users
```

and provide debug log with request header enabled.

**Comment by ryan-c-dev** [comment]
Must be with reverse proxy in nginx as I said, curling on 80 or localhost
won't replicate the situation. I just changed my password to not begin with
two semicolons as a workaround for now and am enjoying radicale!
