### ISSUE TITLE
'NoneType' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by deveth0** [Kozea/Radicale#176]
Hi,

I currently try to synchonize my exchange calendar with radicale. If I export the calendar and upload it with curl into radicale, it works find.
If I use the "publish on webdav" function of outlook, the attached error is thrown.

It seems to be possible to have the text == None in ical.py in some cases. 

/var/log/apache2/radicale.error.log:215:[Sun Jun 22 13:53:37.613226 2014] [:error] [pid 32745] [remote 192.168.2.10:17079] mod_wsgi (pid=32745): Exception occurred processing WSGI script '/var/www/radicale.wsgi'.
/var/log/apache2/radicale.error.log:216:[Sun Jun 22 13:53:37.613462 2014] [:error] [pid 32745] [remote 192.168.2.10:17079] Traceback (most recent call last):
/var/log/apache2/radicale.error.log:217:[Sun Jun 22 13:53:37.613533 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]   File "/usr/lib/python2.7/dist-packages/radicale/**init**.py", line 300, in **call**
/var/log/apache2/radicale.error.log:218:[Sun Jun 22 13:53:37.613624 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]     user)
/var/log/apache2/radicale.error.log:219:[Sun Jun 22 13:53:37.613673 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]   File "/usr/lib/python2.7/dist-packages/radicale/**init**.py", line 548, in put
/var/log/apache2/radicale.error.log:220:[Sun Jun 22 13:53:37.613731 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]     xmlutils.put(environ["PATH_INFO"], content, collection)
/var/log/apache2/radicale.error.log:221:[Sun Jun 22 13:53:37.613778 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]   File "/usr/lib/python2.7/dist-packages/radicale/xmlutils.py", line 440, in put
/var/log/apache2/radicale.error.log:222:[Sun Jun 22 13:53:37.613836 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]     collection.append(name, ical_request)
/var/log/apache2/radicale.error.log:223:[Sun Jun 22 13:53:37.613882 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]   File "/usr/lib/python2.7/dist-packages/radicale/ical.py", line 352, in append
/var/log/apache2/radicale.error.log:224:[Sun Jun 22 13:53:37.614148 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]     items = self.items
/var/log/apache2/radicale.error.log:225:[Sun Jun 22 13:53:37.614213 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]   File "/usr/lib/python2.7/dist-packages/radicale/ical.py", line 311, in _parse
/var/log/apache2/radicale.error.log:226:[Sun Jun 22 13:53:37.614268 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]
/var/log/apache2/radicale.error.log:227:[Sun Jun 22 13:53:37.614310 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]   File "/usr/lib/python2.7/dist-packages/radicale/ical.py", line 59, in unfold
/var/log/apache2/radicale.error.log:228:[Sun Jun 22 13:53:37.614359 2014] [:error] [pid 32745] [remote 192.168.2.10:17079]     if text ==  None:
/var/log/apache2/radicale.error.log:229:[Sun Jun 22 13:53:37.614413 2014] [:error] [pid 32745] [remote 192.168.2.10:17079] AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by SR-G** [comment]
I have the same error when publishing an Outlook calendar through webdav from Outlook 2010 and 2013. It would be nice to have this working with radicale, so +1.

@liZe i can understand your position, but then you should probably remove the "Shares calendars through CalDAV, WebDAV and HTTP" from the homepage, as it is misleading.

**Comment by liZe** [comment]
The current master version of Radicale is not ready for production yet and introduces a lot of changes, including the way calendars are stored, making it incompatible with the current stable version. But I think that this problem is probably solved with this new version, as it's way more compatible with the *DAV and iCal specifications. Can anybody try with Outlook?
