### ISSUE TITLE
Missing documentation of database backends

### ISSUE THREAD

**Issue by chlarsen** [Kozea/Radicale#207]
Dear All,
Unless I am missing something seriously, I have been utterliy unsuccessful in getting ANY of the common database backends (PostgreSQL, my favourite; MySQL/MariaDB, SQLite3) going. The schema import worked, but Radicale did not like it at all.
As there is seemingly (?) zero documentation on the database implementation, this lack makes it very, very tough to use what I consider the only really scalable backend.
Given the terrific code of Radicale so far, please, do your best to fill this gap. A huge thank you!
Chris

**Comment by liZe** [comment]
As it's defined in #372, the storage modules have been removed from Radicale and will be available thanks to external "plugins". Would you be interested in developing a database plugin and/or maintaining it? You can add your comments in #391.
