### ISSUE TITLE
Authentication fails with radicale 0.9 / Evolution 3.4.4

### ISSUE THREAD

**Issue by nhuillard** [Kozea/Radicale#212]
From https://github.com/Kozea/Radicale/issues/204
Radicale 0.9 must be configured with [rights] type = None for Evolution 3.4.4 to work. I just upgraded from Radicale 0.8 to 0.9 with unchanged Evolution settings, Evolution is simply autenticated as "Anonymous" (even though it is still configured with a login/pass), leading to no access to cal/card.
I can provide Radicale debug logs if needed.

**Comment by liZe** [comment]
Please reopen if needed.
