### ISSUE TITLE
Radicale 0.9 hangs after 2 weeks

### ISSUE THREAD

**Issue by Thomas-1985** [Kozea/Radicale#217]
Hi

I just noticed that Radicale 0.9 hangs after running for abou 2 weeks. I have to

killall radicale
radicale

to restart the server, then everything runs fine again (Radicale on top of OpenSuse 13.1, installed via "pip").

netstat -a looks like:

Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        6      0 h2000253.stratose:https _:_                     LISTEN
tcp        0      0 h2000253.stratose:https business-178-015-:50007 SYN_RECV
tcp      274      0 h2000253.stratose:https ip-2-206-0-232.we:32390 CLOSE_WAIT
tcp      273      0 h2000253.stratose:https ip-2-206-2-218.we:52099 VERBUNDEN
tcp      274      0 h2000253.stratose:https ip-2-206-0-232.we:62603 CLOSE_WAIT
tcp        0      0 h2000253.stratose:https 1-163-64-:mctet-gateway VERBUNDEN

unless i restart radicale. There is nothing in the "debug" log i set up, the last access is logged normally:

**Comment by richlv** [comment]
i can currently reproduce this every single time i start up radicale. if anybody has an ideas regarding testing, let me know :)
