### ISSUE TITLE
Warn if `filesystem_folder` is not readable

### ISSUE THREAD

**Issue by paulepanter** [Kozea/Radicale#220]
With Radicale 0.9 from Debian Sid/unstable and running it with Python 3.4 (Python 3.4.2rc1+), during debugging one problem I started Radicale as `root`, which then also created `/var/lib/radicale/collections`, the default filesystem folder, with these permissions. After being done with that, starting Radicale using a init script, it did not work anymore, because the process now run with the permissions of user `radicale`, so it was unable to read or write to `/var/lib/radicale/collections/`. It’d be great if Radicale informs the user about such problems.

**Comment by liZe** [comment]
Duplicated by #447.
