### ISSUE TITLE
Allow authentication for many users for different calendars

### ISSUE THREAD

**Issue by mute02** [Kozea/Radicale#235]
if a client try to authenticate with more then one users for different calenders, the realm from radicale is not unic and the authentication not possible. In my solution i add the user to the realm and it works fine. 

```
     Solution for version 0.9:


--- /usr/lib/python2.7/dist-packages/radicale/__init__.py.ori
+++ /usr/lib/python2.7/dist-packages/radicale/__init__.py
@@ -318,6 +318,10 @@
                 "Basic realm=\"%s\"" % config.get("server", "realm")}
             answer = None

+            if  config.get("rights", "type") == "owner_only":
+                apath = path.split("/", 2)
+                headers = {"WWW-Authenticate":"Basic realm=\"%s for: %s\"" % (config.get("server", "realm"), apath[1])}
         # Set content length
         if answer:
             log.LOGGER.debug(
```

I dont know enough about the code for testing.

**Comment by liZe** [comment]
I'm not sure to understand the real need behind this pull request. What's your real test case?

**Comment by mute02** [comment]
Sorry for my late answer. In my test case an authentication (from one 
client) with two or more accounts for different calendars at the same 
sync was not possible. With the patch, radicale works fine - thank you!
Now i think it is a problem in Thunderbird/Lightning.

Test case:
Thunderbird 31.4.0 with  Lightning 3.3.3 / radicale  0.9-1 on wheezy 
with ispconfig
Config:
[auth]
type = courier
courier_socket = /var/run/courier/authdaemon/socket
[rights]
type = owner_only


Am 12.01.2015 um 19:27 schrieb Guillaume Ayoub:

**Comment by liZe** [comment]
OK, I remember this bug. Thunderbird thinks that "same realm" means "same authentication account". We need to check what's in the RFC about that.

By the way, we need a less specific solution that doesn't rely on a `config.get("rights", "type") == "owner_only"` condition.

**Comment by Unrud** [comment]
You can specify the user in the URL of the calendar like ``http://john@server.tld/john/calendar.ics`` or ``http://jane@server.tld/jane/calendar.ics``. It works in Thunderbird and web browsers.

**Comment by liZe** [comment]
Good to know :+1:. @mute02 would this solution fix your problem, instead of merging the patch?
