### ISSUE TITLE
Support Outlook 2010/2013

### ISSUE THREAD

**Issue by christophdb** [Kozea/Radicale#238]
Hi,

I would like to sync outlook 2010 or outlook 2013 with the help of cfos Outlook DAV against radicale version 0.9.

cfos provides a log. As far as I understand cfos tries to establish the connection but an error 500 is the result. Here is the log: 
https://dl.dropboxusercontent.com/u/473785/cfos.txt

In addition I made some screenshots of the configuration and charley proxy:
https://dl.dropboxusercontent.com/u/473785/1.PNG
https://dl.dropboxusercontent.com/u/473785/2.PNG
https://dl.dropboxusercontent.com/u/473785/3.PNG
https://dl.dropboxusercontent.com/u/473785/4.PNG

Can anybody help me to understand why the sync is not working?
Best regards
Christoph

**Comment by kwisatz** [comment]
I realize this is an old ticket, but going to answer anyway ;)

Not sure about your pfsense settings, but I have never been able to get the cfos plugin to work with a server using SSL. This has nothing to do with self-signed certificates, it just doesn't work with any kind of SSL from my experience.

**Comment by liZe** [comment]
@christophdb @kwisatz many changes occured in the current master branch, you should try it. Be careful to use a brand new installation of Radicale (and not to use the same path for the calendar storage), because the calendars are now stored in a different way.

**Comment by liZe** [comment]
Close for now, current master has been used with Windows phones and seems to work quite well.

**Comment by pbiering** [comment]
outlookcaldavsynchronizer from https://sourceforge.net/projects/outlookcaldavsynchronizer seems working well also
