### ISSUE TITLE
Add a configuration entry to disable collection creation on GET/PROPFIND requests

### ISSUE THREAD

**Issue by grinapo** [Kozea/Radicale#240]
Please see https://github.com/WhisperSystems/Flock/issues/42#issuecomment-56597273

"When executing a PROPFIND request on a non-existent WebDAV collection Radicale pretends that a WebDAV collection is actually present and returns a multi-status response with default properties (displayname set to uri, default color, etc). Creating a new calendar, updating the displayname property, and then deleting the calendar does seem to kinda delete the calendar, as in all of the properties that have been set are reset. However executing a PROPFINDafter the successful DELETE still returns the multi-status response of a default calendar."

**Comment by liZe** [comment]
The feature has been removed.
