### ISSUE TITLE
Do well-known URLs create collections?

### ISSUE THREAD

**Issue by untitaker** [Kozea/Radicale#248]
https://github.com/Kozea/Radicale/commit/b863e8390e06c9dc4d27b519fcec125edca89e3d seems to redirect well-known URLs to a collection path, where the collection autocreation of Radicale might kick in.

In the linked issue there seems to be some sort of consensus that this is the correct behavior, while I've never seen a client rely on that behavior, and e.g. http://sabre.io/dav/service-discovery/ recommends otherwise.

I propose redirecting to ``/%(user)/`` and also removing the introduced config values.

**Comment by deronnax** [comment]
I read many issues and collections auto-creation with GET is a recurring problem. I ran into too myself. If you agree, I will propose a pull request for disabling it by default, but letting the possibility of enabling it for the rare clients that do not support collections creation.
The current behavior is really harmful and dozen of new users fall into the trap.

Otherwise, I have no opinion of this issue. I bet the RFCs don't tell anything about it ?

**Comment by untitaker** [comment]
I'm sure the HTTP RFCs at least strongly recommend that GET requests have no side effects.

**Comment by deronnax** [comment]
The webdav RFC just say that GET for collections follows the same semantic that in HTTP, which is "must make absolutely no side effects" http://tools.ietf.org/html/rfc2518#section-8.4.
Hereby I strongly support the disbling of the current behaviour :)

**Comment by liZe** [comment]
That would be wonderful to remove this hack.

About the clients relying on that behavior, I know at least that Lightning and Evolution were not able to send MKCALENDAR/MKCOL requests the last time I've tried.

**Comment by untitaker** [comment]
Most servers implement this by giving the user a different option for creating collections. In Radicale's case, a CLI tool would be easy to implement?

**Comment by deronnax** [comment]
it seems very odd to me that such an advanced software like evolution doesn't support mkcol. I'll investigate this week-end. For Lightning, I have no idea and no idea where to ask.

**Comment by deronnax** [comment]
#257

**Comment by hobarrera** [comment]
@deronnax: Lightning does not. It doesn't even have a UI for creating calendars, only for adding remote calendars, in which case they're assumed to exist.
Lightning relies heavily on this hack (though I still support this hack being off by default).

**Comment by liZe** [comment]
The feature creating collections on GET requests has been removed.
