### ISSUE TITLE
Thunderbird / SOGO Connector creates empty calendar instead of addressbook

### ISSUE THREAD

**Issue by yuv** [Kozea/Radicale#252]
First of all, THANK YOU for Radicale! I have a strange behaviour to report.

About a year ago I set up "D8" Radicale 0.8 running as user radicale in daemon mode on a Debian 7 server. This weekend I set up "U9" a new Ubuntu 14.04LTS server running Radicale 0.9 as user radicale in daemon mode.  In both setups I use IMAP authentication (Dovecot), the configuration files are practically the same and the storage folder has the same permissions. 

I use two clients: "TB", an Ubuntu 14.04LTS system with Thunderbird and SOGo Connector, which has been updated regularly between the setup of D8 and of U9; and "AD" an Android 4.0.4 phone with DAVdroid (from F-Droid), which is also a moving target and has been updated between the setup of D8 and U9.

After the initial syncinc of D8, TB and AD I forgot about the setup. I think it kind of worked in the background. Never really verified.

Today I tried to set up U9. When I try to create a new remote address book with TB on U9, SOGo connector says nothing happened and on the server I find a .props file with {"tag": "VCALENDAR"}.  Only if I change it manually to {"tag": "VADDRESSBOOK"} TB start syncinc properly.

AD seems to authorize OK but does not list any address book or calendar to connect to.  I use the URL https://example.com:5232/user/ and the username and password are properly recognized, however something goes wrong, and here are extracts from the log file:

```
2015-01-10 22:19:27,748 - INFO: PROPFIND request at /.well-known/carddav received
2015-01-10 22:19:27,750 - DEBUG: Request headers:
{'CONTENT_LENGTH': '88',
...
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.6',
 'wsgi.errors': <open file '/dev/null', mode 'w' at 0xb6e84498>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0xb6fd7c5c>,
 'wsgi.input': <socket._fileobject object at 0xb6e622ec>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-01-10 22:19:27,751 - DEBUG: Sanitized path: /.well-known/carddav
2015-01-10 22:19:27,752 - DEBUG: Request content:
<propfind xmlns="DAV:">
   <prop>
      <current-user-principal/>
   </prop>
</propfind>
2015-01-10 22:19:27,752 - DEBUG: Connecting to IMAP server localhost:143.
2015-01-10 22:19:27,776 - WARNING: IMAP server is local. Will allow transmitting unencrypted credentials.
2015-01-10 22:19:27,869 - DEBUG: Authenticated IMAP user USR via localhost.
2015-01-10 22:19:27,869 - DEBUG: USR has read access to collection .well-known/carddav/
2015-01-10 22:19:27,870 - DEBUG: USR has NO write access to collection .well-known/carddav/
2015-01-10 22:19:27,871 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:">
  <response>
    <href>/.well-known/carddav/</href>
    <propstat>
      <prop>
        <current-user-principal>
          <href>/USR/addressbook.vcf/</href>
        </current-user-principal>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
</multistatus>

2015-01-10 22:19:27,871 - DEBUG: Answer status: 207 Unknown
```

I have no clue why it is trying to access the .well-known sanitize path

To exclude a problem with Radicale, I tried setting up a new remote address book with TB on D8.  Same thing happens as described with U9 above.  I did not try to access it with AD.

So my current status is that with some fiddling I manage to get a TB addressbook on Radicale, but I do not find a way to connect AD to it and I have exausted my resources.  Any suggestion?

**Comment by yuv** [comment]
Release 0.10 fixed the address book access with AD (was a discovery problem). Tahnks!

The addressbook creation I worked around with `sudo chmod -R g+w` on the radicale/collections folder.  I run radicale as a daemon, starting it with `su --login radicale --command "/usr/local/bin/radicale"` in an init.d script.  All the files are stored in /home/radicale. Let me know if/how I can help debugging. I may have some free time in the last January week.

**Comment by liZe** [comment]
The feature creating collections on GET requests has been removed.
