### ISSUE TITLE
CardDAV collection needs to be manually created with Apple Contacts

### ISSUE THREAD

**Issue by 0-wiz-0** [Kozea/Radicale#256]
In the OS X section, please add a paragraph that describes how exactly to set up carddav on the server side when starting from scratch.

I _think_ you have to 
1. manually create contacts.vcf on the server
2. use https://hostname:5352/user/contacts.vcf/ as "Server" in the setup dialog

At least, when I tried without a pre-existing vcf file, or without adding the vcf file to the path, I got a carddav server configured which was read-only (OS  X 10.10.1)

**Comment by liZe** [comment]
Apple Contacts should work out of the box, I'll check that.

**Comment by davidterranova** [comment]
Hi, I see the same issue on my side, using both OS X Contacts App on 10.9 and 10.10

**Comment by halo** [comment]
I'm on Mac OS `10.10.4` and Contacts `9.0` with Radicale running on [Passenger](https://www.phusionpassenger.com) with SSL. Unfortunately I have not yet managed to create the initial address book in Radicale using an URL like `https://example.com/someuser/mybook.vcf/`.

The server gets created just fine, but I cannot drag-and-drop contacts onto it. It's just read-only. Is there a chance this could be related to the Radicale user configuration? At any rate, I remember having had this problem before and I could create the address book using this method.

I'll keep trying.

**Comment by halo** [comment]
Look at that! The `User Name` in the Contacts remote server settings has to match the username provided in the URL. Then it works!

For what it's worth: I have Basic Auth enabled in nginx and no authentication at all in Radicale.

**Comment by liZe** [comment]
This issue is probably fixed in the current master branch and with newer Apple clients.
