### ISSUE TITLE
Error when synchronizing calendar from Outlook to Radicale (upload item FAIL)

### ISSUE THREAD

**Issue by zepouletto** [Kozea/Radicale#261]
Hi,

SInce a few days some of the events (invitation to events) that I received on my outlook mail-client are not correctly synchronized with my radicale server.

Situation:
- On server side, I use radicale as WSGI plugged through apache2 (HTTPS).
- On client side, I use the OutlookDAV tool that synchronizes my local outlook calendar with my account on radicale server (as M$ doesn't speak WebDAV).

On client side I have an error "Upload Item (FAIL)" and an a log message (without helpfull information).

On server side I have:
`radicale.access.log`

```
C.C.C.C - user.name [10/Feb/2015:11:33:02 +0100] "PUT /user.name/calendar.ics/040000008200E00074C5B7101A82E00800000000E0DFE1EA7639D00100000000000000001000000064AB22D1E31CEB44910FC7ABA5F1B41B.ics HTTP/1.1" 500 1019 "-" "SurGATE Outlook DAV Client/v4.0 Thunderbird"
```

`radicale.error.log`

```
[Tue Feb 10 11:33:02 2015] [error] PUT request at /user.name/calendar.ics/040000008200E00074C5B7101A82E00800000000E0DFE1EA7639D00100000000000000001000000064AB22D1E31CEB44910FC7ABA5F1B41B.ics received
[Tue Feb 10 11:33:12 2015] [error] [client C.C.C.C] (70014)End of file found: mod_wsgi (pid=23779): Unable to get bucket brigade for request.
[Tue Feb 10 11:33:12 2015] [error] [client C.C.C.C] mod_wsgi (pid=23776): Exception occurred processing WSGI script '/var/www/radicale/radicale.wsgi'.
[Tue Feb 10 11:33:12 2015] [error] [client C.C.C.C] Traceback (most recent call last):
[Tue Feb 10 11:33:12 2015] [error] [client C.C.C.C]   File "/usr/local/lib/python2.7/dist-packages/radicale/__init__.py", line 268, in __call__
[Tue Feb 10 11:33:12 2015] [error] [client C.C.C.C]     environ["wsgi.input"].read(content_length), environ)
[Tue Feb 10 11:33:12 2015] [error] [client C.C.C.C] IOError: request data read error
```

`radicale.log`

```
2015-02-10 11:33:02,175 - INFO: PUT request at /user.name/calendar.ics/040000008200E00074C5B7101A82E00800000000E0DFE1EA7639D00100000000000000001000000064AB22D1E31CEB44910FC7ABA5F1B41B.ics received
```

Tell me if you need more information,
There seems to be something going wrong that makes radicale reject the request and make an error 500.

Best regards,
ZP

**Comment by untitaker** [comment]
ISTM that Outlook is sending a wrong Content-Length header, while Radicale tries to use that header (https://github.com/Kozea/Radicale/blob/master/radicale/__init__.py#L320).

**Comment by zepouletto** [comment]
Hi,

Thank you for the information, searching more we did notice that this happens only when there is  an attached file in the calendar event... Is this something recurent ?
We will try again with Apple Mail client to see if the problems comes from server or client.

Best regards,
ZP

**Comment by untitaker** [comment]
I think Radicale could just not use that header and instead read data until the last two bytes are newlines?

**Comment by liZe** [comment]
This issue is probably fixed in the current master branch.
