### ISSUE TITLE
Slashes in UIDs break Radicale

### ISSUE THREAD

**Issue by liZe** [Kozea/Radicale#262]

**Comment by eigengrau** [comment]
Is there any workaround? I’m running into this when trying to import my contacts from Owncloud, where all UIDs look like this:

```
https://redacted.com/remote.php/carddav/addressbooks/username/contacts/61E28264-528924BA-2562B9F3.vcf
```
Would it work if I regex replace URLs with just the numeric UUID part? Is that a valid UID?

**Comment by eigengrau** [comment]
Does radicale also evaluate `..` this way? This might be somewhat undesirable.

**Comment by liZe** [comment]
As far as I can remember, slashes are allowed in UIDs, that's just a bug in Radicale. Getting the UUID part of them should fix your problem.

`..` probably breaks things if there are slashes in the UID, but:
- escaping slashes should fix this bug too (as long as the UID is not *only* `..`), and
- that's not a security problem (but I'm no security expert)

**Comment by liZe** [comment]
Fixed, now that paths and UIDs are not related anymore.
