### ISSUE TITLE
Error in SQL syntax (1064)

### ISSUE THREAD

**Issue by leokun** [Kozea/Radicale#267]
Hello,
I'm trying to make worsk Radicale with MariaDB, I am using python3.3, and MySQL_python_1.2.4.
I have the same kind of issue as this one : https://github.com/Kozea/Radicale/issues/59#issuecomment-23962990

`(_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '%s) AS anon_1' at line 4")`

it seems that the `;` is missing at the end of the instruction. As this character is usually optional (depending of the database engine), is it possible to have it all the time ?

Thanks a lot .

Et Merci pour cet outil qui devrait m'être très utile :)

Regards,
Leo

**Comment by liZe** [comment]
The SQL storage backend is currently in bad shape and shouldn't be used. If you're interested in following the status of the SQL backend, you should follow #114 where the different issues and solutions are gathered.
