### ISSUE TITLE
CPU activity when idle

### ISSUE THREAD

**Issue by mjm4456** [Kozea/Radicale#270]
radicale has some CPU activity when in idle state (no clients connected).
(powertop shows about 23 Events/s and a few  o/oo of CPU load.
This is not really a big problem but it consumes a bit of battery when used on a notebook.

Matthias

**Comment by deronnax** [comment]
if you're running it by itself, it uses python stdlib [BaseHttpServer] (https://docs.python.org/2.7/library/basehttpserver.html), which is probably the culprit. Use a dedicated WSGI HTTP server like uwsgi or Gunicorn.
Here, serving ~5000 contacts to ~5000 contacts, load is 0 when idle.

**Comment by mjm4456** [comment]
according '/usr/lib/python2.7/site-packages/radicale/__init__.py' I guess radicale uses 'wsgiref.simple_server'.
If I start  'wsgiref.simple_server' standalone by:

from wsgiref.simple_server import make_server, demo_app
httpd = make_server('', 8000, demo_app)
httpd.serve_forever()

 the load is 0 when idle.

**Comment by untitaker** [comment]
>Use a dedicated WSGI HTTP server like uwsgi or Gunicorn.

@deronnax I suppose you're serving more than one request at a time? This can lead to data corruption if you're using the filesystem storage (and possibly multifilesystem too).

**Comment by deronnax** [comment]
many per seconds but in read only, no modifications are pushed to the
directory :)

**Comment by Unrud** [comment]
This should be resolved by #353

**Comment by liZe** [comment]
Closed by merging #353.
