### ISSUE TITLE
CORS support (Cross-Origin Resource Sharing)

### ISSUE THREAD

**Issue by thesourcerer8** [Kozea/Radicale#277]
I would like to use Radicale with infcloud, but infcloud requires CORS support, see
http://www.inf-it.com/infcloud/readme.txt -> 

 a.) Your server MUST return the following additional HTTP headers:
            Access-Control-Allow-Origin: *
            Access-Control-Allow-Methods: GET, POST, OPTIONS, PROPFIND, PROPPATCH, REPORT, PUT, MOVE, DELETE, LOCK, UNLOCK
            Access-Control-Allow-Headers: User-Agent, Authorization, Content-type, Depth, If-match, If-None-Match, Lock-Token, Timeout, Destination, Overwrite, X-client, X-Requested-With
            Access-Control-Expose-Headers: Etag
      b.) If Access-Control-Request-Method header is sent by your browser (preflight request defined by CORS) then your server MUST return these headers for OPTIONS request WITHOUT requiring authorization and MUST return 200 (or 2xx) HTTP code (Success).
    - Howto add these headers to my CardDAV/CalDAV server?
      Check your server documentation or contact your server developer and ask for CORS or custom HTTP headers support.

As far as I can see, Radicale currently does not support sending those headers. I would suggest to add a configuration option that easily enables all those headers at once, and optionally a configuration method to only allow specific origin servers.

**Comment by liZe** [comment]
You can add headers at the end of the configuration file, in the "headers" section.
http://radicale.org/user_documentation/#idmain-configuration-file

**Comment by glowinthedark** [comment]
@liZe: the link is broken! 🔗 💔

**Comment by liZe** [comment]
> You probably mean this, right? https://radicale.org/3.0.html#documentation/configuration/headers

I do!

**Comment by bchapuis** [comment]
You probably mean this, right? ;-)
https://radicale.org/v3.html#headers

**Comment by pbiering** [comment]
Since 3.5.0 no dedicated InfCloud installation is required, it can be bundled now
- https://github.com/Kozea/Radicale/releases/tag/v3.5.0
- https://github.com/Kozea/Radicale/wiki/Client-InfCloud
