### ISSUE TITLE
Use ldap3 for LDAP support

### ISSUE THREAD

**Issue by stevenroose** [Kozea/Radicale#278]
Currently, the [User Documentation](http://radicale.org/user_documentation/#idldap-authentication) states that python-ldap is used for LDAP support and thus it is only supported in Python 2.

However, a Python 3 LDAP library exists, [ldap3](https://pypi.python.org/pypi/ldap3).
Using this library instead of python-ldap would allow the usage of LDAP with Radical using Python 3.

**Comment by rthill** [comment]
Had the same problem as you and implemented a version for Python 3.x

See https://github.com/Kozea/Radicale/pull/325 for more information and to test ldap3.

**Comment by liZe** [comment]
Please see #325.

**Comment by marcoh00** [comment]
@rthill Now that the plugin interface seems to be documented a bit, I went ahead and made some small changes to your code from #325. It's a real authentication plugin now ;-)

I you are interested to help out or if you want to take ownership of it again (I am not too hesistant in taking care of it to be honest), just drop me a line!

https://github.com/marcoh00/radicale-auth-ldap
