### ISSUE TITLE
Using Radicale for Scheduling 

### ISSUE THREAD

**Issue by Jaikant** [Kozea/Radicale#283]
Hi, I want to use radicale for scheduling. user A should be able to query the free/busy time for a particular date for user B and then schedule a meeting. I have been poking around with radicale for over a week now, and it seems this functionality is not yet coded. 
If I need to code it, can someone give me some high level pointers so I can start.

Cheers,
J.

**Comment by hobarrera** [comment]
Looks like what you're needing is exactly what's mentioned on #34. Or at least depends on it.

**Comment by liZe** [comment]
@Jaikant Yes, you do!
