### ISSUE TITLE
Authenticated user as git committer

### ISSUE THREAD

**Issue by mmonaco** [Kozea/Radicale#285]
I thought it would be helpful to have the committer when using git to reflect the authenticated username. I'll have a crack at this at some point if someone doesn't beat me to it, but it wasn't immediately obvious what the best way to get the username from within the filesystem class.

Having the [git]/committer config option expand something like:

```
%u = user
%i = ip address
```

would be even cooler. Of course, it's not worth it if it adds too much complexity.

**Comment by hobarrera** [comment]
I'd rather have this be the commit summary (instead of author). Strictly speaking, radicale itself is doing the commit, but mostly because we have more flexibility in the summary (the IP would be out-of-place in the author line).

**Comment by mmonaco** [comment]
Well, since the 90% of the change would be making the info available in the filesystem storage backend, it shouldn't be a big deal to have both author and message as config options that expand various tokens such as %u.

That said, I disagree. Yes, radicale is doing the commit. But git commits have an author and a committer for a reason. Generally it's the author you're interested in -- the person responsible for the content of the change.

Either way, I see a few active issues concerning refactoring the storage code so it doesn't make sense to try anything until that all happens.

**Comment by Unrud** [comment]
git support was removed in Radicale 2.0.0. It was replaced by the ``hook`` config option, which also provides the user name. (See http://radicale.org/versioning/)
