### ISSUE TITLE
Moving an event from one calendar to another breaks login

### ISSUE THREAD

**Issue by ccurzio** [Kozea/Radicale#291]
It seems that when you have more than one calendar created on your Radicale server, moving an event from one calendar to another calendar causes some unexpected problems. Here's how to reproduce it quickly using Mac OS X Calendar:
1. Create a CardDAV account connected to a brand new Radicale Server. 
2. Create a new calendar using File > New Calendar > ServerName
3. Create a second calendar using File > New Calendar > ServerName
4. Create a new event. Any time, any date. 
5. Right-click the event, and attempt to move the event from one calendar to another under "Calendar"

Immediately after doing this, the login session is broken. Calendar will complain that it can't connect to the account, and the Radicale logs will start spraying 401 errors.

**Comment by liZe** [comment]
Thanks for the report.

As I don't have access to OSX Calendar, is it possible to have Radicale logs please?

**Comment by liZe** [comment]
No news is good news. We'll use #330 to follow Radicale's compatibility with MacOS Calendars.
