### ISSUE TITLE
Support the htpasswd md5 method

### ISSUE THREAD

**Issue by jgehrcke** [Kozea/Radicale#293]
In the docstring of Radicale's htpasswd module we read 

> Plain-text, crypt and sha1 are supported, but md5 is not (see ``htpasswd`` man page to understand why).

I have grasped through the man page, have read through http://httpd.apache.org/docs/2.4/programs/htpasswd.html and through http://stackoverflow.com/questions/4175707/adding-a-salt-to-htpasswd and still ask myself: why would the md5 (htpasswd's default method) not be supported? The advantage over the sha1 method clearly would be that a random salt is used. The advantage over the crypt method would be that it is "more secure" (longer salt, password not limited to 8 chars, larger number of rounds).

If the reason is that the named md5 method has no equivalent in Python's stdlib (as it is "a version  of MD5 modified for Apache") then I believe that this should not necessarily be a deal breaker. The method is documented and has been implemented by e.g. passlib, too. Documentation: https://pythonhosted.org/passlib/lib/passlib.hash.apr_md5_crypt.html
Implementation: https://code.google.com/p/passlib/source/browse/passlib/handlers/md5_crypt.py

In view of the existing Python implementation: What do you think -- does it make sense for Radicale to support htpasswd's md5 method?

Btw: passlib uses the BSD license.

**Comment by liZe** [comment]
Yes, it does, as long as other methods can still be used without passlib installed.

**Comment by jgehrcke** [comment]
Okay, I'll look into providing a patch.

**Comment by daks** [comment]
just my 2 cents: why still use MD5 method to hash passwords? MD5 is really old and subject to a lot of security problems.

**Comment by jgehrcke** [comment]
This is mainly about supporting the different methods that Apache's htpasswd program provides for storing credentials. See httpd.apache.org/docs/programs/htpasswd.html. Whoever deploys Radicale has to make a deliberate choice about which encryption scheme to use.

BCRYPT and APR1 MD5 are, in this order, currently the most secure password encryption schemes that htpasswd provides. APR1 MD5 is supported by all versions of htpasswd, whereas BCRYPT is only supported since versions 2.4.x.

The MD5 method we are talking about here is "a version of MD5 modified for Apache", also called "APR1". It actually uses a random salt and many computation rounds. That is, this is highly different from simple canonical MD5 hashing in the sense that rainbow table attacks are more difficult to perform, and brute-forcing requires a certain amount of computational power.

This APR1 MD5 method is 
* the default password encryption scheme of the htpasswd program.
* more secure than the other methods provided by htpasswd which are SHA/CRYPT/PLAIN.

These are the reasons why APR1 MD5 should be supported by Radicale.

Note that the "SHA" method implemented by htpasswd less secure than APR1 MD5, because it does not use salting or multiple computation rounds.

I am quite sure that APR1 MD5 can still be brute-forced with only medium effort. So it is not tremendously secure. That's why there also is the more secure BCRYPT scheme, which is supported by htpasswd from version 2.4 on. Therefore, this scheme should also be supported by Radicale and I'll look into considering this in my patch. It is important to note that htpasswd 2.4 is still not natively available on certain widely spread Linux distributions: e,g. CentOS 6 still provides htpasswd 2.2.x.

**Comment by jgehrcke** [comment]
You can actually try this out. http://hashcat.net/oclhashcat/ supports what they call "Apache MD5-APR".

**Comment by liZe** [comment]
Fixed by mergin #297.
