### ISSUE TITLE
storage: does it scale?

### ISSUE THREAD

**Issue by b6d** [Kozea/Radicale#296]
I'll try to decide between radicale and baikal for a personal caldav server. Looking at the source of the radicale storages, It looks at first glance like all items are read/written on any operation.

If I want to put five or ten years of appointments into radicale, will I notice a performance impact?

**Comment by untitaker** [comment]
Frankly, yes.

Radicale has lower constant overhead, but I think Baikal is a better choice in your case (since it is able to run off a database).

**Comment by b6d** [comment]
Thanks for the honest answer! It's a pity, I would have preferred a Python solution ... 

(I'll be watching the Radicale project in the hope that the new storage API mentioned in issue #130 gets defined and implemented someday ...)

Anyways, closing the issue, since my question is answered ...
