### ISSUE TITLE
Radicale logfile not being rotated

### ISSUE THREAD

**Issue by tmst** [Kozea/Radicale#299]
I'm running an instance of 0.7.1. When I was setting it up, it was the latest version I could get to run correctly on my opensuse 13.1 box.

So, I've played with logrotate and, not being sure how to configure it, decided to use the config file provided by @chris5560 in issue #266.

I just checked, and the logfile is now approaching 2MB and hasn't been rotated for 5 days.

The server has been running fine, as a daemon. There's nothing about radicale in the system log (configured for errors, IIRC) Maybe the logging syntax changed after 0.7.1? And something is silently failing?

I suppose I could try to get the latest radicale working on my system. Are there any other compelling reasons to upgrade it if even the latest still has the hanging problem (also in #266)?

**Comment by liZe** [comment]
I've tried to reproduce this bug, but the log rotation works for me with the config file from #266 and 0.7.1.

Upgrading is mainly useful for compatibility with clients and new features, but if 0.7.1 works with you there's no need to update.

**Comment by tmst** [comment]
On Wednesday 19 August 2015 06:08:14 AM Guillaume Ayoub wrote:
> I've tried to reproduce this bug, but the log rotation works for me with the
> config file from #266 and 0.7.1.
> 
> Upgrading is mainly useful for compatibility with clients and new features,
> but if 0.7.1 works with you there's no need to update.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Kozea/Radicale/issues/299#issuecomment-132584977

Wow. You tried this with an old version? Thanks!

I just noticed, today, that Radicale wasn't logging anything after I put the 
new logger in place. So I had to restore the old one for now until I can figure 
out what's happening.

My config file is attached. Does anything look wrong, besides my bewildered 
comments? I would like to comment out everything that is not essential, like 
the LDAP stuff.
# -*- mode: conf -*-
# vim:ft=cfg

# Config file for Radicale - A simple calendar server
#
# Place it into /etc/radicale/config (global) 
# or ~/.config/radicale/config (user)
#
# The current values are the default ones

# 3/7/14
#	changed acl:type from htpass to None
# 8/7/14
#	changed server:hosts from 127... to 0... to run on local machine
#	tried changing server:ssl to True
#		get "SSL Error" in Chrome when accessing https://0....
#	added server:realm
#	changed acl:type to htpasswd
#		unauthenticated access still permitted
#			hence the 'lol'?
#	added [auth] section
#	set auth:type to htpasswd
#		note: ambiguity w/ [acl:type]
#		still no auth required to access calendar(s)

[server]
# To start server: root$> startdav

# CalDAV server hostnames separated by a comma
# IPv4 syntax: address:port
# IPv6 syntax: [address]:port
# IPv6 adresses are configured to only allow IPv6 connections
#hosts = 127.0.0.1:5232	# modified to run on local network, rather than machine -TR
hosts = 0.0.0.0:5232
#hosts = baddomain:5232
#hosts = linux-i11s.site:5232	# no worky at all
#hosts = dodec.sytes.net:5232	# no worky at all
# Daemon flag
daemon = True
# File storing the PID in daemon mode
pid =
# SSL flag, enable HTTPS protocol
ssl = True
# SSL certificate path
certificate = /etc/radicale/radicale.crt
# SSL private key
key = /etc/radicale/radicale.key
# Reverse DNS to resolve client address in logs
dns_lookup = True
# Message displayed in the client when a password is needed
realm = Radicale - Password Required lol


[encoding]
# Encoding for responding requests
request = utf-8
# Encoding for storing local collections
stock = utf-8


[acl]
# Access method
# Value: None | htpasswd | LDAP | PAM | courier
type = htpasswd
# following added in frustration
# see http://pbraun.nethence.com/unix/www/caldav_radicale.html
#personal = True
#filename = /etc/radicale/users
#encryption = None

#[auth]
# I think not used until later version -TR
#type = htpasswd

[rights]
# Rights management method
# Value: None | owner_only | owner_write | from_file
type = owner_only

# Usernames used for public collections, separated by a comma
public_users = public
# Usernames used for private collections, separated by a comma
private_users = private

# Htpasswd filename
htpasswd_filename = /etc/radicale/users

# Htpasswd encryption method
# Value: plain | sha1 | crypt
# plain shouldn't be a problem as using SSL - TR
htpasswd_encryption = crypt
#htpasswd_encryption = sha1


# LDAP server URL, with protocol and port
ldap_url = ldap://localhost:389/
# LDAP base path
ldap_base = ou=users,dc=example,dc=com
# LDAP login attribute
ldap_attribute = uid
# LDAP filter string
# placed as X in a query of the form (&(...)X)
# example: (objectCategory=Person)(objectClass=User)(memberOf=cn=calenderusers,ou=users,dc=example,dc=org)
# leave empty if no additional filter is needed
ldap_filter = 
# LDAP dn for initial login, used if LDAP server does not allow anonymous searches
# Leave empty if searches are anonymous
ldap_binddn =
# LDAP password for initial login, used with ldap_binddn
ldap_password =
# LDAP scope of the search
ldap_scope = OneLevel

# PAM group user should be member of
pam_group_membership =

# Path to the Courier Authdaemon socket
courier_socket =


[storage]
# Storage backend
type = filesystem

# Folder for storing local collections, created if not present
filesystem_folder = /var/lib/radicale/


[logging]
# Logging configuration file
# If no config is given, simple information is printed on the standard output
# For more information about the syntax of the configuration file, see:
# http://docs.python.org/library/logging.config.html
config = /etc/radicale/logging
# Set the default logging level to debug
debug = False
# Store all environment variables (including those set in the shell)
full_environment = False

**Comment by tmst** [comment]
On Thursday 20 August 2015 11:30:26 PM you wrote:
> On Wednesday 19 August 2015 06:08:14 AM Guillaume Ayoub wrote:
> > I've tried to reproduce this bug, but the log rotation works for me with
> > the config file from #266 and 0.7.1.
> > 
> > Upgrading is mainly useful for compatibility with clients and new
> > features,
> > but if 0.7.1 works with you there's no need to update.
> > 
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/Kozea/Radicale/issues/299#issuecomment-132584977
> 
> Wow. You tried this with an old version? Thanks!
> 
> I just noticed, today, that Radicale wasn't logging anything after I put the
> new logger in place. So I had to restore the old one for now until I can
> figure out what's happening.
> 
> My config file is attached. Does anything look wrong, besides my bewildered
> comments? I would like to comment out everything that is not essential, like
> the LDAP stuff.


Also, do you think all the "user refused" messages in the logfile come from 
using the "crypt" password setting? For some reason it still works much of the 
time. I'm also doing preemptive credentials, as security isn't as important as 
privacy (the selling point for Radicale, IMO).

**Comment by tmst** [comment]
On Wednesday 19 August 2015 06:08:14 AM Guillaume Ayoub wrote:
> I've tried to reproduce this bug, but the log rotation works for me with the
> config file from #266 and 0.7.1.
> 
> Upgrading is mainly useful for compatibility with clients and new features,
> but if 0.7.1 works with you there's no need to update.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Kozea/Radicale/issues/299#issuecomment-132584977

Just a note that the following line in the logging file caused my server to not 
start up. An error is thrown about encoding must be a string, rather than an 
integer:
args = ('/var/log/radicale', 'a', 32768, 3)

I don't know how to properly format this tuple. So I took a guess and made it:
args = ('/var/log/radicale', 'a', 'utf-8', 32768)

It complained about 6 args, so I removed the '3'. Maybe it just needs the 
size?

I'm running 0.7.1.

**Comment by tmst** [comment]
Just a note that the following seems to work. At least it doesn't spit out 
error messages when debugging is turned on. The key for me was specifying the 
full path of the file handler:

# File handler (see 'args' below for file destination)
# class logging.handlers.RotatingFileHandler(
#	filename, mode='a', maxBytes=0, backupCount=0, encoding=None, delay=0)
class = logging.handlers.RotatingFileHandler
args = ('/var/log/radicale', 32768, 3)	# error 32768 unknown encoding
formatter = full

The documentation for the "args" tuple is located in the Python docs:
https://docs.python.org/2/library/logging.handlers.html#module-logging.handlers

**Comment by Unrud** [comment]
The documentation on this was improved.
