### ISSUE TITLE
Radicale does not support the current bcrypt format

### ISSUE THREAD

**Issue by MercSec** [Kozea/Radicale#301]
On OpenBSD and other Systems using a modern bcrypt:

htpasswd /tmp/bla test
Password:
Retype Password:
cat /tmp/bla
test:$2b$08$vqrOt5RwvVjcvf1b2rSrbe1l/TajgLvPu/1ahI525C10WR9lkwNYe | test:test

Reference: http://www.openwall.com/crypt/ 
"Version 1.3 adds support for the $2b$ prefix introduced in OpenBSD 5.5+, which behaves exactly the same as crypt_blowfish's $2y$. This way, full compatibility with OpenBSD's bcrypt is achieved at this new prefix."

Radicale wont work with bcrypt generated on such systems. 

Kind regards,
Sebastian Rother

**Comment by Unrud** [comment]
Seems to work now. [passlib](https://pypi.python.org/pypi/passlib) is used for verifying the password.
