### ISSUE TITLE
No addressbook in collection?

### ISSUE THREAD

**Issue by t-ghost** [Kozea/Radicale#303]
Hi all!
This might be a stupid question and an easy issue to resolve, but as I could not find any information on this by googling:
My radicale server (0.10) seems to work fine with calendars, but not so with contacts. In my collection file there is not even a trace of an addressbook and I can't find out how to create one... Is it meant to do that automatically when the user is set up?

Best,
Thomas

**Comment by liZe** [comment]
You have to use different URLs for events+todos and for contacts. Your client is probably able to create an addressbook if you set an URL ending by `.vcf` in its configuration. Documentation is available for many clients here: http://radicale.org/user_documentation/#idstarting-the-client.

**Comment by t-ghost** [comment]
Unfortunately, I already tried that. I am using KDEKontact and it works
fine for the ULR ...../Calendar.ics for the calendar (my browser also
returns the ics file if called), but it finds nothing on
....../AddressBook.vcf , also the browser says that there is no such file...

**Comment by liZe** [comment]
You can create your addressbook with a browser thanks to an URL **with a trailing slash** (something like `.../AddressBook.vcf/`). Note that an empty addressbook is an empty file, so don't worry if there's nothing in the vcf file you just created.

**Comment by t-ghost** [comment]
Thanks very much! I think that worked. Kontact is still finding nothing,
however. But I think that is due to the empty file.
Is there a way to populate it with a dummy entry to get started?

**Comment by liZe** [comment]
You can find some samples of vcf contacts on internet and put them in the vcf file stored by radicale.

**Comment by t-ghost** [comment]
Thanks for all your efforts! That should help me get my contacts sync
working.
