### ISSUE TITLE
Support for sync-collection REPORT

### ISSUE THREAD

**Issue by oupala** [Kozea/Radicale#306]
After discussing with the author of [CalDavZAP](https://www.inf-it.com/open-source/clients/caldavzap/), [CardDavMATE](https://www.inf-it.com/open-source/clients/carddavmate/) and [InfCloud](https://www.inf-it.com/open-source/clients/infcloud/), I think that Radicale lacks an important feature : support for sync-collection REPORT (with sync-tokens).

This is how InfCloud react when a server does not support the **sync-collection REPORT** feature :
- do
  - download a list of _ALL_ URLs+Etags for all objects **=> bandwidth consuming**
  - if there is an URL not already downloaded then this is a new object, then download it **=> cpu consuming**
  - if there is an URL which is already downloaded but the Etag is changed, this object was updated, then re-download it  **=> cpu consuming**
  - if there is an URL which is already downloaded but no more present on the server, this object was deleted, then delete it **=> cpu consuming**
- while(true);

This is how InfCloud react when a server **does** support the **sync-collection REPORT** feature (such as DAViCal) :
- download a list of _ALL_ URLs+Etags + get the sync-token **=> bandwidth consuming** but **only once**
- do
  - perform the synchronization request with the last sync-token **=> minimum bandwith usage**
  - download all _new_ objects returned by the request (if there is any)  **=> nearly zero cpu usage**
  - re-download all _changed_ objects returned by the request (if there is any) **=> nearly zero cpu usage**
  - delete all _deleted_ objects returned by the request (if there is any) **=> nearly zero cpu usage**
- while(true);

It could be a good idea to implement this feature.

**Comment by midemarc** [comment]
+1, I see it as a must-have feature !

**Comment by Unrud** [comment]
The response of a propfind request for all etags of a calendar collection with 1000 calendar objects is about 240kB. The response size scales pretty much linear with the number of calendar objects.
gzip reduces the size by a factor of about 10. Maybe the integrated server should support his.

I think that Radicale currently doesn't support ctags (change id for a whole calendar collection). This could further reduce bandwidth usage and is easy to implement.

For sync-token support the storage backends need to keep track of all calendar object's time of last change / time of deletion.

**Comment by liZe** [comment]
> For sync-token support the storage backends need to keep track of all calendar object's time of last change / time of deletion.

I've come to the same conclusion, and that's a bit hard to add. I change the milestone from 2.0 to later, I'd prefer to have more time to implement this.

**Comment by Unrud** [comment]
It's also possible to use the collection etag as sync-token. When the etag has changed, the server just tells the client that the sync-token is invalid (see RFC). The client falls back to a normal report request.

As long as the collections is not changed very often, this should save nearly as much bandwidth as a real sync-token implementation.

**Comment by pbiering** [comment]
It looks like this missing sync-token implementation (even a simple one) will break vcard sync with SoGo connector, I have here various vcard update pending in Thunderbird, but they are not pushed to server. See also https://sogo.nu/bugs/view.php?id=3896 (looks like the connector has no fallback in case the sync-token is not provided).

How difficult is it to implement the simple way Unrud suggested on 13 Jul? Can one point me to the related code option or create a pull request on top of "pbiering-testing" and I will test the code then here on my system.

Thank you!

**Comment by pbiering** [comment]
it turned out that PROPFIND at least since 0.10 offers 

```
          <supported-report>
            <report>
              <sync-collection />
            </report>
          </supported-report>
```

but no real support is implemented behind currently. Removed the offering, now the sync is working again with SOGo connector (which activates fallback then).

Related code is in xmlutils.py:

```
            for report_name in (
                    "principal-property-search", "sync-collection",
                    "expand-property", "principal-search-property-set"):
                supported = ET.Element(_tag("D", "supported-report"))
```

See commit on "pbiering-testing":
https://github.com/Kozea/Radicale/pull/526/commits/2bd1b4f71a9264e01600a70b15e8e79d57d52493

**Comment by oupala** [comment]
Is it implemented?

**Comment by Unrud** [comment]
> Is it implemented?

Yes

**Comment by oupala** [comment]
Great news. It was not obvious for my eyes if it was implemented or not. Thanks for the confirmation.
