### ISSUE TITLE
version >0.8 causes error 500

### ISSUE THREAD

**Issue by chriscamacho** [Kozea/Radicale#308]
I've been running 0.8 for a fair while and just notice while migrating server that v0.9 and v.10 both cause a server error 500

switching DEBUG on in logs show nothing - things just seem to stop when accessing the rights file (might not be connected ?)

the configs all work fine in 0.8 and without a specific(/any) error message I'm at a bit of a loss - sorry this isn't very useful... :(

I'm having to stay at 0.8 for now as I've been unable to diagnose any fault.

I have .8 .9 and .10 "installed" and can easily switch between them if you need any diagnostic runs...

**Comment by liZe** [comment]
Could you launch Radicale in a terminal with debug logs, and see what's going on?

**Comment by chriscamacho** [comment]
"switching DEBUG on in logs show nothing - things just seem to stop when accessing the rights file (might not be connected ?)"
literally NOTHING even from terminal - so bit hard to diagnose I know!

**Comment by chriscamacho** [comment]
I've made a separate config, removing anything not relevant/unused in case that was causing an issue, it seems to get several requests until it just stops without an error message

the client says
      Caldav sync error (IO)
      StatusCode: 500

(other clients behave similarly)

here's the full log - which looks very similar to a working Radicale-0.8 install...

	Base URL prefix: /
	Listening to XXXXXXXXXXXXX.XX.XX port 5232
	Radicale server ready
	PROPFIND request at /chris/ received
	Request headers:
	{'CONTENT_LENGTH': '284',
	 'CONTENT_TYPE': 'application/xml;charset="UTF-8"',
	 'GATEWAY_INTERFACE': 'CGI/1.1',
	 'HTTP_CONNECTION': 'Keep-Alive',
	 'HTTP_DEPTH': '1',
	 'HTTP_HOST': 'XXXXXXXXXXXXX.XX.XX:5232',
	 'HTTP_USER_AGENT': 'CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.6',
	 'PATH_INFO': '/chris/',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '86.9.183.199',
	 'REMOTE_HOST': 'cpc75572-harg6-2-0-cust966.7-1.cable.virginm.net',
	 'REQUEST_METHOD': 'PROPFIND',
	 'SCRIPT_NAME': '',
	 'SERVER_NAME': 'XXXXXXXXXXXXX.XX.XX',
	 'SERVER_PORT': '5232',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
	 'wsgi.errors': <open file '/dev/null', mode 'w' at 0x7f40016005d0>,
	 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f40016f39a8>,
	 'wsgi.input': <socket._fileobject object at 0x7f40016703d0>,
	 'wsgi.multiprocess': False,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}
	Sanitized path: /chris/
	Reading rights from file /etc/radicale/rights
	PROPFIND request at /chris/ received
	Request headers:
	{'CONTENT_LENGTH': '143',
	 'CONTENT_TYPE': 'application/xml;charset="UTF-8"',
	 'GATEWAY_INTERFACE': 'CGI/1.1',
	 'HTTP_CONNECTION': 'Keep-Alive',
	 'HTTP_DEPTH': '0',
	 'HTTP_HOST': 'XXXXXXXXXXXXX.XX.XX:5232',
	 'HTTP_USER_AGENT': 'CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.6',
	 'PATH_INFO': '/chris/',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '86.9.183.199',
	 'REMOTE_HOST': 'cpc75572-harg6-2-0-cust966.7-1.cable.virginm.net',
	 'REQUEST_METHOD': 'PROPFIND',
	 'SCRIPT_NAME': '',
	 'SERVER_NAME': 'XXXXXXXXXXXXX.XX.XX',
	 'SERVER_PORT': '5232',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
	 'wsgi.errors': <open file '/dev/null', mode 'w' at 0x7f40016005d0>,
	 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f40016f39a8>,
	 'wsgi.input': <socket._fileobject object at 0x7f40016703d0>,
	 'wsgi.multiprocess': False,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}
	Sanitized path: /chris/
	Reading rights from file /etc/radicale/rights
	PROPFIND request at /teamcamacho/ received
	Request headers:
	{'CONTENT_LENGTH': '284',
	 'CONTENT_TYPE': 'application/xml;charset="UTF-8"',
	 'GATEWAY_INTERFACE': 'CGI/1.1',
	 'HTTP_CONNECTION': 'Keep-Alive',
	 'HTTP_DEPTH': '1',
	 'HTTP_HOST': 'XXXXXXXXXXXXX.XX.XX:5232',
	 'HTTP_USER_AGENT': 'CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.6',
	 'PATH_INFO': '/teamcamacho/',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '86.9.183.199',
	 'REMOTE_HOST': 'cpc75572-harg6-2-0-cust966.7-1.cable.virginm.net',
	 'REQUEST_METHOD': 'PROPFIND',
	 'SCRIPT_NAME': '',
	 'SERVER_NAME': 'XXXXXXXXXXXXX.XX.XX',
	 'SERVER_PORT': '5232',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
	 'wsgi.errors': <open file '/dev/null', mode 'w' at 0x7f40016005d0>,
	 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f40016f39a8>,
	 'wsgi.input': <socket._fileobject object at 0x7f40016703d0>,
	 'wsgi.multiprocess': False,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}
	Sanitized path: /teamcamacho/
	Reading rights from file /etc/radicale/rights
	PROPFIND request at /teamcamacho/ received
	Request headers:
	{'CONTENT_LENGTH': '143',
	 'CONTENT_TYPE': 'application/xml;charset="UTF-8"',
	 'GATEWAY_INTERFACE': 'CGI/1.1',
	 'HTTP_CONNECTION': 'Keep-Alive',
	 'HTTP_DEPTH': '0',
	 'HTTP_HOST': 'XXXXXXXXXXXXX.XX.XX:5232',
	 'HTTP_USER_AGENT': 'CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.6',
	 'PATH_INFO': '/teamcamacho/',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '86.9.183.199',
	 'REMOTE_HOST': 'cpc75572-harg6-2-0-cust966.7-1.cable.virginm.net',
	 'REQUEST_METHOD': 'PROPFIND',
	 'SCRIPT_NAME': '',
	 'SERVER_NAME': 'XXXXXXXXXXXXX.XX.XX',
	 'SERVER_PORT': '5232',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
	 'wsgi.errors': <open file '/dev/null', mode 'w' at 0x7f40016005d0>,
	 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f40016f39a8>,
	 'wsgi.input': <socket._fileobject object at 0x7f40016703d0>,
	 'wsgi.multiprocess': False,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}
	Sanitized path: /teamcamacho/
	Reading rights from file /etc/radicale/rights
	PROPFIND request at /teamcamacho/ received
	Request headers:
	{'CONTENT_LENGTH': '284',
	 'CONTENT_TYPE': 'application/xml;charset="UTF-8"',
	 'GATEWAY_INTERFACE': 'CGI/1.1',
	 'HTTP_CONNECTION': 'Keep-Alive',
	 'HTTP_DEPTH': '1',
	 'HTTP_HOST': 'XXXXXXXXXXXXX.XX.XX:5232',
	 'HTTP_USER_AGENT': 'CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.6',
	 'PATH_INFO': '/teamcamacho/',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '86.9.183.199',
	 'REMOTE_HOST': 'cpc75572-harg6-2-0-cust966.7-1.cable.virginm.net',
	 'REQUEST_METHOD': 'PROPFIND',
	 'SCRIPT_NAME': '',
	 'SERVER_NAME': 'XXXXXXXXXXXXX.XX.XX',
	 'SERVER_PORT': '5232',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
	 'wsgi.errors': <open file '/dev/null', mode 'w' at 0x7f40016005d0>,
	 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f40016f39a8>,
	 'wsgi.input': <socket._fileobject object at 0x7f40016703d0>,
	 'wsgi.multiprocess': False,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}
	Sanitized path: /teamcamacho/
	Reading rights from file /etc/radicale/rights
	PROPFIND request at /teamcamacho/ received
	Request headers:
	{'CONTENT_LENGTH': '143',
	 'CONTENT_TYPE': 'application/xml;charset="UTF-8"',
	 'GATEWAY_INTERFACE': 'CGI/1.1',
	 'HTTP_CONNECTION': 'Keep-Alive',
	 'HTTP_DEPTH': '0',
	 'HTTP_HOST': 'XXXXXXXXXXXXX.XX.XX:5232',
	 'HTTP_USER_AGENT': 'CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.6',
	 'PATH_INFO': '/teamcamacho/',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '86.9.183.199',
	 'REMOTE_HOST': 'cpc75572-harg6-2-0-cust966.7-1.cable.virginm.net',
	 'REQUEST_METHOD': 'PROPFIND',
	 'SCRIPT_NAME': '',
	 'SERVER_NAME': 'XXXXXXXXXXXXX.XX.XX',
	 'SERVER_PORT': '5232',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
	 'wsgi.errors': <open file '/dev/null', mode 'w' at 0x7f40016005d0>,
	 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f40016f39a8>,
	 'wsgi.input': <socket._fileobject object at 0x7f40016703d0>,
	 'wsgi.multiprocess': False,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}
	Sanitized path: /teamcamacho/
	Reading rights from file /etc/radicale/rights
	PROPFIND request at /chris/ received
	Request headers:
	{'CONTENT_LENGTH': '284',
	 'CONTENT_TYPE': 'application/xml;charset="UTF-8"',
	 'GATEWAY_INTERFACE': 'CGI/1.1',
	 'HTTP_CONNECTION': 'Keep-Alive',
	 'HTTP_DEPTH': '1',
	 'HTTP_HOST': 'XXXXXXXXXXXXX.XX.XX:5232',
	 'HTTP_USER_AGENT': 'CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.6',
	 'PATH_INFO': '/chris/',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '86.9.183.199',
	 'REMOTE_HOST': 'cpc75572-harg6-2-0-cust966.7-1.cable.virginm.net',
	 'REQUEST_METHOD': 'PROPFIND',
	 'SCRIPT_NAME': '',
	 'SERVER_NAME': 'XXXXXXXXXXXXX.XX.XX',
	 'SERVER_PORT': '5232',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
	 'wsgi.errors': <open file '/dev/null', mode 'w' at 0x7f40016005d0>,
	 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f40016f39a8>,
	 'wsgi.input': <socket._fileobject object at 0x7f40016703d0>,
	 'wsgi.multiprocess': False,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}
	Sanitized path: /chris/
	Reading rights from file /etc/radicale/rights
	PROPFIND request at /chris/ received
	Request headers:
	{'CONTENT_LENGTH': '143',
	 'CONTENT_TYPE': 'application/xml;charset="UTF-8"',
	 'GATEWAY_INTERFACE': 'CGI/1.1',
	 'HTTP_CONNECTION': 'Keep-Alive',
	 'HTTP_DEPTH': '0',
	 'HTTP_HOST': 'XXXXXXXXXXXXX.XX.XX:5232',
	 'HTTP_USER_AGENT': 'CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.6',
	 'PATH_INFO': '/chris/',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '86.9.183.199',
	 'REMOTE_HOST': 'cpc75572-harg6-2-0-cust966.7-1.cable.virginm.net',
	 'REQUEST_METHOD': 'PROPFIND',
	 'SCRIPT_NAME': '',
	 'SERVER_NAME': 'XXXXXXXXXXXXX.XX.XX',
	 'SERVER_PORT': '5232',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
	 'wsgi.errors': <open file '/dev/null', mode 'w' at 0x7f40016005d0>,
	 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f40016f39a8>,
	 'wsgi.input': <socket._fileobject object at 0x7f40016703d0>,
	 'wsgi.multiprocess': False,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}
	Sanitized path: /chris/
	Reading rights from file /etc/radicale/rights

**Comment by liZe** [comment]
It looks like you're using Radicale behind a HTTP server, and this HTTP server is not configured to log errors (according to the `'wsgi.errors': <open file '/dev/null'...` line).

To get the error, you can either:
- configure your HTTP server to log errors, or
- launch Radicale directly in a terminal.

**Comment by chriscamacho** [comment]
The feedback I have *is* from the console

Behaviour is identical without apache running

There are plenty of logging going on for apache, which is only serving port 80 and 443 and isn't effecting radicales port which is 5232 (I think)

On 9 September 2015 17:16:39 BST, Guillaume Ayoub <notifications@github.com> wrote:
>It looks like you're using Radicale behind a HTTP server, and this HTTP
>server is not configured to log errors (according to the
>`'wsgi.errors': <open file '/dev/null'...` line).
>
>To get the error, you can either:
>- configure your HTTP server to log errors, or
>- launch Radicale directly in a terminal.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Kozea/Radicale/issues/308#issuecomment-138960629

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pbiering** [comment]
really old, closed, please reopen if reproducable with current version
