### ISSUE TITLE
iCal don't sychronize when "Sync all events" is not set

### ISSUE THREAD

**Issue by liZe** [Kozea/Radicale#31]
This behavior is described in the documentation, but it's now time to find a real solution.

Some (maybe) useful links:
- [The same problem with DAViCal](http://www.gossamer-threads.com/lists/davical/general/1779)
- [Tests and debug by Ron](http://librelist.com/browser//radicale/2012/3/19/more-iphone-problems/)

According to the DAViCal developers, this problem is due to the missing support of "time-range queries in the calendar-query report".

**Comment by pbiering** [comment]
closed as really old version
