### ISSUE TITLE
radicale.org uses an invalid SSL certificate

### ISSUE THREAD

**Issue by L-P** [Kozea/Radicale#310]
> radicale.org uses an invalid security certificate.  
> The certificate is only valid for the following names: *.kozea.fr, kozea.fr  
> (Error code: ssl_error_bad_cert_domain)

**Comment by liZe** [comment]
We'll probably move the website to GitHub-Pages, fixing this problem.

**Comment by liZe** [comment]
See http://kozea.github.io/Radicale/, but unfortunately no HTTPS available.
