### ISSUE TITLE
Internal server error on calendar creation

### ISSUE THREAD

**Issue by Phyks** [Kozea/Radicale#311]
Hi,

When creating a calendar, I often have the following error:
```
A server error occurred.  Please contact the administrator.
```

Even with debug enabled, there is absolutely no trace of this error in the logs.

Do you know where it can come from? Seems that everything is working as expected afterwards, which is even weirder.

Thanks

**Comment by liZe** [comment]
That's strange. Without any debug message, I can't really help you :/.

**Comment by Phyks** [comment]
It has been a while since I posted this, and I forgot a bit about the way to reproduce it. I will try to post some extra information about it ASAP. Thanks!

**Comment by Phyks** [comment]
Could no longer reproduce it, closing it. Sorry for the late delay =(
