### ISSUE TITLE
can't install radicale 1.0 by pip

### ISSUE THREAD

**Issue by abeudin** [Kozea/Radicale#312]
i can't install radicale 1.0 by pip

the only version available is 0.10, 0.2, 0.3, 0.4, 0.5, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6, 0.7.1, 0.7, 0.8, 0.9, 0.9b1, 0.9b2

**Comment by justinzane** [comment]
Confirmed.

**Comment by liZe** [comment]
Fixed, you can now install 1.0.1.
