### ISSUE TITLE
Include tests in pypi tarballs

### ISSUE THREAD

**Issue by jorti** [Kozea/Radicale#314]
The tarballs in radicale.org have no tests included. I fetch the sources from there to create rpm packages and I'd like to have the tests available.

Thank you.

**Comment by liZe** [comment]
The tarballs provided by GitHub for releases have tests included, are you OK using them instead of the ones listed on radicale.org? I'm not fond of of tests included in packages for pip and end-users who just want to use the software.

**Comment by jorti** [comment]
Ok, I'll fetch the sources from GitHub instead. Just make sure that the releases are tagged for them to be available in the releases tab.

Thank you.

**Comment by liZe** [comment]
I don't forget to tag them, I just sometimes forget to push the tags :).
