### ISSUE TITLE
Windows Phone vcf entry with invalid newline causes SOGo connector to fail

### ISSUE THREAD

**Issue by konmax** [Kozea/Radicale#315]
Hi,

If a vcf (contact) entry including a picture is created with a Windows Phone 8.1, an additional newline is written to the vcf collection file after the PHOTO stream. This causes the SOGo connector within Thunderbird to stop reading everything after the picture for such a contact. Example for such an entry:

BEGIN:VCARD
VERSION:3.0
N:For New line;Test;;;
FN:Test For New line
PHOTO;ENCODING=b;TYPE=JPEG:/9j/4AAQSkZJRgABAQEASABIAAD/...==

TEL;TYPE=CELL;TYPE=VOICE:254215
UID:040000008200E00074C5B7101A82E00800000000C3EC792D9397E646AAAFE50A352C796910000000AD0BDFC767B8144787BED6D37D169DD2
X-RADICALE-NAME:040000008200E00074C5B7101A82E00800000000C3EC792D9397E646AAAFE50A352C796910000000AD0BDFC767B8144787BED6D37D169DD2.vcf
END:VCARD

Logs are available here:

http://www.appdata.de/radicale_vcf_newline_collection_entry.txt
http://www.appdata.de/radicale_vcf_newline_issue_log.txt

Konrad

**Comment by liZe** [comment]
This should be fixed now that we use a real ical parser.
