### ISSUE TITLE
Disable SSLv2, SSLv3

### ISSUE THREAD

**Issue by mrueg** [Kozea/Radicale#316]
The current default config enables also SSLv2 and SSLv3 via https://github.com/Kozea/Radicale/blob/master/config#L37
With python 2.7.9 or later, it's possible to drop support for them, but there's no option to set that in the config. 
https://docs.python.org/2/library/ssl.html#ssl.OP_NO_SSLv2
https://docs.python.org/2/library/ssl.html#ssl.OP_NO_SSLv3

Could you add an option to disable SSLv2 + v3?

**Comment by liZe** [comment]
It's an useful feature that is probably quite easy to add. If someone is interested in providing a pull request, I'll be happy to review and merge it, or I'll add it myself as soon as I find the time to!

**Comment by liZe** [comment]
This problem doesn't exist anymore now that Python 2 support has been dropped.
