### ISSUE TITLE
Dulwich has a python3-supported release now

### ISSUE THREAD

**Issue by mrueg** [Kozea/Radicale#317]
So you probably can update your tox.ini here to depend on >=0.11.1
https://github.com/Kozea/Radicale/blob/master/tox.ini#L28

**Comment by liZe** [comment]
Do you know if it works with Python 3.2 and 3.3?

**Comment by mrueg** [comment]
Sorry, haven't tested that as I'm on py3.4

**Comment by liZe** [comment]
As explained in #372, git is not supported anymore in Radicale, but can be provided by other external tools.
