### ISSUE TITLE
1.0.1: Windows Phone and multifilesystem issue "Is a directory"

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#319]
Hi,

while Windows Phone is working fine with 0.10, it has an issue with 1.0.1 (multifilesystem storage):

<?xml version="1.0" encoding="UTF-8"?><propfind xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns="DAV:"><prop><getctag xmlns="http://calendarserver.org/ns/" /><resourcetype /><displayname /><cal:supported-calendar-data /><cal:supported-calendar-component-set /></prop></propfind>
2015-09-26 09:01:57,539 - WARNING: Error while reading item '/var/lib/radicale/collections/peter.bieringer/PeterTest.ics': IOError(21, 'Is a directory')

Windows Phone Setup:

Type: iCloud
URL: https://server:port/peter.bieringer/

only one calender is currenty inside the directory.

radicale also creates then "collections/peter.bieringer.props" (not seen in 0.10):

$ find collections
collections
collections/peter.bieringer
collections/peter.bieringer/PeterTest.ics
collections/peter.bieringer/PeterTest.ics/*****-***-***-***-****.ics
collections/peter.bieringer/PeterTest.ics.props
collections/peter.bieringer.props  <- fresh created by radicale

From experiences with 0.10, this "collections/peter.bieringer.props" confuses Windows Phone later somehow...

**Comment by liZe** [comment]
Probably fixed with other multifilesystem problems.
