### ISSUE TITLE
Handle nested folders

### ISSUE THREAD

**Issue by MacGyverNL** [Kozea/Radicale#321]
As described in untitaker/vdirsyncer#276.

I updated both vdirsyncer and Radicale recently, and vdirsyncer reports it's not finding my collections. According to @untitaker, Radicale is at fault for not handling or prohibiting nested folders. I have a folder structure:
```
XXXXXX/ (username)
XXXXXX/calendars/
XXXXXX/contacts/
XXXXXX/calendars/cal1.ics
XXXXXX/calendars/cal2.ics
external/
external/calendars/
external/calendars/cal3.ics
external/calendars/cal4.ics
readonly/
readonly/external -> ../external
readonly/XXXXXX -> ../XXXXXX
```

Now apparently, on a discover (see the conversation debug logs at https://ptpb.pw/LFjy and https://ptpb.pw/z-S_ ), Radicale only reports the top level folder (so depending on the query, XXXXXX, external, or read-only) causing vdirsyncer to fail.

caldav-sync and carddav-sync on my android client still work fine though.

I am unsure as to what the correct behaviour is in this case, so don't know how to fix this.

**Comment by untitaker** [comment]
I suppose this kind of usage was simply not anticipated, and I don't know of a clean way to properly figure out calendar-home-sets.

Note that Radicale documentation explicitly states it doesn't respect standards, so this may be marked as wontfix since it works with some clients.

On 1 October 2015 12:50:46 CEST, Pol Van Aubel <notifications@github.com> wrote:
>As described in untitaker/vdirsyncer#276.
>
>I updated both vdirsyncer and Radicale recently, and vdirsyncer reports
>it's not finding my collections. According to @untitaker, Radicale is
>at fault for not handling or prohibiting nested folders. I have a
>folder structure:
>```
>XXXXXX/ (username)
>XXXXXX/calendars/
>XXXXXX/contacts/
>XXXXXX/calendars/cal1.ics
>XXXXXX/calendars/cal2.ics
>external/
>external/calendars/
>external/calendars/cal3.ics
>external/calendars/cal4.ics
>readonly/
>readonly/external -> ../external
>readonly/XXXXXX -> ../XXXXXX
>```
>
>Now apparently, on a discover (see the conversation debug logs at
>https://ptpb.pw/LFjy and https://ptpb.pw/z-S_ ), Radicale only reports
>the top level folder (so depending on the query, XXXXXX, external, or
>read-only) causing vdirsyncer to fail.
>
>caldav-sync and carddav-sync on my android client still work fine
>though.
>
>I am unsure as to what the correct behaviour is in this case, so don't
>know how to fix this.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Kozea/Radicale/issues/321

-- 
Sent from my phone. Please excuse my brevity.

**Comment by liZe** [comment]
@untitaker is right, that was not anticipated, and that's probably not easy to fix.

That's no high priority, but I'm interested if anyone wants to work on that.

**Comment by liZe** [comment]
65659fc makes Radicale usable with cadaver, at least with simple commands.

**Comment by maximilianosbrocca-santex** [comment]
Hello @liZe 

I've a question regarding Radical. Can I contact you by email? Just in case, my address is maximiliano.sbrocca@santexgroup.com. I left a question in the mailing list, but no answers so far. 

I was researching different caldav servers, and we selected RADICALE. Now I'm in research phase 2, and I'm blocked with an issue and I need some help.

Thanks in advance.
Maxi
