### ISSUE TITLE
Documentation improvement: Stress importance of URI endings

### ISSUE THREAD

**Issue by problame** [Kozea/Radicale#322]
I cannot find the source for the [online documentation](http://radicale.org/user_documentation/) which itself is a thing that should be fixed.

It took me a while to figure out that the specific URI endings `.ics` and `.vcf` are mandatory. While a hint about this is in the current documentation, it is 

* buried in the client-specific configuration subsections
* inline
* hence not very visible 

Furthermore, I found that the "full" URL scheme as described below works in more clients than mentioned in the docs.

Hence, as told in IRC, a little enhancement to the documentation text:

Section *Starting the Client*, new  sub-section: *General Configuration*

#### URL Schemes

Protocol | URL
--- | ---
CalDAV | `https://[hostname]:[port]/[username]/[calendarname].ics/`
CardDAV | `https://[hostname]:[port]/[username]/[addressbookname].vcf/`

Default for `port` is `5232`.
Radicale will create the appropriate *collection* (e.g. `calendarname.ics`) automatically in the configured directory.
**Important**: The specific file endings (**.ics**, **.vcf**) and the **trailing slash** are required by some clients. 

### Lightning

[...]

**Comment by liZe** [comment]
The trailing slash is not needed anymore!
