### ISSUE TITLE
Init Database

### ISSUE THREAD

**Issue by mh-manatec** [Kozea/Radicale#324]
Hello,
i've successful installed the Server but the database structure from the file schema.sql does not work! I think the database needs an configuration? I can't find any documentation for setting up radicale with postgresql.

Can anyone help me?

**Comment by liZe** [comment]
As it's defined in #372, the storage modules have been removed from Radicale and will be available thanks to external "plugins". Are you interested in developing a database plugin and/or maintaining it? You can add your comments in #391.
