### ISSUE TITLE
Git hooks are not being executed

### ISSUE THREAD

**Issue by jreinert** [Kozea/Radicale#327]
I added a post-commit git hook which checks if changes to the BDAY field of contacts in address books are made and generates a birthday calendar for this address book, adds and commits it. This hook isn't run though. I tried manually changing a BDAY field and committing it. The hook ran just fine. Maybe It's an issue with dulwich...

**Comment by liZe** [comment]
According to its NEWS file, dulwich launches hooks as long as they're posix shell scripts. I've never used hooks with dulwich, you should ask its developers, it's probably possible to find a solution.

**Comment by liZe** [comment]
Reported in dulwich: jelmer/dulwich#386.

**Comment by liZe** [comment]
I close this ticket as the git support will not be built-in anymore.
