### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by siccegge** [Kozea/Radicale#331]
Somewhen breaks between 0.10 and 1.0.1 (also the 1.0.1-2 debian package which has the two patches from altest git added) breaks radicale on my server (nginx, uwsgi)

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 610, in report
    answer = xmlutils.report(environ["PATH_INFO"], content, collection)
  File "/usr/lib/python2.7/dist-packages/radicale/xmlutils.py", line 552, in report
    return _pretty_xml(multistatus)
  File "/usr/lib/python2.7/dist-packages/radicale/xmlutils.py", line 102, in _pretty_xml
    element, "utf-8").decode("utf-8")).encode(output_encoding)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 71: ordinal not in range(128)
```

**Comment by liZe** [comment]
@siccegge Thank you for reporting this issue. Could you please provide the logs?

**Comment by siccegge** [comment]
Which logs exactly? How should I send these logs? github doesn't seem to let me attach .log or .txt files

**Comment by liZe** [comment]
You can post them on Gist or Pastebin for example. The debugging logs are available either (in a file) by tweaking the [logging] section of the configuration file, or (standard output) by lanuching radicale in a terminal with the `--debug` option.

**Comment by siccegge** [comment]
https://pbot.rmdir.de/Oj8SJhjYjGaWO4CQ2Xg5fA
https://pbot.rmdir.de/X8PBwP_i--MzuAVRr3brhg
https://pbot.rmdir.de/U9rnes6jsnXWTly2ejDFFg

**Comment by siccegge** [comment]
FWIW this seems to affect DAVDroid in some way.

For Mozilla lighning this seems to happen on the first sync (if I do launch it with 0.10 and keep the application open it will still be able to successfully syncronize again untill I kill and restart the process.

Unfortunately TLS makes it a it hard to plug wireshark in between

**Comment by siccegge** [comment]
I'll move to uwsgi <-> nginx via tcp/localhost tonight and see if I can extract the exact query contents

**Comment by liZe** [comment]
No problem, the logs are useful and should be enough to find the cause of the problem

**Comment by liZe** [comment]
I can't reproduce, even with a calendar full of non-ASCII characters.

It would be really useful to get Radicale's logs, not the ones from uwsgi or nginx. The easy (and dirty) way to get them is to launch radicale in a terminal with the `--debug` option and copy/paste the result. If you can share with me your calendar, it may help too.

**Comment by siccegge** [comment]
Hm. I do now have a debuglog. However that seems to contain quite some data from my calendar.

I'll try to anonymize it enough to post somewhere

**Comment by siccegge** [comment]
Hi!

Any news? I think we tracked it down quite a bit on IRC that day

Guess I can try and do any additional logs if you need them

**Comment by liZe** [comment]
I've checked the IRC logs, it was caused by HTTP-encoded UTF-8 characters such as %E2%80%93.

**Comment by siccegge** [comment]
Jep matches my memories. Is this something that's going to be fixed in radicale or shall I try and somehow convert my data? If so, what would be the preferred encoding there?

**Comment by liZe** [comment]
There's a bug in Radicale that needs to be fixed, for sure. But I don't know when I (or anybody else) will find the time to fix it.

If you want to encode your data, you should use ASCII for URLs.

**Comment by Unrud** [comment]
I can't reproduce this issue with the development version. Non-ASCII characters in file names/URLs seem to work.
