### ISSUE TITLE
Deny permission in rights file

### ISSUE THREAD

**Issue by daald** [Kozea/Radicale#334]
I have a cron job creates a calendar (name: 'test'). Changes to it will simply be overwritten. I tried putting this calendar in another namespace, but my Android client DAVdroid only lists objects of my own namespace, so I had to move it back to my own namespace.

The patch below allows to remove permissions in a rule. Instead of:

    [rw]
    user: .+
    #collection: ^%(login)s(/  - all collections except 'test' -  )?$   next line is untested
    collection: ^%(login)s(/(calendar1|calendar2|calendar3|contacts1|contacts2|...).+)?$
    permission: rw

You can now use the following rules, so that you don't have to explicitly name all collections.

    # write access for 'test' user to 'test' objects
    [test]
    user: ^test$
    collection: ^.+/test.*$
    permission: rw
    
    # deny user write to test
    [deny-w-test]
    user: .+
    collection: ^.+/test.*$
    permission: !w
    
    # default "owner_only" rule
    [rw]
    user: .+
    collection: ^%(login)s(/.*)?$
    permission: rw

The permission '!w' breaks the loop and returns False the radicale. Without the patch, radicale would further search for other matching rules (OR operation of the permissions of all matching rules).

Detailed explanation of the above ruleset from bottom to top:
- Allow rw to all collection in $login/*
- But don't allow writing to */test  (this is new)
- For user 'test', Writing to */test is always allowed

Here the patch:

    --- /usr/lib/python2.7/dist-packages/radicale/rights/regex.py_orig	2014-08-13 13:12:19.000000000 +0200
    +++ /usr/lib/python2.7/dist-packages/radicale/rights/regex.py	2015-11-25 00:15:51.718979822 +0100
    @@ -90,7 +92,11 @@
                 re_collection = re_collection.format(*user_match.groups())
                 if re.match(re_collection, collection_url):
                     log.LOGGER.debug("Section '%s' matches" % section)
    -                if permission in regex.get(section, "permission"):
    +                permissions = regex.get(section, "permission")
    +                if "!"+permission in permissions:
    +                    log.LOGGER.debug("Negative permission in '%s'. Denying" % permissions)
    +                    return False
    +                if permission in permissions:
                         return True
                 else:
                     log.LOGGER.debug("Section '%s' does not match" % section)

**Comment by prlw1** [comment]
Wondering whether something like "n" might be easier to parse than "!w", so just use "n" for deny...

**Comment by daald** [comment]
`!w` stands for "writing explicitly denied, but if there is a `r` rule, reading is still allowed"

**Comment by liZe** [comment]
What do you think about getting the rights of the first matching rule? I've created a pull request (#335). It's not compatible with older versions, but it solves you problem quite simply and doesn't need a new syntax.

```cfg
# write access for 'test' user to 'test' objects
[test]
user: ^test$
collection: ^.+/test.*$
permission: rw

# deny user write to test
[deny-w-test]
user: .+
collection: ^.+/test.*$
permission: r

# default "owner_only" rule
[rw]
user: .+
collection: ^%(login)s(/.*)?$
permission: rw
```

If anyone finds a case that this behaviour cannot solve easily, please let me know!

**Comment by daald** [comment]
For me that's a solution which fits my needs
