### ISSUE TITLE
Office Outlook 2016 issue?

### ISSUE THREAD

**Issue by Gregmee** [Kozea/Radicale#338]
Been running Radicale for the past few years without issue. (Love it by the way - thanks!)

Since 'upgrading' from Office 2013 to Office 2016 my calendars won't update and I get the message:

Task 'Internet Calendar Subscriptions' reported error (0xAB404005) : 'Cannot verify or add the calendar to Outlook. Make sure the following link is a valid calendar link:
http://rosterimport.com:5232/caldav/XXXXX/XXXXX.ics/'

The link is valid and I can download it using the URL OK but for some reason Outlook 2016 won't update the calendar.

If I try and add a new calendar into outlook 2016 such as webcal://rosterimport.com:5232/caldav/XXXXX/XXXXX.ics/' no error message is generated but it doesn't appear in Outlook. (Although if I go to http://rosterimport.com:5232/caldav/XXXXX/XXXXX.ics/ then it imports the 'one off' ics file OK.

Has anyone else had similar issues with Outlook 2016? 

I've tried deleting the calendars in Outlook and re-adding them without any luck either.

I'm running Radicale 1.0.1 on a windows box.

**Comment by Gregmee** [comment]
Have also discovered the issue also occurs when trying to add a calendar into calendar.live.com

Once you click on 'subscribe' when in calendar.live.com and enter the URL with the port number in it the message "There's a problem with the calendar URL that you entered. Please make sure you've entered it correctly and try again." appears and the calendar won't add in.

**Comment by liZe** [comment]
Can anybody confirm that #412 fixes this issue?

**Comment by Gregmee** [comment]
Thanks - can confirm it fixes the Outlook 2016 issue. Unfortunately the issue with calendar.live.com still exists :-(

**Comment by liZe** [comment]
I'll close this issue for now. @Gregmee if the issue still exists with calendar.live.com, please open another issue that will be fixed after 2.0.0.
