### ISSUE TITLE
Trouble with owner_write in Radicale 1.1

### ISSUE THREAD

**Issue by Captain-Rage** [Kozea/Radicale#348]
Hey, I just upgraded to Radicale 1.1 on an Arch Linux ARM system and ran into some trouble. Let's skip to the unresolved issue; Radicale starts, but when it gets accessed by a client it throws these errors: http://pastebin.com/QJmATMG4 . From the client's perspective no calendar shows up and neither does any password prompt (using the webb interface). The only thing displayed in the webb interface is “A server error occurred. Please contact the administrator.”. Changing type = owner_write → type = None in the # Rights backend section gets Radicale working again, but feels like an uneasy solution. Any thoughts?

**Comment by liZe** [comment]
Duplicates #347.
