### ISSUE TITLE
bin/radicale --version -> wrong version?

### ISSUE THREAD

**Issue by MrDynamite1984** [Kozea/Radicale#358]
Hi,

first of all its a nice server for small setups. Thx for the project and keep up the good work!

I downloaded the Radicale-1.1.1.tar.gz and unpacked it.
mrd@mylaptop ~/Downloads/test/Radicale-1.1.1/bin $ ./radicale --version
0.9

This can be confusing while trying to get it working.
Regards MrD

**Comment by daks** [comment]
Hello,
I don't have this problem once Radicale installed (in a virtualenv)

    eric@server:~ $ pip freeze|grep Radicale
    Radicale==1.1.1
    eric@server:~ $ radicale --version
    1.1.1

**Comment by liZe** [comment]
@MrDynamite1984 thanks for the report!

The executable file in the `bin` folder is provided for installation (and it works, as @daks says), not to be launched when unpacked. When you launch it with from the unpacked archive, it tries to find a module called `radicale`, but cannot find the local one as it's in the parent folder. It finds the installed one and runs it (if it displays 0.9, it means that **0.9 is actually running**).

If you want to use the version of the unpacked archive, you can use `./radicale.py` (best solution, that's what's written in the documentation) or `./bin/radicale` from the root folder (works now, but may not work in the future), but not `./radicale` from the `bin` folder.

**Comment by MrDynamite1984** [comment]
Hi,

thx for the hints.

But you must admit its tempting to run
radicale -D -f -c ..... and it does not complain and starts listening 
for requests.

And I was almost banging my head against the wall ...
running into this .well-known/... with davdroid
and seeing calendar requests but no addressbook stuff.

MrD


Am 15.02.2016 um 13:55 schrieb Guillaume Ayoub:
