### ISSUE TITLE
CardDav can't be read by Address book V 6.1.3 Mac Os X 10.7.5

### ISSUE THREAD

**Issue by kde35ter** [Kozea/Radicale#359]
I run radicale server on ArchLinux (version from AUR repository), and have a .vcf file created by
Address  Book on Mac OS.  I can connect to radicale on localhost from the same machine as running server, and can read from/write to the address book using Thunderbird with vCardsAddressbook extension, so .vcf file itself should be correct.  However, when I set up an account in MacOS Address book to connect to radicale, the connection is made, but I can't read from/write to the address book on
the radicale server. Attached is an edited version of the logfile (
I kept only one occurrence of 404 error for each item in the address book)  file:///home/tk/Documents/err/radicale.log

**Comment by kde35ter** [comment]
Somehow I couldn't attache the logfile, so I copy and paste the content here

2016-02-15 16:48:55,661 - DEBUG: Answer status: 200 OK
2016-02-15 16:51:43,186 - INFO: PROPFIND request at /CN/vcards.vcf/ received
2016-02-15 16:51:43,191 - DEBUG: Request headers:
{'CONTENT_LENGTH': '717',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'fr-fr',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': 'sam.local:5232',
 'HTTP_USER_AGENT': 'AddressBook/6.1.3 (1091) CardDAVPlugin/200 '
                    'CFNetwork/520.5.3 Mac_OS_X/10.7.5 (11G63)',
 'PATH_INFO': '/CN/vcards.vcf/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.1.11',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'sam.local',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2016-02-15 16:51:43,191 - DEBUG: Sanitized path: /CN/vcards.vcf/
2016-02-15 16:51:43,221 - DEBUG: Anonymous has read access to collection CN/vcards.vcf/
2016-02-15 16:51:43,222 - DEBUG: Anonymous has write access to collection CN/vcards.vcf/
2016-02-15 16:51:43,222 - DEBUG: Anonymous has read access to item 7f625c43-3df4-481c-9eb4-9e1a9358c9a0
2016-02-15 16:51:43,222 - DEBUG: Anonymous has write access to item 7f625c43-3df4-481c-9eb4-9e1a9358c9a0
2016-02-15 16:51:43,298 - DEBUG: Request content:
<?xml version="1.0" encoding="UTF-8"?>
<A:propfind xmlns:A="DAV:">
  <A:prop>
    <A:add-member/>
    <D:bulk-requests xmlns:D="http://me.com/_namespace/"/>
    <A:current-user-privilege-set/>
    <A:displayname/>
    <B:max-image-size xmlns:B="urn:ietf:params:xml:ns:carddav"/>
    <B:max-resource-size xmlns:B="urn:ietf:params:xml:ns:carddav"/>
    <C:me-card xmlns:C="http://calendarserver.org/ns/"/>
    <A:owner/>
    <C:push-transports xmlns:C="http://calendarserver.org/ns/"/>
    <C:pushkey xmlns:C="http://calendarserver.org/ns/"/>
    <A:quota-available-bytes/>
    <A:quota-used-bytes/>
    <A:resource-id/>
    <A:resourcetype/>
    <A:supported-report-set/>
    <A:sync-token/>
  </A:prop>
</A:propfind>

2016-02-15 16:51:43,818 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:CR="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ME="http://me.com/_namespace/">
  <response>
    <href>/CN/vcards.vcf/7f625c43-3df4-481c-9eb4-9e1a9358c9a0</href>
    <propstat>
      <prop>
        <current-user-privilege-set>
          <privilege>
            <all />
            <read />
            <write />
            <write-properties />
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <resourcetype />
        <supported-report-set>
          <supported-report>
            <report>principal-property-search</report>
          </supported-report>
          <supported-report>
            <report>sync-collection</report>
          </supported-report>
          <supported-report>
            <report>expand-property</report>
          </supported-report>
          <supported-report>
            <report>principal-search-property-set</report>
          </supported-report>
        </supported-report-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <add-member />
        <ME:bulk-requests />
        <displayname />
        <CR:max-image-size />
        <CR:max-resource-size />
        <CS:me-card />
        <owner />
        <CS:push-transports />
        <CS:pushkey />
        <quota-available-bytes />
        <quota-used-bytes />
        <resource-id />
        <sync-token />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
  <response>
    <href>/CN/vcards.vcf/e8bd3dec-43a9-4885-bc73-9af4375ffed6</href>
    <propstat>
      <prop>
        <current-user-privilege-set>
          <privilege>
            <all />
            <read />
            <write />
            <write-properties />
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <resourcetype />
        <supported-report-set>
          <supported-report>
            <report>principal-property-search</report>
          </supported-report>
          <supported-report>
            <report>sync-collection</report>
          </supported-report>
          <supported-report>
            <report>expand-property</report>
          </supported-report>
          <supported-report>
            <report>principal-search-property-set</report>
          </supported-report>
        </supported-report-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <add-member />
        <ME:bulk-requests />
        <displayname />
        <CR:max-image-size />
        <CR:max-resource-size />
        <CS:me-card />
        <owner />
        <CS:push-transports />
        <CS:pushkey />
        <quota-available-bytes />
        <quota-used-bytes />
        <resource-id />
        <sync-token />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
</multistatus>

2016-02-15 16:51:43,826 - DEBUG: Answer status: 207 Multi-Status

**Comment by kde35ter** [comment]
Sorry for multiplying the comments, but somehow I am unable to edit my posts (I am using an old "unsupported browser"), so here is what I forgot to wrote in the first post.  In the above, I set the address of the server in the configuration of Address Book as "http://servername.local:5232/CN/vcards.vcf/".  The official documentation in http://radicale.org/user_documentation/ seems to indicate, for Mac OSX, unlike other clients, one should set the server address as "http://servername.local:5232" but this doesn't work either.  The log content is as follows.
2016-02-15 18:35:30,790 - DEBUG: Answer status: 207 Multi-Status
2016-02-15 18:35:35,232 - INFO: PROPFIND request at / received
2016-02-15 18:35:35,237 - DEBUG: Request headers:
{'CONTENT_LENGTH': '717',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'fr-fr',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': 'sam.local:5232',
 'HTTP_USER_AGENT': 'AddressBook/6.1.3 (1091) CardDAVPlugin/200 '
                    'CFNetwork/520.5.3 Mac_OS_X/10.7.5 (11G63)',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.1.11',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'sam.local',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2016-02-15 18:35:35,238 - DEBUG: Sanitized path: /
2016-02-15 18:35:35,240 - DEBUG: Anonymous has read access to collection /
2016-02-15 18:35:35,240 - DEBUG: Anonymous has write access to collection /
2016-02-15 18:35:35,240 - DEBUG: Anonymous has read access to collection tk/
2016-02-15 18:35:35,241 - DEBUG: Anonymous has write access to collection tk/
2016-02-15 18:35:35,241 - DEBUG: Anonymous has read access to collection CN/
2016-02-15 18:35:35,241 - DEBUG: Anonymous has write access to collection CN/
2016-02-15 18:35:35,242 - DEBUG: Anonymous has read access to collection user/
2016-02-15 18:35:35,242 - DEBUG: Anonymous has write access to collection user/
2016-02-15 18:35:35,242 - DEBUG: Request content:
<?xml version="1.0" encoding="UTF-8"?>
<A:propfind xmlns:A="DAV:">
  <A:prop>
    <A:add-member/>
    <D:bulk-requests xmlns:D="http://me.com/_namespace/"/>
    <A:current-user-privilege-set/>
    <A:displayname/>
    <B:max-image-size xmlns:B="urn:ietf:params:xml:ns:carddav"/>
    <B:max-resource-size xmlns:B="urn:ietf:params:xml:ns:carddav"/>
    <C:me-card xmlns:C="http://calendarserver.org/ns/"/>
    <A:owner/>
    <C:push-transports xmlns:C="http://calendarserver.org/ns/"/>
    <C:pushkey xmlns:C="http://calendarserver.org/ns/"/>
    <A:quota-available-bytes/>
    <A:quota-used-bytes/>
    <A:resource-id/>
    <A:resourcetype/>
    <A:supported-report-set/>
    <A:sync-token/>
  </A:prop>
</A:propfind>

2016-02-15 18:35:35,263 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:CR="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ME="http://me.com/_namespace/">
  <response>
    <href>/CN/</href>
    <propstat>
      <prop>
        <current-user-privilege-set>
          <privilege>
            <all />
            <read />
            <write />
            <write-properties />
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <displayname>CN</displayname>
        <resourcetype>
          <collection />
        </resourcetype>
        <supported-report-set>
          <supported-report>
            <report>principal-property-search</report>
          </supported-report>
          <supported-report>
            <report>sync-collection</report>
          </supported-report>
          <supported-report>
            <report>expand-property</report>
          </supported-report>
          <supported-report>
            <report>principal-search-property-set</report>
          </supported-report>
        </supported-report-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <add-member />
        <ME:bulk-requests />
        <CR:max-image-size />
        <CR:max-resource-size />
        <CS:me-card />
        <owner />
        <CS:push-transports />
        <CS:pushkey />
        <quota-available-bytes />
        <quota-used-bytes />
        <resource-id />
        <sync-token />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
  <response>
    <href>/user/</href>
    <propstat>
      <prop>
        <current-user-privilege-set>
          <privilege>
            <all />
            <read />
            <write />
            <write-properties />
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <displayname>user</displayname>
        <resourcetype>
          <collection />
        </resourcetype>
        <supported-report-set>
          <supported-report>
            <report>principal-property-search</report>
          </supported-report>
          <supported-report>
            <report>sync-collection</report>
          </supported-report>
          <supported-report>
            <report>expand-property</report>
          </supported-report>
          <supported-report>
            <report>principal-search-property-set</report>
          </supported-report>
        </supported-report-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <add-member />
        <ME:bulk-requests />
        <CR:max-image-size />
        <CR:max-resource-size />
        <CS:me-card />
        <owner />
        <CS:push-transports />
        <CS:pushkey />
        <quota-available-bytes />
        <quota-used-bytes />
        <resource-id />
        <sync-token />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
  <response>
    <href>/</href>
    <propstat>
      <prop>
        <current-user-privilege-set>
          <privilege>
            <all />
            <read />
            <write />
            <write-properties />
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <displayname />
        <resourcetype>
          <principal />
          <collection />
        </resourcetype>
        <supported-report-set>
          <supported-report>
            <report>principal-property-search</report>
          </supported-report>
          <supported-report>
            <report>sync-collection</report>
          </supported-report>
          <supported-report>
            <report>expand-property</report>
          </supported-report>
          <supported-report>
            <report>principal-search-property-set</report>
          </supported-report>
        </supported-report-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <add-member />
        <ME:bulk-requests />
        <CR:max-image-size />
        <CR:max-resource-size />
        <CS:me-card />
        <owner />
        <CS:push-transports />
        <CS:pushkey />
        <quota-available-bytes />
        <quota-used-bytes />
        <resource-id />
        <sync-token />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
  <response>
    <href>/tk/</href>
    <propstat>
      <prop>
        <current-user-privilege-set>
          <privilege>
            <all />
            <read />
            <write />
            <write-properties />
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <displayname>tk</displayname>
        <resourcetype>
          <collection />
        </resourcetype>
        <supported-report-set>
          <supported-report>
            <report>principal-property-search</report>
          </supported-report>
          <supported-report>
            <report>sync-collection</report>
          </supported-report>
          <supported-report>
            <report>expand-property</report>
          </supported-report>
          <supported-report>
            <report>principal-search-property-set</report>
          </supported-report>
        </supported-report-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <add-member />
        <ME:bulk-requests />
        <CR:max-image-size />
        <CR:max-resource-size />
        <CS:me-card />
        <owner />
        <CS:push-transports />
        <CS:pushkey />
        <quota-available-bytes />
        <quota-used-bytes />
        <resource-id />
        <sync-token />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
</multistatus>

2016-02-15 18:35:35,263 - DEBUG: Answer status: 207 Multi-Status

**Comment by liZe** [comment]
A lot of work has been done in master, is this issue still relevant?

**Comment by liZe** [comment]
@kde35ter last call before closing!

**Comment by kde35ter** [comment]
Le problème persiste, mais malheureusement je n'ai pas pu faire un test complet.  Le Mac appartient à me compagne, et juste après le test pour vcard, elle a fait aussi la mise à jour du
calendrier sur radicale (ça, ça marche par contre) qui a bloqué son ordinateur pendant un moment.
Du coup, elle ne veut plus entendre parler de radicale, et je n'ai aucun moyen de faire le test
(en tous cas, la dernière fois que l'on a testé, ça ne marchait pas, mais je ne suis pas sûr si
j'ai toujour le log).  De toute façon, en ce qui me concerne, je n'en ai plus l'utilité, mais cela ne veut pas dire qu'il n'y a plus de bug...


----- Mail d'origine -----
De: Guillaume Ayoub <notifications@github.com>
À: Kozea/Radicale <Radicale@noreply.github.com>
Cc: kde35ter <kde35@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Sat, 15 Apr 2017 09:26:50 +0200 (CEST)
Objet: Re: [Kozea/Radicale] CardDav can't be read by Address book V 6.1.3 Mac Os X 10.7.5 (#359)

@kde35ter last call before closing!

**Comment by pbiering** [comment]
closed because of outdated
