### ISSUE TITLE
Kontact (Kaddressbook) 4.8.5  doesn't display some fields, instead it displays QR codes 

### ISSUE THREAD

**Issue by kde35ter** [Kozea/Radicale#360]
This is probably not a problem of radicale but one with Kontact.  But here it is: when I read vcards on radicale server by Kontact 4.8.5 (on Linux Mint 13), some fields (including first name, family name) don't get displayed, instead there are QR codes that appear.  But Kontact doesn't seem to be supposed to
display them anyway, at least this is the case with the first name and family name, so it is probably a non-issue.

**Comment by liZe** [comment]
You can look in the file of the addressbook to see what's stored in the fields. I think that a client stored images instead of plain text, or that there's a bug in your client :). But Radicale doesn't know anything about QR codes!

**Comment by kde35ter** [comment]
Vu [](url)https://www.kde.org/applications/office/kaddressbook/ ce serait sans doute normal.  Malheureusement
la documentation date un peu [](url)https://userbase.kde.org/KAddressBook ne parle que de la version
4.4, du coup je ne sais pas ou chercher ce que le client stocke (surement dans le serveur mysql-akonadi, mais plus précisément?)  Merci beaucoup en tous cas.
