### ISSUE TITLE
Creating a /user/ calendar prevents radicale from allowing further calendars

### ISSUE THREAD

**Issue by allo-** [Kozea/Radicale#366]
Steps to reproduce:
- Create a ´/user/´ calendar (no .ics, no subfolder, not sure about trailing slash)
- radicale creates a file `user`
- Try to create a `/user/subcal.ics/` calendar
- Radicale has an exception, because it cannot create a directory ``user``

Possible Solution:
- Always append some extension to files, but not to directories. Then `user.ics` and `user/` can coexist.

**Comment by liZe** [comment]
Thanks for the report.

The first step to solve this problem is to have a storage that can handle this architecture. The `multifilesystem` is one of these solutions, and that's the one I would like to have by default in v2.0 (see #364).

**Comment by allo-** [comment]
By the way, is there a way for deleting calendars completely without help of the admin?

**Comment by liZe** [comment]
You can send a HTTP DELETE request, it should work!

**Comment by liZe** [comment]
@allo- did the DELETE request work?

**Comment by allo-** [comment]
I am not quite sure, which program supports this. lightning in thunderbird seems just to support removing the link to the calendar, not the calendar itself. I tried with ``cadaver`` on the cmdline:

    dav:/username/> rm foo.ics 
    Deleting `foo.ics': failed:
    412 Precondition Failed

**Comment by liZe** [comment]
Radicale is known to *not* work with Cadaver (mainly because Cadaver is smart and Radicale is stupid). You can try with a stupid HTTP client like `curl`: `curl -X DELETE http://localhost:5232/username/foo.ics/`.

**Comment by allo-** [comment]
It works.

**Comment by liZe** [comment]
:)

**Comment by Unrud** [comment]
The [specification](https://tools.ietf.org/html/rfc4791#page-11) (b.) prohibits nested calendar collections.
Maybe Radicale should enforce a collection structure like _/username/calendarname/_. Thus accidental creation or usage of calendar collections like _/user/_ would be prevented.

**Comment by liZe** [comment]
As explained in #321, this problem is now fixed. Nested collections are now correctly handled by Radicale, but please note that nested calendars are not forbidden yet.
