### ISSUE TITLE
PUT for calendar data creates a collection with a single item inside it

### ISSUE THREAD

**Issue by untitaker** [Kozea/Radicale#378]
Consider this test script:

```python
import requests

url_coll = 'http://127.0.0.1:5232/bob/test.ics/'
url = url_coll + 'foo.ics'

payload = b'''
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
DTSTART:19970714T170000Z
DTEND:19970715T035959Z
SUMMARY:Bastille Day Party
X-SOMETHING:{r}
UID:{uid}
END:VEVENT
END:VCALENDAR
'''

r = requests.request('MKCOL', url_coll)
r.raise_for_status()

r = requests.put(url, data=payload, headers={'Content-Type': 'text/calendar'})
r.raise_for_status()

payload = b'''<?xml version="1.0" encoding="utf-8" ?>
<C:calendar-multiget xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
    <D:prop>
	<D:getetag/>
	<C:calendar-data/>
    </D:prop>
    <D:href>/bob/test.ics/foo.ics</D:href>
</C:calendar-multiget>
'''

r = requests.request('REPORT', url_coll, data=payload,
                     headers={'Content-Type': 'application/xml; charset=UTF-8'})
assert b'Bastille' in r.content
assert b'404' not in r.content
```

The response for the last REPORT:

	<?xml version='1.0' encoding='UTF-8'?>        
	<multistatus xmlns="DAV:">                    
	  <response>                                  
		<href>bob/test.ics/foo.ics</href>         
		<status>HTTP/1.1 404 Not Found</status>   
	  </response>                                 
	</multistatus>                                

Our resulting directory structure:

    .
    └── bob
        └── test.ics
            ├── foo.ics
            │   └── ebf3955448354732917a221e01d44058
            └── foo.ics.props

**Comment by untitaker** [comment]
For email users: I edited the OP.

**Comment by untitaker** [comment]
This regression has been introduced with https://github.com/Kozea/Radicale/commit/65659fc909b64f72abc5fde4d0f451183dd84425

**Comment by liZe** [comment]
> This regression has been introduced with 65659fc

I can reproduce this bug even before this commit.

**Comment by untitaker** [comment]
Unfortunately this unveils another problem. When now doing a PROPFIND for finding out the principal URL on a path like `/bob/test.ics/`, Radicale returns `/bob/`. However, when asking for `calendar-home-set` on that URL, a 404 is returned.

I realize this might be working as intended, and users have to be created explicitly now (instead of implicitly by pointing the client to the URL) Is it sufficient to create the folder?

**Comment by untitaker** [comment]
@liZe Should the user explicitly create users by creating their user folder?
