### ISSUE TITLE
Clarification: How to create a user

### ISSUE THREAD

**Issue by untitaker** [Kozea/Radicale#384]
Pre-2.0 it was sufficient to request any URL starting with `/<user>/` to create the user. This appears to be no longer possible. Is it advised to create the user manually by creating the folder?

cont. https://github.com/Kozea/Radicale/issues/378

**Comment by untitaker** [comment]
Also, how to create collections?

**Comment by liZe** [comment]
When using `/user/calendar/` paths, we must:
- create the `/user/` WebDAV collection; and then
- create the `/user/calendar/` CalDAV collection (aka calendar).

According to the specification, the first one could be created using a MKCOL request, and the second one with a MKCOL or MKCALENDAR request. The PUT request is also accepted in Radicale and creates collections, even if the WebDAV RFC tells that:

> This specification does not define the behavior of the PUT method for existing collections.  A PUT request to an existing collection MAY be treated as an error (405 Method Not Allowed).
> 
> The MKCOL method is defined to create collections.

Lightning for example sends PUT requests to "publish" calendars. I'm pretty sure that it can't send a MKCOL request (unfortunately, like a lot of other clients).

We can:
- blindly follow the RFC and force users to create their collections with MKCOL requests (and write this in the documentation); or
- create collections and their parents for some requests (including PUT, and well-known GET requests for example) when the user has the right to write; or
- always create collections and their parents (even on GET or REPORT requests) when the user has the right to write.

The third solution is more or less what's in Radicale 1.x and that was both useful and awful (that's why it's been changed).

The first solution is appealing, but I'm afraid of killing the out-of-the-box dark magic of Radicale 1.x. I don't know how many clients will be unable to create collections with this choice.

The second solution is dangerous, but that's the one I prefer.

**Comment by untitaker** [comment]
I don't understand how the second solution significantly differs from the third one.

On 13 July 2016 16:53:03 CEST, Guillaume Ayoub <notifications@github.com> wrote:
>When using `/user/calendar/` paths, we must:
>- create the `/user/` WebDAV collection; and then
>- create the `/user/calendar/` CalDAV collection (aka calendar).
>
>According to the specification, the first one could be created using a
>MKCOL request, and the second one with a MKCOL or MKCALENDAR request.
>The PUT request is also accepted in Radicale and creates collections,
>even if the WebDAV RFC tells that:
>
>> This specification does not define the behavior of the PUT method for
>existing collections.  A PUT request to an existing collection MAY be
>treated as an error (405 Method Not Allowed).
>> 
>> The MKCOL method is defined to create collections.
>
>Lightning for example sends PUT requests to "publish" calendars. I'm
>pretty sure that it can't send a MKCOL request (unfortunately, like a
>lot of other clients).
>
>We can:
>- blindly follow the RFC and force users to create their collections
>with MKCOL requests (and write this in the documentation); or
>- create collections and their parents for some requests (including
>PUT, and well-known GET requests for example) when the user has the
>right to write; or
>- always create collections and their parents (even on GET or REPORT
>requests) when the user has the right to write.
>
>The third solution is more or less what's in Radicale 1.x and that was
>both useful and awful (that's why it's been changed).
>
>The first solution is appealing, but I'm afraid of killing the
>out-of-the-box dark magic of Radicale 1.x. I don't know how many
>clients will be unable to create collections with this choice.
>
>The second solution is dangerous, but that's the one I prefer.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kozea/Radicale/issues/384#issuecomment-232380493

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by liZe** [comment]
> I don't understand how the second solution significantly differs from the third one.

It doesn't significantly differ, but contrary to the third solution it defines a really short list of exceptions:
- PUT requests creating collections is easy to understand and to accept.
- GET requests on well-known collections should redirect to an existing collection, and creating the collection when it's not been created yet is a simple way to "create" users with one "default" collection. 

It's dirty to create collections on GET requests, but I like this solution better than creating collections on all GET requests, and better than killing the out-of-the-box experience with most of the clients. I'd really like to know how many clients are able to create collections with clean MKCOL requests, even when the well-know request redirects to a 404 response, but I think that the number is low :cry:.

Another solution is to create the well-known collection at startup, but it's only possible when the `user` variable is not used in the well-known URL. That's OK for the out-of-the-box experience as there's no authentication in the default configuration. And for people who configure servers using authentication, they'll have to send MKCOL requests when a new user wants to reach the server with a "stupid" client. We can probably assume that this kind of people can find a way to send a request manually or automatically when a new user is added to their list of users.

**Comment by liZe** [comment]
I should try to set "/" as well-known path with no pre-created collection and see how clients behave. If it works for most of them, we should only keep MKCOL, MKCALENDAR and PUT to create collections. People using authentication will have to create their user's collections.

**Comment by liZe** [comment]
See #248 too.

**Comment by liZe** [comment]
Increadible good news: everything works out-of-the-box on iOS (and should be the same on OSX). With or without auth, with or without rights, the client is able to find a solution to create a collection when the account is added:
- with no auth, it creates `/calendar-UUID/`,
- with auth, it creates `/username/calendar-UUID/`

You can add extra calendars, everything works increadibly fine. I'll check other clients.

**Comment by liZe** [comment]
With #455 merged, we now create the user's collection if needed before any authenticated request. I'm trying many clients to see if it's sufficient.

**Comment by liZe** [comment]
Works well with DAVdroid, as long as you authenticate (fortunately, the "preventive authentication" is ON in the default configuration).

**Comment by liZe** [comment]
CalDAV Sync-Adapter works without authentication, but doesn't with authentication (it doesn't send the authentication, don't know why). I didn't find a way to create a calendar. The project seems to be dead, last commit 3 years ago.

**Comment by liZe** [comment]
Same problem with aCalDAV (fork of CalDAV Sync-Adapter), the client doesn't send the authentication.

**Comment by untitaker** [comment]
You need to send a 401 back so that the client retries with auth.

On 2 August 2016 15:55:55 CEST, Guillaume Ayoub <notifications@github.com> wrote:
>CalDAV Sync-Adapter works without authentication, but doesn't with
>authentication (it doesn't send the authentication, don't know why). I
>didn't find a way to create a calendar. The project seems to be dead,
>last commit 3 years ago.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kozea/Radicale/issues/384#issuecomment-236911624

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by liZe** [comment]
> You need to send a 401 back so that the client retries with auth.

Even that doesn't work.

**Comment by liZe** [comment]
And of course it works when I take the time to read the specs and send the needed headers.

**Comment by liZe** [comment]
Thunderbird's collection publication system is broken instead of #442.

**Comment by liZe** [comment]
I'm testing Thunderbird with #459, I'll close this ticket if it works.

**Comment by liZe** [comment]
It works.

**Comment by untitaker** [comment]
I still don't understand how to create users. Pointing a client to `/user/foo.ics/` (when the user doesn't exist) with any method (including MKCOL) 404s.

It does work when I create the user folder as described in the OP. I use `rights = owner_only` and `auth = plain`. I can't set either to `None` (as implied in the config) because that's not a valid module to import.

**Comment by liZe** [comment]
> I still don't understand how to create users. Pointing a client to /user/foo.ics/ (when the user doesn't exist) with any method (including MKCOL) 404s.

Strange. I've tried with the clients listed above, and they all were able to create their collections. Which client didn't work for you?

**Comment by liZe** [comment]
Another solution to get more administration features would be to have a web interface, as proposed in #484.

**Comment by untitaker** [comment]
>they all were able to create their collections

This thread is about creating users.

**Comment by liZe** [comment]
I'm not sure to understand. If by "creating users" you mean "creating the `/user/` folder", then `MKCOL` works, and that's what's done (or any equivalent request) by the clients I have tested.

**Comment by untitaker** [comment]
Nevermind, I got that working: `PROPFIND /user/foo.ics/` to get current-user-principal returns a 404, but doing the same on `/` works fine.

I'm getting a lot of unrelated failures though, will look into that later.
