### ISSUE TITLE
Raspberry Pi, install radicale_0.9-1+deb8u1_all.deb failed at configure

### ISSUE THREAD

**Issue by caesarsamsi** [Kozea/Radicale#387]
Raspbian Jessie, install 0.9-1+deb8u1 using apt-get gets error:

```
pi@mail:/etc/radicale $ sudo systemctl -l status radicale.service
● radicale.service - Radicale CalDav Server
   Loaded: loaded (/etc/systemd/system/radicale.service; disabled)
   Active: failed (Result: exit-code) since Mon 2016-05-02 08:51:42 PDT; 29s ago

May 02 08:51:41 mail radicale[10906]: Traceback (most recent call last):
May 02 08:51:41 mail radicale[10906]: File "/usr/bin/radicale", line 29, in <module>
May 02 08:51:41 mail radicale[10906]: import radicale.__main__
May 02 08:51:41 mail radicale[10906]: ImportError: No module named radicale.__main__
```
More info at: [https://www.raspberrypi.org/forums/viewtopic.php?p=966282#p966282]

**Comment by untitaker** [comment]
This seems like a packaging problem of Debian to me tbh.

**Comment by liZe** [comment]
Yes, strange.

@caesarsamsi Could you try to reproduce the problem with a simple `pip install` instead of the package?

**Comment by caesarsamsi** [comment]
Hi Guillaume,

I just did.

1. Uninstalled using:
sudo apt-get purge radical

2. Then did:
sudo pip install radicale

3. I ran radicale using:
sudo radicale

Radical is running per ps.
However the radical ports are not open.

Thanks, Caesar.

**Comment by liZe** [comment]
You don't need `sudo` (and you really should avoid it).

The default host is `0.0.0.0:5232`, so everything should be working out of the box. If 5232 is not open, it's caused by another package or configuration of your Raspberry.

**Comment by liZe** [comment]
You can try `curl http://localhost:5232/` on your Raspberry, just to be sure that it works.

**Comment by caesarsamsi** [comment]
Thank you! It’s working on 0.0.0.0 and localhost now. I was not successful using telnet localhost 5232 previously.

With the pip method of installation, I run radicale from command line.

Is there a way to run it as a service (daemon)?

**Comment by liZe** [comment]
> Is there a way to run it as a service (daemon)?

Of course, with the `--daemon` option (hint: `radicale --help`).

**Comment by caesarsamsi** [comment]
Thank you, it’s up and running now!
