### ISSUE TITLE
Define how "plugins" work

### ISSUE THREAD

**Issue by liZe** [Kozea/Radicale#391]
As defined in #372, authentication, rights and storage modules have been removed from Radicale and will be available as external "plugins". We need to find what will be the structure of these plugins, and how they will be advertised in documentation.

An exemple to follow may be [Flask](http://flask.pocoo.org/), because they have a nice [list of extensions](http://flask.pocoo.org/extensions/), and a [documentation](http://flask.pocoo.org/docs/0.10/extensiondev/) with a strong naming convention.

**Comment by madr** [comment]
As a long time Flask user I can confirm that it's plugin approach is excellent.

How the plugins should look in detail I can't say much about, but one thing that concerns me is how the licensing should work. Must the plugins honour the GPL as well, or may they have other licenses?

Therefore I would also like to mention Wordpress as an example, where the Wordpress "core" is GPL licensed, but plugins (and themes) do not have to be.

**Comment by nileshtrivedi** [comment]
Are there plugins for postgresql/mariadb/sqlite/turso? I didn't see any listed in the docs.

**Comment by pbiering** [comment]
> Are there plugins for postgresql/mariadb/sqlite/turso? I didn't see any listed in the docs.

I'm not aware about. How it should work you can see in the code, the "plugin" is more or less one file overloading default functions.
