### ISSUE TITLE
Mention Cardbook addon for Thunderbird

### ISSUE THREAD

**Issue by reitzig** [Kozea/Radicale#395]
I recently found addon [Cardbook](https://addons.mozilla.org/en-US/thunderbird/addon/cardbook/?src=hp-dl-upandcoming) for Thunderbird. I have not done thorough testing, but it may be a better recommendation than SOGo Connector.

**Comment by liZe** [comment]
Oh, thanks for the link, I didn't know Cardbook!

**Comment by clawoflight** [comment]
Wanted to mention that it does indeed work better than SOGo connector, which still creates duplicated contacts.

**Comment by daks** [comment]
I wonder if this addon is opensource, and where the code can be found. @reitzig do you know?

**Comment by Arvedui** [comment]
It licensed under GPLv3, the source is available on amo.
Click on "View other versions" and than "View the source" below your favourite version to get there.

**Comment by pbiering** [comment]
Great hint because I have also issues with SOGo, filed some tickets, looks like development has no fast progress...

Regarding isntallation of Cardbook, I simply searched for the add-on in thunderbird and got version 16.8 - looking nice, working as expected.

**Comment by azrdev** [comment]
Note that CardBook creates its own local copy of your address books, separate from the built-in Thunderbird address book, while sogo connector is just a backend for the latter. I don't know if this raises any interoperability issues, but it is very outstanding in the UI.

Also, it is developed on github, too: https://github.com/CardBook/CardBook

**Comment by Unrud** [comment]
Done: http://radicale.org/clients
