### ISSUE TITLE
Discover fails

### ISSUE THREAD

**Issue by legrostdg** [Kozea/Radicale#396]
see https://github.com/pimutils/vdirsyncer/issues/448

Using

- vdirsyncer, version 0.10.1.dev40+ng45cea8f
- Python 3.5.1+
- debian sid
- radicale 1.1.1-1

radicale seems to return an invalid response to a calendar-home-set query to https://dav.example.com/user/ 

    b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:" />'

**Comment by liZe** [comment]
Should be fixed by #455.
