### ISSUE TITLE
Non authorized users can create calendars

### ISSUE THREAD

**Issue by caesarsamsi** [Kozea/Radicale#406]
Repro steps:
1. Raspbian Jessie
2. pip install radicale
3. config.py setup for SSL, auth type=htpasswd, encryption=crypt, rights=None
4. populate /etc/radicale/users using htpasswd utility
5. Use Mac Yosemite calendar app, create the account using any name, if it fails try to create the exact same out, frequently successful on second try.
6: Debug log notes it is running htpasswd authentication
Note: is seems the authentication module is broken??? it doesn't recognize valid vs bogus users

**Comment by liZe** [comment]
> auth type=htpasswd, encryption=crypt, rights=None

As written in the [documentation](http://radicale.org/user_documentation/#idrights-management), when `rights` is set to `None`, "Everybody (including anonymous users) has read and write access to all collections.".
