### ISSUE TITLE
rights="owner_only" rejects everybody

### ISSUE THREAD

**Issue by caesarsamsi** [Kozea/Radicale#407]
Repro steps:
1. Raspbian Jessie
2. pip install radicale
3. config.py setup for SSL, auth type=htpasswd, encryption=crypt, rights=owner_only
4. Everybody is rejected

**Comment by liZe** [comment]
Could you please provide more information, logs for example?

**Comment by kenthinson** [comment]
I'm also having this issue. Running server in a ubuntu 16.04 lxc. 
The client is Calendar OS X 10.11.5. and also IOS 9.3

What is strange is if I log in first with the setting of "owner_write" then I change the conf file to "owner_only" and restart the server I can still use the connection. However if I log out of the calendar app and try to log in again it gives the error the user name or password is incorrect. I'm using IMAP auth. The other difference is "owner_write" vs "owner_only" for the rejection.

**Comment by liZe** [comment]
Is it possible to have the logs please?

**Comment by caesarsamsi** [comment]
Hi Guillaume,

I have since worked out this issue and have a semi-working radicale installation.

The calendar part of it works, the contacts does not.

Mac El Capitan Contacts UI show: “The operation could not be completed”, (CoreDAVErrorDomain Error 8)

The logs show:

2016-07-13 19:37:18,407 - INFO: Starting Radicale
2016-07-13 19:37:18,411 - DEBUG: Authentication type is htpasswd
2016-07-13 19:37:18,713 - DEBUG: registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
2016-07-13 19:37:18,743 - DEBUG: 'bcrypt' backend lacks '$2$' support
2016-07-13 19:37:20,761 - DEBUG: Cleaning up

Thanks, Caesar.

On Jul 13, 2016, at 4:45 PM, Guillaume Ayoub <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible to have the logs please?

**Comment by liZe** [comment]
OK, think I get it. owner_only rejects everybody for `/`, and with some clients that's a real problem :smile:.

**Comment by liZe** [comment]
Fixed in b517818.
