### ISSUE TITLE
authentication should be specified in ALL CAPS for imap ("IMAP") in 1.1.1 new config.py style

### ISSUE THREAD

**Issue by caesarsamsi** [Kozea/Radicale#408]
No configuration attribute has possible values as they were listed in older config.py

**Comment by liZe** [comment]
I don't get it. `IMAP` is in caps in `[config](https://github.com/Kozea/Radicale/blob/1.1.x/config)`, and there's no `IMAP` in `[config.py](https://github.com/Kozea/Radicale/blob/1.1.x/radicale/config.py)`. What are you talking about exactly?
