### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by Lukse** [Kozea/Radicale#411]
Please add

  # -*- coding: utf-8 -*-

to every python file. Unicode characters (even in comments) causes radicale to fail.

> python radicale.py
SyntaxError: Non-ASCII character '\xc2' in file radicale.py on line 4, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

> python radicale.py
Traceback (most recent call last):
  File "radicale.py", line 30, in <module>
    import radicale.__main__
  File "/home/admin/Radicale/radicale/__init__.py", line 2
SyntaxError: Non-ASCII character '\xc2' in file /home/admin/Radicale/radicale/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by untitaker** [comment]
Radicale only supports Python 3.

**Comment by liZe** [comment]
Yes, the current master branch (and next 2.0) is python3-only. See #372.
