### ISSUE TITLE
Support the SOGo Connector for Thunderbird

### ISSUE THREAD

**Issue by wltb** [Kozea/Radicale#42]
SOGo provides a CardDAV plugin for [Thunderbird](http://www.sogo.nu/about/overview.html). It would be nice if you could support it.

**Comment by opensource21** [comment]
__Server__:
 - Radicale 1.0

__PC__:
- Thunderbird 38.2.0
- SOGo Connector 31.0.1

Some addresses will be duplicated. Categories will not be written if I copied the data from existing adressbook :-(

**Comment by liZe** [comment]
@opensource21 is there anything wrong in the logs?

**Comment by opensource21** [comment]
The Category issue seems a Thunderbird-Problem. I will look into the log with the duplicate issue.

**Comment by opensource21** [comment]
Sorry I can't reproduce the duplication and didn't have a log from yesterday.

**Comment by julpec** [comment]
Hello
Radicale still not support Sogo Connector ?

**Comment by pbiering** [comment]
With "Inverse SOGo Connector 31.0.3" on Thunderbird on Linux and Windows, it's working here quite a while.

Example URL for a particular (previously created/known) addressbook (in case of multi-filesystem storage is used):
`https://cdav.example.local/username/user-addressbook-folder.vcf/`

Example URL for a particular (previously created/known) calendar (in case of multi-filesystem storage is used):
`https://cdav.example.local/username/user-calendar-folder.ics/`

**Comment by julpec** [comment]
I confirm it is working with package `iceowl-extension` for caldav and package `xul-ext-sogo-connector` for carddav on Debian Jessie distrib.

**Comment by Unrud** [comment]
I tested SOGO connector and it behaves strange. It doesn't sync an empty address book. The address book on the server must contain at least one contact. It uses sync-token but if the server tells it that the token is invalid, it stops syncing but shows a success message.

**Comment by Gatak** [comment]
Thunderbird now has another CardDAV extension that is working much better than the SoGo connector: https://addons.mozilla.org/en-US/thunderbird/addon/cardbook/
