### ISSUE TITLE
Wrong URL can result in issues in Lightning with Radicale

### ISSUE THREAD

**Issue by SarenT** [Kozea/Radicale#420]
Hi,

It wasn't clear to me how to configure my clients with Radicale. After some confusion and trial-and-error, I have configured my Lightning and CalDavSync (Android) with (I think same) URL.

However,  they I always had the trouble to change (Edit and Delete) events in Lightning. It always told me that there were changes already and I could discard and reload or submit it anyway. Submiting resulted with the same error again. This loop never ended and I could not submit any changes from Lightning. I could though from the app.

After removing and recreating the calendar in lightning and many different approaches and hours of testing, I realized my URL might be wrong. Because in the logs, I saw errors about access rights. Wierd thing was that I could read the calendar and get all changes into Lightning. I could not edit though.
So I changed from:
<host>/<username>/calendar.ics/
to full path
<host>/var/spool/radicale<username>/calendar.ics/
And this fixed the issue. Maybe I was unable to find this anywhere in the documentations. But it would be useful to hint on URL issues.

Having my own calendar server is great! Thanks!

**Comment by liZe** [comment]
The documentation will be rewritten for 2.0.

**Comment by Unrud** [comment]
The issue should be solved in 2.0.0.
