### ISSUE TITLE
well-known targets wrong

### ISSUE THREAD

**Issue by Unrud** [Kozea/Radicale#431]
``/.well-known/carddav`` points to ``/carddav/`` or ``'/%(user)s/carddav/'`` in the config file.

``/.well-known/caldav`` points to ``/caldav/`` or ``'/%(user)s/caldav/'`` in the config file.

I think that the well-known URLs should just point to the relevant  WebDAV server, ``/`` in our case.

**Comment by liZe** [comment]
Related to #384.
