### ISSUE TITLE
DAVDroid instructions bug

### ISSUE THREAD

**Issue by kousu** [Kozea/Radicale#432]
I have DAVDroid 1.0.9.2 on my phone and radicale 1.1.1 (on python2.7 on FreeBSD). I followed the quickstart instructions to run `radicale` and found I could go to http://site.com:5232/ and get a response from radicale. Then I tried to follow the DAVDroid instructions which currently read

> DAVdroid
> 
> DAVdroid is a free and open-source CalDAV/CardDAV client that is available in Play Store for a small fee or in FDroid for free.
> 
> To make it working with Radicale, just add a new DAVdroid account and enter https://example.com/radicale/user/ as base URL (assuming that your Radicale runs at  https://example.com/radicale/; don't forget to set base_prefix correctly).

This didn't work for me. I had to go with https://example.com/, with an empty trailing path, to get DAVDroid and radicale get along. I don't know if radicale has changed or DAVDroid has changed since this was written, but it's not working right now.

I also find the wording here confusing. For one, I wasn't sure if /user/ was literal or a variable---and then it turned out to be irrelevant. The documentation doesn't mention `base_prefix` until the advanced config section, and presumably the base should be an issue for every client, not just DAVDroid; it would be better if you used http://localhost:5232 like in the other examples and skipped mentioning `base_prefix` until it's needed.

Thank you for the excellent little tidy piece of DAV software. DAV is a tricky, bloated protocol, and I've been using it with ownCloud which is tricky and bloated in its own way. I'm excited to jump to a single-user single-process install.

**Comment by liZe** [comment]
I just keep #435 but I won't forget this too.

**Comment by kousu** [comment]
Thanks! Sorry I submitted this twice, I'm not sure why I did that.
