### ISSUE TITLE
Malformed PUT can result in loss of entire item

### ISSUE THREAD

**Issue by untitaker** [Kozea/Radicale#433]
Radicale skips the upload/update if the href path is invalid: https://github.com/Kozea/Radicale/blob/4872ea5/radicale/storage.py#L435

On the next sync, most clients will interpret this as a deletion, and delete the item from the local storage accordingly. Even an `assert is_safe_filesystem_path_component(...)` is better here.

**Comment by liZe** [comment]
Fixed by #425.
