### ISSUE TITLE
Trying to access a radicale Calendar from Google Calendar fails silently (on google part)

### ISSUE THREAD

**Issue by lebouquetin** [Kozea/Radicale#434]
Hello,

I integrated Radicale in Tracim (python software for sharing information) and we try to access our calendars through Google Calendar. There are even no request forwarded to our servers.

I know it's not a radicale software issue ; but maybe someone here already faced this problem and find a way to fix it.

Thanks for your feedbacks.

Damien

**Comment by liZe** [comment]
Strange, you should at least get requests…

**Comment by liZe** [comment]
@lebouquetin Do you have news about that?

**Comment by tracim** [comment]
No help received, no success on my side :-s

**Comment by liZe** [comment]
You can try to access your calendar from another computer using the same URL you used for Google Calendar and see if it works.

**Comment by lebouquetin** [comment]
@liZe the Radicale server is working. We can access it using Thunderbird or similar clients. It's just not working with google calendar.

Maybe my question was not clear. The fact is  :  our Radicale instance is working ok with thunderbird but not working with google calendar. The question is : is there someone who successfully use radicale with google calendar as a client ?

**Comment by liZe** [comment]
@lebouquetin I've tried:

- Get Radicale and unpack it.
- Launch it with `--debug`.
- Add `http://myserver.com:5232/test.ics/` in Google Calendar (Little triangle next to "Other calendars" > "Add from URL").

It just works for me.

**Comment by lebouquetin** [comment]
I retried with a brand new installation. Actually there was a mistake on my side : I didn't configure the Access-Control-Allow-Origin. Now, the calendar is visible on Google Calendar.

Nevertheless, it's still impossible to create an event on this calendar using Google Calendar.  The calendar still does not appear in calendar list for choosing the one on which the new event should be published

**Comment by liZe** [comment]
> Nevertheless, it's still impossible to create an event on this calendar using Google Calendar. The calendar still does not appear in calendar list for choosing the one on which the new event should be published

Google Calendar is not a CalDAV client (and not even a CalDAV server anymore). It's just an HTTP client with read-only access to icalendar files, you won't be able to edit these calendars :cry:.

**Comment by lebouquetin** [comment]
I didn't know that specificity. Thanks.

**Comment by trougnouf** [comment]
> I didn't configure the Access-Control-Allow-Origin

Can you expand on how and where you configured that?
