### ISSUE TITLE
Documentation: DAVDroid instructions are out of date

### ISSUE THREAD

**Issue by kousu** [Kozea/Radicale#435]
The DAVDroid instructions you give say

> DAVdroid is a free and open-source CalDAV/CardDAV client that is available in Play Store for a small fee or in FDroid for free.
> 
> To make it working with Radicale, just add a new DAVdroid account and enter https://example.com/radicale/user/ as base URL (assuming that your Radicale runs at https://example.com/radicale/; don't forget to set base_prefix correctly).

I found I have to give https://example.com/ as the base URL instead. I'm using DAVDroid 1.0.9.1 on Android 6 and Radicale 1.1.1 on FreeBSD.

Also, the wording here is confusing: base_prefix isn't explained until later down in the docs, and the only reference to URLs before that point uses http://example.com:5232 everywhere; notice the inconsistency in protocol and port. In order to get a URL that looks like that you'd have to go through sticking Apache or nginx in front which is a whole other can of worms that that part of the docs is not ready to address.

**Comment by liZe** [comment]
The whole documentation will be rewritten for 2.0!

**Comment by Unrud** [comment]
The documentation has been updated.
