### ISSUE TITLE
Sync problem with Android & DAVDroid

### ISSUE THREAD

**Issue by captainepoch** [Kozea/Radicale#439]
Hi! 

I set up Radicale today and got a problem with sync. I created a user with htpasswd and put the config into /etc/radicale/config.

Then I created a collection for contacts and another for the calendar. I put a recordatory at the calendar and a Test contact.

Then, when I sync from "Accounts" in Android, I got this error:
https://gist.github.com/adolphenom/d3802fc7fb8cc5e983e3c24b2ccb3964 (too long to put here).

My set up: 
- Raspberry Pi with Jessie.
- Radicale from apt-get packages.
- Nginx 1.10.1

**Comment by liZe** [comment]
Sorry for the delay, I've missed you ticket. Could you please post your gist again?

**Comment by liZe** [comment]
@captainepoch O captain my captain, are you there?

**Comment by captainepoch** [comment]
Hehe I'm still here :) 

I can't post it right now, I'm not at home. But a friend of mine and me think that the problem is I didn't installed OpenTasks on my phone.

**Comment by captainepoch** [comment]
I stopped using Radicale a few years ago in favor of another stack of software at a friend's server, cannot help with this issue.
