### ISSUE TITLE
Discovery of wrong collection

### ISSUE THREAD

**Issue by Unrud** [Kozea/Radicale#442]
``Collection.discover(path)`` returns the collection ``path`` if the directory exists. If it doesn't but the parent folder of ``path`` exists, it returns a collection of the parent folder. Otherwise it returns the collection ``path`` ignoring that the folder doesn't exist.

This leads to some problems:

  - Right checking is performed on the  first collection, that ``discover`` returns. If a user calls ``MKCOL /user``, the request is only granted if the user has write access to ``/``. (Supposed ``/user`` doesn't already exist)
  - If the collection ``/user`` exists and the user calls ``GET /user/does_not_exist``, the server correctly replies with 404 but if the collection ``/user`` does not exist, ``discover`` returns an empty dummy collection.

**Comment by liZe** [comment]
Closed by #459.
