### ISSUE TITLE
Fails to expose records to DAV client 

### ISSUE THREAD

**Issue by madduck** [Kozea/Radicale#446]
Trying to use a command-line DAV client (cadaver), it's not possible to PROPFIND any records on radicale. I can switch to the collection, but when I try to us `ls`, I am told that none of the records are found:

```
% cadaver https://caldav.madduck.net/madduck@madduck.net/addressbook.vcf/
Authentication required for Radicale on server `caldav.madduck.net':               
Username: madduck@madduck.net
Password: 
dav:/madduck@madduck.net/addressbook.vcf/> ls
Listing collection `/madduck@madduck.net/addressbook.vcf/': succeeded.
Error: urn:uuid:de3921a8-a55a-480e-869b-34c9d57bd8b8 404 Not Found
Error: urn:uuid:e6c6538c-a9fe-40e7-b32e-6d1d69ea5ec8 404 Not Found
[…]
```

I've tried removing the `UID` properties from the records on the server, but then I just get auto-generated IDs:

```
Error: eef33ca261cb4ab982c7f9ec8f47118e 404 Not Found
Error: ea71d4d0d8534d93a010e7f95bffefb7 404 Not Found
```

GET and PUT do seem to work fine. I am not entirely sure who's at fault here. radicale does seem to think it's doing everything right:

```
[pid: 29528|app: 0|req: 2661/3302] 91.45.206.90 (madduck@madduck.net) {44 vars in 645 bytes} [Thu Jul 14 13:53:56 2016] PROPFIND /madduck@madduck.net/addressbook.vcf/ => generated 346238 bytes in 474 msecs (HTTP/1.1 207) 3 headers in 132 bytes (3 switches on core 1)
```

**Comment by liZe** [comment]
@madduck Which version of Radicale do you have?

**Comment by madduck** [comment]
> @madduck Which version of Radicale do you have?

I am sorry for leaving out this vital information: 0.9-1+deb8u1 on
Debian stable.

-- 
The sender e-mail address used (reply.github.com@pobox.madduck.net)
is valid and specific to our correspondence. It should not indicate any
affiliation with your organisation.
 
Die verwendete E-mail-Adresse (reply.github.com@pobox.madduck.net)
ist gültig und spezifisch für unsere Korrespondenz. Sie soll in keiner Weise
auf eine Verbindung mit Ihrer Organisation hindeuten.
 
Spamtrap: reply.github.com.bogus@pobox.madduck.net

**Comment by liZe** [comment]
> I am sorry for leaving out this vital information: 0.9-1+deb8u1 on
> Debian stable.

Oh. Even Radicale 1.x isn't able to talk with cadaver, and 0.x versions are even worse. Fortunately, current `master` branch works quite well with WebDAV clients!
