### ISSUE TITLE
Log message on permission issue

### ISSUE THREAD

**Issue by tst2005** [Kozea/Radicale#447]
Hello,
Im using radicale + davdroid on android.

## Step 1 : a try without authentication
The sync was ok with
```
[auth]
type = None
```

## Step 2 : a try with simple authentication

```
[auth]
type = htpasswd
htpasswd_filename = /etc/radicale/users
```

From my client (DavDroid) debug log I read some `Internal Server Error` message coming from the server answer (radicale).

I found and fixed the issue : it was a permission issue.
But I spent lot of time before thinking about something so easy...

The `/etc/radicale/users` was not readable from my radicale user.

## My feature request

Could you please show a warning message in logfile in case of unreadable htpasswd_filename ?

Thanks!

**Comment by agent4** [comment]
Hello,

I'm sorry to disturb you but I am stuck with this same error. Can you just explain a little bit to a beginner user how to solve this problem and to "make readable from my radicale user etc/radicale/users" ??

Thanks ;)
