### ISSUE TITLE
Midding header section in INITIAL_CONFIG

### ISSUE THREAD

**Issue by buxx** [Kozea/Radicale#448]
I can't found ``header`` section in ``INITIAL_CONFIG`` (/radicale/config.py) as we can found it in **/config** file. Is it voluntary ?

**Comment by liZe** [comment]
Yes, as there's no need for additionnal headers in the default configuration, adding a `header` section in `config.py` would be useless.

**Comment by buxx** [comment]
Okay, thank's !
