### ISSUE TITLE
iCal 8.x Unable to add an account

### ISSUE THREAD

**Issue by tonyxiao** [Kozea/Radicale#493]
In macOS 10.11 (El Cap) iCal version is now 8. 

Instructions for OS X now seems out of date - http://radicale.org/user_documentation/#idos-x
- Password is required. When I tried to enter a random password, it doesn't seem to work
- ical wants `server path` in addition to `server address`. Instruction doesn't say what to provide for this (Tried using setting for http://radicale.org/user_documentation/#idid13, but doesn't work either)

![image](https://cloud.githubusercontent.com/assets/696842/18035872/3058dd54-6d13-11e6-9f6c-12656493bd8a.png)

```
PROPFIND request at /calendars/user/ received
Request headers:
{'CONTENT_LENGTH': '127',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-us',
 'HTTP_BRIEF': 't',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_PREFER': 'return=minimal',
 'HTTP_USER_AGENT': 'Mac+OS+X/10.11.6 (15G31) CalendarAgent/361.2',
 'PATH_INFO': '/calendars/user/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '31.1.168.192.in-addr.arpa',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x103e2ea68>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=9>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
Sanitized path: /calendars/user/
Request content:
<?xml version="1.0" encoding="UTF-8"?>
<A:propfind xmlns:A="DAV:">
  <A:prop>
    <A:principal-URL/>
  </A:prop>
</A:propfind>
Answer status: 404 Not Found
```

**Comment by liZe** [comment]
> Instructions for OS X now seems out of date

That's true, they work with previous versions of iCal.

The newest versions of iCal work well with the current `master` branch. As far as I can remember, you don't have to set "Advanced" in the account type, it can automatically find your calendars or create one. So, installing the git version instead of 1.x is probably the easiest solution for you.

The password is always required in many clients, even if there's no authentication. You can safely put a random password.

**Comment by pbiering** [comment]
if reproducable with current version, please reopen
