### ISSUE TITLE
Can't delete a contact

### ISSUE THREAD

**Issue by florencebiree** [Kozea/Radicale#498]
I use Radicale on my Debian server, I use the 1.1.1 version packaged from Debian testing.

Radicale is mainly used to sync contacts between computers. Some users report to me that they cannot delete a contact, either in Thunderbird (Sogo connector) nor with Roundcube (carddav plugin).

I try to check my right file, then change to the owner_only policy to avoid a possible problem in my right file, but the problem is still here.

Here are my logs when trying to delete a contact:

> 2016-08-30 18:12:21,270 - INFO: DELETE request at /florian/adresses.vcf/FAF0641E-487A-460F-97DC-F4A525DECC5F.vcf received
> 2016-08-30 18:12:21,290 - DEBUG: Request headers:
> {'CONTENT_LENGTH': '0',
>  'CONTENT_TYPE': 'text/plain',
>  'GATEWAY_INTERFACE': 'CGI/1.1',
>  'HTTP_ACCEPT': '_/_; q=0.5, text/plain; q=0.8, text/html;level=3;',
>  'HTTP_AUTHORIZATION': 'Basic ZmxvcmlhbjpTU2EgbGVnb0xM',
>  'HTTP_CONNECTION': 'close',
>  'HTTP_HOST': 'localhost:8184',
>  'HTTP_USER_AGENT': 'RCM CardDAV plugin/1.0.0',
>  'PATH_INFO': '/florian/adresses.vcf/FAF0641E-487A-460F-97DC-F4A525DECC5F.vcf',
>  'QUERY_STRING': '',
>  'REMOTE_ADDR': '127.0.0.1',
>  'REMOTE_HOST': 'localhost',
>  'REQUEST_METHOD': 'DELETE',
>  'SCRIPT_NAME': '',
>  'SERVER_NAME': 'thefool.filyb.info',
>  'SERVER_PORT': '8184',
>  'SERVER_PROTOCOL': 'HTTP/1.0',
>  'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
>  'wsgi.errors': <open file '<stderr>', mode 'w' at 0xb75510d0>,
>  'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0xb6f8844c>,
>  'wsgi.input': <socket._fileobject object at 0xb6e4f22c>,
>  'wsgi.multiprocess': False,
>  'wsgi.multithread': True,
>  'wsgi.run_once': False,
>  'wsgi.url_scheme': 'http',
>  'wsgi.version': (1, 0)}
> 2016-08-30 18:12:21,327 - DEBUG: Sanitized path: /florian/adresses.vcf/FAF0641E-487A-460F-97DC-F4A525DECC5F.vcf
> 2016-08-30 18:12:21,328 - DEBUG: Connecting to IMAP server localhost:143.
> 2016-08-30 18:12:22,078 - DEBUG: Authenticated IMAP user florian via localhost.
> 2016-08-30 18:12:22,081 - DEBUG: Rights type 'owner_only'
> 2016-08-30 18:12:22,109 - DEBUG: Test if 'florian:florian/adresses.vcf' matches against '.+:^florian(/._)?$' from section 'rw'
> 2016-08-30 18:12:22,119 - DEBUG: Section 'rw' matches
> 2016-08-30 18:12:22,122 - DEBUG: florian has read access to collection florian/adresses.vcf/
> 2016-08-30 18:12:22,131 - DEBUG: Rights type 'owner_only'
> 2016-08-30 18:12:22,136 - DEBUG: Test if 'florian:florian/adresses.vcf' matches against '.+:^florian(/._)?$' from section 'rw'
> 2016-08-30 18:12:22,147 - DEBUG: Section 'rw' matches
> 2016-08-30 18:12:22,148 - DEBUG: florian has write access to collection florian/adresses.vcf/
> 2016-08-30 18:12:22,736 - DEBUG: Answer status: 404 Not Found

**Comment by pbiering** [comment]
if reproducable with current version, please reopen
