### ISSUE TITLE
Sandboxing radicale with systemd on Linux

### ISSUE THREAD

**Issue by stephane-martin** [Kozea/Radicale#511]
Hello,

A few hints to harden radicale on Linux with systemd.

I use radicale from git HEAD.
# base
- create a system user `radicale` and a system group `radicale`
- create a virtualenv in `/home/radicale/env_radicale`
- install radicale (with pip or setup.py) in the virtualenv
- create radicale config in `/etc/radicale/config`
- create logging config in `/etc/radicale/logging`
- chown them to radicale:radicale

For example `/etc/radicale/config. Notice`daemon=False`.

``` INI
[server]
hosts = 0.0.0.0:5232
daemon = False
max_connections = 40
max_content_length = 10000000
timeout = 10
ssl = False
dns_lookup = False
base_prefix = /
realm = Caldav

[encoding]
request = utf-8
stock = utf-8

[auth]
type = None

[rights]
type = owner_only

[storage]
type = multifilesystem
fsync = True
filesystem_folder = /home/radicale/collections

[logging]
config = /etc/radicale/logging
debug = False
full_environment = False
mask_passwords = True

[headers]
Access-Control-Allow-Origin = *
```
- create directory `var/log/radicale`. chown it to radicale:radicale
# systemd
- create a systemd service in `/etc/systemd/system/radicale.service`

``` INI
[Unit]
Description=Radicale server
After=network.target
Requires=network.target

[Service]
Type=simple
WorkingDirectory=/home/radicale
User=radicale
Group=radicale
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=full
ProtectHome=no
ReadOnlyDirectories=/home
ReadWriteDirectories=/home/radicale
ReadWriteDirectories=/var/log/radicale
ExecStart=/home/radicale/env_radicale/bin/radicale
NoNewPrivileges=yes

[Install]
WantedBy=multi-user.target
```
- enable systemd service: `systemctl enable radicale`
- launch the server: `systemctl start radicale`
# WSGI server and NGINX

You can also put a WGSI server and a HTTP server like nginx in front of the radicale service.

For example with WSGI waitress:
- install waitress in the virtualenv with `pip install waitress`
- create /home/radicale/serve.py with:

``` python
#!/home/radicale/env_radicale/bin/python

WSGI_PORT_NUMBER = 8080
NB_THREADS = 4
NGINX_IP_ADDRESS = "X.X.X.X"

import os
import waitress
from radicale import Application, config, log

configuration = config.load(paths=("/etc/radicale/config", ))
filename = os.path.expanduser(configuration.get("logging", "config"))
debug = configuration.getboolean("logging", "debug")
logger = log.start("radicale", filename, debug)

application = Application(configuration, logger)

waitress.serve(application, listen="*:{}".format(WSGI_PORT_NUMBER), ipv4=True, ipv6=False, threads=NB_THREADS, trusted_proxy=NGINX_IP_ADDRESS)
```

Then modify the systemd service to use serve.py: `ExecStart=/home/radicale/env_radicale/bin/python /home/radicale/serve.py` (and be sure to reload the service with `systemctl daemon-reload`)
# nginx

Proxy traffic from internet to the WSGI server. Something like: 

```
location = / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;
    proxy_pass http://IP_ADDRESS_OF_WGSI_SERVER:WSGI_PORT_NUMBER;
}
```

(Nginx/Apache may be better place than radicale to handle HTTPS termination and authentication).

**Comment by stephane-martin** [comment]
On MacOSX, there is no systemd of course.

Radicale should be ran using a launchd configuration (launchd being the service on macosx that takes care of daemons). I don't know enough to give a proper config, but at minimum radicale should use a specific system user and group. See: http://launchd.info/

```xml
<key>UserName</key>
<string>radicale_user</string>
<key>GroupName</key>
<string>radicale_group</string>
<key>InitGroups</key>
<true/> 
```

**Comment by daks** [comment]
nice, thanks :)

**Comment by Unrud** [comment]
The documentation contains an example for systemd.

**Comment by aimin73** [comment]
Hi @stephane-martin, thanks so much for the tutorial on hardening radicale, i just have some follow up questions.
Where you said:
> install radicale (with pip or setup.py) in the virtualenv
> create radicale config in /etc/radicale/config
> create logging config in /etc/radicale/logging

After installing radicale in a virtualenv, since its in a container, how does it 'see' the global configs of `/etc/radicale/config` and `/etc/radicale/logging` ?
Isnt `/home/radicale/env_radicale` supposed to be completely containerized?

Or did you mean to create an `etc` folder inside `/home/radicale/env_radicale` ?

Please help clarify this?

**Comment by return42** [comment]
Hi @aimin73, this tutorial is very old and there is a difference in installing from releases or from master branch.  For hardening you should place the WSGI application behind apache or nginx.  If you're familiar with, there is a bash-snippet of my scripts for such a installation (behind apache) https://github.com/return42/handsOn/blob/master/scripts/radicale.sh and if you understand german there is also a artiicle describing such an installation (from master) http://return42.github.io/handsOn/radicale/radicale_server.html

FWIW: there is no need for systemd units when you are using apache or any other wsgi capable HTTPS server.

**Comment by aimin73** [comment]
@return42 thank you for the info. I had a look and wondering if you installed in a virtualenv?
Is there ANY benefit to hardening when using virtualenv? (according to my previous questions)

Also, isnt it the same security or still be hardened if i use Nginx SSL termination + Reverse proxy?  Is WSGI really that much more secure?

**Comment by return42** [comment]
> Is there ANY benefit to hardening when using virtualenv?

Since I don not setup a dedicated proxy-server for radicale (what is here done with the systemd) I want to decouple system's python installation from the one I use for Apache WSGI application. It's more about robustness than security. I don't know if there is such more security when using a radicale proxy server .. IMO not that much .. I think using an Apache or nginx as a WSGI server (with SSL) should be secure enough .. At the end, it depends on your infrastructure and your needs .. for me; I try to hardening the whole HTTPS server as much as possible.
