### ISSUE TITLE
Upgrade to git dev branch and rights file

### ISSUE THREAD

**Issue by likeitneverwentaway** [Kozea/Radicale#514]
Hi, I installed Radicale with pip and was wondering how would I go about upgrading to a git branch, and then staying up to date with it.

Also in the rights file, how do I make the whole collection of an user public ? Like collection : ^user$ but that doesn't work.

Thanks for all your work on Radicale, it's an awesome piece of software!

Alexandre

**Comment by liZe** [comment]
> Hi, I installed Radicale with pip and was wondering how would I go about upgrading to a git branch, and then staying up to date with it.

You'll find [different solutions on StackOverflow](http://stackoverflow.com/questions/20101834/pip-install-from-github-repo-branch).

> Also in the rights file, how do I make the whole collection of an user public ? Like collection : ^user$ but that doesn't work.

I think that you want `collection:user(/.*)?`, as it's done in [`rights.py`](https://github.com/Kozea/Radicale/blob/master/radicale/rights.py).

> Thanks for all your work on Radicale, it's an awesome piece of software!

You're welcome, sorry for the delay!
