### ISSUE TITLE
Systemd permission errors

### ISSUE THREAD

**Issue by mglinux** [Kozea/Radicale#524]
Hi!

I'm running latest radicale 1.11 and all is working fine while running in daemon mode. 

If I enable systemd service and radicale gets started with -f (foreground) I get several permission errors and can't access my files. 

Should't radicale work despite it's mode? Only radicale -d seems to work.

**Comment by liZe** [comment]
The permission errors probably happen because you don't launch Radicale with the same user. Could you check with `ps` for example?

**Comment by mglinux** [comment]
Well... I enabled and started the service: permission error. Disabled, enabled and started again: it's working. 

Strange because I already tried it several times. Until now all is ok.
