### ISSUE TITLE
Broken pipe 

### ISSUE THREAD

**Issue by svictor9** [Kozea/Radicale#525]
Hi,

And thanks for Radicale!

I have version 1.1.1 running on Debian testing. I use it for a small family setup where I sync two phones (with Davdroid) and one computer (with Thunderbird/Lightning).

I’m trying to debug an issue where the the sync works fine for a while, but after some time (maybe 10 minutes or so), the clients start to timeout on syncing.

When this happens `tail -F` on the logfile suggests that the server stops getting the sync requests. The file doesn’t move at all when I ask for a sync in the client. 

I disabled daemon mode in the config file, and launched radicale from the shell. There, after some time, I see the following error:
```
----------------------------------------
Exception happened during processing of request from ('37.163.245.111', 37231)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/usr/lib/python2.7/ssl.py", line 747, in sendall
    return socket.sendall(self, data, flags)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
----------------------------------------
```
If I leave the server running like this, the error is repeated several times. Does this ring a bell to you? How can I debug it further? 
For now, my only "solution" is to start and stop radicale from time to time.

**Comment by liZe** [comment]
Thanks for reporting.

This bug has been reported many times, the best issue to understand what's going on is #266. The future 2.x versions don't have this problem.

Short answer: putting Radicale between a solid HTTP server (nginx, Apache…) fixes the problem.

> And thanks for Radicale!

You're welcome!
