### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by MattyShires** [Kozea/Radicale#531]
I recently did a yum update on CentOS 7 and now radicale stops responding after around 20 minutes and has to be restarted, before the update it worked fine.
Nothing obvious is showing the log (/var/log/radicale/radicale.log), it just stops.
ps/top shows that it is still running and there seems to be no difference in the CPU/RAM usage.

Thunderbird gets the error "DAV_NOT_DAV" and using a web browser to access the URL results in a timeout error.

Radicale version: 1.1.1, installed from the EPEL repository.

Getting it working again is critical as we are a small business with 40 employees.

**Comment by liZe** [comment]
Thanks for reporting.

This bug has been reported many times, the best issue to understand what's going on is #266. The future 2.x versions don't have this problem.

Short answer: putting Radicale between a solid HTTP server (nginx, Apache…) fixes the problem.
