### ISSUE TITLE
PAM authentication : no module found

### ISSUE THREAD

**Issue by julpec** [Kozea/Radicale#534]
Hello
Trying to make radicale working on debian jessie, I wanted to authenticate throught PAM, so I have put this in the conf file : 

    # Authentication method
    # Value: None | htpasswd | IMAP | LDAP | PAM | courier | http | remote_user | custom
    type = PAM

  After that, I have installed python-pam but I have this after `radicale --debug` : 

    File "/usr/lib/python2.7/dist-packages/radicale/auth/PAM.py", line 27, in <module>
       import pam
    ImportError: No module named pam

Thanks for helping

**Comment by liZe** [comment]
The PAM module needs the python-pam module as explained in [the documentation](http://radicale.org/user_documentation/#idpam-authentication) :wink:.

**Comment by julpec** [comment]
Hello
That's it ! In my first message, I said that I have installed python-pam.
So, is it possible to re-open the issue because it's exactly the problem ?
Thanks for helping

**Comment by julpec** [comment]
Ok, I found the problem.

Radicale does not work with the python-pam Debian package. Python-pam 1.8.2 must be manually installed.

**Comment by julpec** [comment]
Just to precise for others, I have just installed python-pam with this command : 

`pip install python-pam`
