### ISSUE TITLE
Radicale should add UIDs to conctacts

### ISSUE THREAD

**Issue by detrout** [Kozea/Radicale#537]
Hi,

We were wondering should Radicale make sure that contacts have a UID?

I had a strange problem with contacts running Evolution, Empathy, and libfolks. 
https://bugzilla.gnome.org/show_bug.cgi?id=773011 that would've been avoided if contacts had a UID

It eventually turned out that Evoluton & libfolks were assuming contacts should have UIDs, and behaving very badly when many contacts lacked UIDs.

I worked around the problems being caused to my desktop by manually adding UIDs to all my contacts, and to save others from the problematic behavior the libfolks developer added code to ignoring contacts without UIDs.

I'm currently syncing contacts to Radicale 0.9-1+deb8u1 using DavDroid 1.3.4-ose on my phone and Evolution 3.22.1-2 over WebDav on my laptop.

**Comment by pbiering** [comment]
At least upcoming Radicale 2.x with multi-filesystem storage has an UID per VCARD, which is reflecting the unique name of the VCARD file in the multi-filesystem:

e.g.
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Inverse inc.//SOGo Connector 1.0//EN
UID:C74C4F91-D630-0001-721B-***.vcf
EMAIL;TYPE=work:****
FN:***
N:;***
X-MOZILLA-HTML:FALSE
END:VCARD
```

**Comment by detrout** [comment]
Ok. So it add a UID if whatever created the VCARD didn't set one?

**Comment by pbiering** [comment]
Hmm, according to the code (storage.py) there is no magic currently which creates an UID in case a client has not defined one before uploading. According to RFC UID is "may exists". Perhaps it would make sense to add an UID by the server if missing by client during storage. Let's wait for comments here from maintainers.

**Comment by liZe** [comment]
> Hmm, according to the code (storage.py) there is no magic currently which creates an UID in case a client has not defined one before uploading

That's right.

> According to RFC UID is "may exists". Perhaps it would make sense to add an UID by the server if missing by client during storage. Let's wait for comments here from maintainers.

Adding server-side data and playing with missing UIDs is generally a bad idea, it has caused many bugs before and I'd prefer stay as stupid as possible here. The bug was definitely in Evolution, and as Radicale now tries to avoid workarounds, I think that it's better to keep events and contacts with no UID.

**Comment by rfc2822** [comment]
UID is a "may have" for VCards, but not for CardDAV: [vCard components in an address book collection MUST have a UID property value that MUST be unique in the scope of the address book collection in which it is contained.](https://tools.ietf.org/html/rfc6352#section-5.1)

**Comment by detrout** [comment]
It was indeed contacts without UIDs that was confusing evolution / libfolks.

**Comment by Unrud** [comment]
> vCard components in an address book collection MUST have a UID property value that MUST be unique in the scope of the address book collection in which it is contained.

Instead of adding UIDs to VCards it may be better to reject them in the PUT request. If the user has manually added VCards without UIDs in the filesystem, a useful error message should be shown.

**Comment by detrout** [comment]
That would work too, as long as there was an actual error message from somewhere. This was pretty old data that was migrated from some ancient vcard format

**Comment by Unrud** [comment]
The development version shows the following error messages:

For PUT requests by clients:

    [7fd6828b8700] WARNING: Bad PUT request on '/user/046da7bc-de68-9fe2-b3ad-c94b0a88c339/invalid.ics': UID in VTODO is missing

If the invalid data is already in the storage:

    [7fd6828b8700] ERROR: An exception occurred during request: Failed to parse item 'invalid.ics' from 'user/046da7bc-de68-9fe2-b3ad-c94b0a88c339': UID in VTODO is missing
