### ISSUE TITLE
Need better documentation on the rights file.

### ISSUE THREAD

**Issue by TheBlackViper1996** [Kozea/Radicale#538]
There is no documented way of specifying a particular user to have write access to another user's calendar, i.e. a multi-user calendar.

**Comment by pbiering** [comment]
I solved this by having multi-user calendars outside of the user directory and soft-linked the directory into user's directory (having multi-filesystem setup, which is for concurrent access better anyhow).

```
ls -l username1/ | cut -c 51-
groupA.ics -> ../groups/groupA.ics
groupA.vcf -> ../groups/groupA.vcf
username1.ics
username1.vcf
```

```
ls -l username2/ | cut -c 51-
groupA.ics -> ../groups/groupA.ics
groupA.vcf -> ../groups/groupA.vcf
username2.ics
username2.vcf
```

**Comment by barnabas-szekeres** [comment]
+1

I have related question: Does reflect rights management file also for addressbook or only for calendars? I didn't find information about this in the documentation :(

**Comment by pbiering** [comment]
from server point of view calendars are equal to addressbooks only single files or directories (depending on choosen "filesystem" mode). Usually "rights" pattern are per folder containing the files or directories (or softlinks as shown above). For a mixed behavior, one has to play around with the collection patterns in "right" file and define e.g. softlinked group calendars/addressbooks as read-only (hopefully, this is supported by the rights implentation so far, means the most specific wins).
