### ISSUE TITLE
Rights management: 'authenticated' type right doesn't reflect for Apple Contacts 

### ISSUE THREAD

**Issue by barnabas-szekeres** [Kozea/Radicale#543]
Hi guys!

Expected behaviour:
If I have two user with carddav collection, User 1 see User 2's contacts and User 2 also see User 1's contacts.  So every authenticated user can read and write all collection.

What is really happen: 
- User 1 only see own collection
- User 2 only see own collection

I don't know this is a radicale issue or may just a Contacts bug/issue. Anybody has an information about this?

**Comment by liZe** [comment]
Hi!

Radicale probably only advertises about the users collection, not about the other ones. I don't really know Apple Contacts, but there's probably a way to add an address book from an URL.

Could any Apple user help us?

**Comment by Unrud** [comment]
It's the expected behavior, sharing collections like this is not supported. The rights management is only useful if you access collections by URL.
