### ISSUE TITLE
"Radicale works!" not appearing -- no go  :-(

### ISSUE THREAD

**Issue by SubitoPiano** [Kozea/Radicale#544]
Hi! I hope this is the right place for posting this issue. I installed and configured Radicale according to http://jonathantutorial.blogspot.com/2014/10/how-to-set-up-radicale.html. I login in to https:localhost:5232, whereupon I am asked for my username and password. Apparently I am aallowed to log in, as there is nothing to indicate an incorrect login; but I get no "Radicae works!" greeting. Of course I can't publish or subscribe o any calendars.

I noted three others with this problem who have posted the issue elsewhere on the web but no one has responded. I assume that is representative of many more potential users of Radicale.

Ideas appreciated!

Using Puppy Linux, Tahr version (for those not familiar with Puppy, it's an independent distribution not based on Ubuntu but created to utilize Ubuntu packages).

Thanks.

**Comment by liZe** [comment]
Hi!

You can try first to launch Radicale with the default configuration, and see if it works. After that, you can try to add some configuration from your link, launch Radicale with the `--debug` option and see if it helps.

**Comment by pbiering** [comment]
closed as related to really old verison, please reopen if reproducable with current version
