### ISSUE TITLE
Radicale sandstorm distribution not showing password

### ISSUE THREAD

**Issue by traverseda** [Kozea/Radicale#545]
https://oasis.sandstorm.io/shared/V7x7SDS7pPQWWltOdbevZfHJTNhE_u8lykxbRTUs1sd

Clicking the "sync" button shows user sandstorm, but not password.

**Comment by liZe** [comment]
Hello,

I don't know anything about sandstorm. Could you please explain how we could help you?

**Comment by traverseda** [comment]
It should be the responsibility of @synchrone, and as I understand it they shouldn't have been able to package it for sandstorm.io without permission.

This is an issue with radicale's interactions with sandstorm, and probably requires expert knowledge of sandstorm to sort it out.

I'd encourage someone from this organization to get it removed from the sandstrom app store if you don't have the expertise to maintain it for sandstorm. But hopefully @synchrone and sort it out.

The policy of not allowing third-party maintainers to maintain software for sandstorm was implemented for just this reason, I thought.

**Comment by traverseda** [comment]
Apologies for posting it here. If I had of realized that it was a third-party packager I would have bugged them.

**Comment by liZe** [comment]
No problem!

**Comment by synchrone** [comment]
@traverseda there is a link to the source code on sandstorm app market page, which leads to https://github.com/synchrone/sandstorm-radicale. 
Feel free to use github issues and report it there.
