### ISSUE TITLE
ConnectionResetError: [errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by febriyantoprasetya** [Kozea/Radicale#546]
Hi, is there anyone experienced the error "ConnectionResetError: [errno 104] Connection reset by peer"?

Im currently setup radicale server in my office and facing this problem.

My environment :
-Linux CentOS 6.8
-Apache/2.4.25 (Unix) OpenSSL/1.0.2j mod_wsgi/4.5.13 Python/3.4
-Radicale 1.1.1 (imap authentication)

and this is what i get from error_log : 

```
mod_wsgi (pid=3614): Exception occurred processing WSGI script '/usr/local/apache2/htdocs/radicale.wsgi'.
 Traceback (most recent call last):
   File "/usr/local/python34/lib/python3.4/site-packages/Radicale-1.1.1-py3.4.egg/radicale/__init__.py", line 306, in __call__
     is_authenticated = auth.is_authenticated(user, password)
   File "/usr/local/python34/lib/python3.4/site-packages/Radicale-1.1.1-py3.4.egg/radicale/auth/IMAP.py", line 56, in is_authenticated
     connection = imaplib.IMAP4_SSL(host=IMAP_SERVER, port=IMAP_SERVER_PORT)
   File "/usr/local/python34/lib/python3.4/imaplib.py", line 1222, in __init__
     IMAP4.__init__(self, host, port)
   File "/usr/local/python34/lib/python3.4/imaplib.py", line 182, in __init__
     self.open(host, port)
   File "/usr/local/python34/lib/python3.4/imaplib.py", line 1235, in open
     IMAP4.open(self, host, port)
   File "/usr/local/python34/lib/python3.4/imaplib.py", line 258, in open
     self.sock = self._create_socket()
   File "/usr/local/python34/lib/python3.4/imaplib.py", line 1227, in _create_socket
     server_hostname=self.host)
   File "/usr/local/python34/lib/python3.4/ssl.py", line 362, in wrap_socket
    _context=self)
   File "/usr/local/python34/lib/python3.4/ssl.py", line 580, in __init__
     self.do_handshake()
   File "/usr/local/python34/lib/python3.4/ssl.py", line 807, in do_handshake
     self._sslobj.do_handshake()
 ConnectionResetError: [Errno 104] Connection reset by peer
```

Very glad if someone could help solve this issue.

Thanks.

**Comment by liZe** [comment]
Hi!

Does your IMAP server have a correct SSL certificate? Your problem is probably related to this certificate.

You may find some help on [StackOverflow](http://stackoverflow.com/questions/15954467/python-ssl-example-from-docs-gives-connection-reset-by-peer-error).

**Comment by icanterbang** [comment]
I think this is because my mail server has 2 node in cluster.

**Comment by pbiering** [comment]
please reopen if still happen

**Comment by vanya-robertson** [comment]
I have recently started getting the same. I didn't change the config. SSL is done on a reverse proxy, so I have it disabled completely in radicale. I have set `ssl = False`. Since am running on OpenBSD, am using Radicale v2.1.12. My website and some other services use the same certificate, and that's all working just fine.

**Comment by pbiering** [comment]
> I have recently started getting the same. I didn't change the config. SSL is done on a reverse proxy, so I have it disabled completely in radicale. I have set `ssl = False`. Since am running on OpenBSD, am using Radicale v2.1.12. My website and some other services use the same certificate, and that's all working just fine.

The original issue was related using IMAP server as authentication backend, is your issue identical?

**Comment by vanya-robertson** [comment]
No, it is not.

**Comment by pbiering** [comment]
> No, it is not.

Then you have to diagnost further on and in worst case start a discussion thread.

See Wiki https://github.com/Kozea/Radicale/wiki/Server-Diagnostics---Troubleshooting and search also through closed issues. In case it is a server issue, 2.1.12 is very old and out-of-support, so you have to upgrade to latest 3.5.x version before filing an issue towards server side - client side issues anyhow cannot be supported.
