### ISSUE TITLE
Logging the requester IP

### ISSUE THREAD

**Issue by sorinsfirlogea** [Kozea/Radicale#547]
Hi,
I would like to use fail2ban to protect my Radicale server (running as a daemon on an Ubuntu box) from unauthorized authentication requests, but I need to log the IP of the requester and I cannot figure how. I tried using the %(ip)s interpolation value in the formatter section with no success.
Any idea? Thx.

**Comment by pbiering** [comment]
If using radicale <= 2.0 without my pull request (https://github.com/Kozea/Radicale/pull/526) you have to implement/migrate the logging in code by yourself.

2.0 with my PR logs like:

`2017-01-22 23:04:05,144 - [7f452ffff700] INFO: [95192ea] PROPFIND request  for /user/calendar.ics/ with depth 0 received from 2001:a61:**** using "MSFT-WIN-4/10.0.14393 (gzip)"`

(IPv6 enabled client and server here..)

In cases you have an Apache in front of you can watch the log here also.

**Comment by sorinsfirlogea** [comment]
I'm running version 1.1.1. And I am not good with Python so I would prefer to wait until you merge the pull request into the main branch. Is there a planned date for releasing version 2.0?

**Comment by liZe** [comment]
The pull request is merged, I'm trying to release a 2.0.0-beta as soon as possible!
