### ISSUE TITLE
Long running Requests with DavDroid > 1.2.3

### ISSUE THREAD

**Issue by nudgegoonies** [Kozea/Radicale#549]
Hi,
i use Radicale 1.1.1 on Debian without apache2 and htpasswd file. It works well with https. But with DavDroid Versions > 1.2.3 on Android i have problems with the connections. Synchronization is slow or fails. Especially when calendar, tasks and adressbook is synchronized at the same time. A parallel curl to Radicale is blocked. Is this a DavDroid Problem or a Radicale Problem? Because the curl blocks i first try here. Also when i only sync adressbook and nothing else and i check with "ss" tool on radicale machine i can see two connections from my Android phone. One is established and the second keeps in "FIN-WAIT-2" for a long time.
Kind regards,
Andreas

**Comment by liZe** [comment]
Thanks for your report!

Radicale 1.x can't safely reply to concurrent requests, even behind an HTTP server. There's no simple solution to fix that.

You can try to use the current master branch (2.0.0-pre) that is thread-safe, but read the [migration guide](http://kozea.github.io/Radicale/1to2/) first!

**Comment by nudgegoonies** [comment]
Thank you very much for your answer. I will try the 2.0.0 on a free weekend.
