### ISSUE TITLE
mailinglist site down

### ISSUE THREAD

**Issue by rlucassen2** [Kozea/Radicale#555]
Your request for http://librelist.com/browser/radicale could not be fulfilled, because the connection to librelist.com (71.19.156.177) could not be established

This has been for a few days AFAIK. And if it's gone, then there are broken links on radicale.org.

Richard

**Comment by liZe** [comment]
Yes, looks like librelist has been down for quite a long time now… Thanks!

**Comment by htgoebel** [comment]
http://librelist.com/browser/radicale is availiable
