### ISSUE TITLE
Radicale 1.1.x making lot of noise on a small system

### ISSUE THREAD

**Issue by rlucassen2** [Kozea/Radicale#556]
I run radicale on a small system and it is constantly in top of the process list and consumes quite a lot of memory on a small system. An strace shows:

    _newselect(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=50000}) = 0 (Timeout)
    gettimeofday({tv_sec=1488791965, tv_usec=67611}, NULL) = 0
    _newselect(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=21302}) = 0 (Timeout)
    gettimeofday({tv_sec=1488791965, tv_usec=89460}, NULL) = 0
    gettimeofday({tv_sec=1488791965, tv_usec=89841}, NULL) = 0
    gettimeofday({tv_sec=1488791965, tv_usec=90266}, NULL) = 0
    _newselect(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=1000}) = 0 (Timeout)

Why is it so busy? Wouldn't it be nice if radicale can be run from inetd or tcpserver?

Richard

**Comment by liZe** [comment]
That's strange. Do you have Radicale 1.1.x or the current master branch?

**Comment by rlucassen2** [comment]
I saw this behaviour with an old version (IIRC 0.9) and now I'm running 1.1.1+20160115-3 that comes with Debian Stretch. Now that I write this I see it's january 2016, or is it a typo?

R.

**Comment by rlucassen2** [comment]
I'll try the git version tomorrow, I thought the 1.1.1 was the latest.

To test: strace -p <pid of radicale>

R.

**Comment by liZe** [comment]
> Now that I write this I see it's january 2016, or is it a typo?

It's 2016, not a typo.

> I'll try the git version tomorrow, I thought the 1.1.1 was the latest.

1.1.1 is the latest, and there are looooooots of change in the current git repository (see #372). But you shouldn't have this problem with 1.1.1, if there's a problem it should be fixed ine 1.1.x too.

**Comment by rlucassen2** [comment]
Yep, the one from git is python3 and keeps quiet.

For googlers: in Debian Stretch It also needs python3-vobject package.

Richard.

**Comment by htgoebel** [comment]
@rlucassen2 If this is solved, please close the issue. I got irritated by this ticket, which is obviosuly outdated.
