### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by DeadSix27** [Kozea/Radicale#557]
`ImportError: No module named 'filesystem'`

`https://pypi.python.org/pypi/filesystem `seems to be outdated.

Same goes for database and sqlite support.

**Comment by liZe** [comment]
The `filesystem` storage module was included in Radicale, it's not the external module you're talking about.

The current master branch (pre 2.0.0) only supports the `multifilesystem` storage, that's not exactly the one that was included in 1.1.x.

More information about what's going on with 2.0.0 can be found in #372.

**Comment by DeadSix27** [comment]
@fjl Later on I found the multifilesystem storage ye, forgot to update this issue.
