### ISSUE TITLE
service not starting wit LDAP configured, without error

### ISSUE THREAD

**Issue by Metzlmane** [Kozea/Radicale#571]
I tried to use LDAP authentication and the server simply didn't start.
I only could see that with netstat -alt the port was not listed as LISTEN. All logs were set to DEBUG.
This helped
http://stackoverflow.com/a/4768467

I used Ubuntu Server 16.04 
Can you please somehow list which packages are needed to use LDAP-Auth?

Version: 1.1.1-1
Depends: python-radicale (= 1.1.1-1), python, adduser

**Comment by liZe** [comment]
Radicale needs a package called `python-ldap` on [Ubuntu 16.04](http://packages.ubuntu.com/xenial/radicale).

Could you please provide what's given by `radicale --foreground --debug`?

**Comment by liZe** [comment]
@Metzlmane Can I close this issue?

**Comment by Metzlmane** [comment]
Yes! Sorry, i totally forgot it.
Maybe you can add an error, if this is used but not installed?

**Comment by liZe** [comment]
> Maybe you can add an error, if this is used but not installed?

Authentication methods like LDAP have been removed from Radicale in the current git version, it may be available through an external plugin.

**Comment by dwhagar** [comment]
So this does not come with PAM or LDAP authentication?  Perhaps modify your config file so that it doesn't show them as options, that would be really - really - handy.  I just spent over an hour trying to get them to work.
