### ISSUE TITLE
Long lines and empty line in ics-file from Radicale server

### ISSUE THREAD

**Issue by nneuss** [Kozea/Radicale#572]
Hello, please forgive if I am asking something stupid or at the wrong place.  I have installed a Radicale server for talks at our math departments and tried to parse that file using another tool (a Common Lisp library called soiree).  When trying this library on the ics-file received from "http://cal.math.fau.de/kolloquium/calendar", it bails out at some points which may be due to nonconformance of Radicale:
1. There is an empty line in the file after a DESCRIPTION field. I do not know where this comes from, and if it is allowed at all in an ics-file.  (A remark at https://en.wikipedia.org/wiki/ICalendar reads as if it might be a problem: "Empty lines are not allowed in some versions of usage (Google calendar).")
2. There are lines longer than 75 characters which should not be allowed according to RFC5545, IIUC.
My solution at the moment is to preprocess the ics-file before handing it to that library.  But I would be interested which part of my toolchain (including myself:-) is to blame...

**Comment by liZe** [comment]
@nneuss hi!

The current git version of Radicale uses a real library to parse an generate ics files, this problem is now fixed. A stable release with this fix, called 2.0.0, will be released soon. You can follow #372 if you're interested in the changes in this version!
