### ISSUE TITLE
Issue with VALUE=DATE-TIME

### ISSUE THREAD

**Issue by cedricpim** [Kozea/Radicale#573]
First, let me thank you for the excellent work on radicale.

I am using radicale on the server and I am using khal and vdirsyncer locally (OS X). When I create an event on khal, it creates the event with the following: `DTSTART;VALUE=DATE-TIME:20170218T230000`. When I try to sync this event with radicale, it returns 500. Once I update the line to `DTSTART:20170218T230000`, everything goes fine.

I was doing a small research and seems like the issue might be from one of the python libraries but maybe there is a workaround or they can be updated (I am not from the python world, so please take this with a grain of salt).

Software versions:
radicale: 2.0.0rc0
khal: 0.9.3
vdirsyncer: 0.15.0

**Comment by Unrud** [comment]
This seems to be a bug in [vobject](http://eventable.github.io/vobject/). In general it supports ``DTSTART;VALUE=DATE-TIME:``, but fails when it occurs inside of ``VTIMEZONE``.

**Comment by cedricpim** [comment]
So my research was not that bad. Any idea if we can improve radicale to handle such scenario? My version of vboject is `vobject (0.9.3)`.

**Comment by Unrud** [comment]
> Any idea if we can improve radicale to handle such scenario?

Report the bug to [vobject](https://github.com/eventable/vobject). (It uses [dateutil](https://github.com/dateutil/dateutil) to parse VTIMEZONE.)

**Comment by cedricpim** [comment]
Ok, closing this issue then, since the problem belongs somewhere else :+1:
