### ISSUE TITLE
"A server error occurred. Please contact the administrator" if collections is a file

### ISSUE THREAD

**Issue by unhammer** [Kozea/Radicale#575]
When I installed this on raspbian (jessie), for some reason /var/lib/radicale/collections ended up being a file, not a directory. I could get https://localhost:5232/foo (returned an empty ical file), but not subdirs https://localhost:5232/user/foo/calendar.ics/ etc.

Deleting  /var/lib/radicale/collections fixed the issue.

The logs, however, were not at all helpful, seeming like the request had gone by correctly. Radicale should perhaps check that the file is a directory?

**Comment by liZe** [comment]
I suppose that you're using the current stable version, this behaviour is supposed to be fixed in 2.0.0rc1. If you're interested in testing this version, you can follow the [1to2 migration guide](http://kozea.github.io/Radicale/1to2/) and tell us if it fixed your problem.

**Comment by Unrud** [comment]
Radicale 2.0.0 was released and the development version has nicer error messages for situations like this.
