### ISSUE TITLE
Backport 2.x changes in an branch compatible with Python 2

### ISSUE THREAD

**Issue by canDry** [Kozea/Radicale#578]
Or... perhaps someone's fork of 1.1.1 are keeping up-to-date with fixes that are being applied to the V2RC?

**Comment by liZe** [comment]
Python 3.0 has been released more than 8 years ago and Python 2 will not be maintained past 2020, so there's no "official" plan to backport changes of 2.0.0 in 1.1.1.

If someone is interested in this journey, I'll be happy to merge pull requests in the 1.1.x branch.

**Comment by canDry** [comment]
Closing.  I've seen the light.
