### ISSUE TITLE
New addressbook creates empty vcards (Radicale 2rc1)

### ISSUE THREAD

**Issue by steve-ks** [Kozea/Radicale#579]
Hi there,
I am currently working on the master branch as I just tried to switch from the active v1.1.1 branch. I am working with an armhf debian8 system. After being able to somehow configure the Radicale server I am finally able to connect to old addressbooks as well as creating new ones, though there are still problems. 

While working with v1.1.1 we also had a multifile-system, having all files in `/etc/radicale/collections`. With version 2 I set the filesystem-path to `/etc/radicale` making it effectively `/etc/radicale/collection-root`.

**Regarding the main problem**
When creating a new addressbook using `https://radicale-server:5232/admin/addressbook.vcf` as host address, the path in the filesystem is created as soon as I create a contact entry, yet instead of a vcard a directory with the cvard-filename is created. Refreshing my addressbook client leads to an empty addressbook. As soon as I copy an old vcard file (or create one by hand) and remove the directory vcards - which are empty anyways, thus the server tells me there are none - the server acts correctly when adding new contacts. Then vcards are created not as directories but as files. Removing then the vcards from the directory forcing it to be empty, refreshing the client and finally adding new contacts result in vcard files and everything works normalle. Seems to be an initial wrong behaviour when creating new addressbooks.

Here is also a filestructure tree for an old addressbook and a new addressbook creating empty directory vcards as long as no real vcard has been stored (admin is the test-user, when running the directory is also named admin/addressbook.vcf):

```
[dir] collection-root
  ├── [dir] admin-new   (wrong behaviour)
  │     └── [dir] addressbook.vcf
  │           └── [dir] BBC5FB0A-9BC8E860-203FFF6E.vcf
  └── [dir] admin-old   (correct behaviour)
        └── [dir] addressbook.vcf
              └── [file] BA0E3F8D-05AB602D-630FE618.vcf
```

From my point of view this is a bug.

Greetings,
Steve

_**Further information**
Using SSL & htpasswd authentication, works correctly.
Rights are set to authenticated.
Used client software: Evolution 3.18.5.2 running on ubuntu xenial, gnome desktop
Other client testing software: Thunderbird from different machines_

**Comment by Unrud** [comment]
> From my point of view this is a bug.

It's not a bug, the addressbook is not created correctly.

Evolution and Thunderbird do not support creating new addressbooks/calendars via WebDAV, you can only add already existing addressbooks/calendars to them. You have to use a client that supports creating of addressbooks/calendars.

I made a web interface for exactly this purpose: https://github.com/Unrud/RadicaleWeb

**Comment by steve-ks** [comment]
Thanks for the reply, very good to know.

For your interface, I already have seen it yet it does not meet my needs. I am currently creating collections using curl for a simple creation (I am connecting to radicale using different programms as well as own software). The vcard-filesystem problem remains but I can somehow handle it by creating the addressbook only when needed and adding directly the vcard to the filesystem. 

At least the MKCOL command for creating calendars works flawlessly.

**Comment by Unrud** [comment]
> At least the MKCOL command for creating calendars works flawlessly.

You have to send a body for that request. (``curl -X MKCOL --data @body.xml ...``)
If the body is missing Radicale will use default values for creating a calendar.

For calendars:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<create xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:I="http://apple.com/ns/ical/">
  <set>
    <prop>
      <resourcetype>
        <collection />
        <C:calendar />
      </resourcetype>
      <C:supported-calendar-component-set>
        <C:comp name="VEVENT" />
        <C:comp name="VJOURNAL" />
        <C:comp name="VTODO" />
      </C:supported-calendar-component-set>
      <displayname></displayname>
      <C:calendar-description></C:calendar-description>
      <I:calendar-color></I:calendar-color>
    </prop>
  </set>
</create>
```

For address books:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<create xmlns="DAV:" xmlns:CR="urn:ietf:params:xml:ns:carddav" xmlns:INF="http://inf-it.com/ns/ab/">
  <set>
    <prop>
      <resourcetype>
        <collection />
        <CR:addressbook />
      </resourcetype>
      <displayname></displayname>
      <CR:addressbook-description></CR:addressbook-description>
      <INF:addressbook-color></INF:addressbook-color>
    </prop>
  </set>
</create>
```

The values for ``displayname``, ``description`` and ``color`` are left blank in the example requests, you can change them to something meaningful.

**Comment by steve-ks** [comment]
Many thanks for the MKCOL xml packages! I am already using similar packages and found a minor mistake in the xml data I've used for address books. Now that works also. The xml data I use is similar to yours, so I will update mine thanks to your examples. 

Using a proper MKCOL body makes radicale work as expected now! Thanks for the help :)

I will close the issue here as with using curl my problem is solved.
