### ISSUE TITLE
Wrapper script around transplant.py (for packagers and beginners)

### ISSUE THREAD

**Issue by szotsaki** [Kozea/Radicale#580]
Could you please create a short Python script which does the few basic [migration steps](https://kozea.github.io/Radicale/1to2/) (temporarily comment out config lines, launch Radicale 2 and migrate data with transplant.py).

The migration script could accept some command line arguments which are distro-specific, like how to start/stop Radicale 1, or where is the initial config file.

When upgrading from Radicale 1 package it's necessary to run something like this after the package installation has finished, but I think it'd be useful for non-experienced users as well.

**Comment by Unrud** [comment]
The migration method was improved. You don't need `transplant.py` anymore. Update to Radicale 1.1.3 and start it like you would normally do, but add the ``--export-storage FOLDER`` command line argument.
