### ISSUE TITLE
Open a forum for Radicale

### ISSUE THREAD

**Issue by vlapla** [Kozea/Radicale#583]
I think Radicale users, and maybe also the developers, would benefit from a discussion forum. LEDE has a [nice forum](https://forum.lede-project.org/), using [Discourse](http://www.discourse.org/). A Radicale mailing list was mentioned in #555 ...and I don't know its history - but a forum is slightly different anyway. I appreciate the offer to contribute to documentation using the github Wiki, but this wiki does not offer discussion pages (like Wikipedia), and it feels awkward to share personal configurations there. With [Server Configuration / Sharing Calendars](https://github.com/Kozea/Radicale/wiki/Sharing-Calendars) I now did it anyway, hoping this can be useful to some.

**Comment by sconeyard** [comment]
I'd volunteer to set up a discourse instance on a VPS. I think it would be really helpful to have a discussion board. Could someone please tell me whom to contact about this?

**Comment by htgoebel** [comment]
Alternatively athttp://www.nabble.com/ you can have a mailinglist which can be used as a forum, too. Easy to set-up and probably less data hungry then Discource.

**Comment by sconeyard** [comment]
I'd prefer the discourse variant because it is much nicer for Google to index. This way people could just google for "Radicale Multi-User Setup" and may find the discourse thread on it. I don't know nabble but searching in mailing lists is often just awful.

**Comment by htgoebel** [comment]
> discourse … is much nicer for Google to index … I don't know nabble.

If you don't know nabble, how can you tell?

discourse is [funded](https://de.wikipedia.org/wiki/Discourse_(Software)#Geschichte) by e.g. [Greylock Partners](https://de.wikipedia.org/wiki/Greylock_Partners), who also funded Facebook, Linkedin, and Instagram. All of these businesses are build on collection data about people and selling profiles about people. Further the discourse website
- shows an empty page using a current torbrowser
- includes fonts from google, which means, google will track all your movements on the discourse website
all of this is not meant to establish trust that discourse is respecting privacy.

**Comment by sconeyard** [comment]
I don't care who funds Discourse, the company. I am talking about hosting Discourse, the open source software. Changing fonts in css boils down to 2 lines of code.

**Comment by lenneis** [comment]
Interesting. I just had the same thought when I saw that the 2.0 release is out, had several issues with it and was looking for a place for finding out stuff about 2.0 from discussions and people talking, which also helps fill the gaps in the documentation. An issue queue is just not enough for that. I am also willing to offer server ressources for that kind of setup (board, mailing list, whatever).

**Comment by tr37ion** [comment]
@sconeyard Sounds like ignorance to me. 

Anyways, I don't see any need to make @Kozea's life more difficult. Radicale has a nice [website](http://radicale.org/) a good [documentation](http://radicale.org/documentation/) and already a [Wiki page](https://github.com/Kozea/Radicale/wiki) which everyone can edit.

Additionally, everyone can open an [issue](https://github.com/Kozea/Radicale/issues/) if problems occur. You can contribute code and for having a realtime chat Radicale already offers an IRC channel [##kozea](irc://freenode.net).

Personally, I don't see any benefit form having a forum (which has to be maintained and moderated) for this kind of server software.

Install it - use it - contribute.

**Comment by sconeyard** [comment]
@tr37ion No its not ignorance, I just think the argumentation is dumb. You don't stop using Linux because someone from a large company backed by someone you don't like contributed. Same goes for every OS project. 

Regarding the forum: You may be right and github could be enough.

**Comment by rogue-ronin** [comment]
I logged in just to support this.  I've been struggling with radicale for a long time now.  I'm as close as I've ever been, and was hoping to find a forum to read and learn from.  They're great for that, because you can follow the thinking and discovery.  And when you have to use the older stuff for some reason (distros mostly) no one that's this close to the development side wants to discuss it, for good reason -- they're too busy improving things to go back in time with you.

Anyhow, forum please, or subreddit or something, that gets at least visited occasionally, if only to be read, by coders?

**Comment by pbiering** [comment]
Github "Discussions" are now enabled.
