### ISSUE TITLE
1.1.2 not available on pypi

### ISSUE THREAD

**Issue by gramakri** [Kozea/Radicale#584]
The previous releases were available at pypi like `http://pypi.python.org/packages/source/R/Radicale/Radicale-1.1.1.tar.gz` but not 1.1.2. Is that intentional?

**Comment by liZe** [comment]
Radicale 1.1.2 is available on PyPI: https://pypi.python.org/pypi/Radicale. I don't know why the URL doesn't work when you change 1.1.1 into 1.1.2.

**Comment by gramakri** [comment]
@liZe Thanks. Also, 1.1.2 is not listed here - http://radicale.org/download/

**Comment by liZe** [comment]
It's been added, thank you.

([Holy WTF???](https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package))

**Comment by gramakri** [comment]
Ah, thanks for the pypi issue. I hit that because we rely on it in the [Cloudron radicale](https://git.cloudron.io/cloudron/radicale-app) app.
