### ISSUE TITLE
HEAD requests

### ISSUE THREAD

**Issue by doctormo** [Kozea/Radicale#590]
When using webdav-client python module, it makes HEAD requests to check if a resource exists. radicale responds with error 507:

```
Traceback (most recent call last):
  File "./radicale/__init__.py", line 332, in __call__
    user)
  File "./radicale/__init__.py", line 456, in do_HEAD
    status, headers, answer = self.get(
AttributeError: 'Application' object has no attribute 'get'
```

If the server does respond to GET requests, if should probably respond to HEAD requests too.

**Comment by liZe** [comment]
This issue is both fixed in [1.1.2](https://github.com/Kozea/Radicale/blob/1.1.2/radicale/__init__.py#L453) and [current master](https://github.com/Kozea/Radicale/blob/master/radicale/__init__.py#L508).
