### ISSUE TITLE
Config file is missing

### ISSUE THREAD

**Issue by dannycolin89** [Kozea/Radicale#592]
When I install Radicale with PIP, the config file doesn't seem to be created. I don't have that problem if I install it with my package manager. I'm on Ubuntu 16.04.2.

**Comment by htgoebel** [comment]
pip is a packet manager for python packages, not for system packages. pip has no notion about where to put config-files, how to start programs at boot time, etc. Such kind of things is out of scope for pip.

**Comment by liZe** [comment]
@htgoebel is right, you have to create your configuration file, pip won't install it for you. The way configuration files are created and updated is managed by your distribution / your OS / you, not by the package manager. It's not a bug of pip, it's a feature :wink:.

**Comment by dannycolin89** [comment]
Oh I didn't kown that. Thanks for the answer :)
