### ISSUE TITLE
Seeking example for simple mulit-user setup

### ISSUE THREAD

**Issue by htgoebel** [Kozea/Radicale#596]
I'm seeking an example for a simple mutli-user set-up. The example should include the `rights` and (even more important), the directory/collections structure.

* Two users
* address-books are private
* calendars are readable by the other user
* a common calendar (read-only) e.g. for public holidays

I tried using this directory structure, but did not get it to work:
```
user1/cal
user1/priv 
user2/cal
user2/priv
shared/holidays
```

I'm using DAVdroid as client, which is seeking like this:
```
PROPFIND for / with depth 0 : 401 Unauthorized
PROPFIND for / with depth 0 : 207 Unknown
OPTIONS for /user1/ : 200 OK
PROPFIND for / with depth 0 : 207 Unknown
OPTIONS for /user1/ : 200 OK
PROPFIND /user1/ with depth 0 : 404 Not Found
```

It does not find any other user's resources. I also tried a flat structure (e.g. `user1_cal`), but this does not work either.

**Comment by Unrud** [comment]
Sharing calendars is not supported. You can grant other users access to a calendar with a custom rights file but it's only useful if you access them directly via a URL. Clients like DAVdroid will only detect calendars/address books that are in the folder of the user.

If you feel adventurous you can use symlinks to share calendars or the ``hook`` configuration option to copy calendars from one use to another (when they change).

**Comment by htgoebel** [comment]
> If you feel adventurous you can use symlinks to share calendars

This would be an options. What would be the "adventurous" part of this?

**Comment by Unrud** [comment]
> What would be the "adventurous" part of this?

It has some drawbacks. If you change metadata of the calendar like the displayname or color, it changes for everyone. Reminders/Alarms in a calendar are for everyone, you can't turn them on or off per user.
If the collection is read-only you obviously can't change the above at all.

**Comment by Unrud** [comment]
I close this, because it's not a supported feature. The documentation states, that the `rights` file is only useful if collections are accessed directly by URL.
