### ISSUE TITLE
Gracefully handle offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by htgoebel** [Kozea/Radicale#602]
Syncing a calendar containing old data crashed the server with this error message:
```
if until and res > until:
TypeError: can't compare offset-naive and offset-aware datetimes
```

The server should be able to handle this error case: The value without offset should be given an offset. Per default this offset could be the server's locale offset (an config option could be added later).

**Comment by htgoebel** [comment]
FYI: I implemented an regression test for this and am working on a solution, pull-request to come.

**Comment by htgoebel** [comment]
Reported upstream: https://github.com/eventable/vobject/issues/75

**Comment by Unrud** [comment]
I implemented a workaround for this bug in VObject, the items get included and a WARNING message is printed.

**Comment by htgoebel** [comment]
This issue has been solved in vobject, see https://github.com/eventable/vobject/pull/76#event-1133176617.

**Comment by Unrud** [comment]
Thank you for fixing it.

**Comment by mortlind** [comment]
I am on Debian and my radicale 2.1.5 installation using python3-vobject v. 0.9.5-1 still has these issues. Any good explanations?

**Comment by Unrud** [comment]
> Any good explanations?

Can you provide an example file?

**Comment by mortlind** [comment]
@Unrud I think this may be Korganizer/Akonadi specific, which is the client I use against my Radicale installation. I get the following error in the `radicale.log` when trying to import a specific calendar. The problem is that I do not know how to find the particular VEVENT which causes it. I can try isolating it the painfull way, unless you have a good suggestion?
```
2017-10-05 21:28:30,683 - [-49a254c0] WARNING: Bad PUT request on '/ml/1127ea0a-1d1c-ccdf-2263-f9deca5e0000/1507231709.R724.ics': Fa
iled to store item '1507231709.R724.ics' in collection 'ml/1127ea0a-1d1c-ccdf-2263-f9deca5e0000': can't compare offset-naive and off
set-aware datetimes
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1415, in upload
    href, vobject_item)
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1244, in _store_item_cache
    content = self._item_cache_content(href, vobject_item, cache_hash)
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1238, in _item_cache_content
    tag, start, end = xmlutils.find_tag_and_time_range(vobject_item)
  File "/usr/lib/python3/dist-packages/radicale/xmlutils.py", line 638, in find_tag_and_time_range
    _visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/usr/lib/python3/dist-packages/radicale/xmlutils.py", line 343, in _visit_time_ranges
    for dtstart in dtstarts:
  File "/usr/lib/python3/dist-packages/dateutil/rrule.py", line 1375, in _iter
    while exlist and exlist[0] < ritem:
  File "/usr/lib/python3/dist-packages/dateutil/rrule.py", line 1312, in __lt__
    return self.dt < other.dt
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by Unrud** [comment]
> The problem is that I do not know how to find the particular VEVENT which causes it.

The log contains the content of the VEVENT. Just check the debug messages before the warning message.

**Comment by mortlind** [comment]
Of course! Here you go:
```
2017-10-03 13:27:02,408 - [-49ac94c0] DEBUG: Request content:
BEGIN:VCALENDAR
PRODID:-//K Desktop Environment//NONSGML libkcal 4.3//EN
VERSION:2.0
X-KDE-ICAL-IMPLEMENTATION-VERSION:1.0
BEGIN:VTIMEZONE
TZID:Europe/Oslo
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0043
TZOFFSETTO:+0100
DTSTART:19011213T212852
RDATE;VALUE=DATE-TIME:19011213T212852
END:STANDARD
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19160522T010000
RDATE;VALUE=DATE-TIME:19160522T010000
RDATE;VALUE=DATE-TIME:19400810T230000
RDATE;VALUE=DATE-TIME:19430329T020000
RDATE;VALUE=DATE-TIME:19440403T020000
RDATE;VALUE=DATE-TIME:19450402T020000
RDATE;VALUE=DATE-TIME:19590315T020000
RDATE;VALUE=DATE-TIME:19600320T020000
RDATE;VALUE=DATE-TIME:19610319T020000
RDATE;VALUE=DATE-TIME:19620318T020000
RDATE;VALUE=DATE-TIME:19630317T020000
RDATE;VALUE=DATE-TIME:19640315T020000
RDATE;VALUE=DATE-TIME:19650425T020000
RDATE;VALUE=DATE-TIME:19800406T020000
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19800928T030000
RRULE:FREQ=YEARLY;COUNT=16;BYDAY=-1SU;BYMONTH=9
END:STANDARD
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19160930T000000
RDATE;VALUE=DATE-TIME:19160930T000000
RDATE;VALUE=DATE-TIME:19421102T030000
RDATE;VALUE=DATE-TIME:19431004T030000
RDATE;VALUE=DATE-TIME:19441002T030000
RDATE;VALUE=DATE-TIME:19451001T030000
RDATE;VALUE=DATE-TIME:19590920T030000
RDATE;VALUE=DATE-TIME:19600918T030000
RDATE;VALUE=DATE-TIME:19610917T030000
RDATE;VALUE=DATE-TIME:19620916T030000
RDATE;VALUE=DATE-TIME:19630915T030000
RDATE;VALUE=DATE-TIME:19640920T030000
RDATE;VALUE=DATE-TIME:19650919T030000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20171003T095550Z
X-RADICALE-NAME:1490974102.R440.ics
CREATED:20161016T143130Z
UID:libkcal-1108599422.827
SEQUENCE:8
LAST-MODIFIED:20171003T095550Z
SUMMARY:Håndball\, Jenter 08
LOCATION:Åsvang Skole
RRULE:FREQ=WEEKLY;UNTIL=20161219T171500Z;BYDAY=MO
EXDATE;VALUE=DATE:20161031
DTSTART;TZID=Europe/Oslo:20161017T181500
DTEND;TZID=Europe/Oslo:20161017T191500
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

2017-10-03 13:27:02,652 - [-49ac94c0] WARNING: Bad PUT request on '/ml/7cdbacf2-58fb-38bf-8159-260d167a0000/1507030021.R579.ics': Failed to store item '1507030021.R579.ics' in collection 'ml/7cdbacf2-58fb-38bf-8159-260d167a0000': can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1415, in upload
    href, vobject_item)
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1244, in _store_item_cache
    content = self._item_cache_content(href, vobject_item, cache_hash)
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1238, in _item_cache_content
    tag, start, end = xmlutils.find_tag_and_time_range(vobject_item)
  File "/usr/lib/python3/dist-packages/radicale/xmlutils.py", line 638, in find_tag_and_time_range
    _visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/usr/lib/python3/dist-packages/radicale/xmlutils.py", line 343, in _visit_time_ranges
    for dtstart in dtstarts:
  File "/usr/lib/python3/dist-packages/dateutil/rrule.py", line 1375, in _iter
    while exlist and exlist[0] < ritem:
  File "/usr/lib/python3/dist-packages/dateutil/rrule.py", line 1312, in __lt__
    return self.dt < other.dt
TypeError: can't compare offset-naive and offset-aware datetimes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 900, in do_PUT
    new_item = parent_item.upload(href, items[0])
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1418, in upload
    (href, self.path, e)) from e
ValueError: Failed to store item '1507030021.R579.ics' in collection 'ml/7cdbacf2-58fb-38bf-8159-260d167a0000': can't compare offset-naive and offset-aware datetimes
2017-10-03 13:27:02,663 - [-49ac94c0] DEBUG: Response content:
Bad Request
```

**Comment by mortlind** [comment]
This may be rrule.py which do not take the TZ into account when interpreting the timestamps.

**Comment by Unrud** [comment]
The problem is caused by the line ``EXDATE;VALUE=DATE:20161031``.
``DTSTART`` is specified as non-local date with time and ``EXDATE`` is a local date.
If you change the line to ``EXDATE;TZID=Europe/Oslo:20161031T181500`` it works.

I can't find this case in [RFC 5545](https://tools.ietf.org/html/rfc5545). It also seems ambiguous.

**Comment by mortlind** [comment]
OK. This comes from the libkcal used by Korganizer. I must find a place to file a bug report there. However, this may be due to old calendar events, since when I recreated the events, there was no problem for Radicale to eat them. I will see if the problem pops up again. Kudos for pinpointing the problem, @Unrud !

**Comment by htgoebel** [comment]
> The problem is caused by the line EXDATE;VALUE=DATE:20161031.
DTSTART is specified as non-local date with time and EXDATE is a local date.
If you change the line to EXDATE;TZID=Europe/Oslo:20161031T181500 it works.

I'd appreciate if radicale would gracefully handle this case :-)

**Comment by tmst** [comment]
Confirmed in KDE/KOrg calendar event after migration. Here's the problem event (the only one in nearly 1000):

BEGIN:VCALENDAR
PRODID:-//Radicale//NONSGML Radicale Server//EN
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:20161220T082640Z
X-RADICALE-NAME:1482223139.R484.ics
CREATED:20140810T090837Z
UID:PID5
LAST-MODIFIED:20161220T082640Z
DESCRIPTION:By North County Cruisers\n\nDeparting from Denny's on Ortega Hwy in Capistrano.
SUMMARY:Big Sur Ride
RRULE:FREQ=DAILY;UNTIL=20060910T150000Z
EXDATE:20060909T150000Z
EXDATE:20060910T150000Z
DTSTART:20060908T080000
TRANSP:OPAQUE
BEGIN:VALARM
DESCRIPTION:
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-P2D
X-KDE-KCALCORE-ENABLED:TRUE
X-RADICALE-NAME:1482223139.R484.ics
END:VALARM
END:VEVENT
BEGIN:VTIMEZONE
TZID:America/Anchorage
X-RADICALE-NAME:America/Anchorage
BEGIN:DAYLIGHT
TZOFFSETFROM:-0900
TZOFFSETTO:-0800
TZNAME:AKDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
X-RADICALE-NAME:America/Anchorage
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0800
TZOFFSETTO:-0900
TZNAME:AKST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
X-RADICALE-NAME:America/Anchorage
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:America/Dawson
X-LIC-LOCATION:America/Dawson
X-RADICALE-NAME:America/Dawson
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
TZNAME:PDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
X-RADICALE-NAME:America/Dawson
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
TZNAME:PST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
X-RADICALE-NAME:America/Dawson
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
BEGIN:STANDARD
TZNAME:PST
TZOFFSETFROM:-0752
TZOFFSETTO:-0800
DTSTART:19011213T125254
RDATE;VALUE=DATE-TIME:19011213T125254
X-RADICALE-NAME:America/Los_Angeles
END:STANDARD
BEGIN:DAYLIGHT
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
DTSTART:19500430T010000
RRULE:FREQ=YEARLY;COUNT=17;BYDAY=-1SU;BYMONTH=4
X-RADICALE-NAME:America/Los_Angeles
END:DAYLIGHT
BEGIN:DAYLIGHT
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
DTSTART:19760425T020000
RRULE:FREQ=YEARLY;COUNT=11;BYDAY=-1SU;BYMONTH=4
X-RADICALE-NAME:America/Los_Angeles
END:DAYLIGHT
BEGIN:DAYLIGHT
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
DTSTART:19870405T020000
RRULE:FREQ=YEARLY;COUNT=20;BYDAY=1SU;BYMONTH=4
X-RADICALE-NAME:America/Los_Angeles
END:DAYLIGHT
BEGIN:DAYLIGHT
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
DTSTART:20070311T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
X-RADICALE-NAME:America/Los_Angeles
END:DAYLIGHT
BEGIN:DAYLIGHT
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
DTSTART:19180331T020000
RDATE;VALUE=DATE-TIME:19180331T020000
RDATE;VALUE=DATE-TIME:19190330T020000
RDATE;VALUE=DATE-TIME:19480314T020100
RDATE;VALUE=DATE-TIME:19670430T020000
RDATE;VALUE=DATE-TIME:19680428T020000
RDATE;VALUE=DATE-TIME:19690427T020000
RDATE;VALUE=DATE-TIME:19700426T020000
RDATE;VALUE=DATE-TIME:19710425T020000
RDATE;VALUE=DATE-TIME:19720430T020000
RDATE;VALUE=DATE-TIME:19730429T020000
RDATE;VALUE=DATE-TIME:19740106T020000
RDATE;VALUE=DATE-TIME:19750223T020000
X-RADICALE-NAME:America/Los_Angeles
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:PST
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
DTSTART:19500924T020000
RRULE:FREQ=YEARLY;COUNT=12;BYDAY=-1SU;BYMONTH=9
X-RADICALE-NAME:America/Los_Angeles
END:STANDARD
BEGIN:STANDARD
TZNAME:PST
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
DTSTART:19621028T020000
RRULE:FREQ=YEARLY;COUNT=45;BYDAY=-1SU;BYMONTH=10
X-RADICALE-NAME:America/Los_Angeles
END:STANDARD
BEGIN:STANDARD
TZNAME:PST
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
DTSTART:20071104T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
X-RADICALE-NAME:America/Los_Angeles
END:STANDARD
BEGIN:STANDARD
TZNAME:PST
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
DTSTART:19181027T020000
RDATE;VALUE=DATE-TIME:19181027T020000
RDATE;VALUE=DATE-TIME:19191026T020000
RDATE;VALUE=DATE-TIME:19450930T020000
RDATE;VALUE=DATE-TIME:19490101T020000
X-RADICALE-NAME:America/Los_Angeles
END:STANDARD
BEGIN:DAYLIGHT
TZNAME:PWT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
DTSTART:19420209T020000
RDATE;VALUE=DATE-TIME:19420209T020000
X-RADICALE-NAME:America/Los_Angeles
END:DAYLIGHT
X-RADICALE-NAME:America/Los_Angeles
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:US/Pacific
X-RADICALE-NAME:US/Pacific
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
DTSTART:20070311T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZNAME:PDT
X-RADICALE-NAME:US/Pacific
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
DTSTART:20071104T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZNAME:PST
X-RADICALE-NAME:US/Pacific
END:STANDARD
END:VTIMEZONE
END:VCALENDAR

**Comment by Unrud** [comment]
@htgoebel 
> I'd appreciate if radicale would gracefully handle this case :-)

The case is not in the RFC and it's not clear what time-zone should be used for matching the local ``DATE`` against the non-local ``DATE-TIME``.
Anyway, I think that this should be handled by VObject.

@tmst 
Your problem is slightly different (reversed). The line ``DTSTART:20060908T080000`` specifies ``DTSTART`` as a local date with time, but in the following lines the ``DATE-TIME``s are specified as UTC (trailing ``Z``):

```
RRULE:FREQ=DAILY;UNTIL=20060910T150000Z
EXDATE:20060909T150000Z
EXDATE:20060910T150000Z
```

> Confirmed in KDE/KOrg calendar event after migration. 

It's a very old event, that was probably created by a faulty client a long time ago. I assume that the problem doesn't appear with newly created events.

> It appears to be a repeating event. 

It's a repeating event with deleted recurrences.

**Comment by optimaco** [comment]
@Unrud 
I know this has been closed, but I want to clarify this point:

> The case is not in the RFC and it's not clear what time-zone should be used for matching the local DATE against the non-local DATE-TIME.

I don't think the RFC is unambiguous. For matching the local DATE against the non-local DATE-TIME, you typically extract the date part of the non-local DATE-TIME and compare 2 dates.

For example, it is a common case for all-day events to define date-only DTSTART and DTEND. As described in the RFC, there is no timezone attached to the dates in that case:
DTSTART;VALUE=DATE:20180215
DTEND;VALUE=DATE:20180218

Unfortunately, this whole issue continues to make our life difficult, simply when we want to create a recurring event at a specific time of a day (DATE-TIME values), with exceptions on certain dates (DATE values).

Any further thoughts ?

**Comment by TheTincho** [comment]
Ugh, 2 years later now. I have just updated to radicale 2 and I am getting these same problems... I really don't understand the logic of crashing the server instead of somehow handling the malformed data... Now I have a migrated collection that I can't use unless I manually edit the files, it might take me hours to fix this, and it is only doable because I am hosting only one user account...

**Comment by edwardando** [comment]
Running a local radicale with debug on (I added a line to storage.py to print the details --  especially the UID of the event) and sending data with curl allows errors to be fixed slowly, thanks -- 9200 events imported successfully!

**Comment by spalme77** [comment]
Even though this seems to be an old and long-time topic I want to get back to it. Currently I am planning to migrate from davical to radicale. When trying to import my ICS files to radicale I get exactly the same error message: "Bad PUT request on '/me/b3b1c6ea-2fde-4083-d660-849acd9755c6/': can't compare offset-naive and offset-aware datetimes" (without any clue which event(s) are causing this problem).

Similar issues happen when trying to import ICS files generated by other tools, so it most likely a problem on radicale side.

Is there any solution for this?

I don't want to go over more than 10k events to fix them manually to make them importable with radicale... :-/

**Comment by jonassmedegaard** [comment]
Quoting Stefan Palme (2020-09-24 14:10:39)
> Similar issues happen when trying to import ICS files generated by other tools, so it most likely a problem on radicale side.

...or all those tools are similarly sloppy about time - i.e. happily slap a timezone onto events with no timezone defined.

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by spalme77** [comment]
> ...or all those tools are similarly sloppy about time - i.e. happily slap a timezone onto events with no timezone defined.

In my initial report I wanted to mention this possibility, too. Maybe you really think that Google, Gnome Evolution, davical, MS Outlook, Apple Calendar are ALL creating broken ICS files, and only radicale is correct by rejecting those ICS files.

However, in this case I would change my decision about which software to use, and replace the "theoretically correct" Radical product with a software that worked for in practice for many years (e.g. davical).

**Comment by spalme77** [comment]
In short: I need a solution that works in practice, not a solution that might fit the papers but is incompatible to everything which exists out there

**Comment by jonassmedegaard** [comment]
Quoting Stefan Palme (2020-09-24 16:57:13)
> Maybe you really think that Google, Gnome Evolution, davical, MS Outlook, Apple Calendar are ALL creating broken ICS files, and only radicale is correct by rejecting those ICS files.

No, I think that _each of them - including Radicale - create slightly broken ICS files, and that combining data across them may reveal such flaws.

For the concrete case of "the event happened at 13:00" without including where in the world, I prefer failure to import such data over "helpfully" adding the timezone of the author or the hosting provider or UTC: My dentist appointment is *not* at 13:00 UTC or 13:00 California time, if I previously stored that it was "at 13:00".

**Comment by spalme77** [comment]
I completely agree about the "art to give unambiguous instants". I even ask a friend to meet for lunch at "today at 1pm CEST", even though his office is just around the corner, just because too many of us are working with international colleagues in different timezones, and being imprecise can be root cause for more or less levels of chaos ;-)

Anyway, with regards to a protocol or file format there shouldn't be any ambiguities anyway. So I am still wondering: isn't there a way in radicale, when importing an ICS file with unclear timezone information, to just tell radicale "please assume UTC+6 for all times without explicit timezone data"?

I guess this would not be a big "mistake" from user's perspective, because most likely most of their event data would anyway be from the same time zone, but it would be much better that completely rejecting a file with 10k events if only a single event is "ambiguous" (as it is probably my case)

**Comment by jonassmedegaard** [comment]
Quoting Stefan Palme (2020-09-24 17:58:30)
> I guess this would not be a big "mistake" from user's perspective, because most likely most of their event data would anyway be from the same time zone, but it would be much better that completely rejecting a file with 10k events if only a single event is "ambiguous" (as it is probably my case)

I think that's an excellent feature request.

I got the impression that this issue was meant as a "Radically is broken" severity bugreport, not a feature request, but maybe that's just me...

**Comment by Unrud** [comment]
> For the concrete case of "the event happened at 13:00" without including where in the world, I prefer failure to import such data over "helpfully" adding the timezone of the author or the hosting provider or UTC: My dentist appointment is *not* at 13:00 UTC or 13:00 California time, if I previously stored that it was "at 13:00".

Events with and without timezones are fine. The problem appears then some parts of the same event event have timezones and others are in local time.

> I think that's an excellent feature request.

Workarounds can be added at https://github.com/Kozea/Radicale/blob/81218906c642812ed8c3feb6ae460aec7d2aab21/radicale/item/__init__.py#L61

I think we first need to collect more samples of broken files and decide how to "fix" them.
