### ISSUE TITLE
Default config file not read using wsgi interface

### ISSUE THREAD

**Issue by lleddewk** [Kozea/Radicale#615]
Using radicale version 2.0.0 with radicale.wsgi behind nginx.  Changes made to a config file at /etc/radicale/config are not implemented and the server runs using default config only.  Setting the environment variable RADICALE_CONFIG does have the expected effect and changed config is implemented.  Possibly linked to changes made at #574 ?

**Comment by Unrud** [comment]
Only the config file from RADICALE_CONFIG is loaded. I forgot to mention it in the documentation.

**Comment by lleddewk** [comment]
Ah OK.  Is there a convenient way to set RADICALE_CONFIG from a wsgi app's ini file?  I'm still searching but not found any clues so far.
