### ISSUE TITLE
Creating a custom storage plugin for Radicale

### ISSUE THREAD

**Issue by Ethan920713** [Kozea/Radicale#633]
I read the documentation and found this about plugins: 

"Storage plugins
This plugin is used to store collections and items. The module must contain a class Collection that extends radicale.storage.BaseCollection. Take a look at the file radicale/storage.py in Radicale’s source code for more information."

I already made a class which extends form storage.BaseCollection, but I'd like to know how can I store my calendar events on a custom database instead of a file in my file system. How can I achieve this? I even have custom models to store the calendar information, such as Calendar, Event and Rule (based on Django-Scheduler models). Thanks in advance.

**Comment by Unrud** [comment]
Radicale uses [VObject](http://eventable.github.io/vobject/) for handling VCALENDAR and VCARD. You have to translate between VObject's items and your internal data representation - that's the hard part.

The ``acquire_lock`` class method locks the storage for reading or writing. To get started, you can just use an exclusive lock.

The entry point to your ``Collection`` class is the ``discover`` class method. It's used to find collections and items in a path. You either yield an instance of your Collection class (if the path points to a "folder") or an instance of the ``Item`` class (if the path points to "file"). If the ``depth`` argument is not ``"0"`` and the path points to a folder, you also have to yield all direct children of that folder.
If a path doesn't exist, just return.

``Item`` is a simple data class, that holds the VObject item, the parent ``Collection``, the base name and the time the "file" was last modified (you can just use the current time here).

The ``create_collection`` class method is used to create new "folders". You don't have to implement this, if users are not able to create new calendars and address books. In this case collections on the path ``/``, ``/USERNAME`` and some calendars/address books (e.g. ``/USERNAME/calendar.ics``) must exist implicitly.

Your ``Collection`` instances must have the methods ``get_meta`` and ``set_meta`` for storing arbitrary property key-value-pairs (keys and values are strings). Some clients store configuration in properties on ``/USERNAME``. I guess you could also get away without implementing this, but calendars must have at least ``{"tag": "VCALENDAR", "C:supported-calendar-component-set": "VEVENT,VJOURNAL,VTODO"}`` and address books ``{"tag": "VADDRESSBOOK"}``.

The last set of methods on your ``Collection`` instance are about managing the "files" inside of it. ``list`` lists all "file" in the folder. ``get`` returns an instance of ``Item`` for a file, or ``None`` if the file doesn't exist. ``upload`` creates a new "file" or overwrites an existing "file" with a VObject item. ``delete`` deletes a file.
This methods are only required for Collections that are calendars or address books. They never have child collections.

For ``last_modified`` of ``Collection`` instances, you can again just use the current time. The instance must have the property ``path`` with the path of the collection without leading or trailing ``/``. Also, set ``owner`` with ``self.owner = self.path.split("/", maxsplit=1)[0]`` and ``is_principal`` with ``self.is_principal = bool(self.path) and "/" not in self.path``.
