### ISSUE TITLE
Release Radicale 2.1.0

### ISSUE THREAD

**Issue by Unrud** [Kozea/Radicale#647]
I think that version 2.1.0 is ready for release.

- [x] Documentation
  - [x] Remove mentions of the development version
  - [x] Create post with changelog
  - [x] Update [NEWS.md](https://github.com/Kozea/Radicale/blob/master/NEWS.md)
- [x] Bump version number to 2.1.0
- [x] Create release on Github with tag 2.1.0
- [x] Upload release to [PyPI](https://pypi.python.org/pypi) (@liZe: You have to do this, because I don't have the credentials.)

**Comment by liZe** [comment]
@Unrud Thanks for the great job! Do you have a PyPI account, so that I can add you to the list of maintainers?

**Comment by Unrud** [comment]
> Do you have a PyPI account

unrud

**Comment by liZe** [comment]
Done!
