### ISSUE TITLE
Lost in configuration

### ISSUE THREAD

**Issue by Offerel** [Kozea/Radicale#649]
Before i start, must say, that this is my first contact with Radicale. I have used SabreDAV before. But since the Development there is on hold, im in search for a alternative and found Radicale. 

After Installing Radicale 2.10 its running, but currently not as daemon, it logs directly to the console. But where can i reach the Webinterface? What is the Principal URL or well_known? Can i explore something via a Browser or MUST i use a DAV Client? Is it possible to use 1 URL to rule them all (Calendars and Contacts)?

I have nothing found to bring light in this Questions, if i read the Documentation.

i have made only a base configuration for local testing now. I have tried to connect via eM Client to http://serverip:5232/. It seems that i can connect, since no authentication error appears, but the Client cant get a list of the Ressources on the Server and the Console on the Server bring some 404 errors.

**Comment by Unrud** [comment]
> where can i reach the Webinterface?

Just open the address of the server in the browser. (e.g. http://serverip:5232)

> Principal URL or well_known

The mention of the ".well-known" URL in eM Client is nonsense. Just enter the server URL (e.g. http://serverip:5232). Radicale returns 404 for all ".well-known" URLs, that means for clients that the service can be found at ``/``.

You have to create at least one addressbook and calendar in Radicale's web interface. Otherwise, eM Client doesn't show the server in its UI and you can't create new collections.

**Comment by Offerel** [comment]
**Webinterface**: If i open the URL http://serverip:5232 via Browser, i see only a Message, that the Content can't be found and at the same time a 403 Message appears on the Console in some XML Structured Information. I have enabled Debug in the Config. But there is no hint, how to add a Addressbook or Calendar for the logged-in User.

**Autodiscover**: If i get Radicale working, i have planned to enable Autodiscover for my Server. Currently this works for SabreDAV without a Problem. I have added a caldavs and carddavs entry as SRV at my DNS Provider. This Record point to the Subdomain where my CalDAV Server could be reached. Since CalDAV cant be find at the root, NGINX delivers a redirect for the ".well-known" URLs. With this, eM Client and also DAVDroid do find the Collections, if i only enter my Credentials without any URL. In the case of eM Client, i enter only the Subdomain. Will this work also with Radicale?

**Comment by Unrud** [comment]
> i see only a Message, that the Content can't be found and at the same time a 403 Message appears on the Console in some XML Structured Information. 

That is very strange. Please start Radicale with debugging enabled, open the URL in the browser and post the complete logging output here.

> Will this work also with Radicale?

Yes. Radicale just doesn't provide ".well-known" URLs by itself. If they are provided by NGINX it will work.

**Comment by Offerel** [comment]
Sorry for the late reply. I gave up with radical and im back at SabreDAV. Maybe i come back at a later date.
