### ISSUE TITLE
UID in VEVENT is missing

### ISSUE THREAD

**Issue by marcoh00** [Kozea/Radicale#650]
Hello,

since upgrading to Radicale 2.x I get the following error when I try to synchronize my tasks and calendar again:

```
Jun 29 18:29:14 web-vm docker[18395]: [7fec4899d700] ERROR: An exception occurred during PROPFIND request on '/collection/calendar.ics/': Failed to load item '1486917532.R147.ics' in 'collection/calendar.ics': UID in VEVENT is missing
Jun 29 18:29:14 web-vm docker[18395]: Traceback (most recent call last):
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 1049, in _get_with_metadata
Jun 29 18:29:14 web-vm docker[18395]:     check_item(vobject_item)
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 126, in check_item
Jun 29 18:29:14 web-vm docker[18395]:     raise ValueError("UID in %s is missing" % component.name)
Jun 29 18:29:14 web-vm docker[18395]: ValueError: UID in VEVENT is missing
Jun 29 18:29:14 web-vm docker[18395]: The above exception was the direct cause of the following exception:
Jun 29 18:29:14 web-vm docker[18395]: Traceback (most recent call last):
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/__init__.py", line 298, in __call__
Jun 29 18:29:14 web-vm docker[18395]:     status, headers, answers = self._handle_request(environ)
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/__init__.py", line 464, in _handle_request
Jun 29 18:29:14 web-vm docker[18395]:     environ, base_prefix, path, user)
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/__init__.py", line 742, in do_PROPFIND
Jun 29 18:29:14 web-vm docker[18395]:     base_prefix, path, xml_content, read_items, write_items, user)
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/xmlutils.py", line 748, in propfind
Jun 29 18:29:14 web-vm docker[18395]:     base_prefix, path, collection, props, user, write=True)
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/xmlutils.py", line 929, in _propfind_response
Jun 29 18:29:14 web-vm docker[18395]:     element.text = item.etag
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 1264, in etag
Jun 29 18:29:14 web-vm docker[18395]:     for item in self.get_all():
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 1120, in <genexpr>
Jun 29 18:29:14 web-vm docker[18395]:     return (self.get(href, verify_href=False) for href in self.list())
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 1003, in get
Jun 29 18:29:14 web-vm docker[18395]:     item, metadata = self._get_with_metadata(href, verify_href=verify_href)
Jun 29 18:29:14 web-vm docker[18395]:   File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 1052, in _get_with_metadata
Jun 29 18:29:14 web-vm docker[18395]:     (href, self.path, e)) from e
Jun 29 18:29:14 web-vm docker[18395]: RuntimeError: Failed to load item '1486917532.R147.ics' in 'collection/calendar.ics': UID in VEVENT is missing
```

I see this is probably caused by defective client (I do not know a lot about CalDav unfortunately), but since it worked before, it would probably be nice to see this behavior documented somehow, possibly with some kind of workaround.

Maybe it would be even possible to catch this Error and do something more sensible than return 500, as the UID field doesn't seem to be mandatory according to RFC2445. [The Owncloud folks seem to have fixed a similar error in the past](https://github.com/owncloud/tasks/issues/272).

Thanks for your help!

**Comment by Unrud** [comment]
[rfc4791](https://tools.ietf.org/html/rfc4791#section-4.1) is also relevant here:

```
The UID property value of the calendar components contained in a
calendar object resource MUST be unique in the scope of the calendar
collection in which they are stored.

Calendar components in a calendar collection that have different UID
property values MUST be stored in separate calendar object resources.

Calendar components with the same UID property value, in a given
calendar collection, MUST be contained in the same calendar object
resource.
```

Unfortunately the wording is a bit vague. I'm not quite sure if it implies the existence of the UID property. (An empty/non-existing value is not unique and it's impossible to overwrite recurrences, when the UID is missing.)

The [rfc6352](https://tools.ietf.org/html/rfc6352#section-5.1) (CardDav) is much clearer on this topic and I think that both have the same intention.

What client are you using?

**Comment by marcoh00** [comment]
Hi,

I did not mean to argue about standards, sorry if it came across like that! Thanks for pointing out the right places anyway :)

I still think this is a bug, since radicale 1.x did not care. After reading this, I think just ignoring the error wouldn't be a good solution either. I do not know if the radicale runtime would be a good place to mess with the users' VCards and VCalendars (by just inserting a random UID if none exists), but I guess it is not. Maybe the Radicale 1 to 2 file format conversion routine could be a good place for fixing this automatically?

That's how I was able to solve the problem, by the way: I just gave the VCalendars radicale complained about a unique identifier generated by `python -c "import uuid; print(str(uuid.uuid4()).replace('-', ''))"` so it looked like this afterwards:

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:20170212T163846Z
CREATED:20170212T163846Z
UID:ae9ce90efd7b44fb826d391b765b4cd5
LAST-MODIFIED:20170212T163846Z
[...]
```

If there are any specific requirements about an UID I missed please do not hesistate to complain ;-)

The file itself could (I do not know for sure) have been imported by Kontact. It seems like it created the manually created ones (the ones I put into my calendar myself) just correct with an UID like this: `UID:libkcal-814311950.473` while it did not bother to create an UID for entries I imported from .ics files from the web.

**Comment by Unrud** [comment]
Fixed in https://github.com/Kozea/Radicale/commit/2b3fd1fb9b923634b1313be26aae4572456ec6e9
