### ISSUE TITLE
Calendar exported from v1 fails to load

### ISSUE THREAD

**Issue by szotsaki** [Kozea/Radicale#652]
The following error happens when I try to load a calendar with 2.1.1 exported from 1.1.4 with `--export-storage`:

```
júl 01 18:06:43 linux-suse env[31704]: [7f3c74f75700] ERROR: An exception occurred during PROPFIND request on '/xyz/calendar/': Failed to load item '1433663914.R906.ics' in 'xyz/calendar': Failed to parse item '1433663914.R906.ics' from 'xyz/calendar': "In transformToNative, unhandled exception on line None: <class 'ValueError'>: mandatory DTSTART not found (<VTIMEZONE| [<TZID{}UTC>, <STANDARD| [<DTSTART{}19700101T000000>, <TZNAME{}UTC>, <TZOFFSETFROM{}+0000>, <TZOFFSETTO{}+0000>, <X-RADICALE-NAME{}UTC>]>, <DAYLIGHT| [<X-RADICALE-NAME{}UTC>]>, <X-RADICALE-NAME{}UTC>]>)"
```

**Comment by Unrud** [comment]
Can you post the content of the file ``1433663914.R906.ics`` here?
You can remove any personal information like SUMMARY, LOCATION, COMMENT, ...

**Comment by szotsaki** [comment]
Yes, of course; here it is: [1433663914.R906.txt](https://github.com/Kozea/Radicale/files/1117259/1433663914.R906.txt) (rename .txt to .ics)

**Comment by Unrud** [comment]
The file is invalid.

```
BEGIN:VTIMEZONE
TZID:UTC
....
BEGIN:DAYLIGHT
X-RADICALE-NAME:UTC
END:DAYLIGHT
...
END:VTIMEZONE
```

According to to [rfc5545](https://tools.ietf.org/html/rfc5545#section-3.6.5) the ``BEGIN:DAYLIGHT`` section must contain ``DTSTART``, ``TZOFFSETTO`` and ``TZOFFSETFROM``.

I think that the easiest solution is to remove the invalid time zone component.

**Comment by szotsaki** [comment]
Thank you, that really makes Radicale process the next file.

However, *all* of my exported `.ics` file contain these three lines. Interesting, only in this calendar. Of course, I can write a sed script which removes these, but I'm afraid many users won't do that.

**Comment by Unrud** [comment]
> but I'm afraid many users won't do that.

It's only an issue, if your calendar data in Radicale 1.x.x was invalid to begin with. I'm not sure if it's a good idea to try to repair invalid data automatically.
