### ISSUE TITLE
Name of calendar and addressbook

### ISSUE THREAD

**Issue by bigbig6** [Kozea/Radicale#653]
Hello,

Via the web interface, when you create a calendar and/or an addressbook, you can choose some informations like the title and description.
But the final URL is using a UID. Why not using the title instead of this UID?

It's completely impossible for a human to remember this UID, but the title is easy to remember

Regars,

Big

**Comment by Unrud** [comment]
> Why not using the title instead of this UID?

You can change the title later, but you can't change the path without breaking all existing clients.

This only affects the built-in web interface, other clients can choose whatever path they like.

> It's completely impossible for a human to remember this UID

You are not supposed to remember it. Most clients can list all existing calendars/address books when you enter the server URL and your username. For the rest you can copy the URL from the web interface.

**Comment by bigbig6** [comment]
This is not logical...

if you use http://addressIP:5232/user1/ all elements are stored in the user's repertory, calendar and addressbook, everythings are melted...
The web interface show all elements as a calendar.

if you use http://addressIP:5232/user1/calendar, all elements are stored in this repertory, but the web interface do not show this repertory.

Regards,

Big

**Comment by Unrud** [comment]
> This is not logical...

What exactly is not logical?

> f you use http://addressIP:5232/user1/ all elements are stored in the user's repertory,

> if you use http://addressIP:5232/user1/calendar, all elements are stored in this repertory,

What do you mean by **use** and **elements**? I've no idea what you are doing.

> but the web interface do not show this repertory.

All calendars and address books must be direct children of the collection ``/USERNAME``. CalDav and CardDav do not really support storing calendars and address books in arbitrary folders. Clients (and the web interface) are not able to find calendars and address books that are not in ``/USERNAME``.

**Comment by bigbig6** [comment]
use : the URL (http://addressIP:5232/user1/) in the parameters of the calendar
Elements: a .ics file

If you enter http://addressIP:5232/user1/calendar/ for the URL in the calendar parameter's, a new folder "calendar" will be created in the /user1 collection.
But in the web interface (logged as user1), you won't see this folder

If you enter http://addressIP:5232/user1/ for the URL in the calendar parameter's, all .ics files are created directly in the /user1 folder.
And in this case, on the web interface you will see each .ics as a different calendar (80 meets, so 80 .ics files and 80 lines in the web interface).

**Comment by Unrud** [comment]
> use : the URL (http://addressIP:5232/user1/) in the parameters of the calendar

Where and how do you use the URL? Is this some WebDAV client?

> But in the web interface (logged as user1), you won't see this folder

The problem is that your WebDAV client (or whatever) doesn't create a calendar but a normal collection.

> And in this case, on the web interface you will see each .ics as a different calendar

Same problem. If you upload an iCalendar file into a normal folder, Radicale thinks that you are trying to upload a complete calendar (instead of an element of a calendar) and creates a new calendar for every item.

The [client documentation](http://radicale.org/clients/) has some information about manually creating calendars and address books at the end.

**Comment by bigbig6** [comment]
Yes, with evolution a caldav client for linux

No it can create a calendar with this URL: (http://addressIP:5232/user1/calendar1

If I use (http://addressIP:5232/user1/, each event are created in it's own .ics file, and the radicale web interface see al of them as a calendar.

**Comment by Unrud** [comment]
> No it can create a calendar with this URL: (http://addressIP:5232/user1/calendar1

No, it can't. Please don't add URLs of non-existent calendars to Evolution. The program doesn't create the calendar and it also doesn't check if it exists. It uploads the items anyway. Radicale has a feature that lets you upload complete calendars (a single iCalendar file) and it thinks that every item from Evolution is a complete calendar.

Create calendars and address books in Radicale's web interface and then add them to Evolution.

**Comment by Rabbit10** [comment]
j'ai eu ce même soucis avec Outlook CalDav Synchronizer

pour votre première interrogation j'ai modifier le fichier fn.js
en ajoutant à la ligne 894 du fichier qui se trouve /usr/local/lib/python3.5/dist-packages/radicale/web/fn.js

Voici la fonction d’origine

function read_form() {             
displayname = displayname_form.value;             
description = description_form.value;           
type =   type_form.value;           
color   = color_form.value;   
}

Que j'ai modifié en 

function read_form() {         
displayname = displayname_form.value;         
description = description_form.value;         
href   =  edit ? collection.href : (collection.href + displayname +   "/" );           
type = type_form.value;           
color = color_form.value;   }

est-ce une grosse erreur ?
pour ma part ça fonctionne parfaitement pour le moment.

**Comment by Unrud** [comment]
> est-ce une grosse erreur ?

* ``displayname`` might be empty.
* Use ``encodeURIComponent(displayname)`` instead of ``displayname``.

**Comment by bigbig6** [comment]
Yes, you are right Unrud, but when we manage a lot calendars, it is really usefull to understand wich calendar is where, for a backup/restore for example.

Having a calendar named with the display name just like Rabbit10 done is really more readable I think.

**Comment by pbiering** [comment]
with current version a name instead of the UUID can be chosen in WebUI
