### ISSUE TITLE
Size of events in calendar

### ISSUE THREAD

**Issue by bigbig6** [Kozea/Radicale#654]
[20170704T124823Z-1586-0-1-42_debian-20170704T124903Z.txt](https://github.com/Kozea/Radicale/files/1122027/20170704T124823Z-1586-0-1-42_debian-20170704T124903Z.txt)

Hello,

I did some tests with the new version of calendar.
Seems that the size of each event is 13Kb which is very big.

I think most of the information is written too many time...

I attached a .ics test file.

In this case, a use Evolution as calendar.

Regards

Big

**Comment by Unrud** [comment]
> I think most of the information is written too many time...

No, the timezone information is just encoded very inefficient. Instead of using a recurrence rule, the standard and daylight saving time is stored explicitly for every year.
Anyway, the client creates the files and is responsible for their contents. Radicale has nothing to do with the big file sizes.

**Comment by bigbig6** [comment]
Ok, I will see with Evolution...

The problem is this event is NOT recurrent.

**Comment by Unrud** [comment]
> The problem is this event is NOT recurrent.

The problem is not the event itself (``VEVENT``), but the time zone (``VTIMEZONE``).

**Comment by felixfontein** [comment]
Be happy you only get 13 kb. Most `.ics` files in my calendars are 80 kb or 103 kb each. :)

Interestingly, all these large files are the result of converting Radicale 1.x data to Radicale 2.x format. Newly added `.ics` files are *all* less than 1 kb in size, and were not created with different programs than the `.ics` files stored with Radicale 1.x. So it *is* Radicale (during data conversion) which blew up the files.

**Comment by Unrud** [comment]
> Interestingly, all these large files are the result of converting Radicale 1.x data to Radicale 2.x format. 

That's a different issue. Radicale 1.x.x stores events and time zones separate (it splits the files uploaded by clients). When a client requests an event or todo, it combines them again. But it doesn't check what events/todos require which time zones, instead it adds all time zones to every item. If your calendar contains a lot of different time zones, your files can balloon like that on export.

Radicale 2.x.x just stores whatever the client uploads.

**Comment by bigbig6** [comment]
I will try with another client to see if I have the same problem.

Regards,

Big

**Comment by bigbig6** [comment]
I did a test with evolution in local, and I've got the same effect...

Seems that evolution do not store information correctly.

Sorry for the noise.

Regards,

Big
