### ISSUE TITLE
no logging output using wsgi setup

### ISSUE THREAD

**Issue by DoraPaula** [Kozea/Radicale#655]
Hi,

I run radicale using mod_wsgi and apache 2.4.

Installation of radicale 2.1.1 worked fine.

Setup worked also fine - at least radicale responds with its web-interface (using mod_wsgi).
To further setup and test auth and rights management I would like to turn on debug logging - without success.

My configuration steps so far:

```
mkdir /etc/radicale
chown radicale:radicale /etc/radicale
cd /etc/radicale
wget https://raw.githubusercontent.com/Kozea/Radicale/master/config
wget https://raw.githubusercontent.com/Kozea/Radicale/master/logging

```
Content of /etc/radicale/config (changes only):

```
	[auth]
	type = remote_user

	[rights]
	type = owner_write

	[logging]
	config = /etc/radicale/logging
```

Content of /etc/radicale/logging (changes only):

```
	[handlers]
	keys = file

	[formatters]
	keys = full

	[logger_root]
	level = DEBUG
	handlers = file

	[handler_file]
	class = FileHandler
	# Specify the output file here.
	args = ('/var/log/radicale/log',)
	formatter = full

	[formatter_full]
	format = %(asctime)s - [%(thread)x] %(levelname)s: %(message)s

```

```
mkdir /var/log/radicale
chown radicale:radicale /var/log/radicale

mkdir /var/lib/radicale
chown radicale:radicale /var/lib/radicale
cd /var/lib/radicale
wget https://raw.githubusercontent.com/Kozea/Radicale/master/radicale.wsgi
chown radicale:radicale radicale.wsgi
```

Edit Apache (2.4) Config:

```
	<VirtualHost *:80>
        ServerName calendar.example.com
        ServerAdmin webmaster@example.com

        DocumentRoot /var/www/calendar.example.com

        WSGIDaemonProcess radicale user=radicale group=radicale threads=1
        WSGIScriptAlias / /var/lib/radicale/radicale.wsgi
	
		<Directory /var/lib/radicale/calendar.example.com>
			WSGIProcessGroup radicale
			WSGIApplicationGroup %{GLOBAL}
			Require all granted
		</Directory>
	</VirtualHost>
```

Restart Apache2:
	`/etc/init.d/apache2 restart`

Enter URL in Webbrowser (Firefox):
	https://calendar.example.com/
	
	=> radicale Login Form appears (Browser-URL changes to: https://calendar.example.com/.web/)
	=> Apache AccessLog reports:

```
2001:xxx::1000 - - [07/Jul/2017:22:47:17 -0700] "GET / HTTP/1.1" 302 10582 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
2001:xxx::1000 - - [07/Jul/2017:22:47:17 -0700] "GET /.web HTTP/1.1" 302 316 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
```
	=> Apache ErrorLog reports: nothing

Enter a user and password (test/test) into radicale Login Form:
	==> /var/log/apache2/calendar.example.com_access.log <==
```
2001:xxx::1000 - - [07/Jul/2017:22:52:56 +0200] "PROPFIND / HTTP/1.1" 401 10658 "https://calendar.example.com/.web/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
2001:xxx::1000 - - [07/Jul/2017:22:52:56 +0200] "PROPFIND / HTTP/1.1" 401 390 "https://calendar.example.com/.web/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"

```
Please don't wonder about the https url (I use https, the apache config excerpt above is stripped down to the minumum)

ls /var/log/radicale reports nothing (no radicale logfile)

```
root@ey:/var/log# ls -al /var/log/radicale/
total 8
drwxr-xr-x  2 radicale radicale 4096 Jul  7 22:37 .
drwxr-xr-x 17 root     root     4096 Jul  7 22:37 ..

```

But, if I start radicale via commandline (nothing of the above settings changed) the log gets created and reports:

```
root@ey:/var/lib/radicale# cat /var/log/radicale/log
2017-07-07 23:00:41,984 - [7fe908639700] INFO: Starting Radicale
2017-07-07 23:00:41,984 - [7fe908639700] INFO: Authentication type is 'remote_user'
2017-07-07 23:00:41,984 - [7fe908639700] INFO: Storage type is 'multifilesystem'
2017-07-07 23:00:41,984 - [7fe908639700] INFO: Rights type is 'owner_write'
2017-07-07 23:00:41,984 - [7fe908639700] INFO: Web type is 'internal'
2017-07-07 23:00:41,986 - [7fe908639700] INFO: Listening to 'localhost' on port 5232
2017-07-07 23:00:41,986 - [7fe908639700] INFO: Radicale server ready
Terminating radicale with ctrl-c adds this line:
2017-07-07 23:01:08,565 - [7fe908639700] INFO: Stopping Radicale
```

Question: Why isn't there anything logged when using mod_wsgi? What am I missing?
- Perhaps insufficient permissions? chmod'ing /var/log/radicale 777 and /var/log/radicale/log 666 and restarting apache2 (don't know whether this is needed) does not help.
- Perhaps wrong loglevel? But, I obviously don't know how to enable/managing radical-logging at all.

Thanks for your support.
Dora

**Comment by Unrud** [comment]
The configuration file is not loaded. You have to provide the path in the environment variable ``RADICALE_CONFIG``. ``/etc/radicale/config`` is only loaded in standalone-mode, but not if you load it with WSGI.

See the second paragraph at http://radicale.org/wsgi/

**Comment by DoraPaula** [comment]
Ah, now I understand: I've read the first paragraph of wsgi-documentation, but I thought the "default configuration" == "the default configuration file" == "/etc/radicale/config".

So I added: SetEnv RADICALE_CONFIG /etc/radicale/config
to the virtualehost and restarted apache, but although apache-server-info reports:

```
Module Name: mod_env.c
Content handlers: none
Configuration Phase Participation: Create Directory Config, Merge Directory Configs
Request Phase Participation: Fixups
Module Directives:
    PassEnv - a list of environment variables to pass to CGI.
    SetEnv - an environment variable name and optional value to pass to CGI.
    UnsetEnv - a list of variables to remove from the CGI environment.
Current Configuration:
    In file: /etc/apache2/sites-enabled/calendar.example.com.conf
       2: <VirtualHost *:443>
       8:   SetEnv RADICALE_CONFIG "/etc/radicale/config"
        : </VirtualHost>
```
it seems to have no effect. I don't know what I am doing wrong. Do you have any more ideas?

**Comment by DoraPaula** [comment]
I modified `/var/lib/radicale/radicale.wsgi` and hardcoded the confiration file:

import os
os.environ['RADICALE_CONFIG'] = '/etc/radicale/config'
from radicale import Application, config, log

This works, that mean the radicale logfile `/var/log/radical/log` gets populated.

Nevertheless I would like to get rid of this (very ugly) workaround.

**Comment by DoraPaula** [comment]
To see, whether the environment variable is set, I added the following statement into the virtualhost environment:
`CustomLog ${APACHE_LOG_DIR}/calendar.example.com_https_access.log "RADIiii: \"%{RADICALE_CONFIG}e\""`

Now, each time I browse to http://calendar.example.com the apache access-log reports:

```
cat ${APACHE_LOG_DIR}/calendar.example.com_https_access.log | grep RADI
root@ey:/etc/apache2/sites-enabled# cat /var/log/apache2/calendar.example.com_https_access.log | grep RADI
RADIiii: "/etc/radicale/config"
RADIiii: "/etc/radicale/config"
RADIiii: "/etc/radicale/config"
RADIiii: "/etc/radicale/config"
```

So, the SetEnv works. But why radicale.wsgi cannot get it? (Sorry, I'm no python-expert.)

**Comment by Unrud** [comment]
> So, the SetEnv works.

Unfortunately it doesn't set the application environment for WSGI. It only adds the variable to the request environment.

**Comment by DoraPaula** [comment]
Thanks you very much for the clarifications regarding os- vs. request-environment. It works - issue solved
BTW: I am using debian too. ;-)

I think in regard of a radicale wsgi setup the documentation should go a bit more into details. I also suggest to optimize the wording: default configuration => hardcoded configuration setttings; environment variable => os environment variable (e.g. not apache SetEnv).

Last suggestion: Instead of setting the radicale-config-file-location in a foreign, non-radicale config file (e.g. even not just web-server-, but distribution-specific: /etc/apache2/envvars), setting the config-path within the radicale.wsgi once (during installation) seems at least for me the more generic, easier to remember and more portable solution.
