### ISSUE TITLE
Write PID file in non-daemon mode so logrotate can restart WSGI daemon

### ISSUE THREAD

**Issue by iliis** [Kozea/Radicale#657]
Hi,

I'm not entirely sure where to put this, maybe this is more appropriate for the Debian maintainers.

I'm running Radicale behind Apache as per https://wiki.debian.org/Radicale. It stopped running after a few days and I tracked the problem down to logroate on my Debian 8 box: It creates a new logfile with the wrong user and group (radicale:adm instead of www-data:www-data).

Changing /etc/logrotate.d/radicale to use Apache's www-data user/group is trivial, but in order for the whole log-rotate-thing to work, Radicale needs to be restarted, right? However when it's running as a WSGI daemon it's kinda hard to figure out which PID to SIGINT, because the process is listed as 'apache2' and the 'pid' file option in Radicale doesn't do anything when Radicale isn't running in daemon mode.

I've worked around this by using the 'display-name' option in the WSGIDaemonProcess line:

    WSGIDaemonProcess radicale user=www-data group=www-data threads=1 display-name=radicale_wsgi

Which then can be used to find and restart the correct process in logrotate's postrotate section.
`/etc/logrotate.d/radicale`:

```
/var/log/radicale/*.log {
        rotate 12
        weekly
        compress
        missingok
        create 640 www-data www-data
        postrotate
                    radicale pkill -SIGINT -f radicale_wsgi
        endscript
}
```

So, an update to https://wiki.debian.org/Radicale or http://radicale.org/wsgi/ might be enough to "fix" this, but having an explicit pid file would be nice nevertheless.

**Comment by Unrud** [comment]
In the default configuration, Radicale writes log output to ``stderr``. Apache should log all ``stderr`` output from WSGI applications to the errors log.

You could also use Python's built-in log rotation: http://radicale.org/logging

**Comment by Tntdruid** [comment]
Why not just run it as service?

**Comment by pbiering** [comment]
current version of radicale using systemd for logging, no need to rotate logfiles anymore.
