### ISSUE TITLE
External plugin configuration - break between 2.0.0 and 2.1.0

### ISSUE THREAD

**Issue by tasn** [Kozea/Radicale#658]
Hey,

I wrote an external radicale storage plugin.

It worked great on 2.0.0 but stopped working in newer versions because custom config sections are no longer allowed in the configuration.

I see https://github.com/Kozea/Radicale/commit/276de4fd3a61f94f0faea8ccce3028fa5a05f5f5 was trying to "help extrenal plugins" though I'm not sure how.

Where am I supposed to store my module's config? I'd assume the main config file, but starting from 2.1.0 it seems to be no longer allowed.

The radicale error message:

    ERROR: Invalid configuration: Invalid section 'etesync_storage' in config

**Comment by Unrud** [comment]
You can store them in the ``[storage]`` section.

**Comment by tasn** [comment]
Thanks, that fixes it.
