### ISSUE TITLE
time-range filter does not return results where end time is not within time range.

### ISSUE THREAD

**Issue by assos** [Kozea/Radicale#659]
As per title, if the start time of an event is within the time range the event will be returned. However the same is not true if the end time is within the time range.

Request details below. There is an event in the calendar starting at 0900 and ending at 1000.

Method: REPORT
Headers: ['Content-Type' => 'application/xml; charset="utf8"', 'Depth' => '1']

```
<?xml version="1.0" encoding="utf-8" ?>
<c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
	<c:filter>
		<c:comp-filter name="VCALENDAR">
			<c:comp-filter name="VEVENT">
				<c:time-range start="20170719T093000Z" end="20170719T120030Z"/>
			</c:comp-filter>
		</c:comp-filter>
	</c:filter>
</c:calendar-query>
```

**Comment by Unrud** [comment]
Can you please provide the event that you are trying to filter?
Just post the content of the iCalendar file here. You can remove any personal information like ``SUMMARY``, ``DESCRIPTION`` and so on.

**Comment by assos** [comment]
Certainly - pasted below.

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Apple Inc.//Mac OS X 10.12.4//EN
BEGIN:VTIMEZONE
TZID:Europe/London
BEGIN:STANDARD
DTSTART:19961027T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
TZNAME:GMT
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19810329T010000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
TZNAME:BST
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:AAFD4A3D-A94C-42EE-A963-8A8E5DCED293
DTSTART;TZID=Europe/London:20170719T090000
DTEND;TZID=Europe/London:20170719T100000
CREATED:20170711T113208Z
DTSTAMP:20170711T113212Z
SEQUENCE:0
SUMMARY:nom nom
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
END:VEVENT
END:VCALENDAR
```

**Comment by Unrud** [comment]
The event starts at 08:00 and ends at 09:00 (converted to UTC). The filter range starts at 09:30 and ends at 12:00.30. The filter does not return the event because it's out of range.

**Comment by assos** [comment]
Egg on face! Apologies me being stupid not converting the times to UTC first. Do that and all is working grand - thank you!
