### ISSUE TITLE
Radicale won't run on Windows 10 using Python 3.6.2 or 3.5.3

### ISSUE THREAD

**Issue by daverickdunn** [Kozea/Radicale#671]
Tried getting the "A really simple 5-minute tutorial" to run on Windows 10 for a good 10 minutes.

Tutorial synopsis:
`python -m pip install --upgrade radicale`
`python -m radicale --config "" --storage-filesystem-folder=~/radicale/collections`

The pip install seems fine, I can load the radicale module from the shell.

However, the second command fails complaining about an unknown parameter `-C`. I tried several variations of the command; 3 different consoles; Python 3.5.3 and 3.6.2; elevated command prompts; different _storage-filesystem_ folders; antivirus disabled; you name it...

Full output:

`PS C:\radicale> python -m radicale --config "" --storage-filesystem-folder=~/radicale/collections`
`usage: radicale [OPTIONS]`
`__main__.py: error: argument -C/--config: expected one argument`

Perhaps this is an **argparse** issue?

Most other variations of the command, e.g. omitting the `--config ""` option, would freeze any of the 3 consoles and require that they be relaunched.

**Comment by Unrud** [comment]
> Perhaps this is an argparse issue?

It seems to be a problem with the console. For some reason it doesn't pass the empty argument ``""``. What console are you using? I tried it with ``cmd.exe`` on Windows 10 and it works for me.

> Most other variations of the command, e.g. omitting the ``--config ""`` option, would freeze any of the 3 

Have you tried to open the the website in the browser? Radicale doesn't print anything on the console, unless an error happens or debugging is enabled. The console might seem frozen.

**Comment by daverickdunn** [comment]
Hi, thanks for the reply, I only got round to checking this out now.

It appears to be a PowerShell issue specifically. I think I got a bit mixed up as I assumed the "freezing" was related, or at least due to incorrect parameters, so when I was checking it out on other consoles I was testing without the `--config ""` parameter.

**Solutions for PowerShell users are to use:** `--config '""'` or simply omit the argument altogether.

I'd like to fire out a couple of suggestions, some which are mutually exclusive, make of them what you will...

- Remove `--config ""` from the ["A really simple 5-minute tutorial"](http://radicale.org/tutorial/)

- Add a comment to the tutorial regarding this issue with PowerShell. (Bearing in mind that Windows 10 is now pushing users towards PowerShell over cmd)

- Output _any_ message to indicate the server is running.

- Explain in the tutorial that there's no output

This last one should probably be a separate issue, but part of the reason I thought it was freezing was because it didn't die on SIGTERM or SIGINT. I've had a brief look at the code and can see there's a shutdown handler in there, without picking it apart, it's a fair guess to say it's blocking interrupts, so:

- Enable a signal interrupt for the process.

- Explain in the tutorial that the process can't be interrupted (assuming it's intentional behaviour...)

I'm sure these seem like non issues to some, but as a new user if a project throws some hiccups at the very start it usually results in a new google search... :/

Thanks.

**Comment by Unrud** [comment]
I've added a note for PowerShell to the tutorial and fixed the KeyboardInterrupt problem on Windows.

**Comment by daverickdunn** [comment]
Nice one! :D

**Comment by daverickdunn** [comment]
> I'm curious: Wouldn't using single-quotes only (`--config ''`) work both in Powershell and cmd.exe? If so, the tutorial could be simplified.

To be honest, I really barely even remember this conversation, but I'd be very surprised if I hadn't tried that at the time.
