### ISSUE TITLE
IMAP Authentication

### ISSUE THREAD

**Issue by Tntdruid** [Kozea/Radicale#672]
Can i still use that in 2.x.x?

**Comment by Unrud** [comment]
https://github.com/Kozea/Radicale/issues/643#issuecomment-310024233

**Comment by Tntdruid** [comment]
Thats too bad, gonna find some other caldav i can use.

**Comment by daks** [comment]
Too bad, I was hoping to upgrade to Radicale 2.x soon, but if at the moment there is no IMAP auth plugin, I can't.

**Comment by Unrud** [comment]
> but if at the moment there is no IMAP auth plugin

IMAP authentication plugin for Radicale: https://github.com/Unrud/RadicaleIMAP

I moved the example from https://github.com/Kozea/Radicale/issues/643#issuecomment-310024233 into its own repository. That should make installation and upgrades easier.

**Comment by Tntdruid** [comment]
@Unrud Thanks for making the plugin.

**Comment by daks** [comment]
Thanks @Unrud
