### ISSUE TITLE
Performance issues on a Raspberry Pi

### ISSUE THREAD

**Issue by qfvldaa2xn** [Kozea/Radicale#677]
I have a calendar with 2263 entries.
With version 1.x it always worked well on my Raspberry Pi.
Now after upgrading to version 2.1.2 I experience performance issues (CPU close to 100%) when trying to synchronize, which lead to timeouts and HTTP 502 messages of the nginx reverse proxy.

The server is just used for radicale (plus the nginx reverse proxy for radicale).

Now I downgraded again and no performance problems anymore.

**Comment by Unrud** [comment]
If you import a lot of items, the first request might take a long time. Radicale has to initialize its caches. Clients can time out during this. Future request will be much faster (by a factor of >100).

**Comment by Unrud** [comment]
I added a note about the slow first start up to the documentation.

**Comment by qfvldaa2xn** [comment]
Sorry for the late reply.
You were right, now it works perfectly fine. Thanks for adding it to the documentation!
Appreciate your work very much :)
