### ISSUE TITLE
Title, Description are cleared, when event is saved in thunderbird.

### ISSUE THREAD

**Issue by ipiasecki** [Kozea/Radicale#678]
Hi.

I noticed, that Thunderbird deletes Title and description fields of calendar at Radicale, when event is modificated.

Before modification of event:
{"C:calendar-description": "TIE calendar", "C:supported-calendar-component-set": "VEVENT,VJOURNAL,VTODO", "D:displayname": "TIE", "ICAL:calendar-color": "#f5425cff", "tag": "VCALENDAR"}

Then after event modification:
{"tag": "VCALENDAR"}

It is error in Radicale code or Thunderbird ?

**Comment by ipiasecki** [comment]
Is cleared to, if any evenet is added.

**Comment by ipiasecki** [comment]
This all happen, when Radicale calendar is connected in ThunderBird via iCal protocol ...

**Comment by Unrud** [comment]
> ThunderBird via iCal protocol 

Always use CalDAV. If you select iCalendar, Thunderbirds overwrites the existing calendar on the server everytime.
