### ISSUE TITLE
radicale with  IOS /Iphone

### ISSUE THREAD

**Issue by GitDatei** [Kozea/Radicale#680]
Hello,

i have installed Radicale 2.x it work fine with Thunderbird ...
but i can'not connect radicale with my Iphone.

Who has experience with it?

**Comment by Unrud** [comment]
Related issue: https://github.com/Kozea/Radicale/issues/639

Are you using WSGI or a reverse proxy, too? Can you provide the debug log output?

**Comment by GitDatei** [comment]
i test it with windows.
without proxy or wsgi.

if u say radicale works with iphone only proxy or WSGI , than i install tomorrow one debian minimal with it.

i think with windows install, work outofbox

**Comment by Unrud** [comment]
> if u say radicale works with iphone only proxy or WSGI 

No, I'm not saying that. The reporter of https://github.com/Kozea/Radicale/issues/639, wrote that it worked without a reverse proxy. But apparently that is not true in your case.

Can you run Radicale with the ``--debug`` argument, try to connect with the iPhone and post the output here?

**Comment by GitDatei** [comment]
ok i'm at work , now
after the work i make it

**Comment by GitDatei** [comment]
so i start radicale with debug, i connect with thunderbird , this work fine and debug,too

but if i want connect with ios, The debug remains empty
I use this address: http://1xx.1xx.1xx.1xx:5232/username/b4f0a916-a491-7bda-fe03-78c0b4d77e32/

without SSL

**Comment by Tntdruid** [comment]
On iOS you only need  http://1xx.1xx.1xx.1xx:5232/ to connect.

**Comment by Unrud** [comment]
You have to start Radicale with the ``--hosts 0.0.0.0:5232`` argument. From the tutorial:

> The server is **not** reachable over the network and you can log in with any user name and password.

For security reasons the server only binds to localhost, if not configured explicitly.

> On iOS you only need http://1xx.1xx.1xx.1xx:5232/username/ to connect.

Even http://1xx.1xx.1xx.1xx:5232 should be enough. You have to enter the user name in a separate field.

**Comment by GitDatei** [comment]
@Unrud 
Thanks 
radicale work fine with iphone , now

**Comment by GitDatei** [comment]
so i installed debian and python with radicale
i want creat a calender but , comes error with 408 timeout
`[7efd9fde8700] DEBUG: Request headers:
{'CONTENT_LENGTH': '529',
 'CONTENT_TYPE': 'text/plain;charset=UTF-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'de,en-US;q=0.7,en;q=0.3',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': '192.168.178.131:5232',
 'HTTP_REFERER': 'http://192.168.178.131:5232/.web/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) '
                    'Gecko/20100101 Firefox/54.0',
 'PATH_INFO': '/admin/24876015-de40-af70-8f37-dce2089b1a54/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.178.159',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'MKCOL',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'debian',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7efda4c4fd38>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[7efd9fde8700] DEBUG: Sanitized script name: ''
[7efd9fde8700] DEBUG: Sanitized path: '/admin/24876015-de40-af70-8f37-dce2089b1a54/'
[7efd9fde8700] INFO: Successful login: 'admin'
[7efd9fde8700] DEBUG: client timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/radicale/__init__.py", line 656, in do_MKCOL
    xml_content = self._read_xml_content(environ)
  File "/usr/local/lib/python3.5/dist-packages/radicale/__init__.py", line 533, in _read_xml_content
    content = self.decode(self._read_raw_content(environ), environ)
  File "/usr/local/lib/python3.5/dist-packages/radicale/__init__.py", line 522, in _read_raw_content
    content = environ["wsgi.input"].read(content_length)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
[7efd9fde8700] DEBUG: Response content:
Connection timed out.
[7efd9fde8700] INFO: MKCOL response status for '/admin/24876015-de40-af70-8f37-dce2089b1a54/' in 10.011 seconds: 408 Request Timeout
`

**Comment by GitDatei** [comment]
i dont understand on my windows 7 its work fine
but under debian come 408 timeout request, have somebody a idea ?

**Comment by Unrud** [comment]
> have somebody a idea ?

The timeout (10 seconds) happens while reading the HTTP request body (529 bytes).
That's a pretty strange problem and to investigate it further a dump of the network traffic is required.

You can create a dump with something like:
``sudo tcpdump -i any -s 0 -w output.dump tcp port 5232``
The command writes all TCP packets with source or destination port 5232 to the file **output.dump**.

You can either analyse the file yourself (with e.g. [Wireshark](https://www.wireshark.org/)) or upload it here together with the full logging output from Radicale. Keep in mind that the dump contains IP and MAC addresses, you can use [TraceWrangler](https://www.tracewrangler.com/) to anonymize them

> `` 'HTTP_COOKIE': 'PHPSESSID=a9te...',``

HTTP cookies are shared across all ports on a host. This is the session id for some other service that you are running on the same computer. You can use the incognito mode of your browser to prevent it from sending existing cookies.

**Comment by GitDatei** [comment]
i look with wireshark, the request have 337 byte 
timeout request on wireshark file is No.870
Maybe you find something in the record

**Comment by Unrud** [comment]
> Maybe you find something in the record

Where is the file?

**Comment by GitDatei** [comment]
sry i uploaded the file,now

**Comment by Unrud** [comment]
> Maybe you find something in the record

The browser sends the header of the MKCOL request and then just stops sending data.
Does this only happen with Firefox or also with other browsers?
Does it work with Firefox in [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode#w_how-to-start-firefox-in-safe-mode)?
Do you have any virus scanner or similar that manipulates network traffic?

**Comment by GitDatei** [comment]
Firefox & IE
no isnt safe mode
no i dont have virus scanner or others.

but under Windows7 in same Network it work fine

**Comment by Unrud** [comment]
The problem is not caused by Radicale. My best guess is that some software is running on your computer, that manipulates network connection.

> no i dont have virus scanner or others.

A virus scanner that intercepts HTTP connections to scan downloads for viruses, could have been a possible culprit.

**Comment by GitDatei** [comment]
its very crazy , its work now
I didn't change anything

**Comment by pbiering** [comment]
if reproducable with current version, please reopen
