### ISSUE TITLE
Separate and *large* ICS file being created for each event

### ISSUE THREAD

**Issue by tmst** [Kozea/Radicale#682]
Using the OpenSuse binary package for 2.1.4.

Perhaps having a separate ICS file for each event conforms to the CalDAV or iCal spec. But these are each taking up nearly 5k of space on my file system, which gets rounded up to 8K. So 1000 events would mean 1000 files? And 8M of disk space? I'm really wondering how performant this can be.

My current setup using an older (0.7) version of Radicale seems to use approx 1K per event.

Attached is an ICS file for an event created with KOrganizer using its DAV Groupware calendar resource.

[1502269025.R568.ics.gz](https://github.com/Kozea/Radicale/files/1210971/1502269025.R568.ics.gz)

**Comment by Unrud** [comment]
> I'm really wondering how performant this can be.

Instead of wondering we can measure it. I created a calendar that contains your example event a 1000 times.

Here are the results for Radicale 2.1.4 (the brackets contain the approximate memory usage):

Disk usage: 15688 kB
```
Type: PROPFIND_getetag (initialize cache)
Result: 86.8 seconds ( 2336 kB)

Type: PROPFIND_getetag
Result:  0.1 seconds (    0 kB)

Type: REPORT_calendar-query_getetag
Result:  0.1 seconds ( 1668 kB)

Type: REPORT_calendar-multiget_getetag
Result:  0.1 seconds ( 2056 kB)

Type: REPORT_calendar-multiget_calendar-data
Result:  0.1 seconds (12328 kB)

Type: REPORT_calendar-query_filter-all_getetag
Result:  0.1 seconds ( 1608 kB)

Type: REPORT_calendar-query_filter-none_getetag
Result:  0.1 seconds (  488 kB)

Type: GET
Result:  0.2 seconds (  536 kB)
```

Here are the results for Radicale 1.1.6:

Disk usage: 345 kB
```
Type: PUT_collection
Result:  0.0 seconds ( 3768 kB)

Type: PROPFIND_getetag
Result:  0.0 seconds ( 1760 kB)

Type: REPORT_calendar-query_getetag
Result:  0.1 seconds (10944 kB)

Type: REPORT_calendar-multiget_getetag
Result:  0.1 seconds (12652 kB)

Type: REPORT_calendar-multiget_calendar-data
Result:  0.2 seconds (98508 kB)

Type: REPORT_calendar-query_filter-all_getetag
Result:  0.1 seconds (10948 kB)

Type: REPORT_calendar-query_filter-none_getetag
Result:  0.0 seconds ( 6788 kB)

Type: GET
Result:  0.0 seconds ( 3356 kB)
```

The results are quiet similar. Radicale 1.x.x uses significant more memory. Also keep in mind that Radicale 1.x.x is missing some features (e.g. it doesn't do any locking of the storage, just ignores most filter and doesn't check calendar components for errors).

The real difference comes to light when the disk cache is dropped between requests. On Radicale 2.1.x it adds about 2.5-5 seconds to each requests, on 1.x.x it only adds 0.1-0.3 seconds. Radicale 1.x.x only has to load one file and 2.1.x has to load 2000 files. The access time of my HDD is pretty bad (~15 ms), on a SSD the difference should be much smaller. I don't think that the actual size on disk (15688 kB vs. 345 kB) has an impact on performance.

**Comment by tmst** [comment]
On Wed, 09 Aug 08:45:08 AM Unrud wrote:
> Instead of wondering we can measure it. I created a calendar that contains
> your example event a 1000 times.
> 
> Here are the results for Radicale 2.1.4 (the brackets contain the
> approximate memory usage):
> 
> Disk usage: 15688 kB

Thanks. I didn't expect test results!

Other than startup times I don't see a real problem. Any performance losses 
are counterbalanced by simpler code, increased stability, fewer corrupted 
databases and probably other factors.

**Comment by Tntdruid** [comment]
Odd my events are max 1 kb each, do you have much text in them?

**Comment by tmst** [comment]
On Wed, 09 Aug 12:02:58 PM Tntdruid wrote:
> Odd my events are max 1 kb each, do you have much text in them?

Yes. At least half of each record consists of error text in the TZ portion.

**Comment by tmst** [comment]
On Wed, 09 Aug 07:58:54 PM you wrote:
> On Wed, 09 Aug 12:02:58 PM Tntdruid wrote:
> > Odd my events are max 1 kb each, do you have much text in them?
> 
> Yes. At least half of each record consists of error text in the TZ portion.

Apparently it's just KOrganizer. Basic Thunderbird event files are less than 1k 
(woo hoo!). I guess I need to look at my KDE configuration.

**Comment by tmst** [comment]
Just in case someone wants to take a look at the code and see where the TZ 
thing is getting borked with KDE, I'm attaching screenshots of my KDE 
"calendar" and "date-time" setup.

**Comment by tmst** [comment]
Closing this is fine, but I suspect it will pop up again for KDE users. The problem makes it unusuble for KDE users, as we can't have our data corrupted by massive amounts of timezone error messages inserted into records. Please also note I've been using an earlier version of Radicale for years with all the major clients with no issues.

**Comment by tmst** [comment]
Well, no issues except the server periodically freezing. But I worked around this by setting up a cron job to restart it daily. Since I'm the only user, this is acceptable.

**Comment by Unrud** [comment]
> The problem makes Radicale unusable for KDE users, as we can't have our data corrupted by massive amounts of timezone error messages inserted into records.

Radicale doesn't insert any error messages. One of your clients is at fault here.

> as we can't have our data corrupted by massive amounts of timezone error messages inserted into records

Why is the data corrupted by the messages? It looks like one error message is inserted for every ``RDATE;VALUE=DATE-TIME:...``. They shouldn't cause problems.

**Comment by tmst** [comment]
Here's the VTIMEZONE included in a basic record created with KOrganizer that should be less than 1K but exists on the filesystem as about 5K. There's no way I'm migrating my data consisting of thousands of records to have this happen to each and every one of them:

BEGIN:VTIMEZONE
TZID:America/Los_Angeles
BEGIN:STANDARD
DTSTART:19011213T125254
RDATE;VALUE=DATE-TIME:19011213T125254
TZNAME:PST
TZOFFSETFROM:-075258
TZOFFSETTO:-0800
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
END:STANDARD
BEGIN:STANDARD
DTSTART:19500924T020000
RRULE:FREQ=YEARLY;COUNT=12;BYDAY=-1SU;BYMONTH=9
TZNAME:PST
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
END:STANDARD
BEGIN:STANDARD
DTSTART:19621028T020000
RRULE:FREQ=YEARLY;COUNT=45;BYDAY=-1SU;BYMONTH=10
TZNAME:PST
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
END:STANDARD
BEGIN:STANDARD
DTSTART:20071104T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZNAME:PST
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
END:STANDARD
BEGIN:STANDARD
DTSTART:19181027T020000
RDATE;VALUE=DATE-TIME:19181027T020000
RDATE;VALUE=DATE-TIME:19191026T020000
RDATE;VALUE=DATE-TIME:19450930T020000
RDATE;VALUE=DATE-TIME:19490101T020000
TZNAME:PST
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19500430T010000
RRULE:FREQ=YEARLY;COUNT=17;BYDAY=-1SU;BYMONTH=4
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19760425T020000
RRULE:FREQ=YEARLY;COUNT=11;BYDAY=-1SU;BYMONTH=4
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19870405T020000
RRULE:FREQ=YEARLY;COUNT=20;BYDAY=1SU;BYMONTH=4
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:20070311T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19180331T020000
RDATE;VALUE=DATE-TIME:19180331T020000
RDATE;VALUE=DATE-TIME:19190330T020000
RDATE;VALUE=DATE-TIME:19480314T020100
RDATE;VALUE=DATE-TIME:19670430T020000
RDATE;VALUE=DATE-TIME:19680428T020000
RDATE;VALUE=DATE-TIME:19690427T020000
RDATE;VALUE=DATE-TIME:19700426T020000
RDATE;VALUE=DATE-TIME:19710425T020000
RDATE;VALUE=DATE-TIME:19720430T020000
RDATE;VALUE=DATE-TIME:19730429T020000
RDATE;VALUE=DATE-TIME:19740106T020000
RDATE;VALUE=DATE-TIME:19750223T020000
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19420209T020000
RDATE;VALUE=DATE-TIME:19420209T020000
TZNAME:PWT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DATE-TIME
END:DAYLIGHT
END:VTIMEZONE

**Comment by Tntdruid** [comment]
Looks like KOrganizer is messing stuff up.

**Comment by tmst** [comment]
Whatever condition was causing these large records to be created seems to have gone away and Radicale is now playing well with KOrganizer, both when editing existing records and creating new ones.

I have occasionally observed, when a record is open in KOrganizer, some kind of "Floating" field or notation next to one or more dates or times. I suspect this may be related to the TZ error messages stored in records. I'll try to pay closer attention if I see it again.
