### ISSUE TITLE
1.1.6 --export-storage creates some files with .ics, some without

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [Kozea/Radicale#683]
HI there,

haven't actually made the move to v2 as yet but was just trying out the

`--export-storage= `

option, so as to see what goes on.

I've been running Radicale 1.1.1 for ages now, but ran a 1.1.6
so as to have the `--export-storage= ` option.

I can see that my old one-file-per-calendar files from
`/path/to/collections` have been turned into files within
directories that have the old calendar name but then
noticed that some of the new files have an `.ics` extension
whilst some don't.

Here's the contents of one such directory

```
04845274-4f1f-11e3-1234-00e04d2fd523.ics
04845275-4f1f-11e3-1234-00e04d2fd523.ics
04845276-4f1f-11e3-1234-00e04d2fd523.ics
04845277-4f1f-11e3-1234-00e04d2fd523.ics
04845278-4f1f-11e3-1234-00e04d2fd523.ics
04845279-4f1f-11e3-1234-00e04d2fd523.ics
04845280-4f1f-11e3-1234-00e04d2fd523.ics
04845281-4f1f-11e3-1234-00e04d2fd523.ics
04845282-4f1f-11e3-1234-00e04d2fd523.ics
04845283-4f1f-11e3-1234-00e04d2fd523.ics
04845284-4f1f-11e3-1234-00e04d2fd523.ics
04845285-4f1f-11e3-1234-00e04d2fd523.ics
04845286-4f1f-11e3-1234-00e04d2fd523.ics
04845287-4f1f-11e3-1234-00e04d2fd523.ics
09205654-4f1f-11e3-1234-00e04d2fd523
09205655-4f1f-11e3-1234-00e04d2fd523
09205656-4f1f-11e3-1234-00e04d2fd523
5e91d5df-4ce7-493e-80f3-bffd28c32462.ics
```
Is that to be expected?

Apologies if I have missed someone else asking the
same question, or the docs containing the answer.

**Comment by Unrud** [comment]
> Is that to be expected?

Yes. The UID of the item is used as the filename. The client that creates an item, sets the UID. Radicale doesn't cares about the actual file name.

**Comment by vuw-ecs-kevin** [comment]
> Yes. The UID of the item is used as the filename. The client that creates an item,
> sets the UID. Radicale doesn't cares about the actual file name.

Indeed. I can now see that if I grep for `X-RADICALE-NAME` in the
original one-file-per-calendar file: some of those attributes have
the extension and some don't,

```
X-RADICALE-NAME:04845274-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845275-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845276-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845277-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845278-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845279-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845280-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845281-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845282-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845283-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845284-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845285-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845286-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:04845287-4f1f-11e3-1234-00e04d2fd523.ics
X-RADICALE-NAME:09205654-4f1f-11e3-1234-00e04d2fd523
X-RADICALE-NAME:09205655-4f1f-11e3-1234-00e04d2fd523
X-RADICALE-NAME:09205656-4f1f-11e3-1234-00e04d2fd523
X-RADICALE-NAME:5e91d5df-4ce7-493e-80f3-bffd28c32462.ics
```
and so Radicale has used that attrribute, rather than creating the 
individual filenames from an event's UID  attribute, none of  which,
as one would expect, have an extension, vis:

```
UID:04845274-4f1f-11e3-1234-00e04d2fd523
UID:04845275-4f1f-11e3-1234-00e04d2fd523
UID:04845276-4f1f-11e3-1234-00e04d2fd523
UID:04845277-4f1f-11e3-1234-00e04d2fd523
UID:04845278-4f1f-11e3-1234-00e04d2fd523
UID:04845279-4f1f-11e3-1234-00e04d2fd523
UID:04845280-4f1f-11e3-1234-00e04d2fd523
UID:04845281-4f1f-11e3-1234-00e04d2fd523
UID:04845282-4f1f-11e3-1234-00e04d2fd523
UID:04845283-4f1f-11e3-1234-00e04d2fd523
UID:04845284-4f1f-11e3-1234-00e04d2fd523
UID:04845285-4f1f-11e3-1234-00e04d2fd523
UID:04845286-4f1f-11e3-1234-00e04d2fd523
UID:04845287-4f1f-11e3-1234-00e04d2fd523
UID:09205654-4f1f-11e3-1234-00e04d2fd523
UID:09205655-4f1f-11e3-1234-00e04d2fd523
UID:09205656-4f1f-11e3-1234-00e04d2fd523
UID:5e91d5df-4ce7-493e-80f3-bffd28c32462
```

and so would have allowed Radicale to create a consistent set of filenames
when doing the export?

OK, so in the way that I now think about that, if I wanted all of the files 
stored by Radicale to have a .ics extension (or not to, I suppose) then
I should rename the individual files AND alter the `X-RADICALE-NAME`
attribute within each to match file, or else Radicale will continue to operate 
on the internal value stored in `X-RADICALE-NAME` and expect files of that
name to be there - or Radicale will ignore the `X-RADICALE-NAME`
attribute altogether, once it has the individual files to operate on?

**Comment by Unrud** [comment]
> if I wanted all of the files stored by Radicale to have a .ics extension (or not to, I suppose) then I should rename the individual file

You can rename the files, but it might confuse existing clients.

> AND alter the ``X-RADICALE-NAME`` attribute within each to match file

Radicale 2.x.x ignores this attribute, it was only used by Radicale 1.x.x. Radicale 2.x.x uses the actual file name.
