### ISSUE TITLE
radicale wsgi example script not usable as is

### ISSUE THREAD

**Issue by dorchain** [Kozea/Radicale#685]
Hello,

with version 2.1.4, the supplied radicale.wsgi has some issues when I try to use it:

- in conjunction with libapache2-mod-wsgi-py3 the log says 
> > >  SyntaxError: Non-ASCII character '\\xc2' in file                         
> > >  .../radicale.wsgi on line 4, but no encoding declared; see               
> > >  http://python.org/dev/peps/pep-0263/ for details                         
 Externally a 500 internal error is shown.    

Inserting # coding: utf-8 as second line solves it for me.     
                                                

- it empties out the config path (/etc/radicale/config). To me, it makes more sense to explicitly use the standard config, i.e. make the config_path line read config_paths =["/etc/radicale/config"]

Thanks for considering.

Joerg

**Comment by Unrud** [comment]
> Inserting # coding: utf-8 as second line solves it for me.

UTF-8 is the default encoding for Python 3:  [PEP 3120](https://www.python.org/dev/peps/pep-3120/)
Is this a bug in ``libapache2-mod-wsgi-py3``?

> To me, it makes more sense to explicitly use the standard config

The WSGI specification doesn't define a method for providing configuration options. Radicale uses environment variables, like many other WSGI applications. Unfortunately you can't set them easily with Apache mod_wsgi. As a workaround we could change the WSGI script to defer initialization until the first request, so that ``SetEnv`` can be used.

**Comment by dorchain** [comment]
> UTF-8 is the default encoding for Python 3: PEP 3120
> Is this a bug in libapache2-mod-wsgi-py3?

I'll check.

> The WSGI specification doesn't define a method for providing configuration options. Radicale uses environment variables, like many other WSGI applications. Unfortunately you can't set them easily with Apache mod_wsgi. As a workaround we could change the WSGI script to defer initialization until the first request, so that SetEnv can be used.

I still think that it is least surprising to use the config from /etc/radicale/config also for the wsgi module.

**Comment by MasterRay2** [comment]
Environment variables in Apache2 can be set in /etc/apache2/envvars.

**Comment by return42** [comment]
Here are my two cents ... check your LANG settings see http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html option ```lang=locale``` ..

> Set the current language locale. This is the same as having set the LANG  environment variable. You will need to set this on many Linux systems where Apache when started up from system init scripts uses the default C locale, meaning that the default system encoding is ASCII. Unless you need a special language locale, set this to en_US.UTF-8.
>

mostly you will find an ```export LANG``` in your ```/etc/apache2/envvars```, e.g.:

```
## Uncomment the following line to use the system default locale instead:
. /etc/default/locale
export LANG
````
if so check your ```/etc/default/locale``` ... hope it helps.

**Comment by dorchain** [comment]
You were right: A closer inspection of my apache envvars revealed historic LANG=C entry, whereas the rest of the system uses C.UTF-8.

I'll also set the RADICALE_CONFIG=/etc/radicale/config there.

IMHO the RADICALE_CONFIG for the wsgi use could mention apach envvars as an example on http://radicale.org/wsgi/.

Thanks for the excellent help!

**Comment by return42** [comment]
> I'll also set the RADICALE_CONFIG=/etc/radicale/config there.
> IMHO the RADICALE_CONFIG for the wsgi use could mention apach envvars as an example on http://radicale.org/wsgi/.

IMO since apache's SetEnv can't be used for this approach, getting config from environment is not best practice. In the ```radicale.wsgi``` I replaced::

```config_paths.append(os.environ["RADICALE_CONFIG"]) ``` by 
```config_paths = ["/etc/radicale/config",] ```

and here is my apache-site https://gist.github.com/return42/47ac8aabd19eaad0f10979761d0611a1
