### ISSUE TITLE
Interface only shows "it works!"

### ISSUE THREAD

**Issue by Re4mstr** [Kozea/Radicale#686]
Greetings.

I have set up Radicale with the documentation available, and as far as I can tell, the service is running.
My server is on a RPi3.

When I open the localhost:x URL in my browser, though, I can only seem to meet the "it works!" wall...

The config file did not come with a [web] section, which I added in, but to no avail.

Reopened:
I do not get any instructions on how to create my calendars

**Comment by Re4mstr** [comment]
Little did I know, changing open for all to user based setup activated the rest of the interface.

**Comment by Unrud** [comment]
Have you installed the latest version? Radicale < 2.1.0 doesn't have a web interface.
You can check the version with:
```shell
$ python3 -m radicale --version
```
(The Debian repository contains a old version.)
