### ISSUE TITLE
Can't add contact pictures

### ISSUE THREAD

**Issue by herrwusel** [Kozea/Radicale#687]
I upgraded to latest version 2 recently and I cant get contact photos to work.
Here is my Setup:
PC with Thunderbird(Cardbook) and an Android phone with davdroid.
I created a new adressbook and a test-contact.
Whenever I change a contact's photo sync doesn't work anymore. It doesn't matter if I change it on my phone or PC. Cardbook is giving me this error then:
https://pastebin.com/xiRjFW5P

**Comment by Unrud** [comment]
> I created a new adressbook and a test-contact.
> Whenever I change a contact's photo sync doesn't work anymore.

I created a new address book and added it to Cardbook (vCard: 3.0). Then I created a new contact in Cardbook with a photo and synced the address book. Next I edited the contact, changed the photo and synced the address book again. It works for me.

Can you start Radicale with the ``--debug`` argument, reproduce the error and post the logging output here?

> Cardbook is giving me this error then:

The data of the picture is corrupted or incomplete.

**Comment by herrwusel** [comment]
> Can you start Radicale with the --debug argument, reproduce the error and post the logging output here?

I'm going to. Another question before I try to reproduce: where does radicale get the "server_name" from? Never configured something and it seems weird to me.

**Comment by Unrud** [comment]
I think that I can reproduce the problem. It seems to be some kind of bug in Python <= 3.4 that is triggered by setting a timeout on a socket. Update to a newer version of Python (or as a workaround start Radicale with the argument ``--server-timeout 0``).

The problem is a race-condition, which seems to depend on the speed of the computer and network.

**Comment by herrwusel** [comment]
Updated to Python 3.5 and it fixed my issue. Thanks for the help!
