### ISSUE TITLE
Listing syntactically incorrect files

### ISSUE THREAD

**Issue by szotsaki** [Kozea/Radicale#690]
Switching to Radicale 2 from Radicale 1 brought a lot stricter error checking. Radicale 2 won't serve clients at all when malformed files are present (see e.g. #652) . I now have an other one, too: `Failed to load item 'libkcal-880775651.422.ics' in  'calendar': can't compare offset-naive and offset-aware datetimes` and possibly many more different kinds are present.

Since they are old entries, I don't mind deleting the syntactically incorrect ones but doing it one-by-one (when in #652 there were more than a thousand of ill-formed files) is a never ending story.

Can you please somehow list the wrong files (perhaps with a `--switch`) to be able to delete or move them at once?

**Comment by Unrud** [comment]
Done: ``--verify-storage``
