### ISSUE TITLE
Radicale 2.1.4 and caldav-sync (android client) not happy together

### ISSUE THREAD

**Issue by vuntz** [Kozea/Radicale#691]
I'm trying to move from radicale 1.x to 2.x. Everything went fine, until I tried using the caldav-sync client on Android. What seems to happen is that responses to PROPFIND requests are too slow (110s for one calendar with 124 entries, 150s for another with 171 entries) and the client seems to have a timeout of 60s after which it sends another PROPFIND. This seems to enver end, and eats all the CPU.

Part of it is definitely caldav-sync which should stop after 3-5 attempts. But still, this is extremely slow. Note that it's not just for the first request that it's slow, so it somehow feels like the cache is not working.

**Comment by vuntz** [comment]
And FWIW, the PROPFIND requests for evolution are pretty fast (< 1s), so the cache does work there, I guess.

**Comment by Unrud** [comment]
Start Radicale with the ``--debug`` argument, synchronize with caldav-sync and post the logging output here.
Create a new calendar with some test events, to avoid having private information in the log.

**Comment by vuntz** [comment]
[radicale-debug-full.txt](https://github.com/Kozea/Radicale/files/1256805/radicale-debug-full.txt)

This is the complete log for a dummy account with 12 (valid) events. The log goes from registering this calendar in the app from the first time to synchronization (happening automatically after successful registration). It works fine, even if it's (relatively) slow.

[radicale-debug-107.txt](https://github.com/Kozea/Radicale/files/1256806/radicale-debug-107.txt)

And this one is the log for the same account that I populated with 107 events. And here it just doesn't work. (So I stopped after ~3 minutes)

**Comment by Unrud** [comment]
CalDAV-Sync reads the ``DAV:getcontenttype`` property, which is not cached. It was an oversight and is easy to fix.

**Comment by vuntz** [comment]
Reading the debug, I see in the response tags like `<getetag>"74457fc37af943c17d900fe2ab7aabbc"</getetag>`. Are the quotes really expected here?

**Comment by Unrud** [comment]
> Are the quotes really expected here?

Yes. RFC 2616 quoted-string

**Comment by Unrud** [comment]
The problem should be fixed. Can you try the development version?

**Comment by vuntz** [comment]
Sorry, I tried back then and it didn't work, but I didn't have time to collect proper logs. I tried again with 2.1.7, and it seems to be fine from that perspective now. Thanks!

I'll do some more testing, as I see that people have more issue (https://github.com/Kozea/Radicale/issues/710)
