### ISSUE TITLE
Can a user's access to their own collection not be Read Only?

### ISSUE THREAD

**Issue by JRHutson** [Kozea/Radicale#693]
Trying to leverage Radicale to distribute a contact list to different groups of users on iOS. For simplicity I wanted to set up a user for each group and set it's access to be read only. The lists will be maintained by an admin and that way there would be no chance of a user editing something they shouldn't.

My teammate who is setting things up states that a user must have write permission for their own collection or the client/server connection will fail. Is there a reason for this? Is there a workaround?

If this isn't the best place to seek help, let me know.

Thanks.

**Comment by JRHutson** [comment]
Basically, I'm trying to figure out if setting the below should work or not.

[owner]
user: .+
collection: %(login)s/.*
permission: r

**Comment by Unrud** [comment]
> My teammate who is setting things up states that a user must have write permission for their own collection or the client/server connection will fail.

It depends on the client. You have to test if it works with iOS.

> Basically, I'm trying to figure out if setting the below should work or not.

You also have to grant access to the ``/`` and ``/USER`` collection. Use something like:

```ini
collection: (%(login)s(/.*)?)?
```

**Comment by JRHutson** [comment]
Thanks for the input. 

From testing, access does not work on iOS unless the user has read/write access to their collection.

Could not get access to a collection other than the user's via iOS either.

**Comment by Unrud** [comment]
> Could not get access to a collection other than the user's via iOS either.

That's expected. From the documentation:

> The recommended rights method is `owner_only`. If access to calendars
and address books outside of the home directory of users (that's `/USERNAME/`)
is granted, clients won't detect these collections and will not show them to
the user.
This is only useful if you access calendars and address books directly via URL.

Calendar sharing is not supported by Radicale (#696).

**Comment by pbiering** [comment]
in current version such scenario should be possible, see https://github.com/Kozea/Radicale/wiki/Sharing-Collections
