### ISSUE TITLE
caldav-sync Breaks down

### ISSUE THREAD

**Issue by tiket18** [Kozea/Radicale#695]
Theme - installed and started the server. System - Arch. Errors at startup do not produce. I'm creating a new calendar = ok. I connect the calendar to the phone = ok. I connect the calendar to the laptop (Thun) = ok. I create an event in the laptop's calendar = ok, the event appears on the server = ok, the event does not appear in the phone.
Now on the contrary - I create an event in the phone = ok, the event appears on the server, the event appears in the laptop. I import a small calendar in the laptop = ok, the server appears on the server. In the phone = no. In the logs - silence.

```
python3 -m radicale --debug
[7f87780824c0] INFO: Starting Radicale
[7f87780824c0] INFO: Authentication type is 'htpasswd'
[7f87780824c0] INFO: Storage type is 'multifilesystem'
[7f87780824c0] INFO: Rights type is 'owner_only'
[7f87780824c0] INFO: Web type is 'internal'
[7f87780824c0] INFO: Listening to 'server.name' on port 9919
[7f87780824c0] INFO: Radicale server ready
```

I appeal to the same address -
http://192.168.1.21:9919

And why does not it create a token on my server? - this is when the laptop is successfully synchronized

```
[7f87706e9700] DEBUG: Client provided sync token: 'http://radicale.org/ns/sync/dbcf77ef15d0a98d383e4882b4f30b7a'
[7f87706e9700] DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:">
  <sync-token>http://radicale.org/ns/sync/dbcf77ef15d0a98d383e4882b4f30b7a</sync-token>
</multistatus>
```

although here, the logs began to speak, when you try to synchronize your phone -

```
[7f87706e9700] DEBUG: Sanitized script name: ''
[7f87706e9700] DEBUG: Sanitized path: '/tiket18/a032483a-c65b-4071-ab76-b84af4717f18/'
[7f87706e9700] INFO: Successful login: 'tiket18'
[7f87706e9700] DEBUG: Request content:
<?xml version="1.0"?>
<propfind xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/">
  <prop>
    <supported-report-set />
    <ICAL:refreshrate />
    <displayname />
    <current-user-privilege-set />
    <CS:source />
    <C:managed-attachments-server-URL />
    <add-member />
    <CS:getctag />
    <ICAL:calendar-color />
    <C:max-attachments-per-resource />
    <C:supported-calendar-component-set />
    <C:max-attachment-size />
    <sync-token />
  </prop>
</propfind>

[7f87706e9700] DEBUG: 'tiket18' has read and write access to collection 'tiket18/a032483a-c65b-4071-ab76-b84af4717f18'
[7f87706e9700] DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/">
  <response>
    <href>/tiket18/a032483a-c65b-4071-ab76-b84af4717f18/</href>
    <propstat>
      <prop>
        <supported-report-set>
          <supported-report>
            <report>
              <expand-property />
            </report>
          </supported-report>
          <supported-report>
            <report>
              <principal-search-property-set />
            </report>
          </supported-report>
          <supported-report>
            <report>
              <principal-property-search />
            </report>
          </supported-report>
          <supported-report>
            <report>
              <sync-collection />
            </report>
          </supported-report>
          <supported-report>
            <report>
              <C:calendar-multiget />
            </report>
          </supported-report>
          <supported-report>
            <report>
              <C:calendar-query />
            </report>
          </supported-report>
        </supported-report-set>
        <displayname>https </displayname>
        <current-user-privilege-set>
          <privilege>
            <read />
          </privilege>
          <privilege>
            <all />
          </privilege>
          <privilege>
            <write />
          </privilege>
          <privilege>
            <write-properties />
          </privilege>
          <privilege>
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <CS:getctag>"b554d11bd0532144f46dd8bf300a1c05"</CS:getctag>
        <ICAL:calendar-color>#FF6D00FF</ICAL:calendar-color>
        <C:supported-calendar-component-set>
          <C:comp name="VEVENT" />
        </C:supported-calendar-component-set>
        <sync-token>http://radicale.org/ns/sync/d41d8cd98f00b204e9800998ecf8427e</sync-token>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <ICAL:refreshrate />
        <CS:source />
        <C:managed-attachments-server-URL />
        <add-member />
        <C:max-attachments-per-resource />
        <C:max-attachment-size />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
</multistatus>

[7f87706e9700] INFO: PROPFIND response status for '/tiket18/a032483a-c65b-4071-ab76-b84af4717f18/' with depth '0' in 0.019 seconds: 207 Multi-Status
```

**Comment by Unrud** [comment]
> caldav-sync Breaks down

Do you mean [CalDAV-Sync](https://play.google.com/store/apps/details?id=org.dmfs.caldav.lib)? I've no experience with it.

> In the phone = no. In the logs - silence.

That means that the phone is not connecting to Radicale. **CalDAV-Sync** is not even trying to synchronize.

> And why does not it create a token on my server?

Not all clients use sync-token.

**Comment by tiket18** [comment]
yes, CalDAV-Sync.

**Comment by tiket18** [comment]
And what is the working synchronization client for Android?

**Comment by Unrud** [comment]
The log looks like the calendar is already synced. CalDAV-Sync doesn't download additional items.

I've fixed a bug that caused Radicale to send the wrong component type in **getcontenttype**. It's possible that CalDAV-Sync ignored the events because it didn't recognize the type.
Can you try the development version?

**Comment by tiket18** [comment]
In fact, the issue has lost its relevance - I made Davdroid work, https://davdroid.bitfire.at/faq/entry/miui-no-synchronization/. And caldavsync I deleted, all calendars perfectly synchronized. Your server is just perfect, thanks - it works fine on very weak hardware.
In the Git, I see the version of Master, 1.0, 1.1 and 2. I do not see "dev".

**Comment by Unrud** [comment]
I mean the "master" branch.

**Comment by tiket18** [comment]
сейчас попробую.

**Comment by tiket18** [comment]
'_': '/usr/bin/python3',
 'wsgi.errors': <_io.StringIO object at 0x7fe3cbdd35e8>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[7fe3cac93700] DEBUG: Sanitized script name: ''
[7fe3cac93700] DEBUG: Sanitized path: '/'
[7fe3cac93700] INFO: Successful login: 'tiket18'
[7fe3cac93700] DEBUG: Request content:
<?xml version="1.0"?>
<propfind xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/">
  <prop>
    <CS:source />
    <displayname />
    <resourcetype />
    <current-user-privilege-set />
    <resource-id />
    <ICAL:refreshrate />
    <C:supported-calendar-component-set />
    <getetag />
    <ICAL:calendar-color />
  </prop>
</propfind>

[7fe3cac93700] DEBUG: 'tiket18' has read access to collection ''
[7fe3cac93700] DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/">
  <response>
    <href>/</href>
    <propstat>
      <prop>
        <resourcetype>
          <collection />
        </resourcetype>
        <current-user-privilege-set>
          <privilege>
            <read />
          </privilege>
        </current-user-privilege-set>
        <getetag>"99914b932bd37a50b983c5e7c90ae93b"</getetag>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <CS:source />
        <displayname />
        <resource-id />
        <ICAL:refreshrate />
        <C:supported-calendar-component-set />
        <ICAL:calendar-color />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
</multistatus>

[7fe3cac93700] INFO: PROPFIND response status for '/' with depth '0' in 0.016 seconds: 207 Multi-Status

A message appeared on the phone's screen (this was not the case before) - "error: it seems this URL points to an unsupported calendar"


20170829T202110Z I org.dmfs.caldav.autheticator.AuthenticatorActivity calendar discovery log:
20170829T202110Z V org.dmfs.dav.Dav get principal /.well-known/caldav
20170829T202110Z V org.dmfs.dav.methods.DavPropFind Status: 404
20170829T202110Z V org.dmfs.dav.methods.DavPropFind The requested resource could not be found.
20170829T202110Z V org.dmfs.dav.Dav could not locate current user principal at /.well-known/caldav
20170829T202110Z V org.dmfs.dav.Dav get principal /SOGo/dav/
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Status: 403
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Access to the requested resource forbidden.
20170829T202111Z V org.dmfs.dav.Dav could not locate current user principal at /SOGo/dav/
20170829T202111Z V org.dmfs.dav.Dav get principal /groupdav.php/
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Status: 403
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Access to the requested resource forbidden.
20170829T202111Z V org.dmfs.dav.Dav could not locate current user principal at /groupdav.php/
20170829T202111Z V org.dmfs.dav.Dav get principal /dav/
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Status: 403
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Access to the requested resource forbidden.
20170829T202111Z V org.dmfs.dav.Dav could not locate current user principal at /dav/
20170829T202111Z V org.dmfs.dav.Dav get principal /caldav/
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Status: 403
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Access to the requested resource forbidden.
20170829T202111Z V org.dmfs.dav.Dav could not locate current user principal at /caldav/
20170829T202111Z V org.dmfs.dav.Dav get principal /principals/
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Status: 403
20170829T202111Z V org.dmfs.dav.methods.DavPropFind Access to the requested resource forbidden.
20170829T202111Z V org.dmfs.dav.Dav could not locate current user principal at /principals/
20170829T202111Z V org.dmfs.dav.Dav get principal /
20170829T202112Z I org.dmfs.dav.Dav found principal: /tiket18/
20170829T202112Z V org.dmfs.dav.CalDav get calendars https://188.143.213.150/tiket18/
20170829T202112Z V org.dmfs.dav.CalDav found calendar user address /tiket18/
20170829T202112Z V org.dmfs.dav.CalDav looking for calendars in https://188.143.213.150/tiket18/
20170829T202112Z V org.dmfs.dav.methods.DavPropFind Status: 500
20170829T202112Z V org.dmfs.dav.methods.DavPropFind A server error occurred.  Please contact the administrator.
20170829T202112Z V org.dmfs.dav.CalDav additionally looking for calendar in
20170829T202112Z V org.dmfs.dav.CalDav resourcetypes DAV::collection


App: org.dmfs.caldav.lib
App version: 0.4.27
OS version: 24
OS Info: Xiaomi/capricorn/capricorn:7.0/NRD90M/7.8.24:user/release-keys
Manufacturer: Xiaomi
Date: Tue Aug 29 23:23:38 GMT+03:00 2017

**Comment by Unrud** [comment]
Can you provide the full logging output from Radicale?

> ``20170829T202112Z V org.dmfs.dav.methods.DavPropFind Status: 500``

That error is missing from the log.

**Comment by tiket18** [comment]
It is a fragment of the log caldavsync. full log can not - it is huge.

**Comment by Unrud** [comment]
> full log can not - it is huge.

You can attach it as a file.

**Comment by tiket18** [comment]
I think that you do not need to spend time adapting to the program of the caldavsyc, it even works worse with the server. Your server works fine with a DavDroid - that's nice.

**Comment by tmst** [comment]
I've been using CalDAV-Sync for several years with Radicale and also Google and Fastmail, and am quite happy with it. Fastmail goes so far as to specifically recommend it for use with their services:

"**Set up your calendar**
Android does not support CalDAV natively, however you can easily add support by installing a CalDAV sync adapter. We have tested and recommend CalDAV-Sync, which is approximately $3. Once you have added your account in CalDAV-Sync, you can use the native Android calendar or any other calendar app and the changes will sync with FastMail."

**Comment by Unrud** [comment]
> I think that you do not need to spend time adapting to the program of the caldavsyc, it even works worse with the server.

I just don't want to release a new version that breaks something.

**Comment by Unrud** [comment]
According to https://github.com/Kozea/Radicale/issues/710#issuecomment-331002160 this is fixed.

**Comment by tmst** [comment]
That's correct. Now CalDAV-compatible! But all I've checked so far is tasks...

**Comment by tmst** [comment]
And, again, DAVdroid loses task categories last I checked on 17 Sept.

**Comment by tiket18** [comment]
yes, thank you, everything works fine

**Comment by tmst** [comment]
DAVdroid no longer loses task categories?

**Comment by tiket18** [comment]
I do not know this - I do not use categories of tasks
