### ISSUE TITLE
Getting single .ics with 2.x.x, possible?

### ISSUE THREAD

**Issue by sledgehammer999** [Kozea/Radicale#698]
Hey guys, congrats on this super helpful and possibly lightweight caldav server.

I've been using the 1.0.x series for a few months now.
Today I saw the new 2.0.x releases. Read the migration guide and did a test with `--export-storage`.
However, I am bit disapointed in the new and only storage backend. It seems to split the .ics into several smaller ones.

Is there a way to make it also generate a single .ics per calendar/collection?

2 reasons I need it. On one of my linux machines I use `orage` to view/manage the calendar. Unfortunately `orage` doesn't support caldav. It can however detect file changes to a local file. So in my caldav server machine I also run `syncthing` and I synced the single .ics file to my `orage` machine. Now that workflow isn't possible.
The 2nd reason is that it is far easier to setup automatic backups of a single file with known filename than multiple new ones with uknown names.

**Comment by Unrud** [comment]
> Is there a way to make it also generate a single .ics per calendar/collection?

You can open the URL of the collection directly, to download the whole calendar/addressbook as a single file (e.g. http://localhost:5232/user/calendar/). This is for clients that don't support CalDAV/CardDAV or to export the calendar/addressbook.

> So in my caldav server machine I also run ``syncthing`` and I synced the single .ics file to my ``orage`` machine.

I see two possibilities:

  - You can automatically export an ``.ics`` file every time the calendar changes by using the ``hook`` configuration option:
    ```ini
    [storage]
    hook = curl --user 'user:password' --silent 'http://localhost:5232/user/calendar/' --output '/path/to/Sync/calendar.ics' &
    ````
    The ``&`` at the end is important!
  - You can sync the file system folder of Radicale with ``syncthing`` and run a second instance of Radicale on your ``orage`` machine. You have to add ``(?d).Radicale.cache`` and ``(?d).Radicale.tmp.*`` to ``.stignore``.

> The 2nd reason is that it is far easier to setup automatic backups of a single file with known filename than multiple new ones with uknown names.

You have to backup the whole folder.
```shell
tar -cf backup.tar /path/to/radicale/collections
```

**Comment by sledgehammer999** [comment]
Ok thanks for the quick reply. My initial question is answered so I am closing this.
I'll look into the hook thing.

In the meantime, maybe someone will code a storage plugin for this :p

**Comment by sledgehammer999** [comment]
>hook = curl --user 'user:password' --silent 'http://localhost:5232/user/calendar/' --output '/path/to/Sync/calendar.ics' &

My only gripe is that I wouldn't like to have my password saved in plaintext in the same machine as the server.

**Comment by zootboy** [comment]
In the current version of Radicale, there is a nicer way to present a calendar as a read-only single-file ics without a password. No hooks or plaintext passwords needed. I needed this to import a calendar into Google cal, since they don't provide a mechanism for supplying credentials to a URL import.

This assumes that you have a calendar already set up in Radicale with username authentication.

Set up the /etc/radicale/rights file to emulate the "user_only" plugin, but add an additional stanza allowing GET permission to a specially-named collection:
```
# Allow reading root collection for authenticated users
[root]
user: .+
collection:
permissions: R

# Allow reading and writing principal collection (same as username)
[principal]
user: .+
collection: {user}
permissions: RW

# Allow reading and writing calendars and address books that are direct
# children of the principal collection
[calendars]
user: .+
collection: {user}/[^/]+
permissions: rw

# Allow GET to a special ro-cal collection URL
[ro-calendars]
user: .*
collection: ro-cal/[^/]+
permissions: i
```

Change your /etc/radicale/config to use the rights file:
```
[rights]
type = from_file
file = /etc/radicale/rights
```

Now create the special directory and symlink the desired calendars into it:
```
# mkdir /var/lib/radicale/collections/collection-root/ro-cal
# ln -s /var/lib/radicale/collections/collection-root/<USERNAME>/<CALENDER-COLLECTION-NAME> /var/lib/radicale/collections/collection-root/ro-cal/<SUPER-SECRET-STRING>
```

Restart Radicale, then you can access the ics file like so:
```
http[s]://<RADICALE-HOST>/ro-cal/<SUPER-SECRET-STRING>
```
