### ISSUE TITLE
Radicale 2.1.5 complains about overwritten RRULESET

### ISSUE THREAD

**Issue by felixfontein** [Kozea/Radicale#700]
Yesterday I tried upgrading from Radicale 2.1.0 to 2.1.5, and noticed that it has problems parsing some .ics files. This is probably related to the changes for #630. I don't know much about the .ics file format, but I think that at least some of them should not trigger an error. Here are three examples:

```
BEGIN:VCALENDAR
PRODID:-//Radicale//NONSGML Radicale Server//EN
VERSION:2.0
BEGIN:VTIMEZONE
[... over 800 lines describing switches between summer and winter time ...]
END:VTIMEZONE
BEGIN:VEVENT
UID:20140608T201500Z-17864-1000-17861-2199@mymachine
DTSTAMP:20140608T192241Z
DTSTART:20141201T000000
DTEND:20141202T000000
TRANSP:TRANSPARENT
SEQUENCE:3
SUMMARY:Firstname Lastname
CLASS:PUBLIC
CREATED:20140609T112924Z
LAST-MODIFIED:20140609T112924Z
X-RADICALE-NAME:20140608T201500Z-17864-1000-17861-2199_mymachine-20140609T112924Z.ics
RECURRENCE-ID;VALUE=DATE:20141130
RRULE:FREQ=YEARLY
END:VEVENT
END:VCALENDAR
```
(The full file is available at https://felix.fontein.de/store/1.ics)

```
BEGIN:VCALENDAR
PRODID:-//Radicale//NONSGML Radicale Server//EN
VERSION:2.0
BEGIN:VEVENT
CREATED:20140609T113304Z
UID:117A864A-2A08-4AA0-906A-58675257D83E
DTEND:20140401T000000
TRANSP:OPAQUE
SUMMARY:Firstname Lastname
DTSTART:20140331T000000
DTSTAMP:20140608T200653Z
LOCATION:1977
SEQUENCE:3
X-RADICALE-NAME:117A864A-2A08-4AA0-906A-58675257D83E-20140609T113304Z.ics
RECURRENCE-ID;VALUE=DATE:20140330
CLASS:PUBLIC
RRULE:FREQ=YEARLY
LAST-MODIFIED:20140609T113304Z
BEGIN:VALARM
X-WR-ALARMUID:AEE016D9-631B-4E22-8918-F0434849457E
UID:AEE016D9-631B-4E22-8918-F0434849457E
TRIGGER;VALUE=DATE-TIME:19760401T005545Z
ACTION:NONE
X-RADICALE-NAME:117A864A-2A08-4AA0-906A-58675257D83E-20140609T113304Z.ics
X-EVOLUTION-ALARM-UID:20140609T112553Z-1026-1000-1-196@mymachine
END:VALARM
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Zurich
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:MESZ
TZOFFSETTO:+0200
X-RADICALE-NAME:Europe/Zurich
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:MEZ
TZOFFSETTO:+0100
X-RADICALE-NAME:Europe/Zurich
END:STANDARD
X-RADICALE-NAME:Europe/Zurich
END:VTIMEZONE
END:VCALENDAR
```
(Available at https://felix.fontein.de/store/2.ics)

The third example is more complex (450 lines of event information after removing 4050 lines of timezone information), so I don't want to paste it here. It is available at https://felix.fontein.de/store/3.ics. Since it is quite complex I'm not sure whether it is OK, but with earlier versions it worked fine.

**Comment by Unrud** [comment]
The files ``1.ics`` and ``2.ics`` fail because of the line ``RECURRENCE-ID;...``. It's used to specify a specific instance of a recurring event (and override it). The problem is that the event itself is the recurring event.

The file ``3.ics`` fails because ``DTSTART`` is specified as non-local ``DATE-TIME`` (with timezone information) but ``EXDATE`` is specified as ``DATE``. I couldn't find this case in the specification and I don't know how this should be interpreted or if it's even valid. Anyway, you have to report the issue to [VObject](https://github.com/eventable/vobject).

**Comment by felixfontein** [comment]
Thanks for your reply! I guess these entries were generated by broken clients, then. I'll delete and try to recreate them.

**Comment by pbiering** [comment]
broken client issue circumvented by https://github.com/Kozea/Radicale/pull/1643
