### ISSUE TITLE
Listen on a Unix Socket? 

### ISSUE THREAD

**Issue by dominic-p** [Kozea/Radicale#703]
Would it be possible to support listening on a Unix Socket file instead of a TCP port? When running behind a reverse proxy it would be a nice feature to have. Plus, systemd can handle setting up the directory for the file under /run easily. 

Thanks for the great app by the way.

**Comment by Unrud** [comment]
> Would it be possible to support listening on a Unix Socket file instead of a TCP port?

It's not supported by the built-in server. You can use it with an external WSGI server (e.g. [uWSGI](https://uwsgi-docs.readthedocs.io)).

**Comment by dominic-p** [comment]
Thanks for the quick reply. I will look into uWSGI. Could you point me to any documenation on using an external WSGI server? I found [this page](http://radicale.org/wsgi/), but it wasn't clear to me if that was relevant to this issue or how the `[server]` block should be configured in this scenario.

**Comment by Unrud** [comment]
> Most configuration options in this category are only relevant in standalone mode. All options beside max_content_length and realm are ignored, when Radicale runs via WSGI.

From the [documentation](http://radicale.org/configuration/):

> Most configuration options in this category are only relevant in standalone mode. All options beside ``max_content_length`` and ``realm`` are ignored, when Radicale runs via WSGI.

> I found [this page](http://radicale.org/wsgi/), but it wasn't clear to me if that was relevant to this issue

I added an example configuration for uWSGI.

**Comment by dominic-p** [comment]
Thanks for that. I really appreciate it.
