### ISSUE TITLE
Failed to load item cache entry: not enough values to unpack

### ISSUE THREAD

**Issue by Xylaw** [Kozea/Radicale#704]
My logfile (Radicale 2.1.6) shows many entries like the following:

`WARNING: Failed to load item cache entry '189EBBAD-A328-4C79-9800-B24B390DB52D.ics' in 'bob/9dc21959-9162-ffd7-b048-a32b2a78a235': not enough values to unpack (expected 8, got 7)`

What does that mean?

Could you help me fixing this problem or can I ignore this warnings?

thx

**Comment by felixfontein** [comment]
I had that too when upgrading; I think you can safely ignore these warnings as Radicale apparently recreates the cache entries when this happens. I was able to force Radicale to rebuild all cache entries by running it with command line option `--verify-storage`. (That also found some calender entries which are no longer valid with the newest version.)

**Comment by Xylaw** [comment]
I followed your recommendation and executed `--verify-storage`. After restarting Radicale, there are no more warnings in the log files. So this issue seems to be solved.

Thanks for your quick help.
