### ISSUE TITLE
How to create calender file on the server side?

### ISSUE THREAD

**Issue by voxspox** [Kozea/Radicale#706]
I want to generate calendar events and make them available to calendar clients via Radicale. Therefore I created a file in icalendar format and saved it in the collections folder. This worked fine for Radicale 1.1.1 and storage.type = filesystem

Now I want to upgrade Radicale (2.6). The storage.type has changed and is only multifilesystem now. The file format seems to be different.

How can I transform an icalendar formated file into a radicale calendar file? Call some function of storage.py?

**Comment by voxspox** [comment]
ok, I have found some [docs](http://radicale.org/storage/)

Is there an example .Radicale.prop file available?

I created a new calendar per calendar client. A file with the following fields was created: C:calendar-description C:calendar-timezone C:supported-calendar-component-set D:displayname ICAL:calendar-color tag
Which fields are obligatory?

**Comment by voxspox** [comment]
thanks, this was helpful! Actually I don't want to transform the events but want to generate events. Thus migrating via export is no option here.

I'm still confused how to store the vevents of a calendar. I assume I have to save each vevent in icalendar file format as a single file (else I get "Muliple VEVENT components with different UIDs in object").
I wonder what is the purpose of calendar.ics then (mentioned [here](http://radicale.org/clients/#direct-editing-of-the-storage))

**Comment by Unrud** [comment]
> I wonder what is the purpose of calendar.ics then

``calendar.ics`` is a folder. It contains ``.Radicale.props`` and each calendar object in a separate file.

**Comment by voxspox** [comment]
ok, thank! :)
