### ISSUE TITLE
CalDAV-Sync: Unable to find or access calendars

### ISSUE THREAD

**Issue by tmst** [Kozea/Radicale#707]
I have authentication and SSL disabled. Radicale is running at http://0.0.0.0:5232. There is one calendar in the Radicale folder with 10 tasks which are accessible on the local machine with KOrganizer. The message is "This URL seems not to point to a (supported) CalDAV calendar or you don't have access to it. Please check your account data.":

20170918T024109Z I org.dmfs.caldav.autheticator.AuthenticatorActivity calendar discovery log:
20170918T024111Z V org.dmfs.dav.Dav get principal /
20170918T024111Z I org.dmfs.dav.Dav found principal: /tom/
20170918T024111Z V org.dmfs.dav.CalDav get calendars http://<host>:5232/tom/
20170918T024111Z V org.dmfs.dav.CalDav found calendar user address /tom/
20170918T024111Z I org.dmfs.dav.CalDav also looking for calendar home sets in /
20170918T024111Z V org.dmfs.dav.CalDav get calendars /
20170918T024111Z V org.dmfs.dav.CalDav looking for calendars in http://<host>:5232/tom/
20170918T024111Z V org.dmfs.dav.methods.DavPropFind Status: 500
20170918T024111Z V org.dmfs.dav.methods.DavPropFind A server error occurred. Please contact the administrator.
20170918T024111Z V org.dmfs.dav.CalDav additionally looking for calendar in /
20170918T024111Z V org.dmfs.dav.CalDav resourcetypes DAV::collection

App: org.dmfs.caldav.lib
App version: 0.4.29
OS version: 21
OS Info: lge/y50c_trf_us/y50c:5.0.1/LRX21Y/L22CV10a.1421747164:user/release-keys
Manufacturer: LGE
Date: Sun Sep 17 19:41:13 PDT 2017

**Comment by tmst** [comment]
Looking at my log I see an interesting entry:
[7f7399aac700] ERROR: An exception occurred during PROPFIND request on '/tom/': Failed to load item 'tasks.ics' in 'tom/1dc52dac-fca5-a566-3fde-bbca7ab9fe7d': Muliple component types in object: 'VEVENT', 'VTODO'
lines 2621-2637/2637 (END)

'tasks.ics' is a file from Radicale 0.7.1. So now I know with certainty that simply dropping a 'filesystem'-type file into a Radicale v. 2.x 'multifilesystem' collection doesn't work. :-)

**Comment by Unrud** [comment]
> 'tasks.ics' is a file from Radicale 0.7.1. So now I know with certainty that simply dropping a 'filesystem'-type file into a Radicale v. 2.x 'multifilesystem' collection doesn't work. :-)

[Migration from 1.x.x to 2.x.x](http://radicale.org/1to2/)

**Comment by tmst** [comment]
Thanks. I can't migrate, though, without a working Android sync client for 2.x. As it stands, CalDAV-Sync mysteriously fails to sync from the server to the client, and DAVdroid loses task categories set on the server.
