### ISSUE TITLE
DAVdroid loses task categories

### ISSUE THREAD

**Issue by tmst** [Kozea/Radicale#708]
I was pleased to find that, after fighting to get CalDAV-Sync to work, that DAVdroid does, indeed sync "out of the box." However, any categories set on the server are lost.

That's all I know. I think it's likely an issue with DAVdroid but just thought I'd mention it here.

**Comment by tmst** [comment]
It occurs to me this might also be related to the Android "OpenTasks" implementation, esp since it was written by the authors of CalDAV-Sync. As far as I know, "OpenTasks" is the most popular open-source tasks app for Android.

**Comment by Unrud** [comment]
It's an issue of **DAVdroid**. When a task gets changed in **OpenTasks**, **DAVdroid** uploads a new file to **Radicale**, that is missing the **CATEGORIES** line.

**Comment by tmst** [comment]
@Unrud Good to have that settled. I just tweeted the developer @davdroidapp.

**Comment by Tntdruid** [comment]
categories works fine for my, using eM Client

**Comment by tmst** [comment]
On Sat, Oct 21, 2017, at 06:04 AM, Tntdruid wrote:
> categories works fine for my, using eM Client



Maybe DAVdroid was patched. Have you tried with the native
Android client?

**Comment by pbiering** [comment]
closed because of old version, please reopen if still happen with current version
