### ISSUE TITLE
770 required for collections folder

### ISSUE THREAD

**Issue by Forage** [Kozea/Radicale#712]
Hi,

I finally got round to switch from Radicale 1 to 2.5. While it required some puzzling, it's working in the end.
One thing that will help to speed things up is mentioning [in the documentation](http://radicale.org/setup/) that `/var/lib/radicale/collections` requires 770 permissions. The user is mentioned and the fact that it needs write permissions. If you fail to include execution permissions for just the parent folder, WSGI will keep throwing you a `[Errno 13] Permission denied: '/var/lib/radicale/collections/.Radicale.lock'` in the Apache error.log.

**Comment by tmst** [comment]
Upgrading is still an adventure, isn't it?

I believe the sentence "If you fail..." contradicts the previous sentence about `collections` requiring `770`. Both can't be correct.

**Comment by Unrud** [comment]
The execute bit is required to access a folder. It's always required if you want to do anything in a folder.
The documentation never mentions that you can remove it.

**Comment by Forage** [comment]
Read is implied, write is mentioned, which leaves executable. Especially when you migrate or create the folders manually, I only assign what it mentioned, executable being less logic if you have no knowledge of the background workings.

**Comment by Unrud** [comment]
> Read is implied, write is mentioned, which leaves executable.

Without the ``executable`` bit you can't do anything useful with a folder. (Besides deleting it, if it's already empty.) In my opinion that implies, that you need the ``executable`` bit.
