### ISSUE TITLE
Error on startup when logfile exists

### ISSUE THREAD

**Issue by schvabodka-man** [Kozea/Radicale#713]
Hi. There. I'm trying to run radicale in docker container in pi (https://hub.docker.com/r/funkyfuture/rpi-radicale/)

When starting up with empty created logging file

```
Traceback (most recent call last):
  File "/usr/local/bin/radicale", line 32, in <module>
    radicale.__main__.run()
  File "/usr/local/lib/python3.6/site-packages/radicale/__main__.py", line 210, in run
    log.start()
  File "/usr/local/lib/python3.6/site-packages/radicale/log.py", line 54, in start
    configure_from_file(filename, debug)
  File "/usr/local/lib/python3.6/site-packages/radicale/log.py", line 40, in configure_from_file
    logging.config.fileConfig(filename)
  File "/usr/local/lib/python3.6/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/local/lib/python3.6/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/local/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```

You really should make some workaround for these.

**Comment by Unrud** [comment]
The docker container contains an old (unsupported) version of Radicale.

> When starting up with empty created logging file

I guess it should work if the logging file doesn't exist. Try to delete it.

**Comment by schvabodka-man** [comment]
Yes it works but that would be cool if there would be some workaround for it.

**Comment by Unrud** [comment]
> f there would be some workaround for it.

What do you mean by workaround? Radicale >= 2.0.0 always fails with an error message if you specify a logging config that doesn't exist or is incomplete:

```
ERROR: Failed to start logger: Failed to load logging configuration file '/does/not/exist': 'formatters'
```

**Comment by schvabodka-man** [comment]
I mean workaround for the handling of this error. Not just throwing error on start but doing something about that(removing file and starting, etc)

**Comment by Unrud** [comment]
If the configuration is invalid, we will not try to fix it automatically. It will cause unexpected behavior.

> removing file and starting

In most setups, Radicale shouldn't have write access to the configuration files.

**Comment by Unrud** [comment]
> It would be nice to have a more explicit error though.

The file is evaluated by the ``logging`` module from  Python's stdlib and that error message is all we get.

**Comment by pbiering** [comment]
closed because old version, current version logs to stdout or journald only
