### ISSUE TITLE
Writes and serves RFC-non-comformant iCalendar data

### ISSUE THREAD

**Issue by madduck** [Kozea/Radicale#714]
In RFC 5545, "3.1. Content Lines" it's written:

> Content lines are delimited by a line break, which is a CRLF sequence (CR character followed by LF character).

However, Radicale writes its files using Unix line endings, and also serves such data:

    % GET -C 'user:password' https://caldav.example.org/username/calendar.ics/ | xxd | head -2
    00000000: 4245 4749 4e3a 5643 414c 454e 4441 520a  BEGIN:VCALENDAR.
    00000010: 5052 4f44 4944 3a2d 2f2f 5261 6469 6361  PRODID:-//Radica

Note the `0x0a` without the `0x0d` at the end of the first line.

As a consequence, the [iCalendar.org validator](https://icalendar.org/validator.html) reports an error when passed the data served by Radicale (0.9-1+deb8u1)
<img width="1243" alt="calerror" src="https://user-images.githubusercontent.com/195073/30909831-c5bfe3e6-a382-11e7-99df-172a06de9c28.png">

**Comment by Tntdruid** [comment]
You are using a very old version

**Comment by madduck** [comment]
So this is fixed in a later version? I looked but couldn't identify a changeset. Any hints?

**Comment by Tntdruid** [comment]
Test pass when i upload a .ics file.

**Comment by pbiering** [comment]
related to old version, closing now, if reproducable with current version of radicale, please reopen.
