### ISSUE TITLE
How to add an existing address book into radicale

### ISSUE THREAD

**Issue by pbg42** [Kozea/Radicale#717]
Hi all!
Is there a simple way to get a .vcf file into radicale? I could not find any hints for that in the net. Isn't that a popular use case when you startup a radicale server?

**Comment by bigbig6** [comment]
Hi,

The best way seems to be to use a client (which one you want) connected to your server, and after to import events and contacts...
Regards,

Big

**Comment by tmst** [comment]
The way I've done it so far, such that no migration, import or export is necessary, is to create a new address book and use the contacts manager to copy/paste the contacts into it. IIRC, Lightning has the nice feature of being able to select multiple contacts at once which can't be generally counted upon in clients.

**Comment by pbg42** [comment]
@bigbig6 @tmst : Thanks for your suggestions. My t!sk was to copy my android contacts and I found a small app "CopyContacts" that did that job together with DAVDroid. So, as you said, no need to directly import from a .vcf file.

**Comment by tmst** [comment]
@pbg42 Cool. A method that requires no desktop! Did you use the browser on Android to create the new Calendar?

**Comment by tmst** [comment]
See also #719.

**Comment by pbg42** [comment]
@tmst: no, I did not use the Android browser to create the address book, just the Firefox browser from my Linux Laptop.
@tmst #719: this "curl .." command line would be a great hint in the tutorial documentation!

**Comment by robohobbit** [comment]
@tmst How exactly do you copy addresses from one Thunderbird addressbook to a Radicale one?

I've created a new Radicale addressbook and connected it to Thunderbird and when I create a new contact on it, a new .vcf card is created in Radicale's folder. However, when I move/copy addresses from one addressbook to Radicale, nothing happens in Radicale's folder.
