### ISSUE TITLE
Synchronization problem

### ISSUE THREAD

**Issue by roipoussiere** [Kozea/Radicale#722]
I have just installed Radicale on my [Yunohost server](https://yunohost.org) (see [the Radicale fork for Yunohost](https://github.com/YunoHost-Apps/radicale_ynh)) and the synchronization with [DAVDroid](https://davdroid.bitfire.at/configuration/radicale/) fails with [this stacktrace](https://gist.github.com/roipoussiere/625feb8315929ae4bd34b87adb020140).

**Comment by Unrud** [comment]
> I have just installed Radicale on my [Yunohost server](https://yunohost.org) (see [the Radicale fork for Yunohost](https://github.com/YunoHost-Apps/radicale_ynh))

I don't know anything about it.

> the synchronization with [DAVDroid](https://davdroid.bitfire.at/configuration/radicale/) fails with [this stacktrace](https://gist.github.com/roipoussiere/625feb8315929ae4bd34b87adb020140).

Looks like the authentication fails. The log does not reveal the exact problem. Maybe you typed a wrong password.

**Comment by pbiering** [comment]
closed now after long time, please reopen in case reproducable with latest version
