### ISSUE TITLE
lost in user right file

### ISSUE THREAD

**Issue by typhoon71** [Kozea/Radicale#727]
I'm trying to get radicale working, but I hit a problem while using the rights from file.
Actually, half a problem.

I can get user1 able to read and write on his own calendar.
I can get user2 able to only read from user1 calendar.
But I fail to get user1 able to only read a calendar in his own folder. 
(say, one decides to make a personal calendar read only after a while for a user for, but still wants to let the user read it)

I then noticed that only one rule matching user1 would be accepted: if I have 2 rules for user1, radicale goes crazy, with random-like permission. The logs are cut too.

I'm using radicale 1.1.1 on, since I have/had a semi stringent python2 requirement (but I'm testing it on a ubuntu 16.04 VM, so right now there's python3 abailable too).

My question is: is it possible to have multiple rules for the same user in the right file?
Like to permit one user to only read some other user calendars, but read and write some other?
I don't understand if this is possible, or how.

Also, what does actually happen if there's two user logged with the same username?

Thanks for any help, I'll really appreciate it.

Btw, if using python3 solves my issues, I can switch, but I got troubles building it on my box, and the system package doesn't seem to be up to date.

**Comment by tmst** [comment]
Not sure if this helps, but does it get crazy even with the default `rights` file? And then there's this, though I haven't yet seen any connection failures running on localhost:

`WARNING: Using server.timeout with Python < 3.5.2 can cause network connection failures`

**Comment by typhoon71** [comment]
I scrapped the setup and went with the 2.1.8 release (python3) and I found that the rights file is behaving better.

Network is not an issue, but I'll take note of that line, it'll be handy later, when I'll add the webinterface, maybe the radicale infcloud, but that has bugs on his own (infcloud).

Thanks.
