### ISSUE TITLE
`systemd` messages in openSuse system log

### ISSUE THREAD

**Issue by tmst** [Kozea/Radicale#728]
Have been getting these messages in the system log with the openSuse binary pkgs. I'm not familiar enough with `systemd` to know what they mean. They don't seem to be a problem:

```
$ uname -a
Linux linux-xipe.site 4.4.87-18.29-default #1 SMP Wed Sep 13 07:07:43 UTC 2017 (3e35b20) x86_64 x86_64 x86_64 GNU/Linux

Oct 17 15:04:27 linux-xipe.site systemd[1]: [/usr/lib/systemd/system/radicale.service:16] Failed to parse protect system value, ignoring: strict
Oct 17 15:04:27 linux-xipe.site systemd[1]: [/usr/lib/systemd/system/radicale.service:19] Unknown lvalue 'ProtectKernelTunables' in section 'Service'
Oct 17 15:04:27 linux-xipe.site systemd[1]: [/usr/lib/systemd/system/radicale.service:20] Unknown lvalue 'ProtectKernelModules' in section 'Service'
Oct 17 15:04:27 linux-xipe.site systemd[1]: [/usr/lib/systemd/system/radicale.service:21] Unknown lvalue 'ProtectControlGroups' in section 'Service'
Oct 17 15:04:27 linux-xipe.site systemd[1]: [/usr/lib/systemd/system/radicale.service:23] Unknown lvalue 'ReadWritePaths' in section 'Service'
```

**Comment by Unrud** [comment]
What version of ``systemd`` are you using? The directives were added quiet recently.
I don't get any error messages with version 233.

**Comment by tmst** [comment]
228

On Thu, Oct 19, 2017, at 10:27 AM, Unrud wrote:
> What version of systemd are you using? The directives were added quiet
> recently.>  I don't get any error messages with version 233.


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/Kozea/Radicale/issues/728#issuecomment-337979143
