### ISSUE TITLE
Where does HTTP Requests come from?

### ISSUE THREAD

**Issue by Loader23** [Kozea/Radicale#730]
Hi,

when I start Radicale, I get 4 of these errors:
ERROR: An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:777)

Another ticket mentioned, that these come from an http request. But where do these come from? All my Clients are using SSL, is this something that I should be worried about?

**Comment by Unrud** [comment]
> But where do these come from?

I don't know. If you are using Linux, you can show new connections to Radicale with something like ``sudo tcpdump -i any -nn tcp dst port 5232 | grep 'Flags \[S\]'``.

> All my Clients are using SSL

Maybe a client is trying to connect without SSL first.

> is this something that I should be worried about?

Probably not.

**Comment by dojo90** [comment]
@Loader23 have you found a solution or where it comes from? Got the same behavior!

**Comment by Loader23** [comment]
@dojo90 sadly no, but iam still interested in it. tcpdump is not working for me.
