### ISSUE TITLE
Evolution setup instructions required adjustment before working

### ISSUE THREAD

**Issue by QasimK** [Kozea/Radicale#731]
Hi, I successfully connected my iOS device to my Radicale server, but encountered problems when attempting to setup Gnome Evolution/Contacts/Calendar apps.

The instructions on the client page state:

> In Evolution add a new calendar and address book respectively with WebDAV. Enter the URL of the Radicale server (e.g. `http://localhost:5232`) and your user name. Clicking on the search button will list the existing calendars and address books.

However, the URL that finally worked for me was `http://localhost:5232/myuser/`.

I am running Arch Linux so this may be a recent change to Evolution, but I believe there is scope to update the instructions to make it clear that your username is part of the URL.

Image of working setup:

![image](https://user-images.githubusercontent.com/10064144/31863712-5c8fe3c8-b749-11e7-912d-c06e669cbc2e.png)

I also notice, that the "Type" is "CardDav" - "WebDav" is not available in the drop-down. Perhaps this is the reason why?

**Comment by Unrud** [comment]
> I also notice, that the "Type" is "CardDav" - "WebDav" is not available in the drop-down.

It was renamed in 3.26.

> However, the URL that finally worked for me was ``http://localhost:5232/myuser/``.

The URL ``http://localhost:5232`` works with 3.24. Maybe it's a regression in Evolution.

**Comment by gnumdk** [comment]
Can confirme that it does not work without username

**Comment by genodeftest** [comment]
> Can confirm that it does not work without username.

Same for Evolution 3.28.

**Comment by pbiering** [comment]
related to old version, closing now, if reproducable with current version of radicale, please reopen.
