### ISSUE TITLE
Single .ics file with Multiple VEVENT's

### ISSUE THREAD

**Issue by robertbeal** [Kozea/Radicale#733]
I'm curl-ing a single .ics file (https://www.gov.uk/bank-holidays/england-and-wales.ics) into one of my calendars. The ics file contains multiple VEVENTS (each with a differing UID). I'm effectively trying to have my own calendar sync by doing a daily curl to grab the ics file. 

Upon accessing the calendar, I get a 500 with the error: `Multiple VEVENT components with different UIDs in object` . From looking at the code it's tripping up here: https://github.com/Kozea/Radicale/blob/master/radicale/storage.py#L158

Is this expected behaviour? Should the code be treating it as `is_collection` and be going down a different flow? I can only see `is_collection` set as `False`.

The .ics shows as valid when I pass it through a validator (ie https://icalendar.org/validator.html). 

Am happy to get stuck into some python, just want to make sure I'm understanding it correctly.

**Comment by tmst** [comment]
On Thu, Oct 26, 2017, at 06:54 AM, Robert Beal wrote:
> Upon accessing the calendar, I get a 500 with the error: Multiple
> VEVENT components with different UIDs in object . From looking at the
> code it's tripping up here:
> https://github.com/Kozea/Radicale/blob/master/radicale/storage.py#L158
The storage scheme was changed in the 2.x branch.  A single ICS file now
contains only a single VEVENT. So it may not be possible, or at least
easy, to merge such an ICS file into storage.  I would try Radicale 1.x
if this is essential.

**Comment by robertbeal** [comment]
Ah ok, I did wonder looking at all my non-imported calendars. No worries, might see if I can convert the singular file into multiple via bash and import it that way. Cheers for the info.

**Comment by tmst** [comment]
On Sat, Nov 4, 2017, at 12:01 PM, Robert Beal wrote:
> Ah ok, I did wonder looking at all my non-imported calendars. No
> worries, might see if I can convert the singular file into multiple
> via bash and import it that way. Cheers for the info.Yeah, there's the --export-storage flag that does it. It would require
some setup.

**Comment by robertbeal** [comment]
1. Create a calendar in Radicale
2. `curl -s https://www.gov.uk/bank-holidays/england-and-wales.ics -o /var/radicale/data/collection-root/rob/95a04919-27db-44f1-8258-6adf0d778bb7/public-holidays.ics`
3. Try opening the calender in a browser: `https://localhost/rob/95a04919-27db-44f1-8258-6adf0d778bb7/`

You should get 500 response, and the debug output will mention `Multiple VEVENT components with different UIDs in object`

**Comment by Unrud** [comment]
> 2. `curl -s https://www.gov.uk/bank-holidays/england-and-wales.ics -o /var/radicale/data/collection-root/rob/95a04919-27db-44f1-8258-6adf0d778bb7/public-holidays.ics`

This doesn't work: [Storage Layout](http://radicale.org/storage/#layout)

Try something like
```shell
curl https://www.gov.uk/bank-holidays/england-and-wales.ics | curl -u 'user:password' -X PUT http://localhost:5555/user/holidays --data-binary @-
```
Replace ``'user:password'`` with your real credentials and adjust the collection URL. This will overwrite any existing collection.

**Comment by robertbeal** [comment]
Ah nice, didn't know you could curl files into Radicale instead of just dropping them on the file system. Thanks!

**Comment by IgnisQuisVir** [comment]
I get a message "Bad Request" when I try your curl command. I have also a single .ics file with multiple vevents.

**Comment by dzamo** [comment]
> I get a message "Bad Request" when I try your curl command. I have also a single .ics file with multiple vevents.

Check that you do not have a trailing `/` after the calendar name in the URL that you PUT to.

**Comment by christf** [comment]
the curl command just purged my whole calender and I now need to restore from backup. The only thing that remained was the two vevents that I wanted to add.

**Comment by pbiering** [comment]
> the curl command just purged my whole calender and I now need to restore from backup. The only thing that remained was the two vevents that I wanted to add.

That is an expected behavior, you've overridden the existing collection with new content. There is a toggle to prevent this, named `permit_overwrite_collection`.
