### ISSUE TITLE
Radicale under a folder with uwsgi  and nginx not working

### ISSUE THREAD

**Issue by fariouche** [Kozea/Radicale#735]
Hello,

I'm trying to setup radicale with nginx using uwsgi protocol.
Everything work fine if I setup he location as "/"
But i does not if I setup in a subfolder "/radicale".
In nginx, I've done:
location /radicale/ {
include /etc/nginx/uwsgi_params;
uwsgi_pass unix:/var/run/uwsgi_radicale/radicale.sock;
}
and my uwsgi ini file is:
[uwsgi]
socket = /var/run/uwsgi_radicale/radicale.sock
threads = 8
master = true
plugin = python34
chdir = /var/lib/radicale
wsgi-file = /opt/radicale/radicale.wsgi
#manage-script-name = true
#mount /radicale=web.py
#socket-modifier1 = 30
env = RADICALE_CONFIG=/etc/radicale/config

I tried to fiddle with the manage-script-name, or the old nginx way using modifier1=30 and SCRIPT_NAME /radicale... but no luck

Radicale seems to hardcode the path to "/"...

Anyone have a working configuration?
I do not want to use radicale in http mode, but prefer to use unix domain sockets for security reasons.

Thanks

**Comment by evilham** [comment]
The [docs](http://radicale.org/proxy/) tell you how to do that. See `X-Script-Name`.

**Comment by Unrud** [comment]
> Radicale seems to hardcode the path to "/"...

No. It gets the path from the ``SCRIPT_NAME`` environ variable or from the ``X-Script-Name`` HTTP header.

> See `X-Script-Name``.

This should not be required. **uwsgi** should set ``SCRIPT_NAME`` to ``/radicale``.

**Comment by fariouche** [comment]
very strange... Maybe I do not understand something.
I was able to setup radicale in fastcgi mode. uwsgi mode is still impossible to work (SCRIPT_NAME is not correct). Radicale is not the issue I think. Most likely uwsgi itself
