### ISSUE TITLE
error with systemctl

### ISSUE THREAD

**Issue by GitDatei** [Kozea/Radicale#736]
Hello 
i want start radicale with systemctl, but it is no work fine.

`

root@deb:~# systemctl enable radicale.service
root@deb:~# systemctl start radicale.service
root@deb:~# systemctl status radicale.service
● radicale.service - A simple CalDAV (calendar) and CardDAV (contact) server
   Loaded: loaded (/etc/systemd/system/radicale.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-10-29 17:11:55 CET; 490ms ago
 Main PID: 2187 (python3)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/radicale.service
           └─2187 python3 -m radicale

Okt 29 17:11:55 deb systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
Okt 29 17:11:55 deb systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
Okt 29 17:11:55 deb systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
root@deb:~# systemctl status radicale.service
● radicale.service - A simple CalDAV (calendar) and CardDAV (contact) server
   Loaded: loaded (/etc/systemd/system/radicale.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-10-29 17:11:57 CET; 9s ago
  Process: 2193 ExecStart=/usr/bin/env python3 -m radicale (code=exited, status=1/FAILURE)
 Main PID: 2193 (code=exited, status=1/FAILURE)

Okt 29 17:11:57 deb systemd[1]: radicale.service: Unit entered failed state.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Failed with result 'exit-code'.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
Okt 29 17:11:57 deb systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Start request repeated too quickly.
Okt 29 17:11:57 deb systemd[1]: Failed to start A simple CalDAV (calendar) and CardDAV (contact) server.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Unit entered failed state.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Failed with result 'exit-code'.
root@deb:~# systemctl status radicale.service
● radicale.service - A simple CalDAV (calendar) and CardDAV (contact) server
   Loaded: loaded (/etc/systemd/system/radicale.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-10-29 17:11:57 CET; 12s ago
  Process: 2193 ExecStart=/usr/bin/env python3 -m radicale (code=exited, status=1/FAILURE)
 Main PID: 2193 (code=exited, status=1/FAILURE)

Okt 29 17:11:57 deb systemd[1]: radicale.service: Unit entered failed state.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Failed with result 'exit-code'.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
Okt 29 17:11:57 deb systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Start request repeated too quickly.
Okt 29 17:11:57 deb systemd[1]: Failed to start A simple CalDAV (calendar) and CardDAV (contact) server.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Unit entered failed state.
Okt 29 17:11:57 deb systemd[1]: radicale.service: Failed with result 'exit-code'.

`

/etc/systemd/system/radicale.service
`
[Unit]
Description = A simple CalDAV (calendar) and CardDAV (contact) server
After = network.target
Requires = network.target

[Service]
ExecStart=/usr/bin/env python3 -m radicale
Restart = on-failure
User = radicale
UMask = 0027
PrivateTmp = true
ProtectSystem = strict
ProtectHome = true
PrivateDevices = true
ProtectKernelTunables = true
ProtectKernelModules = true
ProtectControlGroups = true
NoNewPrivileges = true
ReadWritePaths = /var/lib/radicale/collections
[Install]
WantedBy = multi-user.target
`

 /etc/radicale/config
`

[server]
daemon = True
pid = /var/run/radicale.pid
hosts = 0.0.0.0:5232
max_connections = 20
max_content_length = 10000000
timeout = 10

[auth]
type = htpasswd
htpasswd_filename = /etc/radicale/users
htpasswd_encryption = bcrypt
delay = 1

[storage]
filesystem_folder = /var/lib/radicale/collections

`

**Comment by basxto** [comment]
`Type=forking` and `PIDFile=/var/run/radicale.pid` might fix that.

If that does not work, try to run it undaemonized like it’s done [on Arch](https://aur.archlinux.org/cgit/aur.git/tree/radicale.service?h=radicale)

**Comment by GitDatei** [comment]
Started A simple CalDAV (calendar) and CardDAV (contact) server.
Nov 05 13:20:33 deb env[13445]: ERROR: **Invalid configuration: Invalid option 'type' in section 'server' in config**
Nov 05 13:20:33 deb systemd[1]: radicale.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 13:20:33 deb systemd[1]: radicale.service: Unit entered failed state.
Nov 05 13:20:33 deb systemd[1]: radicale.service: Failed with result 'exit-code'.
Nov 05 13:20:33 deb systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
Nov 05 13:20:33 deb systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
Nov 05 13:20:33 deb systemd[1]: radicale.service: Start request repeated too quickly.
Nov 05 13:20:33 deb systemd[1]: Failed to start A simple CalDAV (calendar) and CardDAV (contact) server.
Nov 05 13:20:33 deb systemd[1]: radicale.service: Unit entered failed state.
Nov 05 13:20:33 deb systemd[1]: radicale.service: Failed with result 'exit-code'.
Nov 05 13:24:07 deb systemd[1]: Starting A simple CalDAV (calendar) and CardDAV (contact) server...
Nov 05 13:24:08 deb env[13481]: ERROR: **Invalid configuration: Invalid option 'pidfile' in section 'server' in config**
Nov 05 13:24:08 deb systemd[1]: radicale.service: Control process exited, code=exited status=1

**Comment by GitDatei** [comment]
ok i make other:
 **PIDFile=/var/run/radicale.pid** dont work on debian, i have make only `pid `

`Type=forking ` i add on Service in file radicale.service

now radicale is starting with 

> systemctl start radicale

but with timeout.

> 
> Nov 05 13:30:36 deb systemd[1]: radicale.service: Start operation timed out. Terminating.
> Nov 05 13:30:36 deb systemd[1]: Failed to start A simple CalDAV (calendar) and CardDAV (contact) server.
> Nov 05 13:30:36 deb systemd[1]: radicale.service: Unit entered failed state.
> Nov 05 13:30:36 deb systemd[1]: radicale.service: Failed with result 'timeout'.
> Nov 05 13:30:36 deb systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
> Nov 05 13:30:36 deb systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
> Nov 05 13:30:36 deb systemd[1]: Starting A simple CalDAV (calendar) and CardDAV (contact) server...
> lines 86-131/131 (END)

**Comment by GitDatei** [comment]
OK its work now BUT without creat pidfile pidfile dont creat without daemon option, right ?



> [server]
> **#daemon = True**
> pid = /var/run/radicale.pid
> **#PIDFile=/var/run/radicale.pid # with PIDFILE dont starting radicale on my system**
> hosts = 0.0.0.0:5232
> max_connections = 20
> max_content_length = 10000000
> timeout = 10
> 
> 
> [auth]
> type = htpasswd
> htpasswd_filename = /etc/radicale/users
> htpasswd_encryption = bcrypt
> delay = 1
> 
> 
> [storage]
> filesystem_folder = /var/lib/radicale/collections
> 
> 
> 
> 




> [Unit]
> Description = A simple CalDAV (calendar) and CardDAV (contact) server
> After = network.target
> Requires = network.target
> 
> 
> [Service]
> **#Type = forking   # RADICALE starts only without this Type option on my system , whyy ?**
> ExecStart=/usr/bin/env python3 -m radicale
> Restart = on-failure
> User = radicale
> UMask = 0027
> PrivateTmp = true
> ProtectSystem = strict
> ProtectHome = true
> PrivateDevices = true
> ProtectKernelTunables = true
> ProtectKernelModules = true
> ProtectControlGroups = true
> NoNewPrivileges = true
> ReadWritePaths = /var/lib/radicale/collections
> [Install]
> WantedBy = multi-user.target

**Comment by GitDatei** [comment]
OK have found my error, I need to write the option type and PIDFILE in the service file, logically

but the pidfile dont write, again

**Comment by GitDatei** [comment]
mhhh
if on Section Service i have set Type=forking  make radicale  timeout

**Comment by basxto** [comment]
I’m overriding my service file, will see whether I’ll get it running.

**Comment by basxto** [comment]
Permission issues, that’s all.
User radicale has no right to write at `/var/run`, only root does.
I changed `ReadWritePaths`, since I did not want to put the PID file into the collections folder.

```
[Unit]
Description = A simple CalDAV (calendar) and CardDAV (contact) server
After = syslog.target network.target
Requires = network.target

[Service]
Type = forking
ExecStart=
ExecStart=/usr/bin/env python3 -m radicale --daemon --pid /var/lib/radicale/pid
PIDFile=/var/lib/radicale/pid
Restart = on-failure
User = radicale
Group =
UMask = 0027
PrivateTmp = true
ProtectSystem = strict
ProtectHome = true
PrivateDevices = true
ProtectKernelTunables = true
ProtectKernelModules = true
ProtectControlGroups = true
NoNewPrivileges = true
ReadWritePaths = /var/lib/radicale

[Install]
WantedBy = multi-user.target
```

I don’t think, there is a need to start it daemonized.
It makes sense in scripts, but systemctl can give you the PID of the running service.

**Comment by GitDatei** [comment]
ok thanks , its work

**Comment by tmst** [comment]
On Sun, Oct 29, 2017, at 08:29 AM, GitDatei wrote:
> Hello
>  i want start radicale with systemctl, but it is no work fine.



Maybe the permissions problem was due to the Group missing in your
radicale.service file:
[Service]
...
User=radicale
Group=radicale
...

**Comment by Unrud** [comment]
> If that does not work, try to run it undaemonized like it’s done [on Arch](https://aur.archlinux.org/cgit/aur.git/tree/radicale.service?h=radicale)

Or the documentation http://radicale.org/setup/#linux-with-systemd-system-wide

The drawback of running it daemonized is, that **journald** can't be used for logging.
