### ISSUE TITLE
Creating and sending caldav objects to radicale

### ISSUE THREAD

**Issue by Verdagio** [Kozea/Radicale#738]
Hello,

I am trying to write a typescript api which will interact with the Dockerised Radicale micro service. I am having issues trying to figure out how the 2 services should be interacting with each other. Should I be sending the equivalent  of a curl command to Radicale and allow it to create the calendar & events etc forme, or sending a calDav object or .ics file to Radicale. 

Any clarification on this would be greatly appreciated, thanks.

**Comment by tmst** [comment]
On Thu, Nov 2, 2017, at 03:17 AM, Daniel Verdejo wrote:
> Hello,


> I am trying to write a typescript api which will interact with the
> Dockerised Radicale micro service. I am having issues trying to figure
> out how the 2 services should be interacting with each other. Should I
> be sending the equivalent  of a curl command to Radicale and allow it
> to create the calendar & events etc forme, or sending a calDav object
> or .ics file to Radicale.> Any clarification on this would be greatly appreciated, thanks.


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
Are you going to create a JSON API for Radicale? Woo hoo! ;-)

This looks like a good place to get familiar with CalDAV:
https://tools.ietf.org/html/rfc4791

Links:

  1. https://github.com/Kozea/Radicale/issues/738

**Comment by Unrud** [comment]
> Should I be sending the equivalent of a curl command to Radicale

You can use CalDAV/CardDAV as @tmst suggested.

> or sending a calDav object or .ics file to Radicale

I'm not sure if I understand what you mean by this.
You can lock the filesystem folder and edit/read the files directly while Radicale is running: http://radicale.org/storage/
If you write invalid data to the folder, requests to Radicale will fail.

**Comment by Verdagio** [comment]
Hey, Haven't checked in on this in awhile, got the calendars and events  being created but when trying to retrieve the calendar event i am returned : 

> EPROTO 140381905233728:error:140770FC:SSL

I'm sure with a bit of tinkering I'll figure it out but if you have a suggestion that'd be cool! :p 
 here's a run down of how I am processing the request:

```
    const options = {
        method: 'REPORT',
        url: `https://radicale-caldav-server:5232/${req.params.id}/calendar`,
        data: `<c:calendar-query xmlns:d="DAV:"xmlns:c="urn:ietf:params:xml:ns:caldav">
                    <d:prop>
                        <d:getetag />
                        <c:calendar-data />
                    </d:prop>
                    <c:filter>
                        <c:comp-filter name="VCALENDAR" />
                    </c:filter>
                </c:calendar-query>`
    }

    const message : any = request(options)
    .then(function (response: any){
        res.send(200, response);
        log.debug(response.message, response.statusCode);
    }).catch(function(error:any){
        res.send(500, error);
        log.debug(error.message, error.statusCode);
    });
    return message;
```
For now it's just a rough version to be abstracted and refined. Thanks 👍

**Comment by pbiering** [comment]
old, closing now
