### ISSUE TITLE
Importing from 0.9 ics files

### ISSUE THREAD

**Issue by q6276270** [Kozea/Radicale#739]
Hi,
first of all thank you for creating such a useful piece of software. I'm sorry if I am ignorant of some etiquette, I have looked but not found any guidelines as how to submit issues. I have the following question.

In radicale 0.9 I had several calendar .ics files located in the users directory, i.e.
- user 1
  - cal1.ics
  - cal2.ics
  - cal3.ics
- user 2
  - cal1.ics
  - cal2.ics

indeed there are only 3 users of the server so I’d like to keep it simple also in terms of files. Is there any way to at least import .ics files to radical 2.x created by radicale 0.9? I’ve literally tried everything I can think of but first the server complains about non-matching UIDs which are in separate VEVENT entries, then (having modified the UIDS) there is "more than one main part", which I am apparently too silly to fix.

Thanks for your time!

**Comment by tmst** [comment]
There's an export flag to radicale to get your calendar files into the format for Radicale 2.x.

**Comment by 1ecstasy** [comment]
I know that. But since my files are not from 1.x but from 0.9 I wasn't sure whether this works at all. Also, I'm afraid I expressed it quite badly, I'd like to know whether there is any (sensible) way to keep the current file structure.
Thanks for your time!

**Comment by Unrud** [comment]
> But since my files are not from 1.x but from 0.9 I wasn't sure whether this works at all. 

First you have to update to 1.1.x and then you can export for 2.x.x.

> I'd like to know whether there is any (sensible) way to keep the current file structure.

No, you would have to write a new storage plugin.

**Comment by 1ecstasy** [comment]
thanks a lot, that answers my question completely.

**Comment by pbiering** [comment]
closing as anwered
