### ISSUE TITLE
Radicale jumping to 100% CPU usage after any edits on Raspberry Pi B+ for the longest time

### ISSUE THREAD

**Issue by Captain-Rage** [Kozea/Radicale#742]
I've been running Radicale on a Raspberry Pi B+ (using Arch Linux ARM) for about three years now. The connected clients are a laptop with Thunderbird + Lightning addon and an Android phone with DAVdroid.
The problem seems to have emerged in some recent version of Radicale. When synching calendar modifications from the laptop (even the slightest modifications on a single calendar almost devoid of entries), the server CPU jumps to 100% for over 15 mins. Eventually it writes the changes, but Lightning still throws "MODIFICATION FAILED" error messages, probably because it takes so long.
Before anyone shouts out the low specifications of the Raspberry Pi B+, because indeed they are low, it used to be possible to synchronize quite a few entries from Lightning without getting error messages (even if it would take a while, it would finish writing all changes, and not takes ages to write a single modification while still displaying time-out error messages).
I tried to modify the Radicale config file and setting filesystem_fsync to False (since its description implies that having it enabled might have negative impact on performace) as well as increasing the timeout but the behaviour remains.
Has anything changed in the most recent versions of Radicale? How can this detrimental performance be remedied?

**Comment by evilham** [comment]
Hey @Captain-Rage,
which version of Radicale are you using? If it's 1.X, give 2.X a go. Maybe your collections have grown big and they are being stored in one huge file, so that could be it.
On 2.X a lot has changed, specifically about storage where contacts / events are stored in separate files; so what I am guessing is your issue should be gone.
Do give this a read: http://radicale.org/1to2/

**Comment by Captain-Rage** [comment]
Thank you very much for the reply and input. I'm currently using radicale 2.1.8. That is a very good point. Indeed, I haven't tended to the database for a very long time. Maybe the best thing would simply be to start with a clean one (since only 1-2 users have been using it, and only 1 user actively).
As I recall, I didn't have to do any manual intervention when upgrading from 1.x → 2.x (on Arch Linux ARM). Maybe I should have, but didn't. The upgrade was done a very long time ago, however, and things seemed to be working.
I will read up on the resources you provided and once I get a moment to spare I will start with a fresh calendar / database. Thanks for all the help!

**Comment by Unrud** [comment]
This sounds like you selected **iCalendar (ICS)** in Thunderbird when you added the calendar. You have to choose **CalDAV**.

**Comment by Captain-Rage** [comment]
Yes, how did you know?!? When I was trying to resolve the molasses issue I kept removing/unsubscribing and resubscribing the calendar in Thunderbird using the iCalender (ICS) option (since I was positive that it was the setting I had been using earlier and kept reselecting it). Now I tried the CalDAV option and now everything is back to being fast! Editing/adding/removing events take a few seconds now (in contrast to 15 min; no exaggeration!!!).
Somehow I must have made a change for some reason at some point, which was detrimental for performance.
Thank you very, very, very, very, very much for helping me out. Now Radicale is running swiftly once again and syncing across all my devices.
If you care to elabore why CalDAV is so fast in contrast to the iCalendar option it would be swell, and if not I'm marking this problem as solved. Thank you both once again for saving me a heap of trouble!!

**Comment by Unrud** [comment]
> If you care to elabore why CalDAV is so fast in contrast to the iCalendar option it would be swell,

``iCalendar (ICS)`` overwrites the whole calendar on the server, every time a change is made to any event/task. ``CalDAV`` only uploads the changed events/tasks.

Radicale uses [VObject](https://github.com/eventable/vobject) for parsing calendar and address books. Unfortunately the library is pretty slow. Parsing a big calendar on a very slow computer (like the Raspberry Pi) takes forever.
