### ISSUE TITLE
Unable to sync addressbook, bad client?

### ISSUE THREAD

**Issue by reyaz006** [Kozea/Radicale#743]
I have Python 3.4.4 on Windows Server 2003. And The Bat mail client (latest version).

The problem is that the client does not report any error, and after second sync all contacts disappear. Then in web panel I can see that a new addressbook was created with random name for each contact. The one created through web panel remains empty.

Log shows this on sync attempt:
```
[dd0] ERROR: An exception occurred during REPORT request on '/admin/': [Errno 13] Permission denied: 'C:\\Radicale\\db\\collection-root\\admin\\96172bf2-f96b-1ad1-5697-99b0906df770'
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\radicale\__init__.py", line 321, in __call__
    status, headers, answers = self._handle_request(environ)
  File "C:\Python34\lib\site-packages\radicale\__init__.py", line 494, in _handle_request
    environ, base_prefix, path, user)
  File "C:\Python34\lib\site-packages\radicale\__init__.py", line 944, in do_REPORT
    base_prefix, path, xml_content, collection)
  File "C:\Python34\lib\site-packages\radicale\xmlutils.py", line 1250, in report
    multistatus):
  File "C:\Python34\lib\site-packages\radicale\xmlutils.py", line 1215, in retrieve_items
    for name, item in collection.get_multi2(get_names()):
  File "C:\Python34\lib\site-packages\radicale\storage.py", line 1427, in get_multi2
    yield (href, self.get(href, verify_href=False))
  File "C:\Python34\lib\site-packages\radicale\storage.py", line 1255, in get
    item, metadata = self._get_with_metadata(href, verify_href=verify_href)
  File "C:\Python34\lib\site-packages\radicale\storage.py", line 1362, in _get_with_metadata
    with open(path, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Radicale\\db\\collection-root\\admin\\96172bf2-f96b-1ad1-5697-99b0906df770'

```

**Comment by Unrud** [comment]
> Then in web panel I can see that a new addressbook was created with random name for each contact. 

The client thinks that ``/admin/`` is the URL of the address book and not ``/admin/XXX/``.
Try to add the calendar with the full URL.

**Comment by reyaz006** [comment]
You mean address book? I've been trying exactly that - full URL includes a generated string after /admin/.

**Comment by return42** [comment]
To me it looks like a simple missing (read) 'PermissionError' when it comes to read the file `C:\\Radicale\\db\\collection-root\\admin\\96172bf2-f96b-1ad1-5697-99b0906df770`. Please check the read/write permissions of the Radicale server process, does the user which runs the server has such permissions?

**Comment by Unrud** [comment]
> To me it looks like a simple missing (read) 'PermissionError' when it comes to read the file `C:\\Radicale\\db\\collection-root\\admin\\96172bf2-f96b-1ad1-5697-99b0906df770`.

The error message is misleading. It's caused by a minor bug in Radicale on Windows. Opening the file doesn't fail because of missing permissions, it fails because it's a directory. Python on Windows throws ``PermissionError``, on Linux/Unix it throws ``IsADirectoryError``:

https://github.com/Kozea/Radicale/blob/3471561a9fb339070eda44a26914347c69d458da/radicale/storage.py#L1364

The error can be ignored, it's just an aftereffect of the client thinking that the address book URL is ``/admin/``.

> You mean address book? I've been trying exactly that - full URL includes a generated string after /admin/.

That should work.

**Comment by return42** [comment]
> The error message is misleading.

Ah, ok .. thanks for clarifying!

**Comment by reyaz006** [comment]
Well, like I've said, I've already tried this.

I installed latest The Bat client.
I started Radicale on server. Logged in as "admin" with no password.
I created new addressbook, its URL is http://127.0.0.1:5232/admin/4981f4db-e889-1770-673f-464fd2a8f75c/
I added this URL (with proper IP of course) to the client configuration, added as CardDAV server.
I added one contact to this new addressbook.
I pressed Sync (it asked to log in, I entered "admin" with no password). No errors.
I pressed Sync again. Contact disappeared (got removed, I guess).
I now see 2 addressbooks in Radicale web panel. The latest one is /admin/781F3537-5DD12C1A.vcf/

What am I doing wrong?

**Comment by Unrud** [comment]
> Well, like I've said, I've already tried this.

Yes, I just meant that it should have worked.

The client is buggy. It doesn't use the provided URL, but reads the [CARDDAV:addressbook-home-set](https://tools.ietf.org/html/rfc6352#section-7.1.1) property from the server and uses it as the address book URL. This is wrong. The property doesn't point to a address book, but to a collection that contains address books.

> What am I doing wrong?

Nothing.

**Comment by reyaz006** [comment]
Ok, thank you.
