### ISSUE TITLE
upgrade fails with no such option: --export-storage

### ISSUE THREAD

**Issue by pdarcos** [Kozea/Radicale#744]
Hi,

Trying to upgrade to latest code from 1.1.1 on Debian.
Followed your instructions but when I use the --export-storage switch I get the following error:

root@linux:/etc/radicale# radicale --export-storage /home/debian/radicale_storage/
Usage: radicale [options]

radicale: error: no such option: --export-storage
root@linux:/etc/radicale# 

How can I get around this so I don't lose data on upgrade?

Thanks

**Comment by lemmingz** [comment]
Hi,

you might need to upgrade to at least version 1.1.3,
 where this option has been added. (https://github.com/Kozea/Radicale/blob/1.1.6/NEWS.rst#113---fourth-law-of-nature)

**Comment by pdarcos** [comment]
Yup, that solved it.

Thanks
