### ISSUE TITLE
Can't start Radicale. Permission problem?

### ISSUE THREAD

**Issue by xrobham** [Kozea/Radicale#745]
I installed Radicale on Fedora 26 with dnf install radicale. It was radicale-1.1.6-1.fc26.noarch. Because I installed it on a server without X i didn't try it as installed but went ahead to configure it. For that I used the page http://radicale.org/setup/ I chose  the "Linux with systemd system-wide" path.

When I write systemctl start radicale I don't get any feedback (errors etc). When I write 
systemctl status radicale I get: 

`● radicale.service - A simple CalDAV (calendar) and CardDAV (contact) server
   Loaded: loaded (/etc/systemd/system/radicale.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-11-16 11:35:53 EET; 12min ago
  Process: 21206 ExecStart=/usr/bin/env python3 -m radicale (code=exited, status=1/FAILURE)
 Main PID: 21206 (code=exited, status=1/FAILURE)

nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Main process exited, code=exited, status=1/FAILURE
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Unit entered failed state.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Failed with result 'exit-code'.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
nóv 16 11:35:53 s[...]n.com systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Start request repeated too quickly.
nóv 16 11:35:53 s[...]n.com systemd[1]: Failed to start A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Unit entered failed state.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Failed with result 'exit-code'.
`

If I try journalctl --unit radicale.service I get this:

nóv 16 11:35:50 s[...]n.com systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:50 s[...]n.com python3[21190]: detected unhandled Python exception in '/usr/lib/python3.6/site-packages/radicale/__main__.py'
nóv 16 11:35:50 s[...]n.com python3[21190]: can't communicate with ABRT daemon, is it running? [Errno 13] Permission denied
nóv 16 11:35:50 s[...]n.com python3[21190]: error sending data to ABRT daemon: 
nóv 16 11:35:50 s[...]n.com env[21190]: Traceback (most recent call last):
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
nóv 16 11:35:50 s[...]n.com env[21190]:     "__main__", mod_spec)
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
nóv 16 11:35:50 s[...]n.com env[21190]:     exec(code, run_globals)
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 325, in <module>
nóv 16 11:35:50 s[...]n.com env[21190]:     run()
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 210, in run
nóv 16 11:35:50 s[...]n.com env[21190]:     log.start()
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 54, in start
nóv 16 11:35:50 s[...]n.com env[21190]:     configure_from_file(filename, debug)
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 40, in configure_from_file
nóv 16 11:35:50 s[...]n.com env[21190]:     logging.config.fileConfig(filename)
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib64/python3.6/logging/config.py", line 84, in fileConfig
nóv 16 11:35:50 s[...]n.com env[21190]:     handlers = _install_handlers(cp, formatters)
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib64/python3.6/logging/config.py", line 148, in _install_handlers
nóv 16 11:35:50 s[...]n.com env[21190]:     h = klass(*args)
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1030, in __init__
nóv 16 11:35:50 s[...]n.com env[21190]:     StreamHandler.__init__(self, self._open())
nóv 16 11:35:50 s[...]n.com env[21190]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1059, in _open
nóv 16 11:35:50 s[...]n.com env[21190]:     return open(self.baseFilename, self.mode, encoding=self.encoding)
nóv 16 11:35:50 s[...]n.com env[21190]: PermissionError: [Errno 13] Permission denied: '/var/log/radicale/radicale.log'
nóv 16 11:35:50 s[...]n.com systemd[1]: radicale.service: Main process exited, code=exited, status=1/FAILURE
nóv 16 11:35:50 s[...]n.com systemd[1]: radicale.service: Unit entered failed state.
nóv 16 11:35:50 s[...]n.com systemd[1]: radicale.service: Failed with result 'exit-code'.
nóv 16 11:35:51 s[...]n.com systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
nóv 16 11:35:51 s[...]n.com systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:51 s[...]n.com systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:51 s[...]n.com python3[21194]: detected unhandled Python exception in '/usr/lib/python3.6/site-packages/radicale/__main__.py'
nóv 16 11:35:51 s[...]n.com python3[21194]: can't communicate with ABRT daemon, is it running? [Errno 13] Permission denied
nóv 16 11:35:51 s[...]n.com python3[21194]: error sending data to ABRT daemon: 
nóv 16 11:35:51 s[...]n.com env[21194]: Traceback (most recent call last):
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
nóv 16 11:35:51 s[...]n.com env[21194]:     "__main__", mod_spec)
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
nóv 16 11:35:51 s[...]n.com env[21194]:     exec(code, run_globals)
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 325, in <module>
nóv 16 11:35:51 s[...]n.com env[21194]:     run()
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 210, in run
nóv 16 11:35:51 s[...]n.com env[21194]:     log.start()
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 54, in start
nóv 16 11:35:51 s[...]n.com env[21194]:     configure_from_file(filename, debug)
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 40, in configure_from_file
nóv 16 11:35:51 s[...]n.com env[21194]:     logging.config.fileConfig(filename)
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib64/python3.6/logging/config.py", line 84, in fileConfig
nóv 16 11:35:51 s[...]n.com env[21194]:     handlers = _install_handlers(cp, formatters)
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib64/python3.6/logging/config.py", line 148, in _install_handlers
nóv 16 11:35:51 s[...]n.com env[21194]:     h = klass(*args)
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1030, in __init__
nóv 16 11:35:51 s[...]n.com env[21194]:     StreamHandler.__init__(self, self._open())
nóv 16 11:35:51 s[...]n.com env[21194]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1059, in _open
nóv 16 11:35:51 s[...]n.com env[21194]:     return open(self.baseFilename, self.mode, encoding=self.encoding)
nóv 16 11:35:51 s[...]n.com env[21194]: PermissionError: [Errno 13] Permission denied: '/var/log/radicale/radicale.log'
nóv 16 11:35:51 s[...]n.com systemd[1]: radicale.service: Main process exited, code=exited, status=1/FAILURE
nóv 16 11:35:51 s[...]n.com systemd[1]: radicale.service: Unit entered failed state.
nóv 16 11:35:51 s[...]n.com systemd[1]: radicale.service: Failed with result 'exit-code'.
nóv 16 11:35:51 s[...]n.com systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
nóv 16 11:35:51 s[...]n.com systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:51 s[...]n.com systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:51 s[...]n.com python3[21198]: detected unhandled Python exception in '/usr/lib/python3.6/site-packages/radicale/__main__.py'
nóv 16 11:35:51 s[...]n.com python3[21198]: can't communicate with ABRT daemon, is it running? [Errno 13] Permission denied
nóv 16 11:35:51 s[...]n.com python3[21198]: error sending data to ABRT daemon: 
nóv 16 11:35:51 s[...]n.com env[21198]: Traceback (most recent call last):
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
nóv 16 11:35:51 s[...]n.com env[21198]:     "__main__", mod_spec)
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
nóv 16 11:35:51 s[...]n.com env[21198]:     exec(code, run_globals)
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 325, in <module>
nóv 16 11:35:51 s[...]n.com env[21198]:     run()
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 210, in run
nóv 16 11:35:51 s[...]n.com env[21198]:     log.start()
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 54, in start
nóv 16 11:35:51 s[...]n.com env[21198]:     configure_from_file(filename, debug)
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 40, in configure_from_file
nóv 16 11:35:51 s[...]n.com env[21198]:     logging.config.fileConfig(filename)
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib64/python3.6/logging/config.py", line 84, in fileConfig
nóv 16 11:35:51 s[...]n.com env[21198]:     handlers = _install_handlers(cp, formatters)
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib64/python3.6/logging/config.py", line 148, in _install_handlers
nóv 16 11:35:51 s[...]n.com env[21198]:     h = klass(*args)
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1030, in __init__
nóv 16 11:35:51 s[...]n.com env[21198]:     StreamHandler.__init__(self, self._open())
nóv 16 11:35:51 s[...]n.com env[21198]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1059, in _open
nóv 16 11:35:51 s[...]n.com env[21198]:     return open(self.baseFilename, self.mode, encoding=self.encoding)
nóv 16 11:35:51 s[...]n.com env[21198]: PermissionError: [Errno 13] Permission denied: '/var/log/radicale/radicale.log'
nóv 16 11:35:52 s[...]n.com systemd[1]: radicale.service: Main process exited, code=exited, status=1/FAILURE
nóv 16 11:35:52 s[...]n.com systemd[1]: radicale.service: Unit entered failed state.
nóv 16 11:35:52 s[...]n.com systemd[1]: radicale.service: Failed with result 'exit-code'.
nóv 16 11:35:52 s[...]n.com systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
nóv 16 11:35:52 s[...]n.com systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:52 s[...]n.com systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:52 s[...]n.com python3[21202]: detected unhandled Python exception in '/usr/lib/python3.6/site-packages/radicale/__main__.py'
nóv 16 11:35:52 s[...]n.com python3[21202]: can't communicate with ABRT daemon, is it running? [Errno 13] Permission denied
nóv 16 11:35:52 s[...]n.com python3[21202]: error sending data to ABRT daemon: 
nóv 16 11:35:52 s[...]n.com env[21202]: Traceback (most recent call last):
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
nóv 16 11:35:52 s[...]n.com env[21202]:     "__main__", mod_spec)
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
nóv 16 11:35:52 s[...]n.com env[21202]:     exec(code, run_globals)
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 325, in <module>
nóv 16 11:35:52 s[...]n.com env[21202]:     run()
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 210, in run
nóv 16 11:35:52 s[...]n.com env[21202]:     log.start()
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 54, in start
nóv 16 11:35:52 s[...]n.com env[21202]:     configure_from_file(filename, debug)
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 40, in configure_from_file
nóv 16 11:35:52 s[...]n.com env[21202]:     logging.config.fileConfig(filename)
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib64/python3.6/logging/config.py", line 84, in fileConfig
nóv 16 11:35:52 s[...]n.com env[21202]:     handlers = _install_handlers(cp, formatters)
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib64/python3.6/logging/config.py", line 148, in _install_handlers
nóv 16 11:35:52 s[...]n.com env[21202]:     h = klass(*args)
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1030, in __init__
nóv 16 11:35:52 s[...]n.com env[21202]:     StreamHandler.__init__(self, self._open())
nóv 16 11:35:52 s[...]n.com env[21202]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1059, in _open
nóv 16 11:35:52 s[...]n.com env[21202]:     return open(self.baseFilename, self.mode, encoding=self.encoding)
nóv 16 11:35:52 s[...]n.com env[21202]: PermissionError: [Errno 13] Permission denied: '/var/log/radicale/radicale.log'
nóv 16 11:35:52 s[...]n.com systemd[1]: radicale.service: Main process exited, code=exited, status=1/FAILURE
nóv 16 11:35:52 s[...]n.com systemd[1]: radicale.service: Unit entered failed state.
nóv 16 11:35:52 s[...]n.com systemd[1]: radicale.service: Failed with result 'exit-code'.
nóv 16 11:35:52 s[...]n.com systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
nóv 16 11:35:52 s[...]n.com systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:52 s[...]n.com systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:52 s[...]n.com python3[21206]: detected unhandled Python exception in '/usr/lib/python3.6/site-packages/radicale/__main__.py'
nóv 16 11:35:52 s[...]n.com python3[21206]: can't communicate with ABRT daemon, is it running? [Errno 13] Permission denied
nóv 16 11:35:52 s[...]n.com python3[21206]: error sending data to ABRT daemon: 
nóv 16 11:35:52 s[...]n.com env[21206]: Traceback (most recent call last):
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
nóv 16 11:35:52 s[...]n.com env[21206]:     "__main__", mod_spec)
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
nóv 16 11:35:52 s[...]n.com env[21206]:     exec(code, run_globals)
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 325, in <module>
nóv 16 11:35:52 s[...]n.com env[21206]:     run()
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib/python3.6/site-packages/radicale/__main__.py", line 210, in run
nóv 16 11:35:52 s[...]n.com env[21206]:     log.start()
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 54, in start
nóv 16 11:35:52 s[...]n.com env[21206]:     configure_from_file(filename, debug)
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib/python3.6/site-packages/radicale/log.py", line 40, in configure_from_file
nóv 16 11:35:52 s[...]n.com env[21206]:     logging.config.fileConfig(filename)
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib64/python3.6/logging/config.py", line 84, in fileConfig
nóv 16 11:35:52 s[...]n.com env[21206]:     handlers = _install_handlers(cp, formatters)
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib64/python3.6/logging/config.py", line 148, in _install_handlers
nóv 16 11:35:52 s[...]n.com env[21206]:     h = klass(*args)
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1030, in __init__
nóv 16 11:35:52 s[...]n.com env[21206]:     StreamHandler.__init__(self, self._open())
nóv 16 11:35:52 s[...]n.com env[21206]:   File "/usr/lib64/python3.6/logging/__init__.py", line 1059, in _open
nóv 16 11:35:52 s[...]n.com env[21206]:     return open(self.baseFilename, self.mode, encoding=self.encoding)
nóv 16 11:35:52 s[...]n.com env[21206]: PermissionError: [Errno 13] Permission denied: '/var/log/radicale/radicale.log'
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Main process exited, code=exited, status=1/FAILURE
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Unit entered failed state.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Failed with result 'exit-code'.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
nóv 16 11:35:53 s[...]n.com systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Start request repeated too quickly.
nóv 16 11:35:53 s[...]n.com systemd[1]: Failed to start A simple CalDAV (calendar) and CardDAV (contact) server.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Unit entered failed state.
nóv 16 11:35:53 s[...]n.com systemd[1]: radicale.service: Failed with result 'exit-code'.

It has problems with the ABRT daemon. What should I do about that? Also it has problems with permisson of var/log/radicale/radicale.log. What should the permissons and ownerships be?

Grateful for all help.
Xrobham

**Comment by Unrud** [comment]
The documentation at http://radicale.org/setup/` is for Radicale 2.x.x. Your are using 1.1.x.

**Comment by stronkje** [comment]
You should hange service file, to prevent error 30: read-only file system"
edit this line "#ReadWritePaths=/var/lib/radicale/collection-root'
Uncomment and fill in right path.

**Comment by pbiering** [comment]
closed as report is over 5 years old
