### ISSUE TITLE
Contact sync issue with iOS

### ISSUE THREAD

**Issue by Ozonid** [Kozea/Radicale#746]
Hello!

I'd like to ask for some help related to Radicale cardDAV server. I've set up a droplet in DigitalOcean with nginx, ssl and radicale. We're trying to connect to it with an iPhone using the built-in cardDAV support (add account -> other -> cardDAV account).
From the server logs it's clear that the phone connects to the server. I see multiple "'wsgi.errors': <_io.StringIO object at 0x7f1a5293b798>" lines in the logs, a folder is (automatically) created for the user in collection-root, but it's empty.
Do I have to create an addressbook before trying to connect with the phone?

Here's the config I'm using right now:

For Radicale
```
[auth]
type = htpasswd
htpasswd_filename = /etc/radicale/htpasswd
htpasswd_encryption = plain

[storage]
type = multifilesystem
filesystem_folder = /etc/radicale

[server]
protocol = PROTOCOL_TLS
ssl = True
certificate = /etc/nginx/server_cert.pem
key = /etc/nginx/server_key.pem
certificate_authority = /etc/nginx/client_cert.pem
```

For nginx
```
location /radicale/ {
    proxy_pass           https://localhost:5232/;
    proxy_set_header     X-Script-Name /radicale;
    proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_ssl_certificate         /etc/nginx/client_cert.pem;
    proxy_ssl_certificate_key     /etc/nginx/client_key.pem;
    proxy_ssl_trusted_certificate /etc/nginx/server_cert.pem;
}
```

**Comment by Unrud** [comment]
> I see multiple "'wsgi.errors': <_io.StringIO object at 0x7f1a5293b798>" lines in the logs

That's not an error. It's part of some debug output. Errors start with ``[xxx] ERROR: ...`` and warnings with ``[xxx] WARNING: ...``.

> a folder is (automatically) created for the user in collection-root, but it's empty.

Address books and calendars are not created automatically.

> Do I have to create an addressbook before trying to connect with the phone?

Have you tried to create a new address book on the phone (if it's even possible). You can also try to create address book before connecting the phone.
