### ISSUE TITLE
Getting TLSV1_ALERT_UNKNOWN_CA when trying to use Calendar.app 

### ISSUE THREAD

**Issue by pidydx** [Kozea/Radicale#747]
I am setting up a test server using the snakeoil certs on ubuntu 16.04 and any time I attempt to connect with Calendar.app (9.0 (2155.21) (macOS 10.12.6)  when using ssl I get the following error in the radicale.log:

ERROR: An exception occurred during request: SSL handshake failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:645)

However, when I connect with Safari or Firefox it correctly prompts me to log in and there are no errors in radicale.log.  Is there a setting I am missing or some kind of incompatibility bug?

**Comment by Unrud** [comment]
>
```
ERROR: An exception occurred during request: SSL handshake failed: [SSL:TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:645)
```

This just means, that the invalid certificate was rejected. Some clients allow you to add an exception for invalid certificates.

> However, when I connect with Safari or Firefox it correctly prompts me to log in and there are no errors in radicale.log.

But you must have added an exception for the invalid certificate.

 If Calendar app doesn't allow you the add an exception, you may have the option of installing the CA (probably self-signed) for the snake oil certificates.

**Comment by Tntdruid** [comment]
Apple does not like self-signed certs, you can get a free one whit etc http://letsencrypt.org

**Comment by return42** [comment]
> Apple does not like self-signed certs
Sorry, that's wrong. Add your self signed cert to macOS's Keychain and Calender & Contacts should work. Here, I have the same setup as the opener and for me, it works. BTW Firefox brings its own keychain. It does not matter which OS, if you add a cert in FFox it will never be added to OS's keychain. If you add a cert in Safari, it will be added to macOS's Keychain.

**Comment by pidydx** [comment]
I tried with macOS keychain and didn't have any luck in this case, but normally that has worked for me with other self signed things which is why I was confused as to what else may be happening here.  However, once I got letsencrypt going it worked fine so I may have just screwed up adding the self signed cert.
