### ISSUE TITLE
CardDAV Synch Free support

### ISSUE THREAD

**Issue by typhoon71** [Kozea/Radicale#749]
I'm trying to use Radicale to synch to Android, and it works perfectly with DavDroid, both for addressbooks and calendars. 

My problem is that I cannot seem to syinch the addresbook with CardDAV Synch Free, and I don't see any blatant issue: it logs in I see the logs give permissions to the user and I even see the addressbook... but it's empty. Is CardDAV Synch Free supported? 

I would like to use Radicale to share an addressbook with users that already have that app installed, and don't wich to use DavDroid (because it's not from Google App Store)

I have this running on a ubuntu machine, since I was having issues on my nas. Since I see it working on Android, I'll now try working on the redirect (the other possible issue), and I'd like to know if CardDAV Synch Free is supported (or, if not, if it'll ever be).

Thanks for any help, and for Radicale itself too.

**Comment by Unrud** [comment]
[CardDAV-Sync free](https://play.google.com/store/apps/details?id=org.dmfs.carddav.sync) works for me. You have to add at least one address book to the user before you try to connect with the app, otherwise it fails.

**Comment by tmst** [comment]
On Tue, Dec 5, 2017, at 12:42 PM, typhoon71 wrote:
> I'm trying to use Radicale to synch to Android, and it works perfectly
> with DavDroid, both for addressbooks and calendars.
Did you happen to try it for tasks? I was seeing the category get
deleted when I tried it a few months ago.
> I have this running on a ubuntu machine, since I was having issues on
> my nas. Since I see it working on Android, I'll now try working on the
> redirect (the other possible issue), and I'd like to know if CardDAV
> Synch Free is supported (or, if not, if it'll ever be).
It *should* be supported. But I've been using only the paid version of
CardDAV-Sync with more supported fields, so I can't say the free version
definitely works.

**Comment by pbiering** [comment]
closing as 5 years old, please reopen if replicated with current versions
