### ISSUE TITLE
Can't import .ics file from OwnCloud

### ISSUE THREAD

**Issue by conchyliculture** [Kozea/Radicale#750]
I installed Radicale in a Debian Sid environment with pip3
```
# radicale --version
2.1.8
```
I exported my calendar from owncloud as a  cal.ics file. I moved this file to my storage folder in Radicale:
`filesystem_folder/collection-root/user/cal.ics`, and made sure permissions were correctly sef.
After logging on the web interface, I am greeted with an error 500.

The Radicale log crashes with :

```
2017-12-08 11:10:25,266 - [7fbedb466700] INFO: Successful login: 'user'
2017-12-08 11:10:25,270 - [7fbedb466700] DEBUG: 'user' has read and write access to collection 'user'
2017-12-08 11:10:25,285 - [7fbedb466700] ERROR: An exception occurred during PROPFIND request on '/user/': Failed to load item 'cal.ics' in 'user': Item type 'VCALENDAR' not supported in generic collection
```
This shortened version of my cal.ics file also triggers the error:
```
BEGIN:VCALENDAR 
VERSION:2.0 
PRODID:ownCloud Calendar 0.6.4 
X-WR-CALNAME:cal 
BEGIN:VEVENT 
DTSTAMP:20140107T165713Z 
DTSTART;TZID=Europe/London:20140107T174000 
DTEND;TZID=Europe/London:20140107T184000 
SUMMARY:Lol 
DESCRIPTION:Test 
CLASS:PUBLIC 
STATUS:CONFIRMED 
UID:3cd9a5cb-1c0b-4311-b07b-39572de59d67-caldavsyncadapter 
BEGIN:VALARM 
TRIGGER;VALUE=DURATION:-PT120M 
DESCRIPTION:caldavsyncadapter standard description 
ACTION:DISPLAY 
END:VALARM 
BEGIN:VALARM 
TRIGGER;VALUE=DURATION:-PT60M 
DESCRIPTION:caldavsyncadapter standard description 
ACTION:DISPLAY 
END:VALARM 
END:VEVENT 
END:VCALENDAR 
```

Is there maybe another way to import ICS files in Radicale?

**Comment by Unrud** [comment]
> I moved this file to my storage folder in Radicale

This doesn't work: [Storage Layout](http://radicale.org/storage/#layout)

> Is there maybe another way to import ICS files in Radicale?

```
curl -u 'user:password' -X PUT http://localhost:5232/user/calendar --data-binary @cal.ics
```

**Comment by conchyliculture** [comment]
The curl command works great!
I would suggest having it somewhere more proeminent in the doc =)

**Comment by NopMap** [comment]
I have the same task of importing/migrating a calendar from a differnet machine and was very happy to find this issue.

A section in the documentation about import and migration would be much appreciated.

**Comment by florihupf** [comment]
Just here to say thanks for the curl command.

**Comment by seriousramius** [comment]
> > I moved this file to my storage folder in Radicale
> 
> This doesn't work: [Storage Layout](http://radicale.org/storage/#layout)
> 
> > Is there maybe another way to import ICS files in Radicale?
> 
> ```
> curl -u 'user:password' -X PUT http://localhost:5232/user/calendar --data-binary @cal.ics
> ```

Thanks for the advice but it doesn't helped me. It produced a returncode 400. I'm not sure if the issue was the wrong accessrights, which i found out later. But the solution for me was to export my calender in thunderbird as an ICS-File and install CALDAV/CARDDAV Sync for android. So i created a new calender in radicale at first in their webinterface and configured the connection to radicle via http://localhost:5232/username and the credentials. Then i used simple Calendar Pro and imported the ics file and changed the view to 'year' and let the sync ran.
