### ISSUE TITLE
Address book entries for humans only?

### ISSUE THREAD

**Issue by larsskj** [Kozea/Radicale#752]
Hi,

I'm preparing to upgrade from Radicale 1.x to 2.x. Database converted, moved to my cluster, and Radicale 2.x up and running as a Docker container. Testing version 2.1.8.

But it fails on my first test: Trying to load my addressbook returns

`A server error occurred.  Please contact the administrator.`

The log says:

`ERROR: An exception occurred during GET request on '/lars@skjaerlund.dk/addressbook.vcf/': Failed to load item '4a294155-c32d-4739-9459-78d4ff4202b1.vcf' in 'lars@skjaerlund.dk/addressbook.vcf': 'VCARD components must contain at least 1 FN'`

This is correct: The VCF in question does not contain an FN as this particular entry is for a company without a contact person. Entries like that works fine on all my platforms and with Radicale 1.x - but apparently not 2.x?

Can't you have addressbook entries for anything but humans anymore?

Regards,
Lars

**Comment by mooninite** [comment]
I've seen the same error in a 1.x to 2.x upgrade, but for "N" instead of "FN". The entry had an "FN", but no "N". Adding an "N" resolved it, but yes it was annoying that the 1.x export didn't catch this or that 2.x is so strict.

**Comment by jardleex** [comment]
I just stumbled over the same issue that the FN field is missing in my contacts. I've exported the data with the `--export-storage` flag on the v1.x radicale instance and use the files inside a docker instance based on v2.x then.

Is there an easy way to fix that? I do have several dozend contacts and don't want to edit the vcard's by hand on the servers disk.

**Comment by tmst** [comment]
On Mon, Feb 19, 2018, at 8:56 AM, Robert Hecht wrote:
> I just stumbled over the same issue that the FN field is missing in my
> contacts. I've exported the data with the --export-storage flag on the
> v1.x radicale instance and use the files inside a docker instance
> based on v2.x then.> Is there an easy way to fix that? I do have several dozend contacts
> and don't want to edit the vcard's by hand on the servers disk.> 

Just wondering: Are you using the Thunderbird client?

**Comment by jardleex** [comment]
I've used Davdroid which failed with an error. 
I also use Thunderbird on Ubuntu which gave no error. The radicale log gave logged the same error on both cases.
In the end I fixed the contacts by hand while re-syncing the contacts via Thunderbird (easier then on the mobile phone).

**Comment by tmst** [comment]
So you edited the broken record files one by one by just adding the missing  FN field to each? I hope there weren't 200 of them! I took the other approach and fixed them in Radicale 1.x, then re-exported. Same pain.

**Comment by oneyb** [comment]
Hello there,
yeah, I am having this problem to related to https://github.com/eventable/vobject parsing. Here's how I solved it:
```bash
 find . -type f -name "*vcf" -exec grep -L FN {} + | xargs sed -ri 's/^N:(.*$)/N:\1\nFN:\1/
```
It finds all the VCF-files below the current directory, that don't have a FN tag, pipes them into sed which copies the name "N" field to the full name "FN" field.
HTH

**Comment by tmst** [comment]
Nice. Just don't include eye of bat. LOL.

**Comment by logological** [comment]
> `ERROR: An exception occurred during GET request on '/lars@skjaerlund.dk/addressbook.vcf/': Failed to load item '4a294155-c32d-4739-9459-78d4ff4202b1.vcf' in 'lars@skjaerlund.dk/addressbook.vcf': 'VCARD components must contain at least 1 FN'`
> 
> This is correct: The VCF in question does not contain an FN as this particular entry is for a company without a contact person. Entries like that works fine on all my platforms and with Radicale 1.x - but apparently not 2.x?
> 
> Can't you have addressbook entries for anything but humans anymore?

I don't think being human has anything to do with it. [The vCard specification](https://tools.ietf.org/html/rfc6350#section-6.2.1) defines the `FN` property as follows:
```
  Purpose:  To specify the formatted text corresponding to the name of
      the object the vCard represents.

   Value type:  A single text value.

   Cardinality:  1*

   Special notes:  This property is based on the semantics of the X.520
      Common Name attribute [CCITT.X520.1988].  The property MUST be
      present in the vCard object.
```

So it is true that `FN` must be present in every vCard entry, and it needs to store a name of some sort, but not necessarily a person's name; entering a company name here should be fine.  Radicale is therefore correct to reject vCard entries missing this property.  The proper solution is to edit the vCard entries to make sure they have a `FN` property.  I used a variation of the command provided by @oneyb for this purpose.

I suspect this issue can be closed.

**Comment by mooninite** [comment]
> I suspect this issue can be closed.

The issue is that the Radicale import is not working with its own data set. It is written to import Radicale 1.x data into Radicale 2.x. Radicale 1.x was writing entries "out of spec" based on your interpretation. The import process needs to handle that case instead of just failing out. It's a bad user experience.

**Comment by larsskj** [comment]
> The issue is that the Radicale import is not working with its own data set.
Exactly.

**Comment by logological** [comment]
I see—so the problem is not that Radicale 2.x doesn't serve entries without an `FN`, but rather that you wanted these entries to be automatically converted to the standards-conforming format (either by Radicale 1.x's `--export-storage` command, or by whatever process Radicale 2.x uses to import that storage)?  If so, the title of this issue could be made a bit more accurate.
