### ISSUE TITLE
bad PUT request

### ISSUE THREAD

**Issue by Mikmu** [Kozea/Radicale#753]
Hi there,

I've got a strange issue here. All appointments are OK except two (but I've got other appointments from that contact). 

Client: Thinderbird 52.5.0 with Lighning 5.4.5
Server: Radicale 2.1.8

Debug file has no further infos except this (user@domain.de is replacement for real values of course):

WARNING: Bad PUT request on '/user@domain.de/c3d28ff8-d74d-7e62-8505-e00fe718520b/040000008200E00074C5B7101A82E008000000006095955E8A5CD301000000000000000010000000DD8B76E68775A34A825553DFCFC6A691.ics': Failed to store item '040000008200E00074C5B7101A82E008000000006095955E8A5CD301000000000000000010000000DD8B76E68775A34A825553DFCFC6A691.ics' in collection 'user@domain.de/c3d28ff8-d74d-7e62-8505-e00fe718520b': Main component missing

Lightning reports error code 80004005. Any ideas?

Cu
Mirko

**Comment by tmst** [comment]
Could it be the ICS filename is too short and not unique?

Just joking. The URL seems to be missing a path element for the user
and/or collection root. Right?
On Sun, Dec 10, 2017, at 04:29 AM, Mikmu wrote:
> Hi there,


> I've got a strange issue here. All appointments are OK except two (but
> I've got other appointments from that contact).> Client: Thinderbird 52.5.0 with Lighning 5.4.5
>  Server: Radicale 2.1.8


> Debug file has no further infos except this (user@domain.de is
> replacement for real values of course):> WARNING: Bad PUT request on '/user@domain.de/c3d28ff8-d74d-7e62-8505-
> e00fe718520b/040000008200E00074C5B7101A82E008000000006095955E8A5CD301-
> 000000000000000010000000DD8B76E68775A34A825553DFCFC6A691.ics': Failed
> to store item '040000008200E00074C5B7101A82E008000000006095955E8A5CD3-
> 01000000000000000010000000DD8B76E68775A34A825553DFCFC6A691.ics' in
> collection 'user@domain.de/c3d28ff8-d74d-7e62-8505-e00fe718520b': Main
> component missing> Lightning reports error code 80004005. Any ideas?


> Cu
>  Mirko


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/Kozea/Radicale/issues/753

**Comment by Mikmu** [comment]
> The URL seems to be missing a path element for the user and/or collection root. Right?
Uhm....no clue at all, sorry... Any thing I can do? This appointment is originally posted by Outlook 2010 as many other appointments I receive from that account....

**Comment by tmst** [comment]
On Tue, Dec 12, 2017, at 10:49 AM, Mikmu wrote:
>> The URL seems to be missing a path element for the user and/or
>> collection root. Right?>>  Uhm....no clue at all, sorry... Any thing I can do? This appointment
>>  is originally posted by Outlook 2010 as many other appointments I
>>  receive from that account.
That's about the extent of my insight. Sorry.
