### ISSUE TITLE
Use valid HTTPS for the website

### ISSUE THREAD

**Issue by C0rn3j** [Kozea/Radicale#757]
Hiya, the current website does not work via HTTPS due to it having a wrong certificate (github one)

https://radicale.org

The site should have a valid TLS certificate, and redirect HTTP to HTTPS. (and possibly have HSTS header and be on the HSTS preload list)

Since the website has install instructions + links to downloads, I think HTTPS is important.

More reasons for HTTPS are here -https://doesmysiteneedhttps.com/

**Comment by liZe** [comment]
As far as I know, it's not possible to tell GitHub pages to use a certificate with a custom domain. See isaacs/github#156.

**Comment by return42** [comment]
I can't see any security progress by using signed certificates. Just show the fingerprint (e.g. on the 'About' page)  should be enough.

**Comment by tmst** [comment]
On Mon, Dec 18, 2017, at 8:51 AM, Markus Heiser wrote:
> I can't see any security progress by using signed certificates. Just
> show the fingerprint (e.g. on the 'About' page)  should be enough.
Without HTTPS, can't the page can be intercepted and the fingerprint
altered on its way to the user?

**Comment by return42** [comment]
> Without HTTPS, can't the page can be intercepted 

you can use HTTPS without a signed cert (e.g. manual validation of the fingerprint).

> and the fingerprint altered on its way to the user?

OK, but what is the alternative; you have to trust into the various build in CA lists (e.g. the one of Mozilla https://wiki.mozilla.org/CA/Included_Certificates). 

What I mean: I do not feel secure with such unknown CA lists.

**Comment by C0rn3j** [comment]
>you can use HTTPS without a signed cert (e.g. manual validation of the fingerprint).

Not sure if you can get in HSTS preload list if you do that. Also browsers hate it and users won't put up with that.


>What I mean: I do not feel secure with such unknown CA lists.

>  OK, but what is the alternative; you have to trust into the various build in CA lists 

The CA system is shit but it's the only thing we have at the moment.

**Comment by return42** [comment]
> The CA system is shit but it's the only thing we have at the moment.

right, you say it.

**Comment by NeverDucky** [comment]
one could alternatively use https://kozea.github.io/Radicale/ if it didn't redirect to http://radicale.org
otherwise it shouldn't be too hard for the webmaster to use Let's Encrypt, no?

**Comment by liZe** [comment]
https://radicale.org/
