### ISSUE TITLE
Installation troubles on Ubuntu 16.04

### ISSUE THREAD

**Issue by eraserpencil** [Kozea/Radicale#762]
Have been trying to set up radicale but get stuck at the "sudo -H python3 -m radicale --config "" --storage-filesystem-folder=~/.var/lib/radicale/collections" command from http://radicale.org/tutorial/. Wasnt so much 5 minute tutorial. 

Here's my command line.
PBJ@ubuntu-512mb-sgp1-01:$ sudo -H python3 -m pip install --upgrade radicale
Collecting radicale
  Downloading Radicale-2.1.8.tar.gz (76kB)
    100% |████████████████████████████████| 81kB 3.9MB/s 
Collecting vobject (from radicale)
  Downloading vobject-0.9.5.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 3.9MB/s 
Collecting python-dateutil>=2.4.0 (from vobject->radicale)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 3.7MB/s 
Requirement already up-to-date: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.4.0->vobject->radicale)
Building wheels for collected packages: radicale, vobject
  Running setup.py bdist_wheel for radicale ... done
  Stored in directory: /root/.cache/pip/wheels/25/04/a5/27bf37395e21674f72e365200cde5288587fb093de33844285
  Running setup.py bdist_wheel for vobject ... done
  Stored in directory: /root/.cache/pip/wheels/d0/c9/09/e5ad6d4f5a2f00d62057073e793797fcedb24e3d999fcc4ee7
Successfully built radicale vobject
Installing collected packages: python-dateutil, vobject, radicale
Successfully installed python-dateutil radicale vobject
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
PBJ@ubuntu-512mb-sgp1-01:$ cd /etc/r
rc0.d/      rc2.d/      rc4.d/      rc6.d/      resolvconf/ 
rc1.d/      rc3.d/      rc5.d/      rcS.d/      rsyslog.d/  
PBJ@ubuntu-512mb-sgp1-01:$ sudo -H python3 -m radicale --config "" --storage-filesystem-folder=/home/PBJ/.var/lib/radicale/collections

and just gets stuck.

**Comment by thunderbird-93** [comment]
Exactly same issue here...

**Comment by EoleDev** [comment]
If i am not wrong,
the command "sudo -H python3 -m radicale --config "" --storage-filesystem-folder=~/.var/lib/radicale/collections" is used to launch the radicale server with the storage filesystem set to a specific folder.
The most important part is that it launch the radicale server. So the command doesn't get stuck... it is the normal behavior. This command doesn't daemonize the server, so it will not return before the server is killed. Try to open the web page  http://localhost:5232/ and i think you will have access to the radicale configuration.

**Comment by thunderbird-93** [comment]
Many thanks! Silly me...

**Comment by return42** [comment]
@thunderbird-93,  @eraserpencil: may you want to have a look at issue #511 (Sandboxing radicale with systemd on Linux).

**Comment by szb80** [comment]
Thanks @EoleDev!  Solved my issue, too!
