### ISSUE TITLE
Lightning (Thunderbird) resets existing calendar

### ISSUE THREAD

**Issue by wralach** [Kozea/Radicale#767]
I am using radicale with Lightning in Thunderbird (on a linux machine).

1. After creating a calendar (VEVENT only) in the radicale web frontend I connect to the calendar using Lightning -> so far so good
2. Then, I create a new calendar entry. The entry is saved and is available -> so far so good
3. However, the creation of the entry has changed (resp. resetted) the calendar settings: the color is lost and the type is VEVENT,**VTODO,VJOURNAL**.

Of course, I can adjust the color again, but I am not able to change the type of the calendar. Adding further entries does not have any "side effects" as long as the type stays "cal, tasks + journal".

I am not sure whether it's a radicale or lightning problem. Or, is it intended, that an external applications can change the settings of the calendar in such a manner?

Thx!

**Comment by Unrud** [comment]
It's a configuration error in Lightning. You have to use ``CalDAV`` for the calendar ant not ``iCalendar (ICS)``. I've added it to the [documentation](http://radicale.org/clients/), it know explicitly states that ``iCalendar (ICS)`` should not be used.
