### ISSUE TITLE
'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by ghost** [Kozea/Radicale#770]
Background:
- Migration from Radicale 1.0 (python 2.7) -> 1.1.6 (python 2.7) -> 2.1.8 (python 3.6)
- Gentoo Linux, x64, gcc-7.2.0
- Python 3.6.3
- dev-python/vobject-0.9.3
- dev-python/bcrypt-3.1.4

Process:
- Upgrade to 1.1.6
- Run with --export-storage
- Remove old radicale-1.1.6 and install radicale-2.1.8 as fresh install
- Run with --verify-storage (FAILED)

--verify-storage phase failes with lots of erros with all ending in "**'bytes' object has no attribute 'encode'**"

> gentoo # radicale -verify-storage --config /etc/radicale/config -f
> [7f823c55c700] ERROR: Invalid item '14717e4c-1158-4a1d-9081-58266eec2ee6.vcf' in 'dav/contacts.vcf': Failed to load item '14717e4c-1158-4a1d-9081-58266eec2ee6.vcf' in 'dav/contacts.vcf': 'bytes' object has no attribute 'encode'
> [7f823c55c700] ERROR: Invalid item '32fcaca3887f48109e4eab5604d06e32' in 'dav/contacts.vcf': Failed to load item '32fcaca3887f48109e4eab5604d06e32' in 'dav/contacts.vcf': 'bytes' object has no attribute 'encode'
> [7f823c55c700] ERROR: Invalid item '8a3e293fcf10425cbfed7fd5e1a95b91' in 'dav/contacts.vcf': Failed to load item '8a3e293fcf10425cbfed7fd5e1a95b91' in 'dav/contacts.vcf': 'bytes' object has no attribute 'encode'
> [7f823c55c700] ERROR: Invalid item 'c48ba8a0-1459-41b5-bb3c-d2fb3677a81a.vcf' in 'dav/contacts.vcf': Failed to load item 'c48ba8a0-1459-41b5-bb3c-d2fb3677a81a.vcf' in 'dav/contacts.vcf': 'bytes' object has no attribute 'encode'
> ....

The same again with debug enabled:

> gentoo # radicale --verify-storage --config /etc/radicale/config -f -D
> 
> [7f1d88f2e700] DEBUG: Verified item 'da8478e3-1662-473a-bcc6-c16f3219e88d.1490335014747.ics' in 'dav/user.ics'
> [7f1d88f2e700] DEBUG: Verified item '7e2b215f-cedf-42a7-9a9f-31f09ae3a9f6.ics' in 'dav/user.ics'
> [7f1d88f2e700] DEBUG: Verified item '89544a33-511f-4c7d-926c-86ed74bdcb1f.1441318604853.ics' in 'dav/user.ics'
> [7f1d88f2e700] DEBUG: Verifying collection 'dav/contacts.vcf'
> [7f1d88f2e700] ERROR: Invalid item '14717e4c-1158-4a1d-9081-58266eec2ee6.vcf' in 'dav/contacts.vcf': Failed to load item '14717e4c-1158-4a1d-9081-58266eec2ee6.vcf' in 'dav/contacts.vcf': 'bytes' object has no attribute 'encode'
> Traceback (most recent call last):
>   File "/usr/lib64/python3.6/site-packages/radicale/storage.py", line 1394, in _get_with_metadata
>     href, vobject_item, input_hash)
>   File "/usr/lib64/python3.6/site-packages/radicale/storage.py", line 1277, in _store_item_cache
>     content = self._item_cache_content(href, vobject_item, cache_hash)
>   File "/usr/lib64/python3.6/site-packages/radicale/storage.py", line 1265, in _item_cache_content
>     text = vobject_item.serialize()
>   File "/usr/lib64/python3.6/site-packages/vobject/base.py", line 255, in serialize
>     return behavior.serialize(self, buf, lineLength, validate)
>   File "/usr/lib64/python3.6/site-packages/vobject/behavior.py", line 162, in serialize
>     out = base.defaultSerialize(transformed, buf, lineLength)
>   File "/usr/lib64/python3.6/site-packages/vobject/base.py", line 993, in defaultSerialize
>     child.serialize(outbuf, lineLength, validate=False)
>   File "/usr/lib64/python3.6/site-packages/vobject/base.py", line 255, in serialize
>     return behavior.serialize(self, buf, lineLength, validate)
>   File "/usr/lib64/python3.6/site-packages/vobject/vcard.py", line 227, in serialize
>     VCardTextBehavior.serialize(obj, buf, lineLength, validate)
>   File "/usr/lib64/python3.6/site-packages/vobject/behavior.py", line 162, in serialize
>     out = base.defaultSerialize(transformed, buf, lineLength)
>   File "/usr/lib64/python3.6/site-packages/vobject/base.py", line 1001, in defaultSerialize
>     obj.behavior.encode(obj)
>   File "/usr/lib64/python3.6/site-packages/vobject/vcard.py", line 152, in encode
>     line.value = codecs.encode(line.value.encode(coding), "base64").decode("utf-8")
> AttributeError: 'bytes' object has no attribute 'encode'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib64/python3.6/site-packages/radicale/storage.py", line 906, in exception_cm
>     yield
>   File "/usr/lib64/python3.6/site-packages/radicale/storage.py", line 886, in discover
>     yield collection.get(href)
>   File "/usr/lib64/python3.6/site-packages/radicale/storage.py", line 1255, in get
>     item, metadata = self._get_with_metadata(href, verify_href=verify_href)
>   File "/usr/lib64/python3.6/site-packages/radicale/storage.py", line 1397, in _get_with_metadata
>     (href, self.path, e)) from e
> RuntimeError: Failed to load item '14717e4c-1158-4a1d-9081-58266eec2ee6.vcf' in 'dav/contacts.vcf': 'bytes' object has no attribute 'encode'
> ...

Could it be a problem in dev-python/vobject, or is it something else? I did not have any problems with the contacts or calendar with radicale-1.0.

**Comment by Gatak** [comment]
It was a problem with vobject-0.9.3. I upgraded to vobject-0.9.5 and the problem went away.
