### ISSUE TITLE
freeBSD user login problem

### ISSUE THREAD

**Issue by jemail99** [Kozea/Radicale#772]
I have installed Radicale on freeBSD 11.1 using the package manager.
I can start the radicale server no problem. However, when I go to http://10.7.4.10:5232 I see only the following text:
Radicale works!

The rest of the page is white with no user login textbox. There seems to be no way to login as a user. I have tried setting up htpasswd and a users file, but the result is the same.

Do you have any advice?

**Comment by return42** [comment]
freeBSD ships version 1.1.2 thats why you see ".. works!". Please install with pip. I'am not a freeBSD user but this link might help you: https://blog.tyk.nu/blog/radicale-on-freebsd/

**Comment by MacLemon** [comment]
I'm running Radicale 2.1.8 on FreeBSD 11.1p6 behind nginx (1.13.8) as a reverse proxy.
The linked article is indeed helpful in getting it running.
Only problem I have so far is #774 but that is not related to FreeBSD from what I can tell, but a problem with Radicale not implementing or correctly understanding MOVE.

**Comment by jemail99** [comment]
@MacLemon
I would be interested to know if your nginx and radicale are in jails?

**Comment by MacLemon** [comment]
Yes, of course they are and in separate ones for that matter.
