### ISSUE TITLE
Data loss: Moving an event or task from one collection to another

### ISSUE THREAD

**Issue by MacLemon** [Kozea/Radicale#774]
**Summary:**
Data loss: Moving an event or task from one calendar (collection) to another using Apple Calendar.app on macOS or iOS causes the item to vanish, resulting in complete loss of the event/task.

**Steps to Reproduce:**
Create two calendar collections named „TEST SOURCE“ (orange) and „TEST DESTINATION“ (purple).
Create an event in the TEST SOURCE collection, enter whatever you like in the summary.
Wait for the event to sync to the server.

![screen shot 2018-01-25 at 16 55 19](https://user-images.githubusercontent.com/90635/35399059-b2d968fe-01f3-11e8-9d06-f4f71819aeda.png)

Now bring up the event inspector in Calendar.app and with the pop-up menu, selecte the TEST DESTINATION to move the event to the destination calendar.
![screen shot 2018-01-25 at 16 55 32](https://user-images.githubusercontent.com/90635/35399095-c77ed2d0-01f3-11e8-88d1-ab68cbd8d5bd.png)

The item is now shown as belonging to that other collection.
![screen shot 2018-01-25 at 16 56 15](https://user-images.githubusercontent.com/90635/35399113-d40f716c-01f3-11e8-8060-0f4296bffc42.png)

Wait for the server to sync the changes again. (You can motivate Calendar.app to sync immediately by pressing ⌘R.)
You get an error message:

> The request for “TEST Event in source” in “TEST DESTINATION” in account “Druid” failed.
> The server responded with “502” to operation CalDAVMoveEntityQueueableOperation.
You have three buttons to respond to that error. [ignore], [Try Again], [Revert to Server].
![screen shot 2018-01-25 at 16 57 22](https://user-images.githubusercontent.com/90635/35398984-87ab638a-01f3-11e8-89d8-f63e55fb8a4c.png)

Pressing [ignore], just ignores the error. (expected)
This results in the event not being present in the TEST SOURCE anymore, and that changes propagates to the server and other synced clients, meaning the event is being removed from all clients.
The event now exists on this very client that tried to move the event and on that client only. The event is not `PUT` into the TEST DESTINATION collection. This item is now only existing on that client.
The error message will not reappear until Calendar.app has been quit and launched again.

Pressing [Try again], causes the same error to occur again. (expected)
This results in the event not being present in the TEST SOURCE anymore, and that changes propagates to the server and other synced clients, meaning the event is being removed from all clients.
The event now exists on this very client that tried to move the event and on that client only. The event is not `PUT` into the TEST DESTINATION collection. This item is now only existing on that client and is repeatedly causing the same error to occur in a loop until the user decides to press another button in that dialog.

Pressing [Revert to Server], immediately deletes the event from *both* collections, since it wasn't in the TEST DESTINATION collection before the error occurred. It won't appear in the TEST SOURCE collection, since it had already been removed from that collection.
[Revert to Server] is interpreted by users like “undo”, so they're likely to chose that button to get rid of the alert. This is also the *default* button, making it even more likely.

You cannot undo this action.

You have just lost the entire event.

You can lose tasks the same way with Reminders.app and task collections.

The server log shows this:
```
2018-01-25 16:35:12,430 - [805debe00] INFO: Successful login: 'MacLemon'
2018-01-25 16:35:12,431 - [805debe00] INFO: Unsupported destination address: 'https://server.example.com/MacLemon/<TEST SOURCE collection ID>/C9FFEA5E-581A-4453-B3FE-04289116680F.ics'
2018-01-25 16:35:12,431 - [805debe00] INFO: MOVE response status for '/MacLemon/<TEST SOURCE collection ID>/C9FFEA5E-581A-4453-B3FE-04289116680F.ics' in 0.028 seconds: 502 Bad Gateway
```

**Expected Results:**
Moving an item from one collection to another via a client application should move the corresponding .ics file on the server from the source collection to the destination collection.

**Actual Results:**
The event doesn't get moved from the source collection to the destination collection.
The event *does* get deleted from the source collection and remains *locally* on the client only. It's not possible to sync that event back up to the server in the destination collection.

**Workarounds that are hard to teach a user**
You can copy paste an event to put it into another collection with side-effects. This also creates a new GUID for the new event, resulting in two alike looking events that aren't the same to neither the client nor the server software. They cannot be distinguished unless inspected in the file system or database backend used by Calendar.app.

Also, users are used to moving items, instead of copy pasting them. They do not think that they could lose their data by using a simple feature that should just move an event from one calendar to another. (Often perceived as simply changing the color of an event.)

You can indeed rescue the event by copying it and pasting it into any collection where you want it to land. This can be the TEST SOURCE, the TEST DESTINATION or any other collection present. (Even if not on the same server or account.) This results in a new event with a new GUID but prevents data loss.

**Non working recovery attempts**
When being presented the error message as outlined above, you can press [Ignore]. You can then try to move that event back to the TEST SOURCE collection. This will not bring back the event, or get rid of the error.
This results in the event being in limbo on that single client, unable to move, store or sync it to any collection.

**High risk behaviour**
Given that Calendar.app allows users to *merge* two calendars, meaning *all* event from one calendar get *moved* into another one, this is likely to cause irrecoverable data loss of *all* events in a collection. Depending on the number of event in the two collections, this may require both collections to be deleted completely before operation of the Calendar application can be resumed.

**Regression:**
n/a I haven't tested this with Radicale before 2.1.8.

**Notes:**
Radicale 2.1.8 installed via `pip(1)`, running on FreeBSD 11.1p6, using Python 3.6.4 installed via `pkg(8)`.  
Clients:
- Apple Calendar.app Version 9.0 (2155.21), running on macOS Sierra 10.12.6. (User-Agent `Mac+OS+X/10.12.6 (16G1212) CalendarAgent/386`)
- Apple Calendar.app running on iOS 10.3.3 (14G60). (User-Agent: `iOS/10.3.3 (14G60) dataaccessd/1.0`)

Yes, I'm very much aware that one must have backups and I do. Have you ever tried to recover a *single* event from a calendar client software backup? It's possible for people skilled in sqlite and text editing on the command line. It's impossible to most users.

**Comment by Tntdruid** [comment]
Works fine here, using lates iOS on iPad

Event 1 cal 1 then moved that to cal 2, didnt lose the event.

**Comment by MacLemon** [comment]
Define “latest iOS” please as the term is ambiguous.
I'm pretty sure, if you look into the logs of your Radicale instance you'll find errors 400 or 502 pertainint to that MOVE event and the event won't travel from your source collection to your destination collection on other devices.
At the moment, your event is existing locally on your iPad only.

**Comment by Tntdruid** [comment]
iOS 11.2.5

**Comment by MacLemon** [comment]
Can you provide webproxy logs and radicale logs what is happening while you do that and give some details about the server? (Radicale version, python version, webserver type and version.)
Maybe it's an incompatibility of sorts that is causing MOVE actions to fail?

**Comment by MacLemon** [comment]
I've now tried with an up-to-date iOS 11 device as well as macOS 10.13 and I can reproduce the exact same behaviour including the data loss with these. Same lines in the log, same error messages on macOS.

So this is either a misconfiguration of my server (I'll triple check that) or a bug in Radicale, or a bug in the documentation on how to properly configure a server for Radicale hosting. I'll check if I can find anything.

@Tntdruid Would really help me with tracking that down if you could be so kind to give me some more info about your server setup. (OS, webserver, versions) Thanks!

**Comment by MacLemon** [comment]
Thanks, that helped!

So you're not using a reverse proxy in front of radicale.
I solved it now, it's actually pieces missing from the documentation for the reverse proxy setup!
I'll prepare a pull request for that.

For the scenario where `nginx` is used as a, TLS terminating, reverse proxy for `radicale` and is communicating in plaintext from the reverse proxy to the backend server (on the same machine).
These lines are missing from the `location{ }`block in the documentation.
```
                set $destination $http_destination;
                if ($destination ~* ^https(.+)$) {
                        set $destination http$1;
                }
                proxy_set_header Destination $destination;
                proxy_set_header Host $host;
```
