### ISSUE TITLE
Is it possible to insert Calendar entries from an external source?

### ISSUE THREAD

**Issue by PaskoMoto** [Kozea/Radicale#775]
Hi.
I'm trying to insert entries into my radicale server, but the source is not going to be a regular client as usual:

I am parsing an external agenda in xml format with python so that I can extract the events I'm interested in, and now I want to push these entries to radicale so that all my clients can receive them when they sync to the server.

I've been trying a console-based client called khal, but it is not able to connect to any caldav servers..... 
Are there any other alternatives to push these entries to the server? Maybe adding the appropriate information to the calendar files stored in /var/lib/radicale/collections/..?

Thanks in advance.
Regards.

**Comment by SimplyDanny** [comment]
I do exactly what you are describing on a Raspberry Pi running Radicale. The Pi regularly extracts some events from a website, converts them into the iCalendar format and adds them as `.ics` files to Radicale's collections directory (in the appropriate folder where such calendar files are stored).

The easiest way is to add the calendar through the web interface if it doesn't already exist. There you can also see which folder belongs to your calendar. The shown URL tells you that.

**Comment by PaskoMoto** [comment]
Hi.
Thank you for your kind answer.
I'm specifically interested in the process that generates de .ics files. How are these conversions done?.
Regards.

**Comment by chripo** [comment]
there are a couple of tools outside which will solve our issue.
some time ago i wrote a small python tool to get this job done.
https://github.com/chripo/calflate

**Comment by SimplyDanny** [comment]
> I'm specifically interested in the process that generates de .ics files. How are these conversions done?

Unfortunately, the scripts I use are not worth publishing them. 🙈  They utilize the [icalendar](http://icalendar.readthedocs.io/en/latest/) Python module to create the `.ics` files. Some simple examples are provided on the website. In addition, I recommend to have a separat file for each event in the calendar. Thereby, it is easier to update/change events later on. 

> I was thinking that adding an ICS file to a running Radicale server's collections folder might cause a problem. But I guess it's OK, yes?

It works very well for me. The server also deletes obsolete events regularly without any issues. Everything is synced properly.

**Comment by PaskoMoto** [comment]
Hi.
Ok. I think I got it -mostly- working.
My CalDav client is a bit picky on the formats but all in all I managed to write a simple python script that generates an VCALENDAR file that does the job.
It was easier than I thought in the beginning.
Now I only have one more question and I will hopefully close the issue:
Do I have to restart the server (radicale) whenever I update the VCALENDAR file?
Thank you very much for your answers.

**Comment by chripo** [comment]
> Do I have to restart the server (radicale) whenever I update the VCALENDAR file?
nope.

**Comment by PaskoMoto** [comment]
Great. :)
Thank you!.

**Comment by tmst** [comment]
Yeah, I guess there's some kind of cache thingy that might possibly cause a stale or deleted event to the be returned by the server.
