### ISSUE TITLE
unable to connect to radicale server from outside the LAN

### ISSUE THREAD

**Issue by hakova** [Kozea/Radicale#777]
Hi,

I have a working radicale server (2.1.8) on FreeBSD, and I can connect to it from within the LAN with no problem (Davdroid, KMail, Firefox). The problem is that the connection does not occur from outside the LAN. The server's firewall is not the issue, because it allows connection from within LAN. Additionally, turning the firewall off doesn't resolve the issue.

When I try to connect from outside the LAN, Davdroid and Firefox keeps spinning the cursor with no connection or error. I wonder if any additional port other than 5232 needs to be open since the router seems to block healthy connection somehow.

Any input will be greatly appreciated.

**Comment by hakova** [comment]
I figured this out myself. My cable modem had a gateway function as well and it was keeping the port 5232 closed. Once I forwarded the port there as well, the problem was solved.

**Comment by tmst** [comment]
On Sun, Jan 28, 2018, at 6:49 PM, hakova wrote:
> I figured this out myself. My cable modem had a gateway function as
> well and it was keeping the port 5232 closed. Once I forwarded the
> port there as well, the problem was solved.
Congrats. I still haven't managed to figure out my AT&T DSL router's
port forwarding. But it's just as well, as I probably rightly consider
myself incompetent to properly secure an Internet service running on
my own box.
I hope you've got SSL enabled if you're going to be accessing it over
the Internet. Otherwise your password and resource paths are being
passed in the clear.

**Comment by hakova** [comment]
Thank you for your message.

On Friday, February 2, 2018 6:21:45 PM CST Tom Russell wrote:
> ...
> Congrats. I still haven't managed to figure out my AT&T DSL router's
> port forwarding. But it's just as well, as I probably rightly consider
> myself incompetent to properly secure an Internet service running on
> my own box.

Anything is possible with the right amount of fiddling ;).

> I hope you've got SSL enabled if you're going to be accessing it over
> the Internet. Otherwise your password and resource paths are being
> passed in the clear.

Thank you for the warning. Yes, I did enable SSL via a certificate obtained from EFF/Let's Encrypt. It wasn't as hard as I thought it would be. I didn't setup users, rights, etc. Instead I am using a single family calendar with all members of the family accessing with the same username and credential. It is working amazingly well. I have to admit that iPhone set up was quite easier than android, but bot of them work very well.
