### ISSUE TITLE
Radicale and iOS - Calendar is not syncing

### ISSUE THREAD

**Issue by lsergei** [Kozea/Radicale#786]
I managed to successfully install Radicale as a daemon, behind NGINX reverse proxy. I've tried several apps on different OSX devices, everything works well and syncronizes too. .ics files  are appearimg correctly in /var/lib/radicale/collections/collection-root/xx/xxxxx-x-xxxx-xxx folder.

But I stuck with iOS... I can successfuly create CalDAV profile in iOS, but actual data is not syncing. Calendar app in iOS says "Unable to connect ot the Internet" under Radicale profile which is ridiculous - internet connection is stable and reliable. 

I've tried to delete profile and re-create again, switch WiFi and cellular connection - nothing helps. It just doesn't sync ( Tried to use wrong password while creating the profile - iOS says wrong password, so it actually connects to correct server. 

Could you give a hint?

**Comment by lsergei** [comment]
Finally I managed to get it working. Apparently iOS doesn't recognise all settings correctly, you have to put everything manually. Settings that worked for me are as follows:

Settings -> Accounts & Passwords -> Add account -> Other -> Add CalDAV Account

Server: ******.com
Username: name
Password: password
Description: whatever

Advanced settings ->
Use SSL: On
Port: 443
Account URL: https://*******.com/rl/name

The trick was in Account URL - by default iOS sets it to https://*******.com, so you can save settings but nothing gonna work.

As described before, my Radicale installation is hidden behind NGINX reverse proxy and accessible via URL https://*******.com/rl/

Summarizing, everything is working as expected. My big respect and gratitude to all Radicale team for the great product!

**Comment by return42** [comment]
@lsergei : thanks for sharing your experience. I had simmilar quirks with macOS Contacts Version 10. In my setup Radicale is behind Apache (http://myhost/radicale/). The server-path was ignored by macOS Contacs when I set up the account first. I had to reopen the account properties and set the server-path explicite (I documented it here, but it is only in german http://return42.github.io/handsOn/radicale/dav_client.html#apple-kontakte).

**Comment by hollorol** [comment]
> Advanced settings ->
> Use SSL: On
> Port: 443
> Account URL: https://*******.com/rl/name

I have iOS 14.8. I do the advanced setting correctly as @lsergei  written, but it still rewrites the setting. :(

**Comment by ClassickTech** [comment]
> > Advanced settings ->
> > Use SSL: On
> > Port: 443
> > Account URL: https://*******.com/rl/name
> 
> I have iOS 14.8. I did the advanced setting correctly as @lsergei written, but it still rewrites the setting. :(

Same issue. Does anyone have the exact configuration for how to get this working on iOS?

**Comment by gandalf3** [comment]
@ClassickTech in case you or anyone is still running into this, i had the same issue with ios rewriting the url setting in advanced; setting up the following redirects fixed it:
-  `/.well-known/caldav` -- 301 --> `<your radicale url>`
-  `/.well-known/carddav` -- 301 --> `<your radicale url>`
