### ISSUE TITLE
Installing Radicale on Ubuntu 16.04

### ISSUE THREAD

**Issue by sarhadmac** [Kozea/Radicale#790]
I am running as root on Ubuntu 16.04

I apply the below like which works without any issues:

> python3 -m pip install --upgrade radicale

However, then I run the below:

> python3 -m radicale --config "" --storage-filesystem-folder=~/.var/lib/radicale/collection

But then nothing happens, as if I can type more things in the terminal and I get no response.

I checked inside `/.var/lib/` and I did not find and radicale folders

**Comment by 776166** [comment]
`python3 -m radicale --config "" --storage-filesystem-folder=~/.var/lib/radicale/collection --debug` ?
