### ISSUE TITLE
multiple .ics directories and evolution

### ISSUE THREAD

**Issue by cerisara** [Kozea/Radicale#791]
This calendar looks great, but I don't understand what's happening:
- when creating a new cal from web interface, it returns an URL with a long name, ending with a kind of hashcode.ics. But why such a long name that is impossible to type on another device ?
```
http://hostname:5232/mylogin/24f5afd36423d5c9dc39b2e7a18a2d85576f1374.ics/
```
- OK, so I don't type the long name but just the parent directory (until mylogin/) within evolution; now whenever I create an event, it sometimes create a new .ics directory ! And when reopening evolution later on, no events appear, because I have to choose in evolution one of the long .ics name :-/

What's wrong there ? Why such long dir names that are impossible to set or define ourselves ? why creating several files that are not pooled together or refresh by evolution ? (same thing with davdroid)

Thanks for your explanations, because it's pretty hard to understand

**Comment by cerisara** [comment]
OK, sorry, I guess I did some wrong manipulations, because it seems to work on both evolution and android, even with the multiple .ics files. So it's perfect ! Sorry about the noise ! :-)

**Comment by tmst** [comment]
On Fri, Mar 16, 2018, at 1:05 PM, Christophe Cerisara wrote:
> Sorry about the noise ! :-)



Kind of hard to call this noise. You can hear a mouse around here
these days.
