### ISSUE TITLE
question: where are contact pictures stored?

### ISSUE THREAD

**Issue by hakova** [Kozea/Radicale#792]
Dear Radicale team,

Thank you for a great Cal/CardDAV server. It is simple enough for me to install and use yet is very robust. I love this combination. Please don't get it too complicated in the feature by overdeveloping!

My question is where contact pictures are stored, on the server side or on the client side? My impression is that they are stored on the client side, can somebody please confirm?

If the contact pictures are stored on the client side, is there a way/plan to allow server-side storage?

Thanks again!

**Comment by bigbig6** [comment]
Hello,

Pictures are stored on server side too.

Regards,

Big

**Comment by hakova** [comment]
Thank you so much for your reply! Once again, thank you for a great and easy to use software!

Hakan
