### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by ghost** [Kozea/Radicale#794]
Hi, 

I'm running Radicale in a Docker environment. I've got some Trouble with the SSL certificate. I use a letsencrypt pem certificate and get following error message:
[7f01914c9ae8] ERROR: An exception occurred during request: SSL handshake failed: EOF occurred in violation of protocol (_ssl.c:777)

 49 # SSL Protocol used. See python's ssl module for available values
 50 protocol = PROTOCOL_TLS

**Comment by MacLemon** [comment]
Trying to use broken SSLv3 when it's (rightfully so) no more present in your crypto library?
Have you tried checking that server with [SSLLabs Server Test](https://www.ssllabs.com/ssltest/)?

**Comment by Omniscimus** [comment]
This probably has to do with an outdated version of openssl being installed. Try rebuilding with the `--no-cache` flag? That way Docker does not re-use cached layers in which a previous version of openssl was installed. As in `docker build -t radicale:latest --no-cache .`. See #798 for more information.
