### ISSUE TITLE
Gaps in the documentation on radicale.org

### ISSUE THREAD

**Issue by G-Huber** [Kozea/Radicale#796]
Hi,

when trying to install radicale on Raspbian last weekend, the documentation provided under radicale.org/setup and radicale.org/logging tripped me up.

The [/documentation](http://radicale.org/documentation/) page states that [/setup](http://radicale.org/setup/) provides "A simple but solid setup". And [/logging](http://radicale.org/logging/) states that "This is the recommended configuration for use with modern init systems (like systemd)".

But when you try to set up Radicale as a service using those two pages as a guide, it won't work.

The reason is quite simple and - if you know systemd's .service configuration files - rather easy to spot:
The logging directory (/var/log/radicale/ as per the configuration example) needs to be added to the ReadWritePaths in the .service configuration.

It took me quite some time to figure this out, trying all kinds of file permissions on /var/log/radicale and /var/log/radicale/log as well as changing their owner - to no avail.
I think it would be great, if there was some kind of comment to point that out, so other novices won't have to troubleshoot this particular issue.

**Comment by Unrud** [comment]
> The [/documentation](http://radicale.org/documentation/) page states that [/setup](http://radicale.org/setup/) provides "A simple but solid setup". And [/logging](http://radicale.org/logging/) states that "This is the recommended configuration for use with modern init systems (like systemd)".

The sentence is in reference to "Radicale logs to ``stderr``". I was trying to say that you should use the default configuration and not change anything, if you are using a modern init system. The init system takes care of the logging (e.g. systemd journal).
