### ISSUE TITLE
Infcloudradicale  - update button has no effect

### ISSUE THREAD

**Issue by Joe7new** [Kozea/Radicale#799]
Hi !
I had installed Radicale on ubuntu 16 LTS - worked fine. Then I installed Infcloud - seems to work fine too . If I put in an event in webbrowser , it was synced to android devices and other clients. But when I entered an event on mobile device it's not updated in **Infcloud browser** - specially **the update button on left site has no effect !** 
I can see in source-code that a reload-function is called onclick , but has no effect. Also changing sync-parameters in config.js had no effect. And java-script in browser is of course active.
I had to logout and login again to have an event updated in infcloud/browser !
I installed Infcloud for radicale as described in https://github.com/Unrud/RadicaleInfCloud

ps. when I entered http://localIP:5232 in broswer for testing in local net I was redirected to http://localIP:5232/.web (where I could login and create calendars). On the top of the site there I could see a link to InfCloud. When I clicked on it the Infcloud login windows appears. Then everything worked, but not updating as described above. 
Any idea ? Is Infcloud still maintained ? 

I can not make more testing, because I have installed fresh ubuntu and I can't install radicale , infcloud and try/test settings etc. for lack of time , although liked it very (!) much execpt updating problem with infcloud . And sorry I have no log-files anymore . Nevertheless I hope developement doesn't stop like baikal unfortunately did.

Regards, Joe

**Comment by Unrud** [comment]
The user account needs at least one address book and one calendar for the update button to work. It's a bug in InfCloud.

**Comment by Joe7new** [comment]
Thanks for answering so fast !! I had calendars created, but no addressbook.  Maybe I try this later again.. thanks for hint! (Hope this would help).. kind regards, Joe

**Comment by Joe7new** [comment]
obsolete.. closing
