### ISSUE TITLE
HTTP_X_SCRIPT_NAME not removed from PATH_INFO

### ISSUE THREAD

**Issue by drwilly** [Kozea/Radicale#803]
I just migrated from radicale 1 to 2. My setup is nginx -> uwsgi -> radicale.
I used to rely on the `base_prefix` in radicale's config to get the `SCRIPT_NAME` and `PATH_INFO` parameters right which apparently is no longer possible.
My understanding of the parameter `HTTP_X_SCRIPT_NAME` is that it should overwrite `SCRIPT_NAME` and be stripped off of `PATH_INFO`. So if `HTTP_X_SCRIPT_NAME = /radicale` and `PATH_INFO = /radicale/myuser/` then the latter should be rewritten to `/myuser/`.
However that does not seem to be the case: https://github.com/Kozea/Radicale/blob/master/radicale/__init__.py#L404

**Comment by Unrud** [comment]
This is the expected behaviour (see https://www.python.org/dev/peps/pep-0333/).
My suspicion is that **nginx** is not configured correctly: http://radicale.org/proxy/
The trailing slash causes **nginx** to strip ``/radicale`` from the path.

**Comment by pbiering** [comment]
@chripo : is this still an issue with Radicale major version 3? If not, please close.

**Comment by pbiering** [comment]
I've did a major review of the "apache" reverse proxy config example (supporting 4 different flavors) and stored a template in the repository now: https://github.com/Kozea/Radicale/blob/master/contrib/apache/radicale.conf

Can you please align your "nginx" configuration and check whether the issue disappears then?
