### ISSUE TITLE
WSGI + Alternative Auth methods

### ISSUE THREAD

**Issue by n00b42** [Kozea/Radicale#812]
I wanted to use the Radicale_IMAP auth plugin (found on Github) while running Radicale with Apache2+WSGI.

- Directly starting Radicale works and the IMAP auth works as expected.
- Running Radicale via WSGI seems only to work with the remote auth method. Using Apaches basic for a test worked.
- Also tested the None auth method, but was always rejected.

Is the WSGI setup incompatible with different auth methods? if so, please add that to the WSGI documentation.

**Comment by Unrud** [comment]
> Is the WSGI setup incompatible with different auth methods?

No. This sound like a configuration issue of the WSGI server. Please check that the WSGI server passes the ``WWW-Authenticate`` HTTP header from Radicale to the web browser and the ``Authorization`` header from the web browser to Radicale.

**Comment by n00b42** [comment]
Thanks, Using "WSGIPassAuthorization" did the trick. I think that solved my issue.
