### ISSUE TITLE
VCF with picture not downloaded in Thunderbird - InvalidCharacterError: String contains an invalid character

### ISSUE THREAD

**Issue by svargh** [Kozea/Radicale#815]
Radicale Version: 2.1.9 on Ubuntu 14.04 Python 3.4.3

Ubuntu14.04 Desktop:
Thunderbird1,Thunderbird2: 52.7.0
CardBook Version: 28.5

Win10 Desktop:
Thunderbird1,Thunderbird2: 52.7.0
CardBook Version: 28.5

Step 1:
Thunderbird1: Given VCF is imported and Cardbook tells synchronization is ok
[TestFamily.vcf.zip](https://github.com/Kozea/Radicale/files/1958849/TestFamily.vcf.zip)

Step2:
In Thunderbird2: When synchronizing radicale Addressbook, during download this happens.
The contact is never downloaded in Thunderbord2. After removing the picture, then contact gets downloaded.

2018.04.29 17:04:18:964 : xxxxx : Error when parsing contact : 
InvalidCharacterError: String contains an invalid character 
BEGIN:VCARD
VERSION:4.0
PRODID:-//Thunderbird.net/NONSGML Thunderbird CardBook V28.5//EN
UID:cfec8750-eddf-4b0b-a452-7887b352f9eb
FN:TestFamily
PHOTO:DATA:IMAGE/JPEG\;BASE64
REV:20180429T170349Z
TEL:343434
END:VCARD

Same VCF with picture works fine with contacts on posteo.de addressbook.

Ugly Workaround:
Convert to base64 and paste content into Field 'Role'
or removing the image

**Comment by svargh** [comment]
Any ideas/hints?

**Comment by pbiering** [comment]
please check with current version of radicale+vobject, if replicated still, please reopen once it's verified that the item has passed the validator(s)
https://github.com/Kozea/Radicale/wiki/Reporting-Issues

**Comment by da4089** [comment]
Confirmed the referenced VCF (TestFamily.vcf) appears to parse without issue using current vObject.
