### ISSUE TITLE
Web interface: Name folder

### ISSUE THREAD

**Issue by sphh** [Kozea/Radicale#817]
If I create a new calendar/addressbook in the web interface, the newly created folder in `collection-root/<user>/` is given a random name. When accessing this calendar/addressbook in Thunderbird, I have to specify this random name as the location URI. It would be great if I could give it a name which appears in the URI.

Thanks.

**Comment by Tntdruid** [comment]
I use the imap plugin from here https://github.com/Unrud/RadicaleIMAP

Then the url are collection-root/email@email.tld/

**Comment by sphh** [comment]
I use https://github.com/Arvedui/radicale-dovecot-auth, but I don't know if this matters.

If I create new addressbooks/calendars via the web interface https://<server>:5232/.web/ and the generated urls are (just an example):

1. **Addressbook**: https://<server>:5232/sphh/7df6ed60-27b5-9c37-90a2-4e0cb2cb0613/
2. **Calendar 1**: https://<server>:5232/sphh/3ae660da-e9b4-5f69-9bd0-a2687b413f9e/
3. **Calendar 2**: https://<server>:5232/sphh/2697b593-18e7-983e-a44b-4e1fc6f8f7fc/

**Comment by pbiering** [comment]
Pending 3.2.x will support this by https://github.com/Kozea/Radicale/pull/1456

See also https://github.com/Kozea/Radicale/discussions/1416
