### ISSUE TITLE
Is the filesystem option gone for storage?

### ISSUE THREAD

**Issue by dkanada** [Kozea/Radicale#823]
I recently updated and now all my events and contacts are stored in individual files, which makes them hard to back up. Is the option gone or did I just configure the server wrong?

**Comment by m4tze** [comment]
How can files be "hard to back up"?

**Comment by dkanada** [comment]
Not actually difficult, just more annoying to drag multiple small folders with hundreds of 4KB files instead of a single 4MB file for each calendar or contact group. It's not a huge issue, just seems less convenient in my opinion.

**Comment by mookie-** [comment]
@dkanada how do you do your backup? Perhaps its better to do it automatically instead of manually dragging the files somewhere.

**Comment by dkanada** [comment]
I have an automatic backup, I just liked a single file because it was more atomic than several hundred smaller files when backing up my contact list. I would often run searches through the contact file before but now I would have to search through several hundred files to find a certain field.

@Unrud are there any specific reasons you removed the option? If it wont be too hard to reimplement I would be willing to go through and submit a pull request to add it back in, not sure if there were technical reasons it got removed though.
