### ISSUE TITLE
WARNING: Client provided invalid sync token <-- What ist that and how can i fix this?

### ISSUE THREAD

**Issue by Weuxel** [Kozea/Radicale#825]
Hello,

i see some of these messages in the radicale log. Why is it trying to sync something from the radicale website and how can i fix this?

2018-05-17 10:43:43,627 - [7f001e7fc700] WARNING: Client provided invalid sync token 'http://radicale.org/ns/sync/feaa0c297a50fc3a49e1c43ebc160e71': Token not found: 'http://radicale.org/ns/sync/feaa0c297a50fc3a49e1c43ebc160e71'

Thank you,
Norman

**Comment by superbock** [comment]
For me, deleting the `.Radicale.cache` folders seemed to do the trick. However, this only mitigates the problem and does not solve it.

**Comment by DenisVS** [comment]
Now I got this error with Carddav sync & Caldav sync.

**Comment by DenisVS** [comment]
Just turned token checking off, and all works fine.
`--- storage.py  2019-06-22 19:57:51.597393000 +0400
+++ storage.py.bak      2019-06-22 19:58:25.284920000 +0400
@@ -539,8 +539,8 @@

         """
         token = "http://radicale.org/ns/sync/%s" % self.etag.strip("\"")
-#        if old_token:
-#            raise ValueError("Sync token are not supported")
+        if old_token:
+            raise ValueError("Sync token are not supported")
         return token, self.list()

     def list(self):
@@ -1189,13 +1189,13 @@
             return True

         old_token_name = None
-#        if old_token:
+        if old_token:
             # Extract the token name from the sync token
-#            if not old_token.startswith("http://radicale.org/ns/sync/"):
-#                raise ValueError("Malformed token: %r" % old_token)
-#            old_token_name = old_token[len("http://radicale.org/ns/sync/"):]
-#            if not check_token_name(old_token_name):
-#                raise ValueError("Malformed token: %r" % old_token)
+            if not old_token.startswith("http://radicale.org/ns/sync/"):
+                raise ValueError("Malformed token: %r" % old_token)
+            old_token_name = old_token[len("http://radicale.org/ns/sync/"):]
+            if not check_token_name(old_token_name):
+                raise ValueError("Malformed token: %r" % old_token)
         # Get the current state and sync-token of the collection.
         state = {}
         token_name_hash = md5()
`

**Comment by rprofijt** [comment]
I have the same issue with Caldav sync.. Is this a client issue?

**Comment by rprofijt** [comment]
Removing and re-adding the account to Caldav sync fixed it for me. Happened after the upgrade from 1.x to 2.x

**Comment by balki** [comment]
Got this error when upgrading from 2.x to 3.x

[WARNING] Client provided invalid sync token 'http://radicale.org/ns/sync/c2dbc230fd2bd88da8a8a12751ae83d5': Malformed token: 'http://radicale.org/ns/sync/c2dbc230fd2bd88da8a8a12751ae83d5

**Comment by Unrud** [comment]
When a client sends an unknown (e.g. out of date) or invalid token (e.g. token format changed in Radicale), the appropriate error message is returned to the client. According to the specification the client must handle this by falling back to a full synchronization.

Unfortunately the CalDAV/CardDAV implementations of pretty much every client I encountered are buggy. (It's the fault of the overly complicated and difficult to read specifications.)

> Got this error when upgrading from 2.x to 3.x

Radicale 3 uses sha256 for hashes instead of md5, therefore the old tokens don't work anymore.

> Instead, renaming the account name in DavX5 android app solved the issue. I guess deleting the account and adding again should also have the same effect.

Also got that issue. Noting we can do about it.

**Comment by rfc2822** [comment]
>According to the specification the client must handle this by falling back to a full synchronization.
> Unfortunately the CalDAV/CardDAV implementations of pretty much every client I encountered are buggy. (It's the fault of the overly complicated and difficult to read specifications.)

Do you return 412 Precondition failed with `DAV:valid-sync-token` in `DAV:errors`? In this case,[ DAVx5 should be able to handle it without problems](https://gitlab.com/bitfireAT/davx5-ose/-/blob/7821c4be3c69eec5c4e8b05efb88b55a60674faf/app/src/main/java/at/bitfire/davdroid/syncadapter/SyncManager.kt#L194).

**Comment by Unrud** [comment]
No, we return  409 Conflict. The valid sync token is a precondition of [sync-collection](https://tools.ietf.org/html/rfc6578#section-3.2). According to [rfc4791](https://tools.ietf.org/html/rfc4791#section-1.3) failed method pre- and postconditions must be responded with 403 or 409. I think 412 must only be used for failed If-Headers.

**Comment by rfc2822** [comment]
Ah, true. Well 409 should work too, DAVx5 just checks for any HTTP error with DAV:valid-sync-token.

**Comment by Unrud** [comment]
> Well 409 should work too

I found the error in Radicale it should be fixed in 3.0.1. The XML error response was invalid.

**Comment by captainepoch** [comment]
> > Well 409 should work too
> 
> I found the error in Radicale it should be fixed in 3.0.1. The XML error response was invalid.

I upgraded to the 3.0.3 and the error still exists.

**Comment by TribuneX** [comment]
I am also facing this issue after migrating from radicale v2. I would like to avoid setting up all clients again. Any workaround to get existing clients to properly connect to a v3 instance with data migrated from v2?

**Comment by fhpg** [comment]
In case of using thunderbird: I fixed the "Client provided invalid sync token" error by replacing the invalid token in the thunderbird config file "prefs.js" by a valid token found in radicale addressbook directory on server: /var/lib/radicale/collections/collection-root/[me]/[addrbook-token]/.Radicale.cache/sync-token/[use-any-of-these-tokens]
I just did not want to remove and re-add the address book in thunderbird.
