### ISSUE TITLE
Events without X-RADICALE-NAME but TZID generate wrong href

### ISSUE THREAD

**Issue by madduck** [Kozea/Radicale#828]
Hello,

From zoom.us, I received a `VEVENT` that had a `TZID` field. Given https://github.com/Kozea/Radicale/blob/1.1.x/radicale/ical.py#L73-L90, this mean that Radicale (1.1.1) would now use the timezone name as the `HREF` for the event, which is obviously wrong. There was no `X-RADICALE-NAME` for whatever reason.

Please only use `TZID` in `VTIMEZONE` stanzas.

**Comment by pbiering** [comment]
related to old version, closing now, if reproducable with current version of radicale, please reopen.
