### ISSUE TITLE
missing FN: causes server error 500:

### ISSUE THREAD

**Issue by chriscamacho** [Kozea/Radicale#830]
how the wife managed to save a contact without a name, I don't know, I didn't realise you could with Android!  (using DavDroid as sync provider)

anyhow if any address book record is missing an FN field you can no longer sync

the fix involves the wife pestering her technical support (me!) who has to shut down radicale, change the logging to debug, find the vdf that's at fault and manually editing it so radicale can serve data.

even if a VCARD or VCAL entry is invalid, its not really for the server to police this as there is no real mechanism to feedback to the end user, permanently causing a 500 error isn't very useful.

I seem to remember I've had similar issues to this previously

**Comment by genodeftest** [comment]
Can you please share a traceback from the radicale server when reproducing the bug? This would be important to fix the issue.

**Comment by chriscamacho** [comment]
it does actually look like an exception fortunatly it doesn't bring the whole thing down!

[7fb560069700] ERROR: An exception occurred during GET request on '/chris/AddressBook.vcf/': Failed to load item 'f9cacb1d-751d-48a4-b7ad-936380ce7203.vcf' in 'chris/AddressBook.vcf': 'VCARD components must contain at least 1 FN'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/radicale/storage.py", line 1400, in _get_with_metadata
    href, vobject_item, input_hash)
  File "/usr/lib/python3.6/site-packages/radicale/storage.py", line 1277, in _store_item_cache
    content = self._item_cache_content(href, vobject_item, cache_hash)
  File "/usr/lib/python3.6/site-packages/radicale/storage.py", line 1265, in _item_cache_content
    text = vobject_item.serialize()
  File "/usr/lib/python3.6/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib/python3.6/site-packages/vobject/behavior.py", line 157, in serialize
    cls.validate(obj, raiseException=True)
  File "/usr/lib/python3.6/site-packages/vobject/behavior.py", line 93, in validate
    raise base.ValidateError(m .format(cls.name, val[0], key))
vobject.base.ValidateError: 'VCARD components must contain at least 1 FN'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/radicale/__init__.py", line 323, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3.6/site-packages/radicale/__init__.py", line 496, in _handle_request
    environ, base_prefix, path, user)
  File "/usr/lib/python3.6/site-packages/radicale/__init__.py", line 622, in do_GET
    "ETag": item.etag}
  File "/usr/lib/python3.6/site-packages/radicale/storage.py", line 1534, in etag
    self._etag_cache = super().etag
  File "/usr/lib/python3.6/site-packages/radicale/storage.py", line 492, in etag
    for item in self.get_all():
  File "/usr/lib/python3.6/site-packages/radicale/storage.py", line 1438, in <genexpr>
    return (self.get(href, verify_href=False) for href in self.list())
  File "/usr/lib/python3.6/site-packages/radicale/storage.py", line 1255, in get
    item, metadata = self._get_with_metadata(href, verify_href=verify_href)
  File "/usr/lib/python3.6/site-packages/radicale/storage.py", line 1403, in _get_with_metadata
    (href, self.path, e)) from e
RuntimeError: Failed to load item 'f9cacb1d-751d-48a4-b7ad-936380ce7203.vcf' in 'chris/AddressBook.vcf': 'VCARD components must contain at least 1 FN'


I tried with adding just above N: a line containing only 3 characters FN: and that was enough to allow the server to work

**Comment by genodeftest** [comment]
@chriscamacho : Please use [styling with markdown](https://guides.github.com/features/mastering-markdown/) to make the traceback more readable.

According to the [vCard standard](https://tools.ietf.org/html/rfc6350#section-3.3), any vcard file must contain a "FN" which is the name of a contact. It looks like some code on the android phone does not comply to this specification.

**Comment by chriscamacho** [comment]
of course its not following the standard and is erroneous data this is NOT the issue

as the server has no way to feedback this to the end user, it shouldn't just give up and make the service unusable until someone can go in and manually edit the data

exceptions from third party libraries must be handled properly - at the very least throw a big error message server response you could see in the davdroid debug log, but once it get to this point there is nothing you can do from android you have to go to the server via SSH to fix it... so even if it continued serving this would be a less than idea solution

to be robust you must test with invalid input and make sure it at least does save data that later stops it serving for that collection.

I've already suggested a workaround for this specific exception, I would guess there are a number of other exceptions vobject can/will throw

**Comment by matthijskooijman** [comment]
I also ran into this. I sometimes use this for companies: I then fill in the company/organization field, leaving the name empty.

I ran into this problem when trying to import my complete address book, which enlarges the problem, as it prevents the entire vcf file from being imported.

Also, the error message is quite consise, the webui only says  "Error: 400 Bad Request", while the log only says "VCARD components must contain at least 1 FN", with no reference about *which* contact was problematic.

The vcf file I was importing was exported by Google Contacts.

**Comment by neilromig** [comment]
I also think Radicale should handle this issue - it is still failing to save contacts without FN. Emails that don't have a sender name are still fairly common, and perhaps just a default value for FN could be established?

**Comment by pbiering** [comment]
Radicale 2+ uses external library "vobject" as VCF/ICS parser, one can develop a tool which checks each file on server for validity. Potential this validity check tool can optionally also try to catch the error message and try to turn the input VCF/ICS in an accepted one add/modify.

**Comment by ron-1986** [comment]
I ran into the same problem.
AI wrote a python script to identify contacts without FN ;)
Worked good for me and identified the foul egg in the basket. 
Just change the name of the vcf at file_path var in main()

> def read_vcf(file_path):
>     with open(file_path, 'r', encoding='utf-8') as file:
>         vcf_data = file.read()
>     
>     entries = vcf_data.split('END:VCARD')
>     contacts_without_fn = []
> 
>     for entry in entries:
>         if 'BEGIN:VCARD' in entry and 'FN:' not in entry:
>             contacts_without_fn.append(entry.strip())
> 
>     return contacts_without_fn
> 
> def main():
>     file_path = './contacts.vcf'
>     contacts_without_fn = read_vcf(file_path)
> 
>     if contacts_without_fn:
>         print("Contacts without FN:")
>         for contact in contacts_without_fn:
>             print(contact)
>             print('-' * 80)
>     else:
>         print("All contacts have FN.")
> 
> if __name__ == "__main__":
>     main()

**Comment by hills** [comment]
I am also running into this issue; contacts added in Thunderbird are silently not available because of the error below (and possibly blocking other synchronisations?)

To me, it's a feature (not bug) in Thunderbird that I can have contacts labelled by Organisation, not a person's name.

I notice that on my LineageOS Android using DAVx also allows this, but populates FN with some data based on other fields, but knows not to interpret it as a full name later.

Whether or not Thunderbird confirms to a 'standard', it's clear there are many instances out in the wild. Perhaps Radicale could consider the principle of being conservative of what it sends, and liberal of what it accepts; I did not look at the code to see how internally dependent it is on these fields.

Thunderbird 140.7.1esr
Radicale 3.5.10 on FreeBSD 14.3-RELEASE-p7

```
[2026-02-10 13:44:40 +0000] [63170/Thread-30 (process_request_thread)] [INFO] PUT request for '/mark/contacts/ae0cd656-0e04-4c5b-b024-9e2ecc4d6840.vcf' received from ::1 (forwarded for 'x.x.x.x') using 'Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Thunderbird/140.7.1'
[2026-02-10 13:44:40 +0000] [63170/Thread-30 (process_request_thread)] [INFO] Successful login: 'mark' (http_x_remote_user)
[2026-02-10 13:44:40 +0000] [63170/Thread-30 (process_request_thread)] [WARNING] Bad PUT request on '/mark/contacts/ae0cd656-0e04-4c5b-b024-9e2ecc4d6840.vcf' (prepare): Failed to serialize item None from 'mark/contacts': 'VCARD components must contain at least 1 FN'
[2026-02-10 13:44:40 +0000] [63170/Thread-30 (process_request_thread)] [INFO] PUT response status for '/mark/contacts/ae0cd656-0e04-4c5b-b024-9e2ecc4d6840.vcf' in 0.009 seconds gzip 31 bytes: 400 Bad Request
```

**Comment by pbiering** [comment]
> Perhaps Radicale could consider the principle of being conservative of what it sends, and liberal of what it accepts; I did not look at the code to see how internally dependent it is on these fields.

Radicale is currently not touching any VCF or ICS beside fixing some very ugly things:

https://github.com/Kozea/Radicale/blob/a30e3641cf8ce61e3823679563180d9c59d53c01/radicale/item/__init__.py#L46

Then it's handovered to _vobject_ for parsing -> _vobject_ needs to be extended with a "being-relaxed" option and potentially also an "auto-fill/add" capability if it's a VCF and FN is missing.

**Comment by hills** [comment]
> Radicale is currently not touching any VCF or ICS beside fixing some very ugly things:

Given that, and the comment "Workaround for bug in InfCloud" in the code seems to imply real-life cases are a priority and there are enough cases in this bug report that keep coming up to at least re-open it?

I know almost nothing about these formats, but according to #1066 this poster [explains](https://github.com/Kozea/Radicale/issues/1066#issuecomment-2649708411) it is just part of an earlier vCard specification that FN is not required.

**Comment by pbiering** [comment]
> Given that, and the comment "Workaround for bug in InfCloud" in the code seems to imply real-life cases are a priority and there are enough cases in this bug report that keep coming up to at least re-open it?

Adjusting a single line is different to parse a VCF and inject a line on expected position -> _vobject_ is parsing and therefore able to add on proper position, not _radicale_.
