### ISSUE TITLE
DavDroid: Radicale no VCard/4 support

### ISSUE THREAD

**Issue by n00b42** [Kozea/Radicale#832]
Radicale version: 2.1.9

`davdroid: [syncadapter.ContactsSyncManager] Server advertises VCard/4 support: false`

Resulting in the following behavior: Using TB Cardbook to generate Contact results in a VCard4, then editing it with Davdroid results in a new VCard3.

**Comment by chphmh** [comment]
I have also experienced this problem. Creating contacts with Thunderbird Cardbook in Radicale creates them with VCARD VERSION:4.0. After editing these contacts in Android (I use the default Contacts app in LineageOS) and synchronizing to Radicale with DAVDroid, the Thunderbird Cardbook shows them as VCARD VERSION:3.0.

**Comment by n00b42** [comment]
Here is the relevant logcat when DavDroid determines the capabilites:
```[syncadapter.SyncManager] Preparing synchronization
[syncadapter.SyncManager] Querying server capabilities
[syncadapter.ContactsSyncManager] Contact group method: CATEGORIES

[HttpClient] --> PROPFIND https://dav.example.net/mail%40example.net/COLLECTION-ID/
[HttpClient] Content-Type: application/xml; charset=utf-8
[HttpClient] Content-Length: 296
[HttpClient] Depth: 0
[HttpClient] 
[HttpClient] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><CARD:supported-address-data /><supported-report-set /><n0:getctag xmlns:n0="http://calendarserver.org/ns/" /><sync-token /></prop></propfind>
[HttpClient] --> END PROPFIND (296-byte body)

[HttpClient] <-- 207 Unknown https://dav.example.net/mail%40example.net/COLLECTION-ID/ (465ms)
[HttpClient] Date: Wed, 10 Oct 2018 09:44:01 GMT
[HttpClient] Server: Apache
[HttpClient] DAV: 1, 2, 3, calendar-access, addressbook, extended-mkcol
[HttpClient] Keep-Alive: timeout=5, max=100
[HttpClient] Connection: Keep-Alive
[HttpClient] Content-Type: text/xml; charset=utf-8
[HttpClient] 
[HttpClient] <?xml version='1.0' encoding='utf-8'?>
<multistatus xmlns="DAV:" xmlns:CR="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/"><response><href>/mail%40example.net/COLLECTION-ID/</href><propstat><prop><supported-report-set><supported-report><report><expand-property /></report></supported-report><supported-report><report><principal-search-property-set /></report></supported-report><supported-report><report><principal-property-search /></report></supported-report><supported-report><report><sync-collection /></report></supported-report><supported-report><report><CR:addressbook-multiget /></report></supported-report><supported-report><report><CR:addressbook-query /></report></supported-report></supported-report-set><CS:getctag>"56fc12a79e549c5d6a97381653c7c0be"</CS:getctag><sync-token>http://radicale.org/ns/sync/REDACTED-TOKEN</sync-token></prop><status>HTTP/1.1 200 OK</status></propstat><propstat><prop><CR:supported-address-data /></prop><status>HTTP/1.1 404 Not Found</status></propstat></response></multistatus>
[HttpClient] <-- END HTTP (1086-byte body)

[syncadapter.ContactsSyncManager] Server supports vCard/4: false
[syncadapter.ContactsSyncManager] Server supports Collection Sync: true```

**Comment by n00b42** [comment]
Radicales response is missing info about supported address data formats (3.0/4.0)

Expected something like:
```
<C:supported-address-data>
    <C:address-data-type content-type="text/vcard" version="4.0"/>
    <C:address-data-type content-type="text/vcard" version="3.0"/>
</C:supported-address-data>
```

Actually response:
`<CR:supported-address-data/>`

Therefore, DavDroid falls back to VCard3.


See also the corresponding post on DavDroid: https://forums.bitfire.at/topic/1855/radicale-2-1-10-vcard4-problem

**Comment by n00b42** [comment]
Ok, so my question is actually:
IS VCard4 supported?
If so, then I think there is an issue with storing images.... (as VCard4)

**Comment by n00b42** [comment]
Ok, I contacted the CardBook guy, and he fxied a bug.
No the addon does not assume that Radicale supports VCard4 anymore.

(As according to the standard, it does not tell anyone it supports it and therefore should not be expected to supported it)

As those are my only types of clients (DavDroid and Cardbook), that fixed it for me.


For anyone having that problem: just readd the calenders with the latest cardbook and you should not be able to select v4 at creation anymore.
(And cardbook offers a convert function to rewrite v4 as v3 contacts)
