### ISSUE TITLE
Trying to access .ics from new Google Calendar, without success

### ISSUE THREAD

**Issue by reyman** [Kozea/Radicale#835]
Hi, 
I'm using with success Radicale from multiple month now. 
I update the version very recently 

I need to create a private calendar (user & password are correctly) accessible from **google calendar**
I try multiple things, but google agenda failed silently when i try to import the url ... 

You could try on your side with this test agenda : http://agenda.sebastienreycoyrehourcq.fr/reycoseb/2b4153a9-b416-5c99-ff39-c79423475f0c/ 

The agenda contain some dates in june.

The user is `reycoseb`, and the pwd `umridees` (i change the password later)

My auth config is simple : 

```
# Give write access to owners
[owner-write]
user: .+
collection: %(login)s(/.*)?
permission: rw

[read]
user = .*
collection =
permission = r
```

I also relax the http headers :  
`Access-Control-Allow-Origin = *`

**Comment by daghemo** [comment]
Following. See also #434.

**Comment by pbiering** [comment]
please reopen if problem still exists with current version, and if so, please analyze first debug log related to permission check, potentially something is misconfigured in "rights".
