### ISSUE TITLE
How do I list all contact lists?

### ISSUE THREAD

**Issue by MrMoronIV** [Kozea/Radicale#837]
After looking for quite a while I'm at loss.

I'm trying to list the existing contact lists using PHP but I have no clue what I should send to the server at what address.

Can someone point me in the right direction?
The radicale documentation shows how to create a contact list and an address book but I first want to list all existing ones, what curl command should I send?

**Comment by MrMoronIV** [comment]
In addition to that, how do I add an address book? The example in the docs gives 
`WebDAV precondition failed`

Unfortunately there's very limited information about how to interact with the caldav server on a very basic level. Wish there was an API or better explanation somewhere.

**Comment by pbiering** [comment]
The built-in WebUI uses client side Javascript to access the server and covers
- list of contact lists
- how to add address book
and can be therefore a source how-to beside reading specifications.

If you enable debug mode on server side, one can see all the XML request content.

Feel free to contribute examples for the Wiki (new page in https://github.com/Kozea/Radicale/wiki)
