### ISSUE TITLE
user:password gets logged as referer using reverse proxy setup

### ISSUE THREAD

**Issue by Yyuzu** [Kozea/Radicale#843]
Hello,

I've setup Radicale server 2.1.8-1 from debian experimental package (on a debian stable server) through an Apache reverse proxy handling LDAP authentication, setting X-Remote-User header.

Whenever I access the collection admin page (/.web), the full URL including user:password gets logged in Apache access logs as Referer. Disabling referer logging doesn't seem to be enough as it also gets logged in the error log whenever there is a problem between Apache and Radicale (timeout, auth failure, etc.)

Feel free to ask me if you need more details !
Kind regards.

**Comment by mookie-** [comment]
@Kyoshiro-san can you please paste your Apache configuration?

**Comment by pbiering** [comment]
Please reopen with apache configuration and example log if able to replay with current version
