### ISSUE TITLE
Calendars with UID containing '/' are not shown

### ISSUE THREAD

**Issue by Vardaleb** [Kozea/Radicale#845]
The following example calender is added for the user, but it does not show up in the client:

BEGIN:VCALENDAR
PRODID:-//ATOSS CSD Software GmbH//ATOSS Time Control//DE
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
DTSTAMP:20180704T101819Z
DTSTART;VALUE=3DDATE:20180704
DTEND;VALUE=3DDATE:20180705
SUMMARY:Urlaub Bachmeier Sonja am 04.07.2018
**UID:user@example.com/20180704-20180705**
DESCRIPTION:Urlaub f=C3=BCr Bachmeier Sonja am 04.07.2018\n
SEQUENCE:0
END:VEVENT
END:VCALENDAR

Looking at the storage directory, the .ics file is created in a sub directory _/user@example.com/20180704-20180705/_

The log says:

WARNING:radicale:Skipping invalid path '/user/78359a13-4601-c584-dcd3-9cdc9a950f57/user%2540example.com/20180704-20180705.ics' in REPORT request on '/user/78359a13-4601-c584-dcd3-9cdc9a950f57/': 'user%2540example.com/20180704-20180705.ics' is not a component in collection 'user/78359a13-4601-c584-dcd3-9cdc9a950f57'

The actual calendar file is stored in this directory 20180704-20180705/xxx.ics (where xxx is a generated id)

**Comment by pbiering** [comment]
please reopen if reproducable with current version of radicale+vobject
