### ISSUE TITLE
Bad Request 400

### ISSUE THREAD

**Issue by ghost** [Kozea/Radicale#847]
Hi

Since I updated my ArchLinux ARM Server I have a problem with Bad Request 400.

I realised it later so I can't reproduce it. I don't even know what I updated or when the problem started. It was working before without any problems.

Every time if I wanna add a Contact to my Android Phone (or CardBook) - with Davdroid and Android Version 8.1.0 I get the following error:

`HTTP REQUEST:
Request{method=PUT, url=http://192.168.1.xx:5232/user/50bc3f12-1b10-47cf-0ee6-72b18541ed39/ab3b3246-920b-42a3-9cbd-c6321a7cfdab.vcf, tag=null}
BEGIN:VCARD
VERSION:3.0
PRODID:+//IDN bitfire.at//DAVdroid/1.11.5-ose ez-vcard/0.10.4
UID:ab3b3246-920b-42a3-9cbd-c6321a7cfdab
FN:Name
N:Name
TEL;TYPE=cell:Number
EMAIL:name@provider.com
BDAY:day
REV:2018-07-17T10:07:47Z
END:VCARD `
`HTTP RESPONSE:
Response{protocol=http/1.1, code=400, message=Bad Request, url=http://192.168.1.76:5232/user/50bc3f12-1b10-47cf-0ee6-72b18541ed39/ab3b3246-920b-42a3-9cbd-c6321a7cfdab.vcf}
Bad Request`

On CardBook
`2018.07.18 13:26:31:146 : User : Contact Name failed to be created on server (url : http://192.168.1.76:5232/user/50bc3f12-1b10-47cf-0ee6-72b18541ed39/0f2b56d0-e754-4fa9-af2d-e2deb0d8c782.vcf, status : 400)`

Sometimes it is working when I add a new contact. All my calendar and todos are working. It's so weird. I can't find the problem.

systemctl status radicale
`WARNING: Bad PUT request on '/user/50bc3f12-1b10-47cf-0ee6-72b18541ed39/2b2000b7-a0f9-486f-92ce-c210c9680fe5.vcf': At line 8: In transformToNative, unhandled exception on line 8: In transformToNative, unhandled exception on line 8: <class 'ValueError'>: invalid literal for int() with base 10: '7-' (<REV{}2018-07-18T01:27:14Z>)`

I tried vCard 3 and 4.

Hm...

**Comment by Arvedui** [comment]
This is an issue with current vobject not with radicale. Just downgrade python-vobject to version `0.9.5`.

This issue is tracked in eventable/vobject#120

**Comment by DanSman** [comment]
Thank you very much. That solved the problem.

**Comment by wpercy** [comment]
Should be resolved in vObject 0.9.6.1

**Comment by DanSman** [comment]
Hey

Just tried the new version again ( I had it installed before i guess). Not working. 
python-vobject-0.9.5-4 is working for me.

**Comment by ArchbishopFlabrus** [comment]
Affected by the vobject bug here as well.  

In the hopes that some other wandering soul may find this, the Gentoo ebuild for Radicale 2.1.10 specifies vobject 0.9.6, which means if you update to that version you're affected by this as well.

I simply downgraded Radicale to 2.1.8 (the previous version available via portage) and vobject to 0.9.5 and that solved my issues.

**Comment by dagbdagb** [comment]
@ArchbishopFlabrus thanks. Useful info indeed.

**Comment by potuz** [comment]
Has this really been solved in vobject 0.9.6.1? I am running Radicale-2.1.10, vobject-0.9.6.1 and python-dateutil-2.7.5 on Gentoo and hit this Bad Request with Davdroid 2.2.2

**Comment by mattconnell** [comment]
> Has this really been solved in vobject 0.9.6.1? I am running Radicale-2.1.10, vobject-0.9.6.1 and python-dateutil-2.7.5 on Gentoo and hit this Bad Request with Davdroid 2.2.2

I upgraded to those three versions tonight and I am not experiencing the issue anymore.

**Comment by pbiering** [comment]
Problem:

```
`datetime.date' object has no attribute 'tzinfo' (<CREATED{'VALUE': ['DATE']}20240528>
```

problematic line is

```
CREATED:20240528
```

Assumed item was created by

```
PRODID:-//WordPress - MECv6.5.6//EN
```

to my knowledge `vobject` (which is parsing an item) has less/zero support for all the broken clients around...so one has to fix the unit which creates broken items.

**Comment by pbiering** [comment]
closed as not our bug
