### ISSUE TITLE
who changes LAST-MODIFIED property

### ISSUE THREAD

**Issue by sla29970** [Kozea/Radicale#85]
Apple iCal on Mavericks does not change LAST-MODIFIED when editing a VEVENT.
Gnome Evolution does change LAST-MODIFIED when editing a VEVENT.
It looks like Evolution does not see edits unless LAST-MODIFIED changes, and it looks like Apple believes that it is the server responsibility to produce self-consistent values of LAST-MODIFIED.  RFC 5545 seems not to specify who is responsible for the value in LAST-MODIFIED.  Should radicale ignore any value from the client and always update LAST-MODIFIED using its own notion of the time?

**Comment by pbiering** [comment]
radicale is currently not modifying any content in ICS and VCF, if it would be mandatory to do so, reopen this and somebody has to contribute code for that.
