### ISSUE TITLE
Removing radicale

### ISSUE THREAD

**Issue by oapagit** [Kozea/Radicale#855]
Hi, I am a newbie, although I have had Linux Mint (64 bit) for some time now. My distro is 17.3 Rosa (Ubuntu 14.04.1 Trusty Tahr, Kernel release 4.2.9-22-generic), with XFCE.
I tried to install the calendar server 'radicale' on localhost:5232, as per the instructions, in order to share my Thunderbird/Lightning calendar with my Android smartphone, but although it said 'radicale works', it doesn't seem to do so. So I tried to remove/purge radicale via the terminal and via Synaptic, but it hasn't got rid of everything and every time I use the update manager (to update things), it works but gives me the following error message;

(synaptic:17023): GLib-CRITICAL **: g_child_watch_add_full: assertion 'pid > 0' failed
(Reading database ... 200750 files and directories currently installed.)
Removing radicale (0.8-1) ...
* Stopping Radicale CalDAV server radicale [ OK ]
/etc/init.d/radicale: 144: /etc/init.d/radicale: :./radicale: not found
invoke-rc.d: initscript radicale, action "stop" failed.
dpkg: error processing package radicale (--remove):
subprocess installed pre-removal script returned error exit status 127
update-rc.d: warning: default stop runlevel arguments (0 1 6) do not match radicale Default-Stop values (none)
* Starting Radicale CalDAV server radicale [ OK ]
/etc/init.d/radicale: 144: /etc/init.d/radicale: :./radicale: not found
invoke-rc.d: initscript radicale, action "start" failed.
dpkg: error while cleaning up:
subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
radicale
E: Sub-process /usr/bin/dpkg returned an error code (1)
A package failed to install. Trying to recover:

I note that in Synaptic, it says I have got radicale and python-radicale, which I'm not sure is desirable. But how can I get rid of either/both and stop getting this error message?
Thanks in anticipation
Andrew

**Comment by oapagit** [comment]
Can anybody help me with this problem?

**Comment by skorokithakis** [comment]
Try to install and uninstall again.
