### ISSUE TITLE
Saving contacts with images using InfCloud

### ISSUE THREAD

**Issue by tberger2** [Kozea/Radicale#860]
Trying to save a contact with an image returns error code 400 in InfCloud 0.13.1. This did actually work with baikal, which I replaced with radicale 2.1.8.  
There is no problem using Thunderbird Lightning.

Logs say:

> WARNING: Bad PUT request on '/xxx/xxx.vcf': decoding with 'base64' codec failed (Error: Incorrect padding)

Any ideas?

Thank you in advance!

**Comment by olenchenko** [comment]
Hi.
I had similar problem, though it was long time ago - take a look here https://www.inf-it.com/mlmmj/davclients/2015-09/0000067.html

Vasyl

**Comment by tberger2** [comment]
Downgrade to 0.12.1 solved the problem. Thank you, Vasyl!

**Comment by olenchenko** [comment]
No problem. There is a patch for 0.13 version which should work - https://www.inf-it.com/fixes/photo_attr_fix.diff

**Comment by tberger2** [comment]
Which works as well, thanx again!
