### ISSUE TITLE
Reverse proxy example is wrong

### ISSUE THREAD

**Issue by FAUSheppy** [Kozea/Radicale#869]
https://radicale.org/proxy/

in the nginx configuration it says:

    proxy_pass        http://localhost:5232/; # The / is important!

which leads to an nginx error:

    [emerg] "proxy_pass" cannot have URI part in location given by regular expression, or inside named location [...]

**Comment by mookie-** [comment]
@FAUSheppy the example is correct. I think you use a named location:

```
location @example {
```

instead of a regular location like in the example:

```
location /example/ {
```

Please paste your nginx configuration so I can tell you more.
