### ISSUE TITLE
Support SSL options

### ISSUE THREAD

**Issue by ghost** [Kozea/Radicale#87]
Currently, Radicale is using  ssl_version=ssl.PROTOCOL_SSLv23 to set TLS/SSL protocol. This may leave SSLv2 enabled, unless disabled somewhere.

I would like to be able to specify in the config file which protocols to use, for example only allow TLSv1.1 and TLSv1.2 and which ciphers to use (for example ECDHE-ECDSA-AES256-GCM-SHA384).

**Comment by caesarsamsi** [comment]
Are there examples for TLS specification keywords (e.g. trying to get 1.0, 1.1, 1.2 going).

I have ciphers just fine, man but the ":" character is a pain to type in (I need to use sed)
