### ISSUE TITLE
"Failed to load config file %r: %s" % (path, e)) from e

### ISSUE THREAD

**Issue by brown78** [Kozea/Radicale#873]
Hello,

I want to run radicale on a raspi. I installed everthing without any errors. But when I want to start the service I get this error message:
● radicale.service - LSB: radicale server daemon
   Loaded: loaded (/etc/init.d/radicale; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-09-18 18:41:59 UTC; 46s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 17609 ExecStart=/etc/init.d/radicale start (code=exited, status=1/FAILURE)

Sep 18 18:41:59 raspberrypi radicale[17609]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Sep 18 18:41:59 raspberrypi radicale[17609]:   File "build/bdist.linux-armv6l/egg/radicale/__init__.py", line 32, in <m
Sep 18 18:41:59 raspberrypi radicale[17609]:   File "/usr/local/lib/python2.7/dist-packages/Radicale-2.90.0-py2.7.egg/r
Sep 18 18:41:59 raspberrypi radicale[17609]:     "Failed to load config file %r: %s" % (path, e)) from e
Sep 18 18:41:59 raspberrypi radicale[17609]:                                                         ^
Sep 18 18:41:59 raspberrypi radicale[17609]: SyntaxError: invalid syntax
Sep 18 18:41:59 raspberrypi systemd[1]: radicale.service: Control process exited, code=exited status=1
Sep 18 18:41:59 raspberrypi systemd[1]: Failed to start LSB: radicale server daemon.
Sep 18 18:41:59 raspberrypi systemd[1]: radicale.service: Unit entered failed state.
Sep 18 18:41:59 raspberrypi systemd[1]: radicale.service: Failed with result 'exit-code'.

**Comment by mookie-** [comment]
@brown78 which python version do you have installed?
