### ISSUE TITLE
Error when deleting repeating Events

### ISSUE THREAD

**Issue by dunklesToast** [Kozea/Radicale#878]
Hey!

I found this bug:
When you delete a repeating Event, the Server returns an Error and the Event doesn't get deleted.
The Error Log can be found [as a github gist](https://gist.github.com/dunklesToast/61344aafce14a8a75c58d6b06e537b84)

I am using Apples macOS Calendar App on macOS High Sierra.
The Server is behind an NGINX Proxy and CloudFlare protected.

EDIT: This bug also occurs with CalDAV Sync for Android and on the iOS Calendar Apps

**Comment by yoonsikp** [comment]
Can you leave some more steps so we can reproduce

**Comment by dunklesToast** [comment]
If you create a repeating event, for example something that repeats each week, you cannot delete it. The Server will return an error if you try to delete it. The Event was Created with CalDav Sync for Android and can't be deleted. I am running radicale on the newest version 
![image](https://user-images.githubusercontent.com/17279485/49224990-29d8cd00-f3e3-11e8-8fef-5c4b5e02a677.png)

**Comment by pbiering** [comment]
Is this still happen with latest 3.1.x? If not, please close this issue - thank you!

**Comment by pbiering** [comment]
closing as related to old version, please reopen in case still happened with latest version
