### ISSUE TITLE
Radical with self-signed certificate cause cannot verify server identity

### ISSUE THREAD

**Issue by holian7** [Kozea/Radicale#893]
Masters,

I few weeks ago here in the forum successfully solved the problem, how to use Radicale with IOS 12 (In SSL configured ..)
Here is the new issue:

We use the IOS devices with OSX server / Profile configurator. I set the Carddav server payload and push the configuration to the device. Configuration download, everything seems ok, but contacts not download.
If i delete the password (which is deployed via configurator profile) and type it again, i got a message "cannont verify server identity...). After i confirm this message and click on continou button, then contacts download immediately.

Any idea how to add my self-signed cert to IOS devices remotely, with apple profile manager? Or how to make this cert trusted?

Regards,

Holian

**Comment by Tntdruid** [comment]
Use 
https://letsencrypt.org/ trusted and free

**Comment by holian7** [comment]
Thats did the trick! Thank you!

**Comment by mookie-** [comment]
@holian7 can you please close this issue if your problem is fixed.
