### ISSUE TITLE
Working calendars, no access via web interface with 'rights' file

### ISSUE THREAD

**Issue by sphh** [Kozea/Radicale#898]
I followed the documentation [Authentication and Rights](https://radicale.org/rights/) from Radicale's documentation.

This is the part of the `/etc/radicale/config` file:
```ini
[rights]
type = from_file
file = /etc/radicale/rights
```

And this is the `/etc/radicale/rights` file:
```ini
# Authenticated users can read and write their own collections.
[owner-write]
user = .+
collection = %(login)s(/.*)?
permission = rw

# Shared calendar for users you and me.
[shared-write]
user = (you|me)
collection = shared(/.*)?
permission = rw
```

All calendars work when accessed from a calendar program (`thunderbird/lightning` and `DAVdroid`), but I cannot log into the web interface https://www.myserver.com:5232: I get an `Error: 403 Forbidden`.

The log file is:
```log
2018-11-21 19:30:57,599 - [-48ab6ec0] INFO: Starting Radicale
2018-11-21 19:30:57,623 - [-48ab6ec0] INFO: Authentication type is 'radicale_dovecot_auth'
2018-11-21 19:30:57,624 - [-48ab6ec0] INFO: Storage type is 'multifilesystem'
2018-11-21 19:30:57,624 - [-48ab6ec0] INFO: Rights type is 'from_file'
2018-11-21 19:30:57,624 - [-48ab6ec0] INFO: Web type is 'internal'
2018-11-21 19:30:57,638 - [-48ab6ec0] INFO: Listening to 'www.myserver.com' on port 5232 using SSL
2018-11-21 19:30:57,639 - [-48ab6ec0] INFO: Radicale server ready
2018-11-21 19:31:40,890 - [-496dc4c0] INFO: PROPFIND request for '/' received from 213.162.72.188 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0'
2018-11-21 19:31:40,892 - [-496dc4c0] DEBUG: Request headers:
{'CONTENT_LENGTH': '127',
 'CONTENT_TYPE': 'text/plain;charset=UTF-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'en-GB,en;q=0.5',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'www.myserver.com:5232',
 'HTTP_REFERER': 'https://www.myserver.com:5232/.web/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) '
                    'Gecko/20100101 Firefox/63.0',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '213.162.72.188',
 'REMOTE_CERTIFICATE': None,
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'www.myserver.com',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0xb6965344>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2018-11-21 19:31:40,893 - [-496dc4c0] DEBUG: Sanitized script name: ''
2018-11-21 19:31:40,893 - [-496dc4c0] DEBUG: Sanitized path: '/'
2018-11-21 19:31:41,010 - [-496dc4c0] INFO: Successful login: 'you'
2018-11-21 19:31:41,012 - [-496dc4c0] DEBUG: Rule 'you':'you' matches '.+':'you(/.*)?' from section 'owner-write'
2018-11-21 19:31:41,022 - [-496dc4c0] DEBUG: Rule 'you':'' doesn't match '.+':'you(/.*)?' from section 'owner-write'
2018-11-21 19:31:41,023 - [-496dc4c0] DEBUG: Rule 'you':'' doesn't match '(you|me)':'shared(/.*)?' from section 'shared-write'
2018-11-21 19:31:41,023 - [-496dc4c0] INFO: Rights: 'you':'' doesn't match any section
2018-11-21 19:31:41,024 - [-496dc4c0] DEBUG: Rule 'you':'' doesn't match '.+':'you(/.*)?' from section 'owner-write'
2018-11-21 19:31:41,025 - [-496dc4c0] DEBUG: Rule 'you':'' doesn't match '(you|me)':'shared(/.*)?' from section 'shared-write'
2018-11-21 19:31:41,025 - [-496dc4c0] INFO: Rights: 'you':'' doesn't match any section
2018-11-21 19:31:41,025 - [-496dc4c0] INFO: Access to '/' denied for 'you'
2018-11-21 19:31:41,025 - [-496dc4c0] DEBUG: Response content:
Access to the requested resource forbidden.
2018-11-21 19:31:41,026 - [-496dc4c0] INFO: PROPFIND response status for '/' in 0.135 seconds: 403 Forbidden
```

What puzzles me, is that the line
```log
2018-11-21 19:31:41,012 - [-496dc4c0] DEBUG: Rule 'you':'you' matches '.+':'you(/.*)?' from section 'owner-write'
```
confirms a successful match, but then 3 lines further down:
```log
2018-11-21 19:31:41,023 - [-496dc4c0] INFO: Rights: 'you':'' doesn't match any section
```

Is this a mistake in my `/etc/radicale/rights` file?

**Comment by lukasbestle** [comment]
I also have this issue. I can't get the `from_file` authentication backend to work in the web interface.

**Comment by danofun** [comment]
I'm having the same issue. When using from_file rights I am unable to successfully log into the web interface.

**Comment by Unrud** [comment]
All users need atleast read-access to the root collection:

```
[read-root-collection]
user = .+
collection =
permission = r
```

**Comment by sphh** [comment]
I can confirm, that it works with read access to the root collection as suggested by @Unrud.

Please, can this information be added to the https://radicale.org/rights/ documentation? Thanks.

**Comment by skorokithakis** [comment]
Jeez, yeah, that worked. Please add this to the docs, this took me hours of wasted work.

**Comment by jonassmedegaard** [comment]
I recommend to change the rights.conf to have sane default values by default, instead of the current set of demo setting unusable as-is.

Here's the rights.conf shipped with Debian: https://salsa.debian.org/debian/radicale/blob/master/debian/etc/radicale/rights

**Comment by Antidote00** [comment]
@skorokithakis I totally agree! I would be enough if there would be an FAQ somewhere, redirecting to this issue...

**Comment by crainsaw** [comment]
Everyone coming here with a fresh radicale installation which does not work i.e. when logging in with your newly created user you get a 403 error in the web frontend: You need to use a rights file where access to the root collection is set. For me (installed via pip) I used the contents from the radicale documentation and it works fine for me now (i.e. I can log in and create collections):
`# Allow reading root collection for authenticated users
[root-collection]
user: .+
collection:
permissions: R

# Allow reading and writing principal collection (same as user name)
[principal]
user: .+
collection: {user}
permissions: RW

# Allow reading and writing calendars and address books that are direct
# children of the principal collection
[calendars]
user: .+
collection: {user}/[^/]+
permissions: rw`

If I did not miss any other important configuration or misunderstood something this should be the default behaviour of radicale or at least it should be noted in the documentation as @sphh already mentioned.

**Comment by RalfJung** [comment]
I am still getting "403 Forbidden" even when using the Debian `right` configuration:
```
# Allow reading root collection for authenticated users
[root]
user: .+
collection:
permissions: R

# Allow reading and writing principal collection
# (same as user name)
[principal]
user: .+
collection: {user}/ 
permissions: RW

# Allow reading and writing calendars and address books
# that are direct children of the principal collection
[calendars]
user: .+
collection: {user}/[^/]+
permissions: rw
```
The log says
```
Jul 31 20:21:40 r-thinktop env[481002]: [2021-07-31 20:21:40 +0200] [481002/Thread-3] [INFO] Access to '/ralfj/' denied for 'ralfj'
Jul 31 20:21:40 r-thinktop env[481002]: [2021-07-31 20:21:40 +0200] [481002/Thread-3] [DEBUG] Response content:
Jul 31 20:21:40 r-thinktop env[481002]: Access to the requested resource forbidden.
Jul 31 20:21:40 r-thinktop env[481002]: [2021-07-31 20:21:40 +0200] [481002/Thread-3] [INFO] PROPFIND response status for '/ralfj/' with depth '1' in 0.009 seconds: 403 Forbidden
```
Looks like somehow this is not enough any more? I am using radicale 3.0.6 (Debian testing).

**Comment by RalfJung** [comment]
Also, this affects not just web logins -- DAVx5 on Android cannot access any of my address books or calendars any more, either. (This used to work, and at least calendars still work on one of my old phones, but on my latest one I cannot access anything any more.)

**Comment by RalfJung** [comment]
Oh, the problem is that by default the `rights` config is `type = owner_only`. That default does not work with either the web UI nor DAVx5 though, making one wonder why it is the default in the first place...

**Comment by RalfJung** [comment]
But even then it still doesn't let me access my calendars -- the "root access" rule does not seem to work any more.

Since this is a single-user system, I ended up with this work-around, which is the only way I found to get a functional radicale currently (where "functional" contains "working DAVx5"):
```
[ralfj]
user: ralfj
collection: .*
permissions: rRwW
```

(Sorry for all the spam. I am a little frustrated about the dozens of problems I am encountering in today's Android update...)

**Comment by sphh** [comment]
Documentation updated: #1273
