### ISSUE TITLE
Too strict requirements: ["vobject>=0.9.6", "python-dateutil>=2.7.3"]

### ISSUE THREAD

**Issue by szotsaki** [Kozea/Radicale#899]
I'm packaging [Radicale for openSUSE](https://build.opensuse.org/package/show/home:szotsaki/Radicale) but with the latest version (2.1.11) I found that the aforementioned two libraries are way too new and they are not in the normal release (Leap 42.3 and Leap 15.0). Therefore I cannot package Radicale 2 for regular released openSUSE distros anymore.

Moreover, vobject >= 0.9.6 is not even in the rolling release version (Tumbleweed) therefore I cannot package it for that, either.

I don't know if it's possible to lower the requirements but until they stay this way openSUSE packages cannot be updated anymore, unfortunately.

Supported versions:

| Name | vobject | python-dateutil |
|---------|-----------|--------------------|
| Leap 42.3 | 0.9.4.1 | 2.7.3 (from experimental repo) |
| Leap 15.0 | 0.9.5 | 2.6.1 |
| Tumbleweed | 0.9.5 | 2.7.3 |

**Comment by jubalh** [comment]
@szotsaki the request has been accepted.

**Comment by szotsaki** [comment]
Thank you for the requests, Radicale 2.1.11 is now built on Leap 15.0 and Tumbleweed in my [home](https://build.opensuse.org/package/show/home:szotsaki/Radicale) and for Tumbleweed in [network:Radicale](https://build.opensuse.org/package/show/network/Radicale).
