### ISSUE TITLE
Radicale does not start when logging enabled

### ISSUE THREAD

**Issue by roycec** [Kozea/Radicale#902]
When enabling logging in /etc/radicale/config, e.g. 

```
[logging]
config = /etc/radicale/logging
```

I get the following error in journalctl
```
Nov 26 21:07:48 env[15847]: ERROR: Failed to start logger: Failed to load logging configuration file '/etc/radicale/logging': [Errno 30] Read-only file system: '/var/log/radicale/log'
Nov 26 21:07:49 systemd[1]: radicale.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 21:07:49 systemd[1]: radicale.service: Unit entered failed state.
Nov 26 21:07:49 systemd[1]: radicale.service: Failed with result 'exit-code'.
Nov 26 21:07:49 systemd[1]: radicale.service: Service hold-off time over, scheduling restart.
Nov 26 21:07:49 systemd[1]: Stopped A simple CalDAV (calendar) and CardDAV (contact) server.
-- Subject: Unit radicale.service has finished shutting down
```

The logging config looks like

```
[loggers]
keys = root

[handlers]
keys = file

[formatters]
keys = full

[logger_root]
level = WARNING
handlers = file

[handler_file]
class = FileHandler
args = ('/var/log/radicale/log',)
formatter = full

[formatter_full]
format = %(asctime)s - [%(thread)x] %(levelname)s: %(message)s
```

If logging is disabled, radicale starts just fine. Platform is Debian Stretch and Radicale (2.1.11).

**Comment by mookie-** [comment]
Hello,

your problem is described in first line of your log:
```
[...] [Errno 30] Read-only file system: '/var/log/radicale/log'
```

Your logging location `/var/log/radicale/log` is on a read-only file system, so radicale doesn't start because it can't write to this location.

**Comment by roycec** [comment]
Hello mokie,

the /var directory is on the same partition than the root directory, so it's definetly not read-only. I also tried creating files as the radicale user in this directory - with success. I think the error message is quiet misleading.

**Comment by roycec** [comment]
@mookie- With log destination /tmp, radicale starts without error. But on the other side, /var/log/radicale has ownership radicale:radicale and permission of 750. Isn't this enough?

**Comment by roycec** [comment]
@mookie- 


sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=4077416k,nr_inodes=1019354,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=817712k,mode=755)
/dev/vda3 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=33,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=1635)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
/dev/vda1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=817708k,mode=700,uid=1000,gid=1000)

**Comment by mookie-** [comment]
@roycec that looks good. Can you please also paste your systemd unit file here? It's probably in `/etc/systemd/system/` (but I'm not sure as I don't know how you've installed it).

Do you use a chroot or something like that for radicale? Because it works when you log to `/tmp/...` and it doesn't work when logging to `/var/log/radicale/log`. So it's not a radicale problem but somehow radicale can't write to `/var/log/radicale/log` and thinks it's a read only file system.

**Comment by roycec** [comment]
This was a copy/paste from the radicale web site:

```
[Unit]
Description=A simple CalDAV (calendar) and CardDAV (contact) server
After=network.target
Requires=network.target

[Service]
ExecStart=/usr/bin/env python3 -m radicale
Restart=on-failure
User=radicale
Group=radicale
# Deny other users access to the calendar data
UMask=0027
# Optional security settings
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
NoNewPrivileges=true
ReadWritePaths=/var/lib/radicale/collections

[Install]
WantedBy=multi-user.target
```

This is a fresh Debian VPS and I first thought about SELinux being active, but this seems not to be the case.

**Comment by mookie-** [comment]
@roycec I think it's due to `ReadWritePaths=/var/lib/radicale/collections`. Please add also this `ReadWritePaths=/var/log/radicale` and try it again.

**Comment by roycec** [comment]
@mookie- This configuration works, thanks! An (empty) log file has also been created.

**Comment by roycec** [comment]
The systemd service now looks like

```
[Unit]
Description=A simple CalDAV (calendar) and CardDAV (contact) server
After=network.target
Requires=network.target

[Service]
ExecStart=/usr/bin/env python3 -m radicale
Restart=on-failure
User=radicale
Group=radicale
# Deny other users access to the calendar data
UMask=0027
# Optional security settings
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
NoNewPrivileges=true
ReadWritePaths=/var/lib/radicale/collections
ReadWritePaths=/var/log/radicale

[Install]
WantedBy=multi-user.target
```
