### ISSUE TITLE
Sharing permissions

### ISSUE THREAD

**Issue by slinxy** [Kozea/Radicale#905]
Hi I'm trying to setup a server to share one address bookt o multiple users...
the server is up and working and I got the rights from_file setup.

adminrights has read/write permissions to make adjustable to the contacts
enduser only has read access to adminrights contracts

I can get as far as using endusers username and password and add adminrights contact url but it doesn't bring up any of the actual contacts.

this is my rights file:
`## GLOBAL ##

# any authenticated user can reach root collection
[read]
user = .+
collection =
permission = r

# specific to login to web panel, if not you can't login because only your data is allowed and not your root
[rw_own_root]
user = .+
collection = %(login)s
permission = rw

# any authenticated user can rw its data
[rw_own]
user = .+
collection = %(login)s/.*
permission = rw

[shared]
user = enduser
collection = adminuser/.*
permission = r
`
thanks

**Comment by alberttwong** [comment]
https://github.com/Kozea/Radicale/issues/1058

**Comment by pbiering** [comment]
meanwhile a wiki page was created with examples for collection sharing
https://github.com/Kozea/Radicale/wiki/Sharing-Collections
