### ISSUE TITLE
incorrect vcf extensions cause response 500 "A server error occured" with no log messages

### ISSUE THREAD

**Issue by jheidemann** [Kozea/Radicale#908]

**Comment by jheidemann** [comment]
Suggestion: Radicale needs to log clearer messages for invalid files in its database.
(This bug is a variant on https://github.com/Kozea/Radicale/issues/830 )

Background:
In reinstalling a Fedora 29 system, Radicale stopped serving a vcard account that it used to serve correctly.  (Version is radicale-2.1.9-6.fc29.noarch, from the OS vendor's packages.)

When the client software (DAVdroid on android) sent PROPFIND to the carddav account, radicale returns code 500, "A server error occurred".  There was nothing in journald, nor /var/log/radicale, even after "debug = true" in /etc/radicale/config, and running by hand.

The problem turned out to be there were files in the carddav directory that had no extension, or were named ${UUID}vcf without a dot, for some UUID.  I don't know how these got there (I'm sure it was my years of dissolute VCarding).  Why these worked on the prior Radicale installation (which I thought was exactly the same version), I don't know.

Giving all the files correct extensions (.vcf, with the dot!) fixed the problem for me.

But I really had zero clue what was wrong from radicale.  It would be nice to log something about the offending entry in the log on the server.  Because "500 a server error occured" is about as good as the ed editor's ? error: "an experiend user will usually know what is wrong".

(That said: THANK YOU VERY MUCH for maintaining a almost always useful caldav/carddav server!)

**Comment by jheidemann** [comment]
(To be clearer: files with no extension are my error.  Being strict until I fix my problem is a design choice that Radicale-2 seems to embrace.  I can live with strict.  But not giving me any clue what specifically is wrong to help me fix the problem, that makes me sad.)

**Comment by Seegras** [comment]
In fact, _any_ file with a weird name within collection-root will throw a 500 instead of being ignored...

**Comment by logological** [comment]
I'm not able to reproduce this problem with Radicale 2.1.11 on Raspbian.  All my vCard files have no extensions and Radicale is happy to serve them.
