### ISSUE TITLE
radicale only connects to nearby computers

### ISSUE THREAD

**Issue by belanger** [Kozea/Radicale#924]
Hi Everybody,

I'm not sure this is a bug, but it is a problem I'm having with
Radicale, and I don't know of any other places to ask questions.
This looks similar to issue #777, "unable to connect to radicale
server from outside the LAN", but I'm not (knowingly) using a cable
modem.

I installed and set up Radicale according to the web pages
(https://radicale.org/, https://radicale.org/tutorial/ and
https://radicale.org/setup/).  (A copy of the config file is at the
bottom.)  It looks like it works great, I can go to
http://mycomputer.com:5232
and log in as user1, with no problem.  But only if I'm on campus; if
I'm off campus and I go to
http://mycomputer.com:5232
nothing comes up.  Either on or off campus, I can get to my web page at
http://mycomputer.com
and it comes up just fine.  Does anybody know what could cause this?

Thanks,
Jay

-- config file, with commented lines omitted for brevity ---

[server]

hosts = 0.0.0.0:5232

type = htpasswd

htpasswd_filename = /etc/radicale/users
htpasswd_encryption = bcrypt

[storage]

filesystem_folder = /var/lib/radicale/collections

**Comment by return42** [comment]
Looks like your port 80 is exported from intranet to outside internet while 5232 not.  Anyway I cant recommend to use unencrypted http:// from the internet: all your passwords are delivered unencrypted.  I really recommend to use https:// from internet.

**Comment by belanger** [comment]
Thanks for the information! 
I knew/know nothing about ports and blocking, but this explains my problem completely.  I'll have to talk to the powers that be on campus and see about opening it, or find a different server.

Thanks!
Jay
