### ISSUE TITLE
raise severity of failed login

### ISSUE THREAD

**Issue by slavkoja** [Kozea/Radicale#926]
Current implemenntation logs failed logins at INFO severity. At this severity is logged a lot of events, vhich are not always needed, then if one want/need to track failed logins, there is loged a lot of noise.

Please, raise severity to more important level, e.g. WARNING. Loging client's IP with this will be great to integrate with someting as fail2ban.

**Comment by galaxy4public** [comment]
I think the whole logging framework should be reviewed and restructured to make it easier to automatically process.  E.g. with the master branch moving toward modularised approach there should be a standard on how authN modules log (for example, the entry point into the authentication should log and INFO level message about the attempt, then either INFO level message about a success or WARNING about a failure.  The modules themselves could add additional INFO level messages about notable events).

**Comment by pbiering** [comment]
looks like this is related: https://github.com/Kozea/Radicale/pull/988

**Comment by pbiering** [comment]
was already implemented with https://github.com/Kozea/Radicale/pull/1104
