### ISSUE TITLE
Migration from 1.1.6 to 2.1.11 fails with single .isc calendar

### ISSUE THREAD

**Issue by leahoswald** [Kozea/Radicale#929]
I use radicale for a some years now with single .ics files with my radical 1.1.1 on a debian stretch. I tried the export to be able to use version 2.1.11 (in buster). To export my old data I installed a radicale 1.1.6 in a virtual environment. The problem is, that the migration or export doesn't work, it fails with the following error and I could find nothing mentioning this error message.

```
INFO: Exporting storage for Radicale 2.0.0 to '/opt/radicale'
ERROR: Failed to find child collections of '/user/my-calendar.ics': generator raised StopIteration
```

**Comment by audax** [comment]
I have the same problem. Any pointers?

**Comment by audax** [comment]
I exported the calendar, made a new one with Radicale 2 and imported it again.
Not the most elegant solution, but good enough in my case, since I am the only user.

**Comment by marcelvb** [comment]
@audax I have the same problem as @nazco. How did you export and import it exactly?

**Comment by audax** [comment]
@marcelvb I exported the calendar from Thunderbird, deleted the CalDav sync from Thunderbird. Then I installed Radicale 2.x, without migrating any data, set up my account again, synced the empty calendar from the new Radicale install into Thunderbird and then imported the previously exported calendar into the newly synced calendar.

I had to fix some recurring events after that, but nothing major.

**Comment by Tntdruid** [comment]
I always do it that way, works great.

**Comment by marcelvb** [comment]
Thanks @audax. My problem was that I upgraded to Debian 10 (and Radicale 2) before making the export. So I could not access my calendar at all. I fixed it by using Docker to spin up an environment with Radicale 1, apply the above mentioned patch and export my data there. It took me hours to figure it all out, but it seems it all works now, finally.

**Comment by ronnicek** [comment]
I have the same problem.. export ends with error:

```
INFO: Exporting storage for Radicale 2.0.0 to '/data/radicale/export/'
ERROR: Failed to find child collections of '/user/contacts.vcf': generator raised StopIteration
```

**Comment by b-abadie** [comment]
I fixed it with 
```
diff --git a/radicale/__main__.py b/radicale/__main__.py
index 4c3c12a..e492de5 100644
--- a/radicale/__main__.py
+++ b/radicale/__main__.py
@@ -79,15 +79,16 @@ def export_storage(config, path, debug=False):
                     if debug:
                         traceback.print_exc()
                     continue
-                try:
-                    remaining_collections.extend(collection.children(
-                        collection.path))
-                except Exception as e:
-                    print("ERROR: Failed to find child collections of %r: %s" %
-                          ("/" + collection.path, e))
-                    if debug:
-                        traceback.print_exc()
-                    exit(1)
+                if collection.is_node(collection.path):
+                    try:
+                        remaining_collections.extend(collection.children(
+                            collection.path))
+                    except Exception as e:
+                        print("ERROR: Failed to find child collections of %r: %s" %
+                              ("/" + collection.path, e))
+                        if debug:
+                            traceback.print_exc()
+                        exit(1)
                 os.makedirs(filesystem_path)
                 with collection.props as props:
                     if props:
```

(by wrapping line 82's try/except with `if collection.is_node(collection.path):` in `radicale/__main__.py`)
