### ISSUE TITLE
Website is missing release notes for 2.1.11

### ISSUE THREAD

**Issue by Hawk777** [Kozea/Radicale#931]
It seems that 2.1.11 was released a good few months ago now (PyPI claims November 2018), but the website doesn’t have any mention of it, neither on <https://radicale.org/download/>, nor on <https://radicale.org/news/>, nor on the front page.

**Comment by galaxy4public** [comment]
Yes, it seems that the project is drifting.  The 2.1.11 changes went to the 2.1.x branch and the master branch is currently behind.  There were no commits for an year :(, it is a bit sad since this is such a nice project.

**Comment by galaxy4public** [comment]
Moreover, the master branch is quite different in terms it is cleaner and has that module approach to stuff like storage and auth, yet it is not the branch the latest version for PyPI was built from.

**Comment by galaxy4public** [comment]
Also, the master branch is version *2.90.0* :), which is also not mentioned anywhere :)

**Comment by return42** [comment]
It seems that master is a refactoring while 2.11 is an undocumented release ([see graph](https://github.com/Kozea/Radicale/network)). Maybe @Unrud can clarify how Radicale development will go on.

**Comment by therentabrain** [comment]
Yes - does anyone know anything about the future of Radicale?

**Comment by Tntdruid** [comment]
Looks dead no updated in a very long time

**Comment by Hawk777** [comment]
Uh, looks like there are commits going up to yesterday—I would hardly call that “not updated in a very long time”! Just no release for a long time. I suppose maybe there were bugfixes in 2.11 and master is ongoing refactoring work which will be released eventually? I agree, would be nice for someone to document 2.11.
