### ISSUE TITLE
Required user for calendar creation

### ISSUE THREAD

**Issue by buxx** [Kozea/Radicale#934]
For given config:

```
[server]
hosts = 0.0.0.0:5232

[auth]
type = None

[rights]
type = None

[storage]
filesystem_folder = ./collections
```

And radicale 2.1.11 ran with `radicale -C radicale.ini --debug`.

When try to create a collection `public/public1:

``` bash
curl -X MKCOL 'http://localhost:5232/public/public1' --data \ 
'<?xml version="1.0" encoding="UTF-8" ?>
<create xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:I="http://apple.com/ns/ical/">
  <set>
    <prop>
      <resourcetype>
        <collection />
        <C:calendar />
      </resourcetype>
      <C:supported-calendar-component-set>
        <C:comp name="VEVENT" />
        <C:comp name="VJOURNAL" />
        <C:comp name="VTODO" />
      </C:supported-calendar-component-set>
      <displayname>Calendar</displayname>
      <C:calendar-description>Example calendar</C:calendar-description>
      <I:calendar-color>#ff0000ff</I:calendar-color>
    </prop>
  </set>
</create>'
Conflict in the request.
```

Server say (
[complete log](https://github.com/Kozea/Radicale/files/2952560/rlog.txt)
):

> [7f47caf42700] INFO: MKCOL response status for '/public/public1' in 0.002 seconds: 409 Conflict

But if i use basic auth in my request (adding `-u "public:foo"` to my curl command), it's working.

It is a normal behaviour ?
Thank's !

**Comment by pbiering** [comment]
related to old version, closing now, if reproducable with current version of radicale, please reopen.
