### ISSUE TITLE
iPhone IOS12 denied access 

### ISSUE THREAD

**Issue by allinaseng** [Kozea/Radicale#936]
Hello, 
Currently facing a problem with trying to get Radicale to syn to an iPhone. The issue present seems to be a denied access. 
I can get the contacts through a browser but if I add the account using CardDav then it does not work and get an authentication error. I posted the log and rights file to help further explain the case. 

Maybe it's something I made a mistake on. 
[rights1.txt](https://github.com/Kozea/Radicale/files/3009487/rights1.txt)

[log1.txt](https://github.com/Kozea/Radicale/files/3009484/log1.txt)

**Comment by return42** [comment]
Just a blind shot ...

    Sanitized path: '/ppfmadmin/ppfm_master/'
    ...
    INFO: PROPFIND response status for '/ppfmadmin/ppfm_master/' with depth '0' in 0.017 seconds: 401 Unauthorized
    DEBUG: anonymous user has read access to collection 'ppfmadmin/ppfm_master' 2019-03-26 10:29:28,858 - [49e0] 
    INFO: Access to '/ppfmadmin/ppfm_master/' denied for anonymous user

Your user seems to be 'anonymous'  ... next question will be; Did you check your rights file ..
   
    # The first rule matching both user and collection patterns will be returned.

**Comment by allinaseng** [comment]
I have the rights file listed as well. For the rights file according to the documentation, using .* would be anonymous and the DEBUG shows that anonymous has read access.

Unless I wrote my rights file wrong or it's not reading the rights file correctly due to first match rule.

Thanks,

Allina



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by allinaseng** [comment]
the rights file has it set as: 
[iphone-staff-read]
user: .*
collection: ppfmadmin/*
permission: r

this works as it points to the users' root collection but as to whether or not it passes anything back to the device in question is where I am stuck. 

This is a snippet of the log as of recent: 

2019-03-26 11:37:25,260 - [352c] DEBUG: Rule '':'ppfmadmin/ppfm_master' matches '.*':'ppfmadmin/ppfm_master' from section 'iphone-staff-read'
2019-03-26 11:37:25,260 - [352c] DEBUG: anonymous user has read access to collection 'ppfmadmin/ppfm_master'
2019-03-26 11:37:25,260 - [352c] INFO: Access to '/ppfmadmin/ppfm_master/' denied for anonymous user
2019-03-26 11:37:25,260 - [352c] DEBUG: Asking client for authentication
2019-03-26 11:37:25,260 - [352c] DEBUG: Response content:
Access to the requested resource forbidden.
2019-03-26 11:37:25,261 - [352c] INFO: PROPFIND response status for '/ppfmadmin/ppfm_master/' with depth '0' in 0.024 seconds: 401 Unauthorized
2019-03-26 11:45:11,101 - [490c] INFO: OPTIONS request for '/ppfmadmin/ppfm_master/' received from 10.33.51.223 using 'iOS/12.1.4 (16D57) dataaccessd/1.0'
2019-03-26 11:45:11,104 - [490c] DEBUG: Request headers:

**Comment by balki** [comment]
If the server is not running https, it wont work on iphone/ios. ref: https://github.com/Kozea/Radicale/issues/870#issuecomment-458397475

**Comment by allinaseng** [comment]
How would you set the onfig file for Radicale then if we are using https? I had some trouble with that.

Should this:
#hosts = 127.1.1.15:5232

Be
Hosts = 127.1.1.15:8083 or 127.1.1.15:443 since iphones use a different https port?

Thanks

Allina Seng

**Comment by allinaseng** [comment]
This has been resolved. Creating SSL certs worked like a charm. 

Thanks for all the help.
