### ISSUE TITLE
space needed for conversion to 2.X seems excessive

### ISSUE THREAD

**Issue by AvdN** [Kozea/Radicale#937]
I started looking into upgrading from 1.1.X to 2.1.11 and commenced with the "database" conversion using 1.1.6
I have over 30 (thirty) times the size of the 1.1 database free on the partition where I need to write the export. 

After the program takes a long time, I am running out of space on this target partition. I assume this is some temporary disc-space needed, is there is some way to put those temporary files somewhere else.

Can the documentation please give some indication on how much temporary space is going to needed to do the conversion and by how much a typical database is going to be larger  due to the conversion. (20%, 50%, 100%? hopefully not the full 3000%+ I am experiencing now) 

FWIW: all of the elements in the database (contact as well as calendar items) are put into radicale using Outlook + OutlookCaldavSync

**Comment by AvdN** [comment]
I found the problem causing this: https://github.com/Kozea/Radicale/blob/7568ec39f09a753217fb2d525c5f8db64f4d98f4/radicale/__main__.py#L111

**All** the VTIMEZONE definitions that occur in the original file are added to **each** of calendar items. With 40+ VTIMEZONES in the original file not being an exception that makes a *32Kb* single VEVENT .ics file out of something that is *860 bytes* if all the VTIMEZONES unreferenced by that particular VEVENT are removed (1.2Kb if the start and end (of a flight) are not in the same timezone).

**Comment by AvdN** [comment]
I retried the abandoned attempt to upgrade at the end of last month, and wrote some clean-up software to reduce the timezones in the resulting files. I am now at 3.0.6.

**Comment by jonassmedegaard** [comment]
Quoting Anthon van der Neut (2021-01-11 12:22:46)
> I retried the abandoned attempt to upgrade at the end of last month, and wrote some clean-up software to reduce the timezones in the resulting files. I am now at 3.0.6.

Care to share those scripts?

**Comment by AvdN** [comment]
> Care to share those scripts?
They are part of a larger setup of routines, I currently don't have the time to determine & extract what could be shared.
