### ISSUE TITLE
Support writing calendars from any source by certain protocol or format?

### ISSUE THREAD

**Issue by fishfree** [Kozea/Radicale#940]
Can we write events from any other source systems into Radicale by certain protocol or format? If so, users can add the singele Radicale CalDAV account in their smart phones to received all events published in differenct systems, i.e. meeting management system,  internal announcements publishing system etc. 

I've read the documentation, but I cannot figure out how to make it.

**Comment by jonassmedegaard** [comment]
Quoting fishfree (2019-04-03 08:45:24)
> Can we write events from any other source systems into Radicale by 
> certain protocol or format? If so, users can add the singele Radicale 
> CalDAV account in their smart phones to received all events published 
> in differenct systems, i.e. meeting management system, internal 
> announcements publishing system etc.
> 
> I've read the documentation, but I cannot figure out how to make it.

Radicale implements the network protocols [CalDAV] and [CardDAV].

[CalDAV]: <https://en.wikipedia.org/wiki/CalDAV>

[CardDAV]: <https://en.wikipedia.org/wiki/CardDAV>

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by fishfree** [comment]
@jonassmedegaard Thank you very much! Could you please explain a little furtherly? I want to 3rd party systems can call REST interfaces provided by Radicale to write events, then end users can add a Canlendar account in iOS (maybe Radicale need LDAP authentication). I don't know what the REST interfaces are, either how to or whether necessarily merge multiple 3rd-party-system-sourced events into a certain file or URL path managed by Radicale.

**Comment by return42** [comment]
> Can we write events from any other source systems into Radicale by certain protocol 

Radicale itself is an CalDAV & CardDAV Server, any CalDAV or CardDAV client can connect to. If you didn't understand that, then the whole questioning might be superfluous.

**Comment by fishfree** [comment]
This tutorial is useful. http://sabre.io/dav/building-a-caldav-client/
