### ISSUE TITLE
How to set up rights file

### ISSUE THREAD

**Issue by jmfoleyjr** [Kozea/Radicale#947]
I've now got radicale 2.1.11 running with a basic config and SSL. Currently, the only auth I have configured is htpasswd and any authenticated user can update any calendar. Now, I want to do some special things. I've looked at https://radicale.org/rights/ and some examples I've found on this github forum, but I'll have to admit I'm very confused by the rights file syntax. What I want is for all users to have read/write to their own calendars and read to all calendars. Also, I want a particular user to have write access to another specific user's calendar. Here's what I've come up with so far:

```
# Authenticated users can read and write their own collections.
# (basically copy/pasted from https://radicale.org/rights. No idea what the "collection =" regex evaluates to.
[owner-write]
user = .+
collection = %(login)s(/.*)?
permission = rw

# All authenticated users can read everyone's collection
[read]
user = .+
collection = .*
permission = r

# User Jane can write user Joe's calendar
[shared]
user = jane 
collection = joe
permission = rw


```# All authenticated users can update the Office Calendar
user = .+
collection = officeCalendar
permission = rw

So, does this look correct? I don't have an example for a specific "collection". I assume they refer to folders in .../collections/collection-root.

**Comment by return42** [comment]
> sorry, don't know why the comments appear extra-large bold

See section "Syntax highlighting" in https://guides.github.com/features/mastering-markdown

Or just mark the code-block and press the `<>` Button.

**Comment by jmfoleyjr** [comment]
Tried the code-block thing, but did it wrong. I clicked the <> button, then tried pasting. I guess I should have pasted, then marked the block, then clicked <>. I'll try that next time.

**Comment by jmfoleyjr** [comment]
Actually, I was able to edit the original posting and do as I described above and it worked. Thanks.

**Comment by return42** [comment]
> Actually, I was able to edit the original posting 

nitpicking: You included your last section into the code-block

> but I'll have to admit I'm very confused by the rights file syntax. 

The relevant sentences of the [rights description](https://radicale.org/rights/ ) are :

> Permissions from the first matching section are used. The user name is empty for anonymous users. Therefore, the regex .+ only matches authenticated users and .* matches everyone (including anonymous users).

So you have to place the _more specific_ at the beginning _and less specific_ at the end (whatever this means). I also have to think twice, when it comes to the rights setup. Your requirements are:

> What I want is for all users to have read/write to their own calendars and read to all calendars. Also, I want a particular user to have write access to another specific user's calendar. Here's what I've come up with so far:

I guess you have to change the sections `[read]` and the officeCalender part and don't forget to add a `[office]` section tag on top of the officeCalender part.

I don't know if there is any simpler solution, but here is how I setup the rights along three users with individual sharing option ... 

```conf
# -*- mode: conf -*-

# Rights management file for Radicale - A simple calendar server
#
# The default path for this kind of files is ~/.config/radicale/rights
# This can be changed in the configuration file::
#
#   [rights]
#   type = from_file
#   file = /etc/radicale/rights
#
# This file gives independant examples to help users write their own
# configuration files.
#
# .. hint::
#
#    1. The first rule matching both user and collection patterns
#       will be returned.
#    2. I needed to setup some 'R' & 'W' to get radicale's internal
#       WEB interface running
#
# About 'R' & 'W' see https://github.com/Kozea/Radicale/commit/0a492a ::
#
#   R: read collections without tag
#   r: read collections with tag and included objects
#   W: write and delete collections without tag
#   w: write and delete collection with tag and included objects

# 1. The user "admin" can read and write any collection.
[admin]
user: admin
collection: .*
permissions: RWrw

# 2. Example: dedicated sharing with 3 users
[user001]
user: user001
collection: user002(/.*)?
permissions: r

[user002]
user: user002
collection: user001(/.*)?|user003(/.*)?
permissions: r

[user003]
user: user003
collection: user002(/.*)?
permissions: r

# 3. Authenticated users can read and write their own collections.
[owner-write]
user: .+
collection: %(login)s(/.*)?
permissions: RWrw

# 4. Added 'R' to get WEB interface running
[read]
user: .+
collection: .*
permissions: R

```
Take care of the order 1. /  2. /  3. and so on. This is what I use with a Radicale installation from current master.  I don't know if there are difference between 2.1.11 and master. As far as I know (https://github.com/Kozea/Radicale/commit/0a492a) the upper letter are new in master but the whole config file should be downward compatible.

Hope that helps ..

**Comment by donjan** [comment]
@return42 but you still need to symlink the calendars into the other user's directory, right? Using 2.1.11 and it doesn't show calendars that are granted in the rights file, but not symlinked.

**Comment by return42** [comment]
Haven't tested with 2.1.11 but want to say no, since it make no sense to have rights management and need to symlink. Are you sure the configuration file with the rights is used by your Radicale process?

**Comment by donjan** [comment]
Let's try to keep this short, not to clutter the original report...
From `/etc/radicale/config`:
```
[...]
[rights]
type                = from_file
file                = /etc/radicale/rights
```
From `/etc/radicale/rights`:
```
[...]
[test2]
user = user2
collection = user3(/.*)?
permission = rw
```
Calendars for each user show up in their own web UI. user3's calendar doesn't show up in user2's web UI or OpenSync. Symlinking it inside user2's collection makes it show up in both.

Is this a potential difference between the current release and dev? I'm too short on time for testing out master.
Also, what's Radicale's convention for `R` vs `r` permissions?

**Comment by return42** [comment]
> Calendars for each user show up in their own web UI. user3's calendar doesn't show up in user2's web UI 

In the WEB UI the shared calender (from user3) is shown only in the owner folder, but via DAV user2 should have read/write permissions .

**Comment by return42** [comment]
@donjan is your question answered? .. if so, please close this issue / thanks!

**Comment by return42** [comment]
argh sorry, I confused @donjan and @jmfoleyjr .. forget my question about closing this issue.

**Comment by jmfoleyjr** [comment]
Based on the feedback, I've come up with the modifications shown below. Assumptions and questions:
.+  --- means authenticated users?
joe(/.*)? --- means the collection(s) belonging to joe? What does the '?' indicate in this expression.
%(login)s(/.*)? --- can someone interpret this for me?

Where can I find documentation on these regex's? Is this a Python thing?

Regarding return42's comment:
#   R: read collections without tag
#   W: write and delete collections without tag

What is mean by with/without tag? What is a tag?

Revised config:
```
# User Jane can write user Joe's calendar
[shared]
user = jane 
collection = joe(/.*)?
permission = rw

# Authenticated users can read and write their own collections.
[owner-write]
user = .+
collection = %(login)s(/.*)?
permission = rw

[office]
# All authenticated users can update the Office Calendar
user = .+
collection = officeCalendar(/.*)?
permission = rw

# All authenticated users can read everyone's collection
[read]
user = .+
collection = .*
permission = r

```

**Comment by jmfoleyjr** [comment]
Perhaps this should be a new issue, but I'll try posting here first as I believe I have a "rights" problem. I have set up my rights file as shown below. This works just fine when connecting from Thunderbird on Mac, Windows 7 and Linux. It also works when connecting from Windows 10 and Outlook 365 with caldavsynchronizer. It does not work when connecting from Mac Calendar or Windows 7 with Outlook 2010 and caldavsynchronizer. Below is the error response I get from the Window 7/Outlook/caldavsynchroniser when running radicale with debug (-D):

```
[7f5930ddc700] DEBUG: Sanitized script name: ''
[7f5930ddc700] DEBUG: Sanitized path: '/ConferenceRoom/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec/'
[7f5930ddc700] INFO: Successful login: 'mark'
[7f5930ddc700] DEBUG: Rule 'mark':'mark' doesn't match '.+':'ConferenceCalendar(/.*)?' from section 'conference'
[7f5930ddc700] INFO: Rights: 'mark':'mark' doesn't match any section
[7f5930ddc700] WARNING: Access to principal path '/mark/' denied by rights backend
[7f5930ddc700] DEBUG: Rule 'mark':'ConferenceRoom/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec' doesn't match '.+':'ConferenceCalendar(/.*)?' from section 'conference'
[7f5930ddc700] INFO: Rights: 'mark':'ConferenceRoom/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec' doesn't match any section
[7f5930ddc700] DEBUG: Rule 'mark':'ConferenceRoom' doesn't match '.+':'ConferenceCalendar(/.*)?' from section 'conference'
[7f5930ddc700] INFO: Rights: 'mark':'ConferenceRoom' doesn't match any section
[7f5930ddc700] INFO: Access to '/ConferenceRoom/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec/' denied for 'mark'
[7f5930ddc700] DEBUG: Response content:
Access to the requested resource forbidden.
[7f5930ddc700] INFO: PROPFIND response status for '/ConferenceRoom/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec/' with depth '0' in 0.003 seconds: 403 Forbidden

```
Below is the debug output from a successful connection, in this case from a Mac running Thunderbird:

```
[7ff194a42700] DEBUG: Rule 'mark':'ConferenceCalendar/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec' matches '.+':'ConferenceCalendar(/.*)?' from section 'conference'
[7ff194a42700] DEBUG: Client provided sync token: 'http://radicale.org/ns/sync/86549883de7ef4f4a9f44710b7a6362d'
[7ff194a42700] DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:">
  <sync-token>http://radicale.org/ns/sync/86549883de7ef4f4a9f44710b7a6362d</sync-token>
</multistatus>

[7ff194a42700] INFO: REPORT response status for '/ConferenceCalendar/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec/' with depth '1' in 0.005 seconds: 207 Multi-Status

```
Both have "INFO: Successful login: 'mark'" (though that line is not shown in the Mac/Tbird output. The bits I believe are of interest in these two sections are the lines beginning with "DEBUG: Rule". For the Win7/Outlook 2010/caldavsychronizer (and Mac Calendar, but not show), that line has:

`DEBUG: Rule 'mark':'mark' doesn't match '.+':'ConferenceCalendar(/.*)?' from section 'conference'
`
whereas the the successful logins with the Mac/Linux/Windows7 Tbird, and Windows10/Outlook/caldavsynchronizer have:

`DEBUG: Rule 'mark':'ConferenceCalendar/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec' matches '.
`
The difference is that the failed connections have "Rule 'mark':'mark'" and the successful connections have "Rule 'mark':'ConferenceCalendar/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec' "

For some reasons, The Windows 7/Outlook 2010/caldavsynchronizer and Mac/MacCalendar don't get processed by radicale the same way. Since surely lots of people are able to connect from these clients, I have to believe it has something to do with the way I have my rights file set up:

```
# All authenticated users can update the Conference Room Calendar
[conference]
user = .+
collection = ConferenceCalendar(/.*)?
permission = rw
```
I would really love to solve this problem!

**Comment by return42** [comment]
I see `ConferenceRoom` and `ConferenceCalendar` in the log, is this (Room vs Calender) what you want?

**Comment by jmfoleyjr** [comment]
Well, don't I have "Stupid" written all over my face! Yes, the collection name is ConferenceCalendar, not ConferenceRoom. "Conference Room" is what I named the calendar in Outlook. When I fixed that, the Windows 7/Outlook 2010/caldavsynchronizer computer started working. Duh! The Mac/Calendar is still a problem, so I'll do a bit more research on that and possible post back. Thanks for being an effective 2nd pair of eyes!

**Comment by jmfoleyjr** [comment]
Mac/Calendar still not working. Output of -D below. After configuring this calendar on Mac Calendar, the server host name (not the calendar name) appears on the Calendar app with a gray triangle. Clicking on that says, "The server specified on invalid calendar home. No calendar home was specified for the account "mail.ohprs.org". My Mac/Calendar account setup is:
User Name: mark
Password: *******
Server Address: mail.ohprs.org
Server Path: /ConferenceCalendar/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec/
Port: 5232
Use SSL, checked
Use Kerberos, not checked

output from radicale -D:

```
[7f580e54a700] DEBUG: Sanitized script name: ''
[7f580e54a700] DEBUG: Sanitized path: '/ConferenceCalendar/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec/'
[7f580e54a700] INFO: Successful login: 'mark'
[7f580e54a700] DEBUG: Rule 'mark':'mark' doesn't match '.+':'ConferenceCalendar(/.*)?' from section 'conference'
[7f580e54a700] INFO: Rights: 'mark':'mark' doesn't match any section
[7f580e54a700] WARNING: Access to principal path '/mark/' denied by rights backend
[7f580e54a700] INFO: OPTIONS response status for '/ConferenceCalendar/2c7a4b91-e0d9-6d05-d6ec-29112fec18ec/' in 0.003 seconds: 200 OK

```
What's wrong on this one? Thanks!

**Comment by jmfoleyjr** [comment]
I'll make this a separate post.

**Comment by return42** [comment]
Yuor separate post is https://github.com/Kozea/Radicale/issues/954#issuecomment-497133349 right? (just to wrap it here for other coming accross)

**Comment by jmfoleyjr** [comment]
Yes, 954

**Comment by wsirhc** [comment]
Hi, 
I've tried many of the example rules for the rights-file, but I can't get it working on radicale 3.0.3.

So what should be the rule, that matches the problem, similar to [[438893512]](https://github.com/Kozea/Radicale/issues/947#issue-438893512)
_Jane requires reading and writing access to Joe's calendar named "shared"._

thanks in advance
