### ISSUE TITLE
how to stop radicale daemon

### ISSUE THREAD

**Issue by jmfoleyjr** [Kozea/Radicale#948]
How do I gracefully stop the radicale daemon? I have the 'pid = filename' configured, but if the daemon is stopped due to reboot or kill, the pid file remains and attempting to restart radicale gives the error, "OSError: PID file exists: '~/pid'. For now, I've removed the 'pid =' setting.

Is there a proper way to handle this?

**Comment by return42** [comment]
Very strange that the PID is stored in your HOME folder (`~/`).  Anyway, my question is; how is the daemon started?

**Comment by jmfoleyjr** [comment]
I'm starting from a boot script as: 
su radicale --command "/usr/bin/radicale -d -D >> /home/radicale/radicale.log 2>&1"
so it runs as the radicale user, not root.

Some programs (dovecot, samba) have arguments to stop them, e.g. 'dovecot stop'. If there is nothing built-in like that for radicale, I can do a normal startup/shutdown script, such as:

```
#!/bin/bash
# script: /etc/rc.d/rc.radicale
# date: 2019-05-01
#
# Start/Stop the radicale CalDAV server

RADDIR=/home/radicale

stop()
{
    if [ -e $RADDIR/PID ]
    then
        kill -9 `cat $RADDIR/PID`
        sleep 2         # give it time to die, maybe don't need this
        rm $RADDIR/PID
    fi
}

start()
{
    stop        # just in case
    su radicale --command "/usr/bin/radicale -d -D >> /home/radicale/radicale.log 2>&1"
}

case "$1" in
'start')
  echo "Starting radicale CalDAV server"
  start
  ;;

'stop')
  echo "Stopping radicale CalDAV server" 
  stop
  ;;

'restart')
  echo "Retarting radicale CalDAV server"
  start
  ;;
*)
  echo Syntax: "rc.radicale [start | stop | restart]"
esac
exit 0

```

**Comment by jmfoleyjr** [comment]
The start/stop script as shown works fine.
