### ISSUE TITLE
Website: Update references to DAVdroid

### ISSUE THREAD

**Issue by logological** [Kozea/Radicale#949]
The website (on the [Clients](https://radicale.org/clients/) page and possibly elsewhere) contains references to an Android client named DAVdroid, which link to https://davdroid.bitfire.at/.  That link no longer works.  Apparently the project has been renamed from DAVdroid to DAVx⁵ and now lives at https://www.davx5.com/.

**Comment by Tntdruid** [comment]
#938

**Comment by Unrud** [comment]
Fixed by #938
