### ISSUE TITLE
Cannot access radicale from local LAN workstation using public FDQN

### ISSUE THREAD

**Issue by jmfoleyjr** [Kozea/Radicale#950]
I am running radicale 2.1.11 on a server with the LAN IP of 192.168.0.2 and the following config:
```
[server]
hosts = 0.0.0.0:5232
pid = ~/pid
ssl = True
certificate = /etc/ssl/certs/OHPRS/GoDaddy/Apache/2016-08-10/54e789087d419b6e.crt
key = /home/radicale/mail.ohprs.org.key

[encoding]

[auth]
type = htpasswd
htpasswd_filename = /etc/httpd/passwords
htpasswd_encryption = bcrypt

[rights]
type = from_file
file = ~/rights

[storage]
filesystem_folder = ~/collections

[logging]
[headers]

```
This works fine from outside the LAN referencing the public IP (FQDN). A firewall port-forwards 5232 to host 192.168.0.2. I can connect from LAN workstations to 192.168.0.2, but I get a security certificate error because the certificate is for the FDQN. If I try connecting from a LAN workstation to the FDQN, I get connection refused. 

I have verified using tcpdump that in this latter case the connection attempt is making it to 192.168.0.2, but the connection fails. Nothing shows on the server console when running 'radicale -f -D'. After lots of different experiments I'm concluding that radicale is refusing the connection, perhaps because I need something different or additional in the "hosts" setting.

Does anyone have any ideas on why I can't use the FDQN from within the LAN? This is a show-stopper for using radicale if I can't figure this out.

**Comment by Tntdruid** [comment]
Does your router have dns rebinding protection?

**Comment by jmfoleyjr** [comment]
No idea. The firewall/router is a Sonicwall TZ 400. The spec sheet doesn't mention dns rebinding. However, other ports work, so I don't think it's DNS:
```
LAN workstations -> FQDN:80 -- works
LAN workstations -> FQDN:25 -- works
LAN workstations -> FQDN:5232 -- Connection refused
```
If it were problem with the router, connections on other ports should not work either. It seem to be only the port on which radicale is listening.

These do work: 
```
LAN workstations -> 192.168.0.2:5232
WAN -> FQDN:5232
```
Only LAN workstations to FQDN on radicale listening port 5232 does not connect. Sure seems to point to radicale getting the request, but refusing the connection.

**Comment by jonassmedegaard** [comment]
Quoting jmfoleyjr (2019-05-10 16:29:59)
> No idea. The firewall/router is a Sonicwall TZ 400. The spec sheet doesn't mention dns rebinding. However, other ports work, so I don't think it's DNS:
> ```
> LAN workstations -> FQDN:80 -- works
> LAN workstations -> FQDN:25 -- works
> LAN workstations -> FQDN:5232 -- Connection refused
> ```
> If it were problem with the router, connections on other ports should not work either. It seem to be only the port on which radicale is listening.

Why not?

A router treating popular ports different from other ports would not 
surprise me.


> These do work: 
> ```
> LAN workstations -> 192.168.0.2:5232
> WAN -> FQDN:5232
> ```
> Only LAN workstations to FQDN on radicale listening port 5232 does not connect. Sure seems to point to radicale getting the request, but refusing the connection.

When you connect from inside to FQDN then do _do_ involve the router and 
the router _has_ to reroute.  Unless you have special "split horizon" 
name service lookup which I highly doubt (since you didn't mention 
that).


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jmfoleyjr** [comment]
Jonas - you may be right. I stopped radicale and ran 'nc -lv -p 5232' on the server instead. Same "Connection refused" from the LAN. So, must not be radicale's fault. My next step is to call Sonicwall.

**Comment by jmfoleyjr** [comment]
After a nearly all-day session, much of it with Sonicwall Tech Support, it did turn out to be an issue with the Sonicwall device. We got that straightened out and now have no problem connecting within the LAN using the FDQN.
