### ISSUE TITLE
"serve" existing ics to devices?

### ISSUE THREAD

**Issue by prankousky** [Kozea/Radicale#951]
Hi everybody,

I just stumbled upon this great program and am trying to automate my calendar workflow (more below).

Is it possible to provide an existing `.ics` file to `radicale`, then have other devices sync this file; **and** change that `.ics` file so that these changes will be synced to all connected devices?

This is my config

```
[server]
# Bind all addresses
hosts = 0.0.0.0:5232

[auth]
type = htpasswd
htpasswd_filename = /home/me/.config/radicale/users
# encryption method used in the htpasswd file
htpasswd_encryption = plain
[storage]
filesystem_folder = /home/me/.config/radicale/ics
```
This is what I did

* `radicale -d` to start as daemon
* open URL in browser
* login with username and password
* create calendar `test` (type calendar only)
* got this url for the calendar `http://localhost:5232/test/6b9e5696-3622-f54a-fe49-e73bf716fe38/`

Now I can setup `DAVx5` (previously `DAVdroid`) to sync this calendar to my android phone. It works. I can create an event on my phone, sync, then have an ics file in `/home/me/.config/radicale/ics/...` (long string as in calendar url).

However, I want to do the opposite. First, I want to create an empty calendar, then set up sync for this calendar on all devices that need it. Once this is done, I want to provide **another** ics file which gets changed regularly via a bash script; my devices should always get the latest version of this ics file.

I have tried overwriting the created ics file with my ics file. This does not seem to work. I cannot open the URL in my browser, and DAVx5 will not sync any longer. If I delete my ics file, everything works again. I can sync again, a new file gets created, etc. But changing the local ics file on the radicale server breaks everything.

My use case is that I need to re-download my local trash pickup schedule from the company website regularly; they allow subscribing to their feed, but if I do this, I cannot set reminders to the events (and will forget putting my trash out the previous night EACH TIME). 

So I wrote a script to regularly download their ics file, add reminders for each event with a bash / awk script, and save the ics. **This** ics file gets update every month or so and needs to be changed with the current (or: then previous) ics file. I don't know how often they provide new files, so I was going to just do this every 2 weeks. If I created a new calendar each time I do this, I'd have overlapping events (because the "current" calendar would include some of the same events the "new" calendar would include as well).

So I was hoping I could just set up this calendar in radicale, find out where the ics file is located, and overwrite that ics file each time my script has generated a new version of this file. Sync should still work because the file would be in the same location. I only need to read this file, no connected device needs to have write access to it.

Can this be achieved with radicale, if so, how? Thanks in advance for your help :)

**Comment by jonassmedegaard** [comment]
Quoting prankousky (2019-05-11 15:02:29)
> Is it possible to provide an existing `.ics` file to `radicale`, then 
> have other devices sync this file; **and** change that `.ics` file so 
> that these changes will be synced to all connected devices?
[...]
> So I wrote a script to regularly download their ics file, add 
> reminders for each event with a bash / awk script, and save the ics. 
> **This** ics file gets update every month or so and needs to be 
> changed with the current (or: then previous) ics file. I don't know 
> how often they provide new files, so I was going to just do this every 
> 2 weeks. If I created a new calendar each time I do this, I'd have 
> overlapping events (because the "current" calendar would include some 
> of the same events the "new" calendar would include as well).
> 
> So I was hoping I could just set up this calendar in radicale, find 
> out where the ics file is located, and overwrite that ics file each 
> time my script has generated a new version of this file. Sync should 
> still work because the file would be in the same location. I only need 
> to read this file, no connected device needs to have write access to 
> it.
> 
> Can this be achieved with radicale, if so, how? Thanks in advance for 
> your help :)

I wouln't and mess with the Radicale backend storage directly: Even if 
it seems to be iCalendar files, there is caching files and other 
machinery going on.

Instead talk to Radicale:

  * Create a calendar e.g. with DAVx5
  * fetch the trash .ics file e.g. with cURL from cron
  * push it to your calendar e.g. with cURL from cron
  * Add alarms to the calendar e.g. with DAVx5
  * fetch the calendar as a .ics file e.g. with cURL from cron
  * publish your .ics file as static file e.g. with apache2

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by prankousky** [comment]
Thank you. I just realized thanks to your approach that I was totally overthinking this.

I have a local nginx server. The ics file can go there, constantly be overwritten and also subscribed to via nextcloud directly. This file has my reminders and everything works. Yay :+1:
