### ISSUE TITLE
Question: simple addressbook server recommendations

### ISSUE THREAD

**Issue by gitvb** [Kozea/Radicale#953]
Hi,
I was using radicale 1.1 version quite happily. It suited my humble needs.
All I needed to do is keep my address book in a single file and share access
to it from different hosts on my small local network and a limited set of clients
on different operating systems. Recently, I've decided to move on and upgrade.
It turned out that the upgraded OS only supports radicale 2.0 which is completely
incompatible with 1.x version. I can't even use the same URL for my address book.
IIUC, the older version will be completely deprecated and forgotten soon since it
uses python2. I'd like to keep it small and simple. With version 2.0 my address book
becomes scattered in numerous files with growing cache and tmp directories created
in the collection path, so that a 200kB file has turned into a bunch of folders of 8MB
total size. This looks like an overkill to me. I thought one of goals of the radicale project
was to keep it as simple as possible. If I needed something more complicated I'd probably
use  Davical or Baïkal.

Is it possible to implement optional backward compatibility? Otherwise, I think I'll need to find
an alternative solution. What would you recommend?

Thanks,
V.

**Comment by dgtlmoon** [comment]
`upgraded OS`  which "OS" are you talking about? can you explain the connection clearly between the OS and the radicale version? you mean radicale changed their protocol? or?

**Comment by gitvb** [comment]
Radicale is included in many Linux distributions. Thus, the latest ones provide radicale 2.xx that is incompatible with radicale 1.xx which I used to have on my older Linux distribution.

My problem is that I need to share a rather small address book between a number of e-mail clients I use.

Radicale 1.xx was almost perfect for that. With version 2.xx, everything has changed. I can't even use the same address book url. Besides, my collection folder used to contain a single 200kB vcf file.
Now it's is split onto hundreds of single-contact vcf files, with ever-growing cache, history and other temporary junk hanging around in the same collection folder. So 200kB has turned into 8MB.
I think it's an overkill really.

IIUC, radicale 1.xx is not supported anymore.
My question is: are there any simple alternatives to radicale v2.xx, or is there any way to add v1.xx compatibility to v2.xx?

Thanks,
V.

**Comment by pbiering** [comment]
Meanwhile, 2.x is also EOL, but one can setup 2 servers in parallel and use a DAV client to copy or move items from old to new server.
