### ISSUE TITLE
Periodically import from ics file

### ISSUE THREAD

**Issue by novoid** [Kozea/Radicale#955]
Hi,

Can you tell me if radicale is able to support me with my requirement?
I'm using Emacs Org mode to manage my calendar. I export my agenda via daily cron job to an ics file. How may I update (overwrite) a radicale calendar with the content of this ics file?

I think I'd need to flush the old content of the calendar and re-import the ics file somehow so that I get updated entries only once.

Do you have any tips for me here? I'd prefer not to depend on any GUI client to do it manually or semi-automatically.

Thanks!

**Comment by return42** [comment]
I do not have a solution for you, but I want to wrap some similar issues #925 #806 #750 
Some of them use curl and some of them had problems with curl .. may you find a solution that way?

**Comment by Unrud** [comment]
```bash
curl -u user -X PUT 'http://localhost:5232/user/calendar' --data-binary @calendar.ics
```
