### ISSUE TITLE
Does Radicale support repeating / recurrent events?

### ISSUE THREAD

**Issue by jmfoleyjr** [Kozea/Radicale#958]
Before converting all locally owned calendars to Radicale, I need feedback on an important question. Does radicale support recurring events, and in what way? Recurring events are mentioned in https://radicale.org/news for releases 2.1.4, 2.1.0 and 0.7, the latter being the first  explicit reference to repeating events. 

If a calendar with recurring events is served by radicale and there is no specific owner of the calendar (read/write by all), how does the recurring event work? I've always assumed that the calendar owner's calendar client (e.g. Lightning) handled updating recurring events. If that's true, how does this work without an owner?

**Comment by partofthething** [comment]
Unofficially, I'm using radicale with lots of recurring events and it works fine. You specify the recurrence in the event and it shows up at the interval on your calendars

**Comment by jmfoleyjr** [comment]
Thanks for the feedback and reassurance. So far no issues on this end, but I've been running radicale live for less than a week. I'll leave this open a bit longer to give users a chance to verify their recurring events are behaving.

**Comment by PeterNerlich** [comment]
@jmfoleyjr bump. It's been a while, and I'm interested in your conclusion. I'm suspecting recurring events don't work well in my current setup, but it's well possible that it's just my client screwing up

**Comment by dradux** [comment]
@PeterNerlich, I've been using radicale for 6+ months with no issues with recurring events. I have an android phone using DAVx5 to sync the stock calendar with radicale and also the Lightning extension for Thunderbird. I just tested by creating a repeating event on my phone and it synced to my calendar in Thunderbird.
In regards to ownership - I've not looked at the code but the calendar would have to be 'owned' by someone - even it is is a shared account. I'd guess that if you have access to read/write to that account then you could edit it.

**Comment by jmfoleyjr** [comment]
PeterNerlich: Yes, recurring events work fine. I've been using radicale for many months with Windows 7 and 10, Outlook 2010 and 365 and Thunderbird on Windows and Linux. No problem with this.
