### ISSUE TITLE
Slashes in UIDs break Radicale

### ISSUE THREAD

**Issue by tasn** [Kozea/Radicale#962]
In a sense, it's a revival of #262. The problem is that Radicale uses path functions to get the parent_item of the current item being discovered.
Example: https://github.com/Kozea/Radicale/blob/master/radicale/app/put.py#L49

To be honest, I'd expect Thunderbird to have to urlescape that, but like it or not, this is still the reality we have to deal with here.

One possible solution is have Radicale call a function from the storage backend to get the parent of the item, rather than just assume dirname suffices. As the storage backend is aware of the hierarchy.

Note: I'm using a custom storage backend, so maybe it doesn't get triggered in the default filesystem one. Though that would be because of luck rather than design.

**Comment by tasn** [comment]
In particular, the "is_safe_path_component" function seems to be very specific to the filesystem storage backend, rather than applies to all of the backends. Or at the very least the part checking if "/" is in the path at all.

**Comment by pbiering** [comment]
can this be replicated with latest version 3.1.x?

**Comment by pbiering** [comment]
please reopen if reproducable with current version
