### ISSUE TITLE
Login not possible when running Radicle behind Apache

### ISSUE THREAD

**Issue by null0x** [Kozea/Radicale#966]
Hello together,

I successfully installed Radicale. If I run "sudo radicale" the calendar server is started according the /etc/radicale/config file and everything works fine. The "sudo radicale" command basically runs the script /usr/local/bin/radicale which looks like this
```

#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from radicale.__main__ import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```

However, I'd like to run Radicale behind an Apache server. At first glance my configuration seems to work:

**/etc/apache2/sites-enabled/radicale**
```
<VirtualHost *:80>
    ServerName my-calender.mydomain.com

    WSGIDaemonProcess radicale user=www-data group=www-data threads=1
    WSGIScriptAlias / /var/www/radicale.wsgi

    <Directory /var/www>
        WSGIProcessGroup radicale
        WSGIApplicationGroup %{GLOBAL}
        AllowOverride None
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>
```

**/var/www/radicale.wsgi**
```
from radicale import Application, config, log
config_paths = ["/etc/radicale/config"]
configuration = config.load(config_paths, ignore_missing_paths=False)
filename = os.path.expanduser(configuration.get("logging", "config"))
debug = configuration.getboolean("logging", "debug")
logger = log.start("radicale", filename, debug)
application = Application(configuration, logger)
```

Once I start the apache2 server, the Radicale webpage is accessible. However, I cannot login. I keep getting a **"Error: 401 Unauthorized"**. No matter what username and what password I type in, the access is always denied. I have no access to already existing calenders via Thunderbird Lightning. Once I stop the apache2 and run again the above script "sudo radicale" which starts a server without apache, everything works fine.

Does anyone know how to solve this problem? I want to use Radicale behind Apache, but after many wasted hours, I have no ideas anymore.This is my config file:

**/etc/radicale/config**
```
[server]
hosts = 192.168.1.0:80
max_connections = 20
max_content_length = 10000000
timeout = 10
[encoding]
[auth]
type = None
[rights]
type = None
[storage]
filesystem_folder = /var/lib/radicale/collections
[logging]
[headers]
```

I am working with python 3.5.3 and all Radicale files are owned by www-data.

**Comment by return42** [comment]
> Once I stop the apache2 and run again the above script "sudo radicale" which starts a server without apache, everything works fine.

This mostly indicates some missing rights for the www-data user.  Please double check acces rights of you collections folder:

    [storage]
    filesystem_folder = /var/lib/radicale/collections

**Comment by null0x** [comment]
I granted all necessary rights to /var/lib/radicale/collections. Just to be on the safe side, I have just run recursively sudo chmod 777 on /var/lib/radicale. No change! Any further suggestions?

**Comment by null0x** [comment]
After many hours  of debugging I have just found the solution which I'd like to share with you. Apparently, some Apache server strip the HTTP_AUTHENTICATION field from the header. In case this field is missing, Radicale returns a 403 even if authentication is disabled. I am using Apache/2.4.25 (Debian).

You can fix this by forcing Apache to not strip the authentication field. Just add this line into your configuration file (e.g. in /etc/apache2/sites-available/radicale.conf).

`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

Have fun!

**Comment by return42** [comment]
@null0x thanks for sharing your experience .. very strange for me, I have a similar setup (behind apache) and I don't need to set `HTTP_AUTHORIZATION` even if I enable authentication.

If the problem is solved for you, can you please close this issue / thanks a lot!

**Comment by null0x** [comment]
As far as I understood only some Apache versions strip off the `HTTP_AUTHORIZATION` field in case it is not needed. This is why this problem does not always occur.

**Comment by return42** [comment]
> only some Apache versions strip off the HTTP_AUTHORIZATION

I guess it depends on how the Linux distributor sets up a apache installation, I'am using ubuntu (where the [debian setup is used](https://github.com/dcmorton/apache24-ubuntu/blob/master/debian/apache2.README.Debian) ).

Which distro do you use?

**Comment by null0x** [comment]
I am using Debian GNU/Linux 9 (stretch)

**Comment by return42** [comment]
Hm, strange .. thanks for your information!

**Comment by tomwright01** [comment]
> As far as I understood only some Apache versions strip off the `HTTP_AUTHORIZATION` field in case it is not needed. This is why this problem does not always occur.

Same problem for me on debian bullseye.

**Comment by pbiering** [comment]
For WSGI related reverse proxy configuration one has to configure `WSGIPassAuthorization On`
see also example configuration https://github.com/Kozea/Radicale/blob/master/contrib/apache/radicale.conf
