### ISSUE TITLE
 Radicale fails when uploading a photo in a vcard

### ISSUE THREAD

**Issue by DenisVS** [Kozea/Radicale#969]
This is not the same issue as a "Radicale fails when uploading a photo in a vcard #721" ( https://github.com/Kozea/Radicale/issues/721 ).
My problem is that the log shows the correct upload:
```
REV:20190715T121113Z
PHOTO:DATA:IMAGE/JPEG;BASE64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAw MEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGB
...
<Long photo data here, 32.1 KB>
...
 cquhTyQkgFt9sGR4ck/wDTNitFFbVHaokvIuOx6Hqd5JpcTzTXU0MTAySYVSu5y3OepwA54/vi
vGlu7j4m+NDBCxj0pJNzMQQCFzgc+uDRRRVk42S6iR63o0+m+KrpNKs5X+zyHy5JBGQFiUe46c
 Vcu0SbWJLlLnzvsbiO2hwNkbFcIDj+6pOPdhRRV05OabZLRg/2/F/zzvv+/if40UUVY7I//9k=
X-RADICALE-NAME:3869aabc-57d4-4ddc-8f8e-cd92ecc88a90.vcf
END:VCARD

2019-07-15 12:11:26,927 - [806439000] INFO: PUT response status for '/username/contd92ecc88a90.vcf' in 0.078 seconds: 201 Created
```
But inside the vcf file I found that:
```
UID:3869aabc-57d4-4ddc-8f8e-cd92ecc88a90
FN:<name here>
N:<name here>;;;
PHOTO:DATA:IMAGE/JPEG\;BASE64
REV:20190715T121113Z
TEL;PREF=1:<phone here>
```
i.e. empty photo data, but head only.

**Comment by Tntdruid** [comment]
Works for me on iOS and eM Client.

**Comment by tasn** [comment]
Radicale and vObject (the vCard library radicale uses) both don't support vCard 4.0. The PHOTO field looks like a v4.0 one which is why it's failing most likely.

Relevant vObject issue: https://github.com/eventable/vobject/issues/106

**Comment by pbiering** [comment]
closed here, still open in _vobject_
