### ISSUE TITLE
radicale exits every night, no error message

### ISSUE THREAD

**Issue by lewoberst** [Kozea/Radicale#975]
I used to run an old version of radicale 1 and switched to the current version this week. Now I'm running radicale 2.1.11 on Debian, packaged version. Since upgrading, radicale stops every night without any obvious reason. I have debug logging with timestamps enabled, however, the last log line today is:

```
2019-07-26 04:36:37,802 18056/140496800528128 INFO __init__.py:response:387 PROPFIND response status for '/nadine/privat/' with depth '0' in 0.226 seconds: 207 Multi-Status
```

The server is no longer running:
```
# systemctl status --no-pager radicale
● radicale.service - LSB: Radicale CalDAV and CardDAV server
   Loaded: loaded (/etc/init.d/radicale; generated; vendor preset: enabled)
   Active: active (exited) since Thu 2019-07-25 10:36:09 CEST; 23h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 18023 ExecStop=/etc/init.d/radicale stop (code=exited, status=0/SUCCESS)
  Process: 18029 ExecStart=/etc/init.d/radicale start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/radicale.service
```

I had the same experience the last days at similar points in time:

```
2019-07-24 04:33:22,099 11379/140209479329536 INFO __init__.py:response:387 PROPFIND response status for '/nadine/privat/' with depth '0' in 0.231 seconds: 207 Multi-Status
2019-07-25 04:36:07,554 8914/140418361247488 INFO __init__.py:response:387 PROPFIND response status for '/n+j/wir/' with depth '0' in 0.323 seconds: 207 Multi-Status
```

So there is something syncing at that time. The calendar accessed before the server dies is different in each request. `journalctl` has no messages for radicale.

I tried to set `ulimit -c unlimited`, but radicale changes its cwd to `/` and the radicale user cannot write there, so I don't know whether a core dump would have been generated.

I'm no python expert. Please advise how to debug this further.

Side issue: What makes this problem even more annoying is that automatic restart is prevented by radicale's pid check, although `[server] pid` setting is unset:

```
2019-07-24 11:31:37,082 7936/140706823153408 ERROR __main__.py:run:141 An exception occurred during server startup: PID file exists: '/run/radicale/radicale.pid
'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/radicale/__main__.py", line 153, in daemonize
    pid_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
FileExistsError: [Errno 17] File exists: '/run/radicale/radicale.pid'
```

Currently I'm removing the pid file by hand and have systemd restart radicale as a workaround.

**Comment by ilakast** [comment]
I have the exact same issue
`2019-12-26 04:15:14,594 - [b47ff460] INFO: PROPFIND response status for '/ilakast/832252a4-1dd7-3084-e7b1-4a2cbf3a32e0/' with depth '0' in 1.756 seconds: 207 Multi-Status
2019-12-26 05:00:05,239 - [b6bc78e0] INFO: Stopping Radicale`

It happened on two consecutive days at exactly the same time (5am)

This is on radicale 2.1.11-6 on Raspbian 10 buster

**Comment by jonassmedegaard** [comment]
Quoting ilakast (2019-12-26 12:12:51)
> I have the exact same issue
> `2019-12-26 04:15:14,594 - [b47ff460] INFO: PROPFIND response status for '/ilakast/832252a4-1dd7-3084-e7b1-4a2cbf3a32e0/' with depth '0' in 1.756 seconds: 207 Multi-Status
> 2019-12-26 05:00:05,239 - [b6bc78e0] INFO: Stopping Radicale`
> 
> It happened on two consecutive days at exactly the same time (5am)
> 
> This is on radicale 2.1.11-6 on Raspbian 10 buster

I suggest you check which cron jobs run at that time.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by ilakast** [comment]
> I suggest you check which cron jobs run at that time. - Jonas

You were absolutely right (and I was being thick). I forgot I used to restart the system when I was using motion as a security camera... Problem fixed for me but I guess the OP still has a similar problem.
