### ISSUE TITLE
Trouble setting up  - documentation

### ISSUE THREAD

**Issue by Isaacson33** [Kozea/Radicale#980]
Following the documentation instructions for setting up on Linux as a user. I've copied exactly the instructions so far, but when it comes to

`$ systemctl --user enable radicale`

I just get
`Failed to enable unit: Unit file ~/.config/systemd/user/default.target.wants/radicale.service does not exist.`

What is missing?

**Comment by return42** [comment]
Sorry, I do not have wide experience with systemd's user units. Do you have sudo access / did you tried a systemd system-wide installation?

**Comment by return42** [comment]
Lets close, opener lost interest.
