### ISSUE TITLE
Rights "alias"

### ISSUE THREAD

**Issue by 10RUPTiV** [Kozea/Radicale#981]
Hi,

In the documentation we have an example on how to share something like

[alice-family-access]
user = alice
collection = bob(/.*family.*)?
permission = rw

But in real life, we need to use the UID of the "family" collection.

Am I missing something in the config so I can use the "Title" of the collection in my rights ?

**Comment by sents** [comment]
I modified the rights class to do just that:
https://github.com/sents/radicale-rights-fromfile2.
You use it with following radicale configuration:
```
[rights]
type = radicale_rights_fromfile2
file = /path/to/your/rights/file
```
The rights configuration file could then look as such:
```
[read-public-collection]
user = .+
displayname = ^public.+$
collection = .*
permission = r
```
The matching for displayname works the same as with collection.

**Comment by pbiering** [comment]
closed because of inactivity, btw. collection directory can be renamed on server storage side on OS level from UUID to a more friendly name
