### ISSUE TITLE
VEVENT components cannot contain both DTEND and DURATION

### ISSUE THREAD

**Issue by fleather** [Kozea/Radicale#985]
Hi,

when I try to move an item of an recurring event, Thunderbird says 

MODIFICATION_FAILED
Status-Code: 2147500037
Server Replied with 400

In server log I can read: 

Failed to store item '1900403a-2eb3-4e70-accb-01a525dfbe55.ics' in collection 'floyd/regelm': 'VEVENT components cannot contain both DTEND and DURATION                     components'

I checked this item, there is not both an DTEND and DURATION - only DTEND...

Can I provide more information?

Kind regards,
Stefan

**Comment by jmfoleyjr** [comment]
I just had this same issue. I tried to modify a recurring event to edit "this occurance only" in Thunderbird. I got the following error in the Radicale log file:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/radicale/__init__.py", line 948, in do_PUT
    new_item = parent_item.upload(href, items[0])
  File "/usr/lib64/python3.7/site-packages/radicale/storage.py", line 1487, in upload
    (href, self.path, e)) from e
ValueError: Failed to store item '8a143894-5fe6-4123-b157-e1fbb62417fe.ics' in collection 'mfoley/7cdd63ff-651d-ddf5-1be6-88578e710000': 'VEVENT components cannot contain both DTEND and DURATION                     components'
[7f88fa602700] DEBUG: Response content:
Bad Request
[7f88fa602700] INFO: PUT response status for '/mfoley/7cdd63ff-651d-ddf5-1be6-88578e710000/8a143894-5fe6-4123-b157-e1fbb62417fe.ics' in 0.058 seconds: 400 Bad Request

```
The event causing the problem is:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
BEGIN:VTIMEZONE
TZID:America/New_York
BEGIN:STANDARD
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZNAME:EST
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:8a143894-5fe6-4123-b157-e1fbb62417fe
DTSTART;TZID=America/New_York:20190717T140000
DTEND;TZID=America/New_York:20190717T163000
CREATED:20190711T140641Z
DTSTAMP:20191023T201822Z
EXDATE:20190828T180000Z
EXDATE:20190731T180000Z
EXDATE:20190814T180000Z
EXDATE:20190925T180000Z
EXDATE:20200101T190000Z
EXDATE:20200909T180000Z
EXDATE:20201230T190000Z
EXDATE:20191218T190000Z
EXDATE:20191009T180000Z
EXDATE:20191023T180000Z
EXDATE:20191106T190000Z
EXDATE:20191204T190000Z
LAST-MODIFIED:20191023T201822Z
RRULE:FREQ=WEEKLY;INTERVAL=2
SEQUENCE:12
SUMMARY:Renee- early day
TRANSP:OPAQUE
X-MOZ-GENERATION:13
END:VEVENT
BEGIN:VEVENT
UID:8a143894-5fe6-4123-b157-e1fbb62417fe
RECURRENCE-ID;TZID=America/New_York:20200701T140000
DTSTART;TZID=America/New_York:20200701T140000
DTEND;TZID=America/New_York:20200701T163000
CREATED:20190904T152851Z
DTSTAMP:20190904T153000Z
LAST-MODIFIED:20190904T153000Z
SEQUENCE:6
SUMMARY:Renee- early day
TRANSP:OPAQUE
X-LIC-ERROR:No value for LOCATION property. Removing entire property:
X-MOZ-GENERATION:6
END:VEVENT
END:VCALENDAR

```I find no actual DURATION component.

**Comment by fleather** [comment]
I dug deeper on this problem, because I was desperate for a solution.

**Summary:**
Thunderbird/Lightning causes the problem: When updating a single item of a recurring event (editing, or in my case moving), actually a new event gets created, because it is extracted from the "parent" recurring event. Unfortunately Thunderbird creates an invalid event object with both DURATION and DTEND information. This object gets validated by the VObject library that radicale uses (https://github.com/eventable/vobject/blob/master/vobject/icalendar.py)

I made a dirty hack in my local setup, where the duration is kicked out of the object in this case, and it works.

**Comment by jonassmedegaard** [comment]
Quoting fleather (2020-01-05 04:11:13)
> Thunderbird/Lightning causes the problem: When updating a single item 
> of a recurring event (editing, or in my case moving), actually a new 
> event gets created, because it is extracted from the "parent" 
> recurring event. Unfortunately Thunderbird creates an invalid event 
> object with both DURATION and DTEND information. This object gets 
> validated by the VObject library that radicale uses 
> (https://github.com/eventable/vobject/blob/master/vobject/icalendar.py)
> 
> I made a dirty hack in my local setup, where the duration is kicked 
> out of the object in this case, and it works.

Would be nice if you could how you did your local hack.

Also, cool if you report the bug upstream to Thunderbird/Lightning.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by fleather** [comment]
HACK:

Edit the file "icalendar.py". Location in my setup is "/usr/local/lib/python3.6/dist-packages/vobject/icalendar.py"

Search for the error string: "VEVENT components cannot contain both DTEND and DURATION". This leads to the following code segment:

```
    @classmethod
    def validate(cls, obj, raiseException, *args):

        if 'dtend' in obj.contents and 'duration' in obj.contents:
            if raiseException:
                m = "VEVENT components cannot contain both DTEND and DURATION\
                     components"
                raise ValidateError(m)
            return False
        else:
            return super(VEvent, cls).validate(obj, raiseException, *args)

```

Adapt it to the following (just insert the two new lines between the HACK comments):

```
    @classmethod
    def validate(cls, obj, raiseException, *args):

        # HACK
        # HACK
        # HACK
        if 'dtend' in obj.contents and 'duration' in obj.contents:
            del obj.contents['duration']
        # HACK
        # HACK
        # HACK

        if 'dtend' in obj.contents and 'duration' in obj.contents:
            if raiseException:
                m = "VEVENT components cannot contain both DTEND and DURATION\
                     components"
                raise ValidateError(m)
            return False
        else:
            return super(VEvent, cls).validate(obj, raiseException, *args)

```

That does the trick for me... ugly, but works. Don't hesitate to ask in case of further questions!

**Comment by fleather** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1611544
