### ISSUE TITLE
Radicale 2 with Mac Os mojave calendar client - not working

### ISSUE THREAD

**Issue by EdG91** [Kozea/Radicale#986]
Hello,
May someone help me to configure radicale 2 with a Mac OS calendar client ?
The Mac Os version is Mojave, with calendar 11

I set a reverse proxy https between Mac OS client and radical server ; it works with windows lightning thunderbird, but this is not working with Mac OS.
In Mac OS, it says that it cannot send login/password or connect to the radicale server...

Maybe I do not know how to configure the Mac OS client properly.

I set a advanced Caldav account in Mac OS client.
Does someone have an example of configuration which works with radicale server ?

Best Regards

**Comment by Tntdruid** [comment]
Using https whit a real ssl certifikat?

**Comment by EdG91** [comment]
Hello,
Yes, my certificate is from digicert

But I think this is a configuration issue, and I cannot find a example of configuration for Mac OS.

**Comment by EdG91** [comment]
Or maybe it is in the apache reverse proxy config ?
I set 
  <Location "/radicale/">
    ProxyPass http://myradicale.mydomain.com:5232/
    ProxyPassReverse http://myradicale.mydomain.com:5232/
    RequestHeader    set X-Script-Name /radicale/
  </Location>
in the apache reverse config

It works with thunderbird/lightning <----> Reverse Proxy <-----> radicale server
But it does not work with :
mac os Calendar <----> Reverse Proxy <-----> radicale server

**Comment by EdG91** [comment]
Does I need to set authentication  especially for mac os (in addition to set the reverse proxy) ?
It is mentionned in documentation https://radicale.org/setup/ : 
"Authentication
In its default configuration Radicale doesn’t check user names or passwords. If the server is reachable over a network, you should change this."
Set a users file ?

I only create local linux accounts to create the shared calendars...
And started the radicale server with command :+1: 
python3.6 -m radicale --config "" --server-hosts 0.0.0.0:5232 --storage-filesystem-folder=/var/lib/radicale/collections

**Comment by return42** [comment]
What dies the LOG say?  How did you setup the Mac-Client-Calendar?

We already had a lot of Mac problems discussed here in the issue tracker here. Did you grabbed our radicale issues? E.g take a look at https://github.com/Kozea/Radicale/issues/954#issuecomment-497425243 (verify your path setting in Mac-Calender).

More to read

- SSL https://github.com/Kozea/Radicale/issues/879#issuecomment-436253411 and #945
- Cert #893
- iOS Client: #786 and https://github.com/Kozea/Radicale/issues/870#issuecomment-458397475)

If you understand German, I recommend also http://return42.github.io/handsOn/radicale/ 

If you have more details come back.

**Comment by EdG91** [comment]
Hello,
Thank you for your help.
After many tries... I finally use a virtual box machine with Mac Os to perform tests.
I works like a charm with my proxy server on the virtual machine Mac OS...
But It was not on the real machine Mac OS...

So I started to look forward differences between the 2 ... And ...
The issue on real mac os machine was due to the mac os firewall enable !
I stopped the firewall, and It works now.

So maybe a line on documentation could be added about firewall for Mac Os client, and how to add an exception for radicale in this firewall.

Best regards

**Comment by return42** [comment]
> So I started to look forward differences between the 2 ... And ...
> The issue on real mac os machine was due to the mac os firewall enable !
> I stopped the firewall, and It works now.

Thanks a lot for sharing your solution! .. if it is solved for you, can you please close this issue / Thanks!
