### ISSUE TITLE
CardDAV stopped syncing (404)

### ISSUE THREAD

**Issue by MrksHfmn** [Kozea/Radicale#989]
Unfortunately, the address book synchronization has given up and I can't really understand why. All sync adapters (Cardbook, TbSync) except the iPhone fail. In the error message I also find a 404 entry but no hint what exactly is broken. I am using Radicale behind a nginx reverse proxy on a subdomain.

**This works:**
Sync appointments
Sync contacts via iPhone
Weblogin + create new calendars / address books

**Logs:**
- [Radicale Debug startup + one failed sync with Thunderbird](https://pastebin.com/ThWenASG)
- [NGINX Reverse Proxy](https://pastebin.com/eD4mZApn)

**Comment by Waringham** [comment]
It seems I have the same problem (But I don't get a 404). I have the cardbook plugin and/or new version of Thunderbird in suspicion. The sync from my iPhone even works. Could it be?

Maybe you should try an old Thunderbird version before 68.0 with the old cardbook plugin.

**Comment by MrksHfmn** [comment]
I tracked it down. It‘s no radicale error. Sorry for that. Thunderbird 68 and/or cardbook have broken the sync feature. Thunderbird 60 with the old cardbook plugin works. But once synced with the new combination you can‘t go back to the old thunderbird and cardbook. Something’s completely messed up here

**Comment by return42** [comment]
> Something’s completely messed up here

https://gitlab.com/CardBook/CardBook/issues/680

**Comment by return42** [comment]
@MrksHfmn if it is OK for you, please close the issue / thanks!
