### ISSUE TITLE
Installation of Radicale on Raspberry Pi 2 with Raspbian Buster Lite does not work

### ISSUE THREAD

**Issue by hubi96** [Kozea/Radicale#990]
Hi,

I had to do a new full installation of the tools for my raspi. I used radicale before and was very happy with it. Now I tried to install radicale twice - the second try was a total new installation of raspbian buster (latest build = July 2019) for verification of my problem. I used an apt-get update / apt-get upgrade, then the following steps:

sudo apt-get install python3-pip
python3 -m pip install --upgrade radicale
(Successfully installed python-dateutil-2.8.0 radicale-2.1.11 vobject-0.9.6.1)
python3 -m radicale --config "" --storage-filesystem-folder=~/.var/lib/radicale/collections

After that there was no answer from the command. I was only able to stop it via control-C.
What can I do now?

**Comment by Tntdruid** [comment]
You can use apt install radicale too

**Comment by hubi96** [comment]
Thanks, my fault. It was to long ago that I setup my server the last time.
Just remembered that it was handled differntly... :-(
