### ISSUE TITLE
Documentation: One way sync

### ISSUE THREAD

**Issue by ShalokShalom** [Kozea/Radicale#992]
Hi there :)

I am using KAddressbook to create my contacts and davx5 on Android to consume them.

Can I use KAddressbook -> Radical -> davx5 in a one way form, simply by copying the dav's from KAddressbooks folder into the Radical one?

**Comment by ShalokShalom** [comment]
Or simply by setting [storage] filesystem_folder to that one of KAddressbook?

**Comment by pbiering** [comment]
Collection sttorage filesystem is unique to _Radicale_ and cannot be shared with other applications. But one can copy or sync ICS or VCF files from one to another solution.
