### ISSUE TITLE
User-friendly URLs

### ISSUE THREAD

**Issue by tcdaly** [Kozea/Radicale#996]
Using Radicale's own internal webserver, is there any way of changing the default URL of an address book or calendar to something more user-friendly (i.e. shorter, without a UUID at the end of the URL)?

**Comment by KoMa1978** [comment]
I have just a single addressbook and I moved the directory UUID/ to addressbook/.

Now I can access the addressbook via https://server.lan.internal/radicale/USERNAME/addressbook/

Works fine ...

**Comment by tcdaly** [comment]
Thank you!
