### ISSUE TITLE
Future of Radicale?

### ISSUE THREAD

**Issue by return42** [Kozea/Radicale#997]
Is Radicale dead or what is the planned future?

**Comment by Tntdruid** [comment]
Looks dead to me 🧐

**Comment by return42** [comment]
Should we consider to fork?

**Comment by xoxys** [comment]
@return42 Has anybody tried to contact someone from kozea.fr or @Unrud? Maybe they can add some more maintainers from the community to continue. 

If there will be no reaction, I would also suggest creating a new organization and fork. But publishing packages (e.g. to PyPi) will not that easy in this case. Anyway, I would also like to help and work together on radicale.

**Comment by xoxys** [comment]
I've tried to contact someone on [ICR](irc://chat.freenode.net/%23%23kozea). Let's see

**Comment by return42** [comment]
@xoxys Thanks for your effort. To be clear: I really prefer to continue the work under the kozea hood.  They have made a great work for a very long time. Hope you get some feedback.

**Comment by liZe** [comment]
Long time no see.

If someone is interested to become the new maintainer, just ask, I'll give you the admin rights here and on PyPI.

Maintaining packages is hard but can be very rewarding. The hard part is not the code, the hard part is to keep the desire to triage issues, talk with angry bug reporters, and take good decisions to help Radicale becoming better and better … for years :wink:.

**Comment by xoxys** [comment]
@liZe Thanks for your feedback. I would suggest to add up to 5 core maintainers like some other projects e.g. gitea did. Doing it this way design decisions, reviews, development, issue und PR management and all the hard parts will be teamwork and don't depend on a single person. I would be happy to be a part of this team.

**Comment by liZe** [comment]
> I would suggest to add up to 5 core maintainers like some other projects e.g. gitea did. Doing it this way design decisions, reviews, development, issue und PR management and all the hard parts will be teamwork and don't depend on a single person.

:heart:

> I would be happy to be a part of this team.

Cool!

Is anyone else interested?

**Comment by xoxys** [comment]
Lets see :) https://social.tchncs.de/@xoxys/103086424979024311

**Comment by matthinc** [comment]
If you're still searching I would be happy to help.
I hope it does not bother that I'm still a CS student (but with 3+ years of working experience).

I'm using Radicale for more than a year now and I am very happy with it. It would be a shame if this project would die because of the lack of maintainers.

**Comment by xoxys** [comment]
@matthinc would be cool. Can we have a chat or something like this? 

@liZe sadly not really much response... Can you add @matthinc and me to the GH repo and pypi?

**Comment by matthinc** [comment]
@xoxys Sure - do you have an IRC or something like that?

**Comment by xoxys** [comment]
@matthinc https://geeklabor.de/contact/ :) but you can also send me an invite to something else if you like

**Comment by jaesivsm** [comment]
Same, if you're still searching I'm also interested. 
I'm running my Radicale from some time. I've got a good experience with python (it's my job eh) but sadly I'm very poor on CalDAV / CardDAV protocol knownledge. 

Still would be happy to contribute !

I'm jaes on freenode if you need to reach out (also [ways to contact me](https://1pxsolidblack.pl/pages/about.html))

**Comment by felixfontein** [comment]
How about having a channel on Freenode for Radicale? I don't know much about CalDAV and CardDAV either, but I have some Python knowledge and am using Radicale since a few years.

**Comment by 532910** [comment]
https://radicale.org/contribute/

**Comment by matthinc** [comment]
I Created a Slack-Group as an alternative to IRC some days ago:
https://join.slack.com/t/radicale-dev/shared_invite/enQtODUxOTM2MTI5NTg5LTk3ODAxYjBiZDNhNTYxZGVlODFlNmQ0NTE0ZDVjYjIwNDJhNjNjODFmMTM3OWJhNDVkMjU0OWU4MWI3ZDA1YTQ

IMO Slack is great for managing team conversations. Feel free to join!

**Comment by return42** [comment]
If you're still searching I'm also interested.  IMO radicale needs some leading, especially the master branch but I haven't enough time and knowledge in DAV to fill such a leading position. What I can do is prope and merge PRs .. and closing obsolete issues ;)

**Comment by craftyguy** [comment]
Perhaps there should be a screening process for adding maintainers... 

Randos on the internet cannot be trusted to take over your project. Here's a refresher: 
https://www.theregister.co.uk/2018/11/26/npm_repo_bitcoin_stealer/

**Comment by return42** [comment]
> Perhaps there should be a screening process for adding maintainers...

And who is the instance of truth ..I'am "return42" and you are "craftguy", why should someone trust us? IMO we have to check commits, especially those modifying the required modules.  But who checks the required modules of the required modules .. Anyway, your are right to be carefull.

**Comment by craftyguy** [comment]
Well other projects tend to trust folks who show a good history of submitting patches, working with users that have problems and, you know, generally participating more than just submitting a single ticket that basically says "you can trust me! I promise! :smile:"

**Comment by daks** [comment]
> Well other projects tend to trust folks who show a good history of submitting patches, working with users that have problems and, you know, generally participating more than just submitting a single ticket that basically says "you can trust me! I promise! smile"

I think it's a good way to find maintainers, to ensure quality and trust.

**Comment by xoxys** [comment]
Over weeks nobody raised bis hand to help and now everyone has to say something about trust and how it should work? Fine for me, I'm out

**Comment by felixfontein** [comment]
It's unfortunate IMO that the discussion here ended this way. I can understand most arguments here (doesn't mean I agree with them), but there's one point I do not understand at all. I wrote the following comment:

> How about having a channel on Freenode for Radicale? I don't know much about CalDAV and CardDAV either, but I have some Python knowledge and am using Radicale since a few years.

@craftyguy since you explicitly downvoted this: why don't you like the idea that there should not be a Freenode IRC channel for Radicale? IMO having such a channel to discuss issues and PRs (and other stuff) would really help the project, especially since there's no active maintenance right now. Also, it's a way of helping out and learning to know each other without having to commit too much time.

**Comment by craftyguy** [comment]
@felixfontein I didn't downvote on the basis of 'having an IRC channel for radicale'.. I think that's an excellent idea, a far better one that using Slack or some other proprietary bullshit. The downvotes are for ideas of giving power to push to folks who ask for it, but haven't demonstrated that they can be trusted yet.

**Comment by felixfontein** [comment]
Anyway, I registered ##radicale on Freenode, so if anyone wants to hang out there, feel free to join.
