### ISSUE TITLE
radicale + wsgi: multiprocessing / multithreading setup?

### ISSUE THREAD

**Issue by m1027** [Kozea/Radicale#999]
What is the recommended and safe way to run radicale 2.x with wsgi (apache) in
a multithreaded or multiprocessed way?

Here is what I've found so far:

- radicale mentions thread-safety on radicale.org but IMHO this probably
  applies to the radicale stand-alone daemon (not to apache/wsgi).

- For the apache conf, there is mentioned over and over again this line:
  WSGIDaemonProcess radicale user=radicale group=radicale threads=1
  however, with threads=1, never greater than 1.

- WSGIDaemonProcess also knows processes=, however, this is omitted
  everywhere, thus wsgi will behave as non-multiprocessed.

- Obviously there are apache's mpm modules (prefork, worker, ...).

Which way to go?

Merci pour radicale.

**Comment by return42** [comment]
Radicale seem dead .. don't spend to mutch time on.

**Comment by Unrud** [comment]
You have to use multiple processes. Thread's are mostly pointless because of Python's GIL.
Using multiple processes/threads is safe. The locking is filesystem based.

Radicale 2 runs read-only requests in parallel. The development version also runs write requests in parallel.
